name: Required Review
description: Check that a Pull Request has reviews from required teams.
branding:
  icon: 'user-check'
  color: 'green'
inputs:
  requirements:
    description: >
      Requirements, as a string containing YAML.
      Either this or `requirements-file` is required.
    required: false
  requirements-file:
    description: >
      Requirements file.
      Either this or `requirements` is required.
    required: false
  status:
    description: Status context for the status check.
    required: false
    default: Required review
  fail:
    description: Fail the status check if a review is required.
    required: false
    type: boolean
    default: false
  request-reviews:
    description: >
      Automatically request reviews from teams or users needed to fulfill a requirement.
    required: false
    type: boolean
    default: false
  token:
    description: >
      GitHub Access Token. The user associated with this token will show up
      as the "creator" of the status check, and must have access to read
      pull request data, create status checks (`repo:status`), and to read
      your organization's teams (`read:org`).
    required: true
runs:
  using: node16
  main: dist/index.js
