import { renderHook } from '@testing-library/react';
import { fetchVideoItem } from '../../../client/lib/fetch-video-item';
import {
	deleteTrackForGuid,
	isAutogeneratedChapterFile,
	uploadTrackForGuid,
} from '../../../client/lib/video-tracks';
import generateChaptersFile from '../../../client/utils/video-chapters/generate-chapters-file';
import { makeLibraryItem } from '../../test-utils/library-item';
import { useUpdateChapters } from '../use-update-chapters';
import type { LibraryItem } from '../../types/library';
import type { ChaptersSyncStatus } from '../use-update-chapters';

jest.mock( '../../../client/lib/fetch-video-item', () => ( {
	__esModule: true,
	fetchVideoItem: jest.fn(),
} ) );
const mockedFetchVideoItem = fetchVideoItem as jest.Mock;

jest.mock( '../../../client/lib/video-tracks', () => ( {
	__esModule: true,
	deleteTrackForGuid: jest.fn(),
	isAutogeneratedChapterFile: jest.fn(),
	uploadTrackForGuid: jest.fn(),
} ) );
const mockedIsAutogenerated = isAutogeneratedChapterFile as jest.Mock;
const mockedUploadTrack = uploadTrackForGuid as jest.Mock;
const mockedDeleteTrack = deleteTrackForGuid as jest.Mock;

jest.mock( '../../../client/utils/video-chapters/generate-chapters-file', () => ( {
	__esModule: true,
	default: jest.fn(),
} ) );
const mockedGenerateChaptersFile = generateChaptersFile as jest.Mock;

// Variables referenced inside jest.mock() factories must be prefixed with
// "mock" (case-insensitive) to satisfy Jest's babel-jest hoisting restrictions.
const mockWarningNotice = jest.fn();
jest.mock( '@automattic/jetpack-components/global-notices', () => ( {
	useGlobalNotices: () => ( {
		createWarningNotice: mockWarningNotice,
	} ),
} ) );

// Three chapters, first at 0:00, titled, 30s apart — passes the validator.
const VALID_DESCRIPTION = [
	'A tour of the studio.',
	'',
	'00:00 Intro',
	'00:30 Editing',
	'01:00 Export',
].join( '\n' );

const PROSE_DESCRIPTION = 'Just prose now — the timestamps are gone.';

const EXISTING_TRACK = { tracks: { chapters: { en: { src: 'chapters.vtt', label: 'English' } } } };
const NO_TRACKS = { tracks: {} };

const VIDEO = makeLibraryItem( { guid: 'abc123', isPrivate: false, durationSeconds: 90 } );

const syncChapters = async (
	video: LibraryItem,
	description: string
): Promise< ChaptersSyncStatus > => {
	const { result } = renderHook( () => useUpdateChapters() );
	return result.current.syncChapters( video, description );
};

describe( 'useUpdateChapters', () => {
	const generatedFile = new File( [ 'WEBVTT' ], 'chapters.vtt', { type: 'text/vtt' } );

	beforeEach( () => {
		jest.clearAllMocks();
		mockedFetchVideoItem.mockResolvedValue( NO_TRACKS );
		mockedIsAutogenerated.mockResolvedValue( true );
		mockedUploadTrack.mockResolvedValue( 'chapters.vtt' );
		mockedDeleteTrack.mockResolvedValue( {} );
		mockedGenerateChaptersFile.mockReturnValue( generatedFile );
	} );

	it( 'uploads a regenerated track with the real video duration when no track exists', async () => {
		await expect( syncChapters( VIDEO, VALID_DESCRIPTION ) ).resolves.toBe( 'uploaded' );

		// The generator receives the video's actual duration in milliseconds,
		// not the legacy 999:59:59 sentinel, so the last cue ends at video end.
		expect( mockedGenerateChaptersFile ).toHaveBeenCalledWith( VALID_DESCRIPTION, 90000 );
		expect( mockedUploadTrack ).toHaveBeenCalledWith(
			{
				label: 'English (auto-generated)',
				srcLang: 'en',
				kind: 'chapters',
				tmpFile: generatedFile,
			},
			'abc123'
		);
		// No existing file means nothing to probe and nothing to delete.
		expect( mockedIsAutogenerated ).not.toHaveBeenCalled();
		expect( mockedDeleteTrack ).not.toHaveBeenCalled();
		expect( mockWarningNotice ).not.toHaveBeenCalled();
	} );

	it( 'overwrites an existing track after confirming it is auto-generated', async () => {
		mockedFetchVideoItem.mockResolvedValue( EXISTING_TRACK );

		await expect( syncChapters( VIDEO, VALID_DESCRIPTION ) ).resolves.toBe( 'uploaded' );

		expect( mockedIsAutogenerated ).toHaveBeenCalledWith(
			'https://videos.files.wordpress.com/abc123/chapters.vtt',
			{ guid: 'abc123', isPrivate: false }
		);
		expect( mockedUploadTrack ).toHaveBeenCalled();
	} );

	it( 'never overwrites a manually uploaded chapters track', async () => {
		mockedFetchVideoItem.mockResolvedValue( EXISTING_TRACK );
		mockedIsAutogenerated.mockResolvedValue( false );

		await expect( syncChapters( VIDEO, VALID_DESCRIPTION ) ).resolves.toBe( 'skipped-manual' );

		expect( mockedUploadTrack ).not.toHaveBeenCalled();
		expect( mockedDeleteTrack ).not.toHaveBeenCalled();
		expect( mockWarningNotice ).not.toHaveBeenCalled();
	} );

	it( 'deletes the auto-generated track when the description no longer has valid chapters', async () => {
		mockedFetchVideoItem.mockResolvedValue( EXISTING_TRACK );

		await expect( syncChapters( VIDEO, PROSE_DESCRIPTION ) ).resolves.toBe( 'deleted' );

		expect( mockedDeleteTrack ).toHaveBeenCalledWith(
			{ kind: 'chapters', srcLang: 'en' },
			'abc123'
		);
		expect( mockedUploadTrack ).not.toHaveBeenCalled();
		expect( mockWarningNotice ).not.toHaveBeenCalled();
	} );

	it( 'leaves a manually uploaded track alone even when the description has no chapters', async () => {
		mockedFetchVideoItem.mockResolvedValue( EXISTING_TRACK );
		mockedIsAutogenerated.mockResolvedValue( false );

		await expect( syncChapters( VIDEO, PROSE_DESCRIPTION ) ).resolves.toBe( 'skipped-manual' );

		expect( mockedDeleteTrack ).not.toHaveBeenCalled();
	} );

	it( 'does nothing when there are no valid chapters and no track', async () => {
		await expect( syncChapters( VIDEO, PROSE_DESCRIPTION ) ).resolves.toBe( 'unchanged' );

		expect( mockedIsAutogenerated ).not.toHaveBeenCalled();
		expect( mockedUploadTrack ).not.toHaveBeenCalled();
		expect( mockedDeleteTrack ).not.toHaveBeenCalled();
		expect( mockWarningNotice ).not.toHaveBeenCalled();
	} );

	it( 'raises a warning notice and resolves (never rejects) when the upload fails', async () => {
		mockedUploadTrack.mockRejectedValue( new Error( 'boom' ) );

		await expect( syncChapters( VIDEO, VALID_DESCRIPTION ) ).resolves.toBe( 'error' );

		expect( mockWarningNotice ).toHaveBeenCalledWith( 'Video chapters could not be updated.' );
	} );

	it( 'treats a WPCOM error envelope from the tracks endpoint as a failure', async () => {
		// The tracks endpoints respond 200 with `{ error }` instead of
		// rejecting, so the envelope must be treated as a failure explicitly.
		mockedUploadTrack.mockResolvedValue( { error: 'unauthorized' } );

		await expect( syncChapters( VIDEO, VALID_DESCRIPTION ) ).resolves.toBe( 'error' );

		expect( mockWarningNotice ).toHaveBeenCalledWith( 'Video chapters could not be updated.' );
	} );

	it( 'resolves as an error when the track probe itself fails', async () => {
		mockedFetchVideoItem.mockRejectedValue( new Error( 'network down' ) );

		await expect( syncChapters( VIDEO, VALID_DESCRIPTION ) ).resolves.toBe( 'error' );

		expect( mockedUploadTrack ).not.toHaveBeenCalled();
		expect( mockedDeleteTrack ).not.toHaveBeenCalled();
		expect( mockWarningNotice ).toHaveBeenCalledWith( 'Video chapters could not be updated.' );
	} );
} );
