<?php
/**
 * Handles the Jetpack Admin functions.
 *
 * @package automattic/jetpack-beta
 */

namespace Automattic\JetpackBeta;

use Automattic\Jetpack\Admin_UI\Admin_Menu;
use Automattic\Jetpack\WP_Build_Polyfills\WP_Build_Polyfills;

/**
 * Handles the Jetpack Beta plugin Admin functions.
 */
class Admin {

	/**
	 * Admin page hook name.
	 *
	 * @var string|false
	 */
	private static $hookname = false;

	/**
	 * URL-facing menu slug (`admin.php?page=jetpack-beta`).
	 */
	const MENU_SLUG = 'jetpack-beta';

	/**
	 * Slug emitted by `@wordpress/build` (`wpPlugin.pages[0]`). wp-build's
	 * auto-generated enqueue callback only fires when `$screen->id` matches this
	 * value, so we alias the screen id to it via `current_screen` without
	 * changing the user-facing URL.
	 */
	const WP_BUILD_SLUG = 'jetpack-beta-dashboard';

	/**
	 * Render function generated by `@wordpress/build` into
	 * `build/pages/jetpack-beta-dashboard/page-wp-admin.php`. Naming convention:
	 * `{wpPlugin.name}_{page-with-underscores}_wp_admin_render_page`.
	 */
	const WP_BUILD_RENDER_FN = 'jetpack_beta_jetpack_beta_dashboard_wp_admin_render_page';

	/**
	 * Key under `window.JetpackScriptData` the React app reads its state from
	 * (`window.JetpackScriptData.betaTester`). Must match the JS-side reader in
	 * `src/js/api/boot.ts`.
	 */
	const SCRIPT_DATA_KEY = 'betaTester';

	/**
	 * Initialize admin hooks.
	 */
	public static function init() {
		// Priority 1: load the wp-build bundle (and define its render function)
		// before `add_actions()` runs at priority 998 and needs it.
		add_action( 'admin_menu', array( self::class, 'maybe_load_wp_build' ), 1 );
		add_action( 'network_admin_menu', array( self::class, 'maybe_load_wp_build' ), 1 );
		add_action( 'admin_menu', array( self::class, 'add_actions' ), 998 );
		add_action( 'network_admin_menu', array( self::class, 'add_actions' ), 998 );
		add_action( 'admin_notices', array( self::class, 'render_banner' ) );
	}

	/**
	 * Action: Attach hooks common to all Jetpack admin pages.
	 *
	 * Action for `admin_menu` and `network_admin_menu`.
	 */
	public static function add_actions() {
		self::$hookname = Admin_Menu::add_menu(
			'Beta Tester',
			'Beta Tester',
			'update_plugins',
			'jetpack-beta',
			array( self::class, 'render' ),
			998
		);

		if ( false !== self::$hookname ) {
			add_action( 'load-' . self::$hookname, array( self::class, 'admin_page_load' ) );
		}

		add_filter( 'plugin_action_links_' . JPBETA__PLUGIN_FOLDER . '/jetpack-beta.php', array( self::class, 'plugin_action_links' ) );
	}

	/**
	 * Filter: Create the action links for the plugin's row on the plugins page.
	 *
	 * Filter for `plugin_action_links_{$slug}`.
	 *
	 * @param array $actions An array of plugin action links.
	 * @return array $actions
	 */
	public static function plugin_action_links( $actions ) {
		$settings_link = '<a href="' . esc_url( Utils::admin_url() ) . '">' . __( 'Settings', 'jetpack-beta' ) . '</a>';
		array_unshift( $actions, $settings_link );
		return $actions;
	}

	/**
	 * Admin page 'view' entry point.
	 *
	 * This will write the page content to standard output.
	 *
	 * @throws PluginDataException It doesn't really, but phpcs is dumb.
	 */
	public static function render() {
		if ( is_network_admin() && ! is_plugin_active_for_network( JPBETA__PLUGIN_FOLDER . '/jetpack-beta.php' ) ) {
			$exception = new \RuntimeException( __( 'Jetpack Beta Tester must be activated for the network to be used from Network Admin.', 'jetpack-beta' ) );
			require_once __DIR__ . '/admin/exception.template.php';
			exit( 0 );
		}

		ob_start();
		try {
			// phpcs:ignore WordPress.Security.NonceVerification.Recommended
			$plugin_name = isset( $_GET['plugin'] ) ? filter_var( wp_unslash( $_GET['plugin'] ) ) : null;

			if ( null !== $plugin_name ) {
				$plugin = Plugin::get_plugin( $plugin_name, true );
				if ( ! $plugin ) {
					throw new PluginDataException(
						// translators: %s: Requested plugin slug.
						sprintf( __( 'Plugin %s is not known.', 'jetpack-beta' ), $plugin_name )
					);
				}
			}

			// Hand off to wp-build's generated renderer (it prints the mount node
			// and critical boot styles). Falls back to a bare mount node on an
			// unbuilt checkout so the page never fatals.
			if ( function_exists( self::WP_BUILD_RENDER_FN ) ) {
				// The render function is generated by wp-build into
				// build/pages/jetpack-beta-dashboard/page-wp-admin.php, so it
				// doesn't exist at static-analysis time — hence the function_exists
				// guard and the phan suppression.
				// @phan-suppress-next-line PhanUndeclaredFunctionInCallable
				call_user_func( self::WP_BUILD_RENDER_FN );
			} else {
				echo '<div id="jetpack-beta-dashboard-wp-admin-app" class="boot-layout-container"></div>';
			}

			// A couple of our own critical styles, appended after the generated
			// ones so they win the cascade.
			echo self::critical_styles(); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- static style markup.
		} catch ( PluginDataException $exception ) {
			ob_clean();
			require_once __DIR__ . '/admin/exception.template.php';
		} finally {
			ob_end_flush();
		}
	}

	/**
	 * Critical inline styles for the Beta dashboard page.
	 *
	 * Rendered after the wp-build-generated styles so these win the cascade.
	 *
	 * @return string A `<style>` element.
	 */
	private static function critical_styles() {
		return '<style>'
			// wp-admin enables cross-document view transitions (`@view-transition
			// { navigation: auto }`), and the wp-build boot shell tags the stage
			// with `view-transition-name: boot--stage`, so each full-page reload
			// between the overview and a plugin's manage screen plays a jarring
			// zoom. Opt the Beta pages out — this rule comes after wp-admin's, so
			// it wins, and a cross-document transition needs both pages opted in.
			. '@view-transition{navigation:none}'
			// The wp-build shell paints the canvas with its dark token
			// (`--wpds-color-fg-content-neutral`), which is meant for the admin-ui
			// chrome. Beta uses the standard jetpack-components page, so restore
			// the default wp-admin content background instead.
			. '#wpwrap{background:#f0f0f1}'
			. '</style>';
	}

	/**
	 * Action: Handles Beta plugin admin page load.
	 *
	 * Action for `load-{$hook}`.
	 */
	public static function admin_page_load() {
		// phpcs:ignore WordPress.Security.NonceVerification.Recommended
		$plugin_name = isset( $_GET['plugin'] ) ? filter_var( wp_unslash( $_GET['plugin'] ) ) : null;

		// If a plugin is specified, check that it's valid.
		// This comes before any redirect for the access control.
		if ( null !== $plugin_name ) {
			$plugin = Plugin::get_plugin( $plugin_name );

			// Access control: If the plugin being managed is network-activated, redirect to Network Admin if `! is_network_admin()`.
			if ( $plugin && is_multisite() && ! is_network_admin() &&
				( is_plugin_active_for_network( $plugin->plugin_file() ) || is_plugin_active_for_network( $plugin->dev_plugin_file() ) )
			) {
				// phpcs:ignore WordPress.Security.NonceVerification.Recommended
				wp_safe_redirect( Utils::admin_url( $_GET ) );
				exit( 0 );
			}
		}
	}

	/**
	 * Action: Render beta plugin banner.
	 *
	 * Shows a banner on the plugins page if no dev versions have been downloaded yet.
	 *
	 * Action for `admin_notices`.
	 */
	public static function render_banner() {
		global $current_screen;

		if ( 'plugins' !== $current_screen->base || Utils::has_been_used() ) {
			return;
		}

		require __DIR__ . '/admin/notice.template.php';
	}

	/**
	 * Action: On the Beta admin page, load the wp-build bundle, alias the screen
	 * id so wp-build enqueues its assets, and bootstrap the app's initial state.
	 *
	 * Hooked at `admin_menu`/`network_admin_menu` priority 1 so the polyfills
	 * register and the render function is defined before `add_actions()` runs at
	 * priority 998.
	 *
	 * Action for `admin_menu` and `network_admin_menu`.
	 */
	public static function maybe_load_wp_build() {
		if ( ! self::is_beta_admin_request() ) {
			return;
		}

		self::load_wp_build();
		add_action( 'current_screen', array( self::class, 'alias_screen_id_for_wp_build' ) );
		add_filter( 'jetpack_admin_js_script_data', array( self::class, 'inject_script_data' ) );

		// Stable body class so the React layout styles (jetpack-admin-page-layout)
		// can pin the header/footer and scroll the middle, independent of the
		// hook-derived `{parent}_page_jetpack-beta` class.
		add_filter(
			'admin_body_class',
			static function ( $classes ) {
				return trim( $classes . ' jetpack-beta-page' );
			}
		);
	}

	/**
	 * Load wp-build's generated registration file and register the polyfills the
	 * bundle depends on. No-op on a fresh checkout before `pnpm build`, in which
	 * case {@see self::render()} falls back to a bare mount node.
	 */
	private static function load_wp_build() {
		$build_index = plugin_dir_path( JPBETA__PLUGIN_FILE ) . 'build/build.php';

		if ( ! file_exists( $build_index ) ) {
			return;
		}

		require_once $build_index;

		WP_Build_Polyfills::register(
			'jetpack-beta',
			array_merge( WP_Build_Polyfills::SCRIPT_HANDLES, WP_Build_Polyfills::MODULE_IDS )
		);
	}

	/**
	 * Alias the current screen id to wp-build's expected slug so its
	 * auto-generated enqueue callback fires for our user-facing page.
	 *
	 * @param \WP_Screen|null $screen The current screen object (passed by WP).
	 */
	public static function alias_screen_id_for_wp_build( $screen ) {
		if ( ! is_object( $screen ) ) {
			return;
		}

		$screen->id = self::WP_BUILD_SLUG;
	}

	/**
	 * Bootstrap the React app's initial state onto `window.JetpackScriptData.betaTester`.
	 *
	 * Because wp-build pages load as ES modules, `wp_localize_script` can't attach
	 * data to them; the shared `jetpack_admin_js_script_data` filter (printed onto
	 * the `jetpack-script-data` handle the bundle already depends on) is the
	 * supported channel. Mirrors Podcast, Newsletter, and SEO.
	 *
	 * @param array $data Script data being injected onto the page.
	 * @return array
	 */
	public static function inject_script_data( $data ) {
		if ( ! is_array( $data ) ) {
			$data = array();
		}

		// phpcs:ignore WordPress.Security.NonceVerification.Recommended
		$plugin_slug = isset( $_GET['plugin'] ) ? sanitize_text_field( wp_unslash( $_GET['plugin'] ) ) : null;

		// Resolve the human-readable plugin name up front (from cached data) so the
		// React header/breadcrumb can render immediately, without waiting for the
		// get-plugin ability to resolve.
		$plugin_display_name = null;
		if ( null !== $plugin_slug ) {
			try {
				$beta_plugin = Plugin::get_plugin( $plugin_slug );
				if ( $beta_plugin ) {
					$plugin_display_name = $beta_plugin->get_name();
				}
			} catch ( PluginDataException $e ) {
				$plugin_display_name = null;
			}
		}

		// Always preload the plugins list (cached data) so the overview renders
		// instantly — including when it's reached client-side after landing on a
		// plugin's manage screen, where there is no full page reload to seed it.
		$plugin_list = null;
		try {
			$payload     = Abilities\Beta_Abilities::build_plugin_list();
			$plugin_list = $payload['plugins'];
		} catch ( PluginDataException $e ) {
			$plugin_list = null;
		}

		$data[ self::SCRIPT_DATA_KEY ] = array(
			'apiRoot'    => esc_url_raw( rest_url() ),
			'apiNonce'   => wp_create_nonce( 'wp_rest' ),
			'pluginName' => $plugin_display_name,
			'plugins'    => $plugin_list,
			'adminUrl'   => Utils::admin_url(),
		);

		return $data;
	}

	/**
	 * Whether the current request targets the Beta admin page.
	 *
	 * @return bool
	 */
	private static function is_beta_admin_request() {
		// phpcs:ignore WordPress.Security.NonceVerification.Recommended
		if ( ! is_admin() || ! isset( $_GET['page'] ) ) {
			return false;
		}

		// phpcs:ignore WordPress.Security.NonceVerification.Recommended
		return self::MENU_SLUG === sanitize_text_field( wp_unslash( $_GET['page'] ) );
	}

	/**
	 * Determine content for "To test" and "What changed" boxes.
	 *
	 * @param Plugin $plugin Plugin being processed.
	 * @return (string|null)[] HTML and diff summary.
	 */
	public static function to_test_content( Plugin $plugin ) {
		if ( $plugin->is_active( 'stable' ) ) {
			$path = dirname( $plugin->plugin_path() );
			$info = (object) array(
				'source' => 'stable',
			);
		} elseif ( $plugin->is_active( 'dev' ) ) {
			$path = dirname( $plugin->dev_plugin_path() );
			$info = $plugin->dev_info();
			if ( ! $info ) {
				return array(
					sprintf(
						// translators: %s: Plugin name.
						__( 'This development instance of %s seems to be from an old verison of Jetpack Beta Tester, or has otherwise lost essential metadata. You should use Jetpack Beta Tester to reinstall the desired PR, Release Candidate, or Bleeding Edge version.', 'jetpack-beta' ),
						$plugin->get_name()
					),
					null,
				);
			}
		} else {
			return array( null, null );
		}

		if ( 'pr' === $info->source ) {
			$res = Utils::get_remote_data( sprintf( 'https://api.github.com/repos/%s/pulls/%d', $plugin->repo(), $info->pr ), "github/pulls/$info->pr" );
			if ( ! isset( $res->body ) ) {
				return array( 'GitHub commit info is unavailable.', null );
			}
			$html = Utils::render_markdown( $plugin, $res->body );

			$res  = Utils::get_remote_data( sprintf( 'https://api.github.com/repos/%s/pulls/%d/files', $plugin->repo(), $info->pr ), "github/pulls/$info->pr/files" );
			$diff = null;
			if ( is_array( $res ) ) {
				// translators: %d: number of files changed.
				$diff  = '<div>' . sprintf( _n( '%d file changed ', '%d files changed', count( $res ), 'jetpack-beta' ), count( $res ) ) . "<br />\n";
				$diff .= "<ul class=\"ul-square jpbeta-file-list\">\n";
				foreach ( $res as $file ) {
					$added_deleted_changed = array();
					if ( $file->additions ) {
						$added_deleted_changed[] = '+' . $file->additions;
					}
					if ( $file->deletions ) {
						$added_deleted_changed[] = '-' . $file->deletions;
					}
					$diff .= sprintf( '<li><span class="container"><span class="filename">%s</span><span class="status">&nbsp;(%s %s)</span></span></li>', esc_html( $file->filename ), esc_html( $file->status ), implode( ' ', $added_deleted_changed ) ) . "\n";
				}
				$diff .= "</ul></div>\n\n";
			}

			return array( $html, $diff );
		}

		WP_Filesystem();
		global $wp_filesystem;

		$file = $path . '/to-test.md';
		if ( ! file_exists( $file ) ) {
			$file = __DIR__ . '/../docs/testing/testing-tips.md';
		}
		return array( Utils::render_markdown( $plugin, $wp_filesystem->get_contents( $file ) ), null );
	}

	/**
	 * Display autoupdate toggle.
	 *
	 * @deprecated 4.3.0 The settings UI is now a React app backed by the Abilities API.
	 */
	public static function show_toggle_autoupdates() {
		_deprecated_function( __METHOD__, '4.3.0' );
	}

	/**
	 * Display email notification toggle.
	 *
	 * @deprecated 4.3.0 The settings UI is now a React app backed by the Abilities API.
	 */
	public static function show_toggle_emails() {
		_deprecated_function( __METHOD__, '4.3.0' );
	}

	/**
	 * Display autoupdate and email notification toggles.
	 *
	 * @deprecated 4.3.0 The settings UI is now a React app backed by the Abilities API.
	 */
	public static function show_toggle() {
		_deprecated_function( __METHOD__, '4.3.0' );
	}
}
