name: "Setup tools"
description: "Setup needed versions of PHP, Node, and Pnpm."
inputs:
  php:
    description: "Override the PHP version, or set 'false' to skip setting up PHP."
  node:
    description: "Override the Node version, or set 'false' to skip setting up Node and Pnpm."
runs:
  using: composite
  steps:
    - name: "Read tool versions"
      id: versions
      shell: bash
      env:
        INPUT_NODE: ${{ inputs.node }}
        INPUT_PHP: ${{ inputs.php }}
      run: |
        # Read tool versions
        . .github/versions.sh

        if [[ "${INPUT_PHP:-$PHP_VERSION}" == 5.6 || "${INPUT_PHP:-$PHP_VERSION}" == 7.[01] ]]; then
          printf "Downgrading composer for PHP %s\n\n" "${INPUT_PHP:-$PHP_VERSION}"
          COMPOSER_VERSION=2.2.12
        fi

        printf "\n\e[1mSelected tool versions\e[0m\n"
        echo " PHP: ${INPUT_PHP:-$PHP_VERSION}"
        echo "php-version=${INPUT_PHP:-$PHP_VERSION}" >> "$GITHUB_OUTPUT"
        echo " Composer: $COMPOSER_VERSION"
        echo "composer-version=$COMPOSER_VERSION" >> "$GITHUB_OUTPUT"
        echo " Node: ${INPUT_NODE:-$NODE_VERSION}"
        echo "node-version=${INPUT_NODE:-$NODE_VERSION}" >> "$GITHUB_OUTPUT"
        echo " Pnpm: $PNPM_VERSION"
        echo "pnpm-version=$PNPM_VERSION" >> "$GITHUB_OUTPUT"

    - name: Remove disabled tools
      shell: bash
      if: steps.versions.outputs.php-version == 'false' || steps.versions.outputs.node-version == 'false'
      env:
        PHP: ${{ steps.versions.outputs.php-version }}
        NODE: ${{ steps.versions.outputs.node-version }}
      run: |
        # Remove disabled tools
        torm=()
        if [[ "$PHP" == "false" ]]; then
          torm+=( php composer )
        fi
        if [[ "$NODE" == "false" ]]; then
          torm+=( node npm pnpm )
        fi
        for tool in "${torm[@]}"; do
          while command -v "$tool" &>/dev/null; do
            sudo rm -v "$(command -v "$tool")"
          done
        done

    - name: Setup PHP
      if: steps.versions.outputs.php-version != 'false'
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ steps.versions.outputs.php-version }}
        ini-values: error_reporting=E_ALL, display_errors=On, zend.assertions=1
        tools: composer:${{ steps.versions.outputs.composer-version }}
        extensions: mysql, imagick
        coverage: none

    - name: Configure composer
      if: steps.versions.outputs.php-version != 'false'
      shell: bash
      run: |
        composer config --global github-protocols https
        composer config --global use-github-api false

    - name: Get Composer cache directory
      if: steps.versions.outputs.php-version != 'false'
      id: composer-cache
      shell: bash
      run: |
        # Get Composer cache directory
        echo "dir=$(composer config cache-files-dir)" >> "$GITHUB_OUTPUT"
    - name: Use composer cache
      if: steps.versions.outputs.php-version != 'false'
      uses: actions/cache@v3
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Setup pnpm
      if: steps.versions.outputs.node-version != 'false'
      uses: pnpm/action-setup@v2.2.4
      with:
        version: ${{ steps.versions.outputs.pnpm-version }}
    - name: Setup Node
      if: steps.versions.outputs.node-version != 'false'
      uses: actions/setup-node@v3
      with:
        # Prefix the version with a caret as otherwise actions/setup-node will waste API calls finding where to download the exact version.
        node-version: ^${{ steps.versions.outputs.node-version }}
        cache: pnpm

    - name: Configure composer 304-short-circuiting proxy
      if: steps.versions.outputs.php-version != 'false' && steps.versions.outputs.node-version != 'false'
      shell: bash
      run: |
        # Generate a self-signeed cert for the proxy
        openssl req -new -newkey rsa:2048 -sha256 -days 1 -nodes -x509 -subj "/CN=localhost" -keyout "$HOME/cert.key" -out "$HOME/cert.crt"

        # Start the proxy
        nohup "$GITHUB_ACTION_PATH"/packagist-proxy.mjs "$HOME/cert.key" "$HOME/cert.crt" &> "$HOME/proxy.log" &
        disown $!

        # Configure the plugin via env
        export JP_304_PLUGIN_CERT=$HOME/cert.crt
        echo "JP_304_PLUGIN_CERT=$JP_304_PLUGIN_CERT" >> "$GITHUB_ENV"

        # Install the plugin globally
        composer global config repositories.304-proxy-package path "$GITHUB_ACTION_PATH/composer-plugin"
        composer global config --no-interaction allow-plugins.automattic/composer-304-plugin true
        composer global require automattic/composer-304-plugin=@dev

    - name: Dump proxy log post-run
      if: steps.versions.outputs.php-version != 'false' && steps.versions.outputs.node-version != 'false'
      # Alas we have to use a JS sub-action to have a "post" step. Composite actions can't do it.
      uses: ./.github/actions/tool-setup/post-run-action

    - name: Tool versions
      shell: bash
      run: |
        # Tool versions
        function docmd {
          if [[ -z "$(command -v $1)" ]]; then
            echo "$1 is not available"
          else
            which $1
            "$@"
          fi
        }

        printf "\n\e[1mInstalled tool versions\e[0m\n"
        docmd php --version
        docmd composer --version
        docmd node --version
        docmd pnpm --version
        docmd jq --version
