export const offlineFeaturesResponse = {
	counts: {
		offline_safe: 2,
		enabled: 1,
		partial: 1,
	},
	groups: {
		content: 'Content and editor',
		audience: 'Audience and engagement',
	},
	recommended: [ 'contact-form', 'blocks' ],
	features: [
		{
			slug: 'contact-form',
			module: 'contact-form',
			name: 'Forms',
			description: 'Add forms.',
			documentation_url: 'https://jetpack.com/redirect/?source=jetpack-support-contact-form',
			type: 'module',
			group: 'content',
			active: true,
			available: true,
			recommended: true,
			limitation: '',
			underlying_module: 'contact-form',
		},
		{
			slug: 'blocks',
			module: 'blocks',
			name: 'Blocks',
			description: 'Add blocks.',
			documentation_url: 'https://jetpack.com/redirect/?source=jetpack-support-blocks',
			type: 'module',
			group: 'content',
			active: false,
			available: true,
			recommended: true,
			limitation: '',
			underlying_module: 'blocks',
		},
		{
			slug: 'newsletter',
			module: 'subscriptions',
			name: 'Newsletter',
			description: 'Build newsletter flows.',
			documentation_url:
				'https://jetpack.com/redirect/?url=https%3A%2F%2Fjetpack.com%2Fsupport%2Fnewsletter',
			type: 'partial',
			group: 'audience',
			active: false,
			available: true,
			recommended: false,
			limitation: 'Email delivery still requires a connection.',
			underlying_module: 'subscriptions',
		},
	],
};
