export const offlineFeaturesResponse = {
	counts: {
		offline_safe: 1,
		enabled: 1,
		partial: 3,
		always_available: 1,
	},
	groups: {
		boost: 'Boost',
		forms: 'Forms',
		newsletter: 'Newsletter',
		writing: 'Writing',
		design: 'Design',
	},
	recommended: [ 'contact-form', 'blocks' ],
	features: [
		{
			slug: 'contact-form',
			module: 'contact-form',
			name: 'Forms',
			description: 'Add forms.',
			documentation_url: 'https://jetpack.com/redirect/?source=jetpack-support-contact-form',
			type: 'module',
			group: 'forms',
			active: true,
			available: true,
			recommended: true,
			toggleable: true,
			limitation: '',
			underlying_module: 'contact-form',
		},
		{
			slug: 'blocks',
			module: 'blocks',
			name: 'Blocks',
			description: 'Add blocks.',
			documentation_url: 'https://jetpack.com/redirect/?source=jetpack-support-blocks',
			type: 'partial',
			group: 'writing',
			active: false,
			available: true,
			recommended: true,
			toggleable: true,
			limitation: 'Some blocks require a WordPress.com connection.',
			underlying_module: 'blocks',
		},
		{
			slug: 'newsletter',
			module: 'subscriptions',
			name: 'Newsletter',
			description: 'Build newsletter flows.',
			documentation_url:
				'https://jetpack.com/redirect/?url=https%3A%2F%2Fjetpack.com%2Fsupport%2Fnewsletter',
			type: 'partial',
			group: 'newsletter',
			active: false,
			available: true,
			recommended: false,
			toggleable: true,
			limitation: 'Email delivery still requires a connection.',
			underlying_module: 'subscriptions',
		},
		{
			slug: 'boost',
			module: '',
			name: 'Boost',
			description: 'Use local performance optimizations.',
			documentation_url: 'https://jetpack.com/redirect/?source=jetpack-support-boost',
			type: 'partial',
			group: 'boost',
			active: true,
			available: true,
			recommended: false,
			toggleable: false,
			limitation: 'Image Guide works locally. Speed scores require a publicly reachable site.',
			underlying_module: '',
		},
		{
			slug: 'theme-tools',
			module: '',
			name: 'Theme tools',
			description: 'Use Jetpack theme integrations.',
			documentation_url: 'https://jetpack.com/redirect/?source=jetpack-support-theme-tools',
			type: 'always_available',
			group: 'design',
			active: true,
			available: true,
			recommended: false,
			toggleable: false,
			limitation: 'Theme tools are loaded automatically.',
			underlying_module: '',
		},
	],
	requires_connection: [
		{
			slug: 'comments',
			module: 'comments',
			name: 'Jetpack Comments',
			description: 'Requires a WordPress.com connection for enhanced commenting.',
			type: 'requires_connection',
			group: 'social',
			active: false,
			available: false,
			recommended: false,
			toggleable: false,
			limitation: 'This feature requires a WordPress.com connection.',
			underlying_module: 'comments',
		},
		{
			slug: 'jetpack-ai',
			module: '',
			name: 'Jetpack AI',
			description: 'Requires a WordPress.com connection to generate AI content.',
			type: 'requires_connection',
			group: 'writing',
			active: false,
			available: false,
			recommended: false,
			toggleable: false,
			limitation: 'This feature requires a WordPress.com connection.',
			underlying_module: '',
		},
		{
			slug: 'scan',
			module: 'scan',
			name: 'Jetpack Scan',
			description: 'Requires a WordPress.com connection to scan site files.',
			type: 'requires_connection',
			group: 'protect',
			active: false,
			available: false,
			recommended: false,
			toggleable: false,
			limitation: 'This feature requires a WordPress.com connection.',
			underlying_module: 'scan',
		},
	],
};
