/**
 * External dependencies
 */
import { QueryClientProvider } from '@tanstack/react-query';
import { Button, Modal, Notice } from '@wordpress/components';
import { useCallback, useEffect, useMemo, useReducer, useRef, useState } from '@wordpress/element';
import { __, sprintf } from '@wordpress/i18n';
import { close, plus } from '@wordpress/icons';
import debugFactory from 'debug';
/**
 * Internal dependencies
 */
import {
	deleteTrackForGuid,
	isAutogeneratedChapterFile,
	normalizeVideoTextTrackResponse,
	uploadTrackForGuid,
} from '../../lib/video-tracks';
import applyChaptersToDescription from '../../utils/video-chapters/apply-chapters-to-description';
import { chapterStartAtToSeconds } from '../../utils/video-chapters/chapter-time';
import extractVideoChapters from '../../utils/video-chapters/extract-video-chapters';
import generateChaptersFile from '../../utils/video-chapters/generate-chapters-file';
import CaptionPreviewPlayer from '../caption-manager-modal/caption-preview-player';
import ConfirmationOverlay from '../caption-manager-modal/confirmation-overlay';
import { createCaptionManagerQueryClient } from '../caption-manager-modal/query-client';
import { useVideoTracks } from '../caption-manager-modal/use-video-tracks';
import ChapterList from './chapter-list';
import {
	canSaveChapters,
	chapterWorkspaceReducer,
	getChapterValidationErrors,
	hasUnsavedChapterEdits,
	initialChapterWorkspaceState,
} from './chapter-workspace';
import './style.scss';
/**
 * Types
 */
import type { ChapterManagerModalProps } from './types';
import type { UploadTrackDataProps } from '../../lib/video-tracks/types';
import type { CaptionPreviewPlayerHandle } from '../caption-manager-modal/caption-preview-player';
import type { KeyboardEvent, ReactElement } from 'react';

const debug = debugFactory( 'videopress:chapter-manager-modal' );

/* Manual rows are suggested this far after the current last chapter. */
const NEW_ROW_OFFSET_SECONDS = 10;

type NoticeState = { status: 'error' | 'success'; message: string } | null;

type ConfirmationState = {
	message: string;
	confirmLabel: string;
	onConfirm: () => void;
};

/**
 * Shared VideoPress chapter manager modal.
 *
 * The outer component owns the environment (query client); the inner one owns
 * the modal itself.
 *
 * @param props - Component props (see {@link ChapterManagerModalProps}).
 * @return Chapter manager modal.
 */
export default function ChapterManagerModal( props: ChapterManagerModalProps ): ReactElement {
	const [ queryClient ] = useState( createCaptionManagerQueryClient );

	return (
		<QueryClientProvider client={ queryClient }>
			<ChapterManagerModalInner { ...props } />
		</QueryClientProvider>
	);
}

/**
 * The chapter manager modal: a structured editor over the description's
 * chapter lines. Saving rewrites those lines and immediately regenerates the
 * auto-generated chapters VTT track — or deletes it when all chapters are
 * removed.
 *
 * @param props             - Component props (see {@link ChapterManagerModalProps}).
 * @param props.isOpen      - Whether the modal is open.
 * @param props.guid        - VideoPress GUID.
 * @param props.title       - Optional video title.
 * @param props.description - The current description, parsed on open.
 * @param props.videoSrc    - Optional preview video source.
 * @param props.poster      - Optional preview poster image.
 * @param props.isPrivate   - Whether the video is private, so previews need a playback token.
 * @param props.tracks      - Track list already known to the host.
 * @param props.durationMs  - Video duration in milliseconds.
 * @param props.onClose     - Close handler.
 * @param props.onSaved     - Called with the rewritten description and updated tracks after a save.
 * @return The modal, or null while closed.
 */
function ChapterManagerModalInner( {
	isOpen,
	guid,
	title,
	description,
	videoSrc,
	poster,
	isPrivate = false,
	tracks = [],
	durationMs,
	onClose,
	onSaved,
}: ChapterManagerModalProps ): ReactElement | null {
	const playerRef = useRef< CaptionPreviewPlayerHandle >( null );
	const [ workspace, dispatch ] = useReducer(
		chapterWorkspaceReducer,
		initialChapterWorkspaceState
	);
	const [ notice, setNotice ] = useState< NoticeState >( null );
	const [ confirmation, setConfirmation ] = useState< ConfirmationState | null >( null );
	const [ isSaving, setIsSaving ] = useState( false );
	/* Whether the existing chapters track may be overwritten without asking. */
	const [ isOverwriteSafe, setIsOverwriteSafe ] = useState( true );

	const { managedTracks, previewAspectRatio } = useVideoTracks( {
		guid,
		isOpen,
		isPrivate,
		tracks,
		onError: () =>
			setNotice( {
				status: 'error',
				message: __(
					'Couldn’t load the latest track list for this video. It may be incomplete.',
					'jetpack-videopress-pkg'
				),
			} ),
	} );

	const chaptersTrack = useMemo(
		() => managedTracks.find( track => track.kind === 'chapters' && track.srcLang === 'en' ),
		[ managedTracks ]
	);

	/*
	 * Snapshot the description into chapter rows when the modal opens;
	 * concurrent description edits elsewhere are last-write-wins.
	 */
	useEffect( () => {
		if ( ! isOpen ) {
			return;
		}
		dispatch( {
			type: 'SEED',
			chapters: extractVideoChapters( description ).map( chapter => ( {
				seconds: chapterStartAtToSeconds( chapter.startAt ),
				title: chapter.title,
			} ) ),
		} );
		setNotice( null );
		setConfirmation( null );
	}, [ isOpen ] );

	// Mirrors the auto-generated check the block editor runs before overwriting.
	const chaptersTrackSrc = chaptersTrack?.src;
	useEffect( () => {
		if ( ! isOpen ) {
			return;
		}
		if ( ! chaptersTrackSrc ) {
			setIsOverwriteSafe( true );
			return;
		}

		let isStale = false;
		const fileUrl = /^https?:/.test( chaptersTrackSrc )
			? chaptersTrackSrc
			: `https://videos.files.wordpress.com/${ guid }/${ chaptersTrackSrc }`;
		isAutogeneratedChapterFile( fileUrl, { guid, isPrivate } )
			.then( isAutogenerated => {
				if ( ! isStale ) {
					setIsOverwriteSafe( isAutogenerated );
				}
			} )
			.catch( error => {
				debug( 'auto-generated chapter check failed', error );
				// Unknown provenance: be safe and ask before overwriting.
				if ( ! isStale ) {
					setIsOverwriteSafe( false );
				}
			} );

		return () => {
			isStale = true;
		};
	}, [ isOpen, chaptersTrackSrc, guid, isPrivate ] );

	const errors = useMemo( () => getChapterValidationErrors( workspace.rows ), [ workspace.rows ] );

	const performSave = useCallback( async () => {
		setIsSaving( true );
		const nextDescription = applyChaptersToDescription( description, workspace.rows );
		let updatedTracks = managedTracks;

		try {
			if ( ! workspace.rows.length ) {
				if ( chaptersTrack ) {
					await deleteTrackForGuid( { kind: 'chapters', srcLang: 'en' }, guid );
					updatedTracks = managedTracks.filter( track => track !== chaptersTrack );
				}
			} else {
				const tmpFile = generateChaptersFile( nextDescription, durationMs );
				// The rewritten description always carries chapter lines here.
				if ( ! tmpFile ) {
					throw new Error(
						__( 'Failed to generate the chapters file.', 'jetpack-videopress-pkg' )
					);
				}
				const trackToUpload: UploadTrackDataProps = {
					label: __( 'English (auto-generated)', 'jetpack-videopress-pkg' ),
					srcLang: 'en',
					kind: 'chapters',
					tmpFile,
				};
				const response = await uploadTrackForGuid( trackToUpload, guid );
				const uploadedTrack = normalizeVideoTextTrackResponse( response, trackToUpload );

				/*
				 * A response with no stored track file is an upload failure (e.g. an
				 * error envelope); surface it instead of reporting a src-less track.
				 */
				if ( ! uploadedTrack?.src ) {
					debug( 'chapter track upload failed: %o', response );
					throw new Error( __( 'Failed to upload chapters track.', 'jetpack-videopress-pkg' ) );
				}

				updatedTracks = chaptersTrack
					? managedTracks.map( track => ( track === chaptersTrack ? uploadedTrack : track ) )
					: [ ...managedTracks, uploadedTrack ];
			}
		} catch ( error ) {
			debug( 'chapter save failed', error );
			setNotice( {
				status: 'error',
				message:
					error instanceof Error && error.message
						? error.message
						: __( 'Failed to save chapters.', 'jetpack-videopress-pkg' ),
			} );
			setIsSaving( false );
			return;
		}

		/*
		 * The track change is persisted; hand off outside the try so a host
		 * callback error can't read as a save failure and provoke a re-upload.
		 */
		setIsSaving( false );
		dispatch( { type: 'MARK_SAVED' } );
		onSaved( nextDescription, updatedTracks );
		onClose();
	}, [
		chaptersTrack,
		description,
		durationMs,
		guid,
		managedTracks,
		onClose,
		onSaved,
		workspace.rows,
	] );

	const handleSave = useCallback( () => {
		if ( chaptersTrack && ! isOverwriteSafe ) {
			setConfirmation( {
				message: __(
					'This video’s chapters file may have been uploaded manually. Saving will replace it.',
					'jetpack-videopress-pkg'
				),
				confirmLabel: __( 'Replace', 'jetpack-videopress-pkg' ),
				onConfirm: () => void performSave(),
			} );
			return;
		}
		void performSave();
	}, [ chaptersTrack, isOverwriteSafe, performSave ] );

	const handleRequestClose = useCallback( () => {
		if ( ! hasUnsavedChapterEdits( workspace ) ) {
			onClose();
			return;
		}
		setConfirmation( {
			message: __( 'Discard unsaved chapter changes?', 'jetpack-videopress-pkg' ),
			confirmLabel: __( 'Discard', 'jetpack-videopress-pkg' ),
			onConfirm: onClose,
		} );
	}, [ onClose, workspace ] );

	/*
	 * Escape is handled here, before the Modal's own handler: the Modal plays
	 * its exit animation before asking `onRequestClose`, so a vetoed close
	 * (unsaved edits) would flash the modal closed and open again.
	 */
	const handleContentKeyDown = useCallback(
		( event: KeyboardEvent< HTMLDivElement > ) => {
			if ( event.key === 'Escape' && ! event.defaultPrevented ) {
				event.preventDefault();
				handleRequestClose();
			}
		},
		[ handleRequestClose ]
	);

	const addChapterAtCurrentTime = useCallback( () => {
		dispatch( {
			type: 'ADD_ROW',
			seconds: Math.floor( playerRef.current?.getCurrentTime() ?? 0 ),
		} );
	}, [] );

	const addChapter = useCallback( () => {
		const lastRow = workspace.rows[ workspace.rows.length - 1 ];
		dispatch( {
			type: 'ADD_ROW',
			seconds: lastRow ? lastRow.seconds + NEW_ROW_OFFSET_SECONDS : 0,
		} );
	}, [ workspace.rows ] );

	const aggregateErrorMessage = useMemo( () => {
		if ( errors.some( error => error.code === 'start-at-zero' ) ) {
			return __( 'The first chapter must start at 0:00.', 'jetpack-videopress-pkg' );
		}
		if ( errors.some( error => error.code === 'min-count' ) ) {
			return __( 'Add at least 3 chapters.', 'jetpack-videopress-pkg' );
		}
		return null;
	}, [ errors ] );

	return isOpen ? (
		<Modal
			title={ sprintf(
				/* translators: %s: video title. */
				__( 'Manage chapters for %s', 'jetpack-videopress-pkg' ),
				title || __( 'VideoPress video', 'jetpack-videopress-pkg' )
			) }
			onRequestClose={ handleRequestClose }
			className="videopress-chapter-manager"
			focusOnMount={ false }
			/*
			 * The built-in dismiss button and outside-click both play the close
			 * animation before consulting `onRequestClose`, which flashes the
			 * modal away and back when the discard confirmation vetoes the
			 * close. Escape is intercepted in the content for the same reason.
			 */
			isDismissible={ false }
			shouldCloseOnClickOutside={ false }
			headerActions={
				<Button
					size="small"
					icon={ close }
					label={ __( 'Close', 'jetpack-videopress-pkg' ) }
					onClick={ handleRequestClose }
				/>
			}
		>
			{ /* eslint-disable-next-line jsx-a11y/no-static-element-interactions -- Intercepts Escape before the Modal's animate-then-close handling. */ }
			<div className="videopress-chapter-manager__body" onKeyDown={ handleContentKeyDown }>
				{ notice && (
					<Notice status={ notice.status } isDismissible={ false }>
						{ notice.message }
					</Notice>
				) }

				<div className="videopress-chapter-manager__workspace">
					<div className="videopress-chapter-manager__preview">
						<CaptionPreviewPlayer
							ref={ playerRef }
							guid={ guid }
							videoSrc={ videoSrc }
							poster={ poster ?? undefined }
							isPrivate={ isPrivate }
							previewAspectRatio={ previewAspectRatio }
						/>
						<Button
							variant="secondary"
							icon={ plus }
							disabled={ isSaving }
							onClick={ addChapterAtCurrentTime }
						>
							{ __( 'Add chapter at current time', 'jetpack-videopress-pkg' ) }
						</Button>
					</div>

					<div className="videopress-chapter-manager__editor">
						{ workspace.rows.length ? (
							<ChapterList
								rows={ workspace.rows }
								errors={ errors }
								disabled={ isSaving }
								onSetTime={ ( id, seconds ) => dispatch( { type: 'SET_TIME', id, seconds } ) }
								onSetTitle={ ( id, value ) => dispatch( { type: 'SET_TITLE', id, title: value } ) }
								onRemove={ id => dispatch( { type: 'REMOVE_ROW', id } ) }
								onSeek={ seconds => playerRef.current?.seekTo( seconds ) }
							/>
						) : (
							<p className="videopress-chapter-manager__empty">
								{ __(
									'Chapters help viewers navigate long videos. Add at least three, starting at 0:00.',
									'jetpack-videopress-pkg'
								) }
							</p>
						) }

						<div className="videopress-chapter-manager__editor-actions">
							<Button variant="tertiary" icon={ plus } disabled={ isSaving } onClick={ addChapter }>
								{ __( 'Add chapter', 'jetpack-videopress-pkg' ) }
							</Button>
						</div>

						{ aggregateErrorMessage && (
							<p className="videopress-chapter-manager__error">{ aggregateErrorMessage }</p>
						) }

						<div className="videopress-chapter-manager__save">
							<Button
								variant="primary"
								isBusy={ isSaving }
								disabled={ ! canSaveChapters( workspace ) || isSaving }
								onClick={ handleSave }
							>
								{ __( 'Save chapters', 'jetpack-videopress-pkg' ) }
							</Button>
						</div>
					</div>
				</div>

				{ confirmation && (
					<ConfirmationOverlay
						message={ confirmation.message }
						confirmLabel={ confirmation.confirmLabel }
						onConfirm={ () => {
							const pending = confirmation;
							setConfirmation( null );
							pending.onConfirm();
						} }
						onCancel={ () => setConfirmation( null ) }
					/>
				) }
			</div>
		</Modal>
	) : null;
}
