name: Push to mirrors
description: Push built versions of projects from a monorepo to mirror repos.
branding:
  icon: 'package'
  color: 'green'
inputs:
  commit-message:
    description: >
      Commit message to use for the mirror commits. If omitted, it will be read
      from the monorepo checkout pointed at by `source-directory`.
    required: false
  no-upstream-refs:
    description: >
      Set to `true` to suppress the "Upstream-Ref" footers in mirrored commits.
    required: false
  source-directory:
    description: >
      Directory containing a checkout of the commit being mirrored. Used to
      fetch git metadata for the mirror commits, and to find the base commit
      for new mirror branches.
    required: false
    default: ${{ github.workspace }}
  token:
    description: >
      GitHub Access Token. This token must allow for pushing to all relevant
      branches of all relevant mirror repos.
    required: true
  upstream-ref-count:
    description: >
      When checking "Upstream-Ref" to find a base commit for a new mirror
      branch, only consider this many monorepo commits at most.
    required: false
  upstream-ref-since:
    description: >
      When checking "Upstream-Ref" to find a base commit for a new mirror
      branch, only consider monorepo commits since this date (in any format
      accepted by `git log`'s `--since` or `--since-as-filter` parameter).
    required: false
  username:
    description: Name of the user the token belongs to.
    required: true
  user-email:
    description: >
      Email address of the user the token belongs to. If omitted, defaults to
      `${username}@users.noreply.github.com`.
    required: false
  working-directory:
    description: >
      Directory containing the contents of the mirror repositories to push.
      This directory must contain a file `mirrors.txt` that contains, one per
      line, the GitHub repository names (with owner) of the mirrors to push to.
      The contents of each mirror must be in identically-named subdirectories.
    required: true
runs:
  using: composite
  steps:
    - shell: bash
      env:
        API_TOKEN_GITHUB: ${{ inputs.token }}
        BUILD_BASE: ${{ inputs.working-directory }}
        COMMIT_MESSAGE: ${{ inputs.commit-message }}
        DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
        NO_UPSTREAM_REFS: ${{ inputs.no-upstream-refs }}
        SOURCE_DIR: ${{ inputs.source-directory }}
        UPSTREAM_REF_COUNT: ${{ inputs.upstream-ref-count }}
        UPSTREAM_REF_SINCE: ${{ inputs.upstream-ref-since }}
        USER_EMAIL: ${{ inputs.user-email }}
        USER_NAME: ${{ inputs.username }}
      run: $GITHUB_ACTION_PATH/push-to-mirrors.sh
