import { renderHook } from '@testing-library/react';
import useFeaturedImage from '../../use-featured-image';
import useImageGeneratorConfig from '../../use-image-generator-config';
import useMediaDetails from '../../use-media-details';
import { getValidationError, isMediaConvertible } from '../../use-media-restrictions';
import { useConnectionMediaValidation } from '../index';
import type { Connection } from '../../../social-store/types';

jest.mock( '../../use-featured-image', () => jest.fn() );
jest.mock( '../../use-image-generator-config', () => jest.fn() );
jest.mock( '../../use-media-details', () => jest.fn() );
jest.mock( '../../use-media-restrictions', () => ( {
	getValidationError: jest.fn(),
	isMediaConvertible: jest.fn(),
} ) );

const mockUseFeaturedImage = useFeaturedImage as jest.MockedFunction< typeof useFeaturedImage >;
const mockUseImageGeneratorConfig = useImageGeneratorConfig as jest.MockedFunction<
	typeof useImageGeneratorConfig
>;
const mockUseMediaDetails = useMediaDetails as jest.MockedFunction< typeof useMediaDetails >;
const mockGetValidationError = getValidationError as jest.MockedFunction<
	typeof getValidationError
>;
const mockIsMediaConvertible = isMediaConvertible as jest.MockedFunction<
	typeof isMediaConvertible
>;

const makeConnection = ( overrides: Partial< Connection > = {} ): Connection => {
	return {
		connection_id: 'test-123',
		display_name: 'Test',
		external_handle: 'test',
		external_id: '123',
		profile_link: '',
		profile_picture: '',
		service_label: 'Facebook',
		service_name: 'facebook',
		shared: false,
		status: 'ok',
		wpcom_user_id: 1,
		enabled: true,
		...overrides,
	};
};

const MEDIA = [ { id: 10, url: 'http://example.com/img.jpg', type: 'image/jpeg' } ];

describe( 'useConnectionMediaValidation', () => {
	beforeEach( () => {
		jest.clearAllMocks();
		mockUseFeaturedImage.mockReturnValue( 0 );
		mockUseImageGeneratorConfig.mockReturnValue(
			// @ts-expect-error -- partial mock, only isEnabled is used by the hook
			{ isEnabled: false }
		);
		mockUseMediaDetails.mockReturnValue( [ {}, false ] );
		mockGetValidationError.mockReturnValue( null );
		mockIsMediaConvertible.mockReturnValue( false );
	} );

	it( 'should skip validation for SIG source and return no error', () => {
		const { result } = renderHook( () =>
			useConnectionMediaValidation( makeConnection( { media_source: 'sig' } ) )
		);

		expect( result.current ).toEqual( { error: null, isConvertible: false } );
		expect( mockGetValidationError ).not.toHaveBeenCalled();
	} );

	it( 'should pass undefined media ID for "none" source', () => {
		renderHook( () => useConnectionMediaValidation( makeConnection( { media_source: 'none' } ) ) );
		expect( mockUseMediaDetails ).toHaveBeenCalledWith( undefined );
	} );

	it( 'should use featured image ID for "featured-image" source', () => {
		mockUseFeaturedImage.mockReturnValue( 42 );
		renderHook( () =>
			useConnectionMediaValidation( makeConnection( { media_source: 'featured-image' } ) )
		);
		expect( mockUseMediaDetails ).toHaveBeenCalledWith( 42 );
	} );

	it( 'should use attached media ID for "media-library" source', () => {
		renderHook( () =>
			useConnectionMediaValidation(
				makeConnection( { media_source: 'media-library', attached_media: MEDIA } )
			)
		);
		expect( mockUseMediaDetails ).toHaveBeenCalledWith( 10 );
	} );

	it( 'should fall back to featured image ID when attached media is empty', () => {
		mockUseFeaturedImage.mockReturnValue( 42 );
		renderHook( () =>
			useConnectionMediaValidation(
				makeConnection( { media_source: 'media-library', attached_media: [] } )
			)
		);
		expect( mockUseMediaDetails ).toHaveBeenCalledWith( 42 );
	} );

	it( 'should pass hasAttachedMedia=true when media is attached', () => {
		renderHook( () =>
			useConnectionMediaValidation(
				makeConnection( { media_source: 'upload-video', attached_media: MEDIA } )
			)
		);
		expect( mockGetValidationError ).toHaveBeenCalledWith(
			undefined,
			undefined,
			'facebook',
			true,
			false
		);
	} );

	it( 'should pass hasAttachedMedia=false for featured-image source', () => {
		renderHook( () =>
			useConnectionMediaValidation( makeConnection( { media_source: 'featured-image' } ) )
		);
		expect( mockGetValidationError ).toHaveBeenCalledWith(
			undefined,
			undefined,
			'facebook',
			false,
			false
		);
	} );

	it( 'should pass hasAutoGeneratedImage=true for Instagram when SIG is enabled', () => {
		mockUseImageGeneratorConfig.mockReturnValue(
			// @ts-expect-error -- partial mock, only isEnabled is used by the hook
			{ isEnabled: true }
		);
		renderHook( () =>
			useConnectionMediaValidation(
				makeConnection( { service_name: 'instagram-business', media_source: 'none' } )
			)
		);
		expect( mockGetValidationError ).toHaveBeenCalledWith(
			undefined,
			undefined,
			'instagram-business',
			false,
			true
		);
	} );

	it( 'should pass hasAutoGeneratedImage=false for non-Instagram even with SIG enabled', () => {
		mockUseImageGeneratorConfig.mockReturnValue(
			// @ts-expect-error -- partial mock, only isEnabled is used by the hook
			{ isEnabled: true }
		);
		renderHook( () => useConnectionMediaValidation( makeConnection( { media_source: 'none' } ) ) );
		expect( mockGetValidationError ).toHaveBeenCalledWith(
			undefined,
			undefined,
			'facebook',
			false,
			false
		);
	} );

	it( 'should return error and isConvertible from validation functions', () => {
		mockGetValidationError.mockReturnValue( 'FILE_SIZE_ERROR' );
		mockIsMediaConvertible.mockReturnValue( true );

		const { result } = renderHook( () =>
			useConnectionMediaValidation(
				makeConnection( { media_source: 'media-library', attached_media: MEDIA } )
			)
		);

		expect( result.current ).toEqual( { error: 'FILE_SIZE_ERROR', isConvertible: true } );
	} );
} );
