export const JETPACK_SET_INITIAL_STATE = 'JETPACK_SET_INITIAL_STATE';

export const CONNECT_URL_FETCH = 'CONNECT_URL_FETCH';
export const CONNECT_URL_FETCH_FAIL = 'CONNECT_URL_FETCH_FAIL';
export const CONNECT_URL_FETCH_SUCCESS = 'CONNECT_URL_FETCH_SUCCESS';

export const DISCONNECT_SITE = 'DISCONNECT_SITE';
export const DISCONNECT_SITE_FAIL = 'DISCONNECT_SITE_FAIL';
export const DISCONNECT_SITE_SUCCESS = 'DISCONNECT_SITE_SUCCESS';

export const UNLINK_USER = 'UNLINK_USER';
export const UNLINK_USER_FAIL = 'UNLINK_USER_FAIL';
export const UNLINK_USER_SUCCESS = 'UNLINK_USER_SUCCESS';

export const USER_CONNECTION_DATA_FETCH = 'USER_CONNECTION_DATA_FETCH';
export const USER_CONNECTION_DATA_FETCH_FAIL = 'USER_CONNECTION_DATA_FETCH_FAIL';
export const USER_CONNECTION_DATA_FETCH_SUCCESS = 'USER_CONNECTION_DATA_FETCH_SUCCESS';

export const JETPACK_MODULES_LIST_FETCH = 'JETPACK_MODULES_LIST_FETCH';
export const JETPACK_MODULES_LIST_FETCH_FAIL = 'JETPACK_MODULES_LIST_FETCH_FAIL';
export const JETPACK_MODULES_LIST_RECEIVE = 'JETPACK_MODULES_LIST_RECEIVE';
export const JETPACK_MODULE_FETCH = 'JETPACK_MODULE_FETCH';
export const JETPACK_MODULE_FETCH_FAIL = 'JETPACK_MODULE_FETCH_FAIL';
export const JETPACK_MODULE_RECEIVE = 'JETPACK_MODULE_RECEIVE';
export const JETPACK_MODULE_ACTIVATE = 'JETPACK_MODULE_ACTIVATE';
export const JETPACK_MODULE_ACTIVATE_SUCCESS = 'JETPACK_MODULE_ACTIVATE_SUCCESS';
export const JETPACK_MODULE_ACTIVATE_FAIL = 'JETPACK_MODULE_ACTIVATE_FAIL';
export const JETPACK_MODULE_DEACTIVATE = 'JETPACK_MODULE_DEACTIVATE';
export const JETPACK_MODULE_DEACTIVATE_FAIL = 'JETPACK_MODULE_DEACTIVATE_FAIL';
export const JETPACK_MODULE_DEACTIVATE_SUCCESS = 'JETPACK_MODULE_DEACTIVATE_SUCCESS';
export const JETPACK_MODULE_UPDATE_OPTIONS = 'JETPACK_MODULE_UPDATE_OPTIONS';
export const JETPACK_MODULE_UPDATE_OPTIONS_FAIL = 'JETPACK_MODULE_UPDATE_OPTIONS_FAIL';
export const JETPACK_MODULE_UPDATE_OPTIONS_SUCCESS = 'JETPACK_MODULE_UPDATE_OPTIONS_SUCCESS';

export const JETPACK_CONNECTION_STATUS_FETCH = 'JETPACK_CONNECTION_STATUS_FETCH';

export const JUMPSTART_ACTIVATE = 'JUMPSTART_ACTIVATE';
export const JUMPSTART_ACTIVATE_FAIL = 'JUMPSTART_ACTIVATE_FAIL';
export const JUMPSTART_ACTIVATE_SUCCESS = 'JUMPSTART_ACTIVATE_SUCCESS';
export const JUMPSTART_SKIP = 'JUMPSTART_SKIP';
export const JUMPSTART_SKIP_FAIL = 'JUMPSTART_SKIP_FAIL';
export const JUMPSTART_SKIP_SUCCESS = 'JUMPSTART_SKIP_SUCCESS';

export const DASHBOARD_PROTECT_COUNT_FETCH = 'DASHBOARD_PROTECT_COUNT_FETCH';
export const DASHBOARD_PROTECT_COUNT_FETCH_FAIL = 'DASHBOARD_PROTECT_COUNT_FETCH_FAIL';
export const DASHBOARD_PROTECT_COUNT_FETCH_SUCCESS = 'DASHBOARD_PROTECT_COUNT_FETCH_SUCCESS';

export const RESET_OPTIONS = 'RESET_OPTIONS';
export const RESET_OPTIONS_FAIL = 'RESET_OPTIONS_FAIL';
export const RESET_OPTIONS_SUCCESS = 'RESET_OPTIONS_SUCCESS';

export const VAULTPRESS_SITE_DATA_FETCH = 'VAULTPRESS_SITE_DATA_FETCH';
export const VAULTPRESS_SITE_DATA_FETCH_FAIL = 'VAULTPRESS_SITE_DATA_FETCH_FAIL';
export const VAULTPRESS_SITE_DATA_FETCH_SUCCESS = 'VAULTPRESS_SITE_DATA_FETCH_SUCCESS';

export const AKISMET_DATA_FETCH = 'AKISMET_DATA_FETCH';
export const AKISMET_DATA_FETCH_FAIL = 'AKISMET_DATA_FETCH_FAIL';
export const AKISMET_DATA_FETCH_SUCCESS = 'AKISMET_DATA_FETCH_SUCCESS';

export const AKISMET_KEY_CHECK_FETCH = 'AKISMET_KEY_CHECK_FETCH';
export const AKISMET_KEY_CHECK_FETCH_FAIL = 'AKISMET_KEY_CHECK_FETCH_FAIL';
export const AKISMET_KEY_CHECK_FETCH_SUCCESS = 'AKISMET_KEY_CHECK_FETCH_SUCCESS';

export const PLUGIN_UPDATES_FETCH = 'PLUGIN_UPDATES_FETCH';
export const PLUGIN_UPDATES_FETCH_FAIL = 'PLUGIN_UPDATES_FETCH_FAIL';
export const PLUGIN_UPDATES_FETCH_SUCCESS = 'PLUGIN_UPDATES_FETCH_SUCCESS';

export const STATS_SWITCH_TAB = 'STATS_SWITCH_TAB';
export const STATS_DATA_FETCH = 'STATS_DATA_FETCH';
export const STATS_DATA_FETCH_FAIL = 'STATS_DATA_FETCH_FAIL';
export const STATS_DATA_FETCH_SUCCESS = 'STATS_DATA_FETCH_SUCCESS';

export const JETPACK_SETTINGS_FETCH = 'JETPACK_SETTINGS_FETCH';
export const JETPACK_SETTINGS_FETCH_RECEIVE = 'JETPACK_SETTINGS_FETCH_RECEIVE';
export const JETPACK_SETTINGS_FETCH_FAIL = 'JETPACK_SETTINGS_FETCH_FAIL';
export const JETPACK_SETTING_UPDATE = 'JETPACK_SETTING_UPDATE';
export const JETPACK_SETTING_UPDATE_SUCCESS = 'JETPACK_SETTING_UPDATE_SUCCESS';
export const JETPACK_SETTING_UPDATE_FAIL = 'JETPACK_SETTING_UPDATE_FAIL';
export const JETPACK_SETTINGS_UPDATE = 'JETPACK_SETTINGS_UPDATE';
export const JETPACK_SETTINGS_UPDATE_FAIL = 'JETPACK_SETTINGS_UPDATE_FAIL';
export const JETPACK_SETTINGS_UPDATE_SUCCESS = 'JETPACK_SETTINGS_UPDATE_SUCCESS';
export const JETPACK_SETTINGS_SET_UNSAVED_FLAG = 'JETPACK_SETTINGS_SET_UNSAVED_FLAG';
export const JETPACK_SETTINGS_CLEAR_UNSAVED_FLAG = 'JETPACK_SETTINGS_CLEAR_UNSAVED_FLAG';

export const JETPACK_SITE_DATA_FETCH = 'JETPACK_SITE_DATA_FETCH';
export const JETPACK_SITE_DATA_FETCH_RECEIVE = 'JETPACK_SITE_DATA_FETCH_RECEIVE';
export const JETPACK_SITE_DATA_FETCH_FAIL = 'JETPACK_SITE_DATA_FETCH_FAIL';
export const JETPACK_SITE_FEATURES_FETCH = 'JETPACK_SITE_FEATURES_FETCH';
export const JETPACK_SITE_FEATURES_FETCH_RECEIVE = 'JETPACK_SITE_FEATURES_FETCH_RECEIVE';
export const JETPACK_SITE_FEATURES_FETCH_FAIL = 'JETPACK_SITE_FEATURES_FETCH_FAIL';

export const JETPACK_ACTION_NOTICES_DISMISS = 'JETPACK_ACTION_NOTICES_DISMISS';

export const JETPACK_NOTICES_DISPATCH_TYPE = 'JETPACK_NOTICES_DISPATCH_TYPE';
export const JETPACK_NOTICES_DISMISS = 'JETPACK_NOTICES_DISMISS';
export const JETPACK_NOTICES_DISMISS_FAIL = 'JETPACK_NOTICES_DISMISS_FAIL';
export const JETPACK_NOTICES_DISMISS_SUCCESS = 'JETPACK_NOTICES_DISMISS_SUCCESS';

export const JETPACK_PLUGINS_DATA_FETCH = 'JETPACK_PLUGINS_DATA_FETCH';
export const JETPACK_PLUGINS_DATA_FETCH_RECEIVE = 'JETPACK_PLUGINS_DATA_FETCH_RECEIVE';
export const JETPACK_PLUGINS_DATA_FETCH_FAIL = 'JETPACK_PLUGINS_DATA_FETCH_FAIL';

export const JETPACK_SEARCH_TERM = 'JETPACK_SEARCH_TERM';
export const JETPACK_SEARCH_FOCUS = 'JETPACK_SEARCH_FOCUS';
export const JETPACK_SEARCH_BLUR = 'JETPACK_SEARCH_BLUR';

export const DEV_CARD_DISPLAY = 'DEV_CARD_DISPLAY';
export const DEV_CARD_HIDE = 'DEV_CARD_HIDE';
export const MOCK_SWITCH_USER_PERMISSIONS = 'MOCK_SWITCH_USER_PERMISSIONS';
export const MOCK_SWITCH_THREATS = 'MOCK_SWITCH_THREATS';

export const REWIND_STATUS_FETCH = 'REWIND_STATUS_FETCH';
export const REWIND_STATUS_FETCH_RECEIVE = 'REWIND_STATUS_FETCH_RECEIVE';
export const REWIND_STATUS_FETCH_FAIL = 'REWIND_STATUS_FETCH_FAIL';

export const MOCK_SWITCH_REWIND_STATE = 'MOCK_SWITCH_REWIND_STATE';
