export const JETPACK_SET_INITIAL_STATE = 'JETPACK_SET_INITIAL_STATE';

export const CONNECT_URL_FETCH = 'CONNECT_URL_FETCH';
export const CONNECT_URL_FETCH_FAIL = 'CONNECT_URL_FETCH_FAIL';
export const CONNECT_URL_FETCH_SUCCESS = 'CONNECT_URL_FETCH_SUCCESS';

export const DISCONNECT_SITE = 'DISCONNECT_SITE';
export const DISCONNECT_SITE_FAIL = 'DISCONNECT_SITE_FAIL';
export const DISCONNECT_SITE_SUCCESS = 'DISCONNECT_SITE_SUCCESS';

export const UNLINK_USER = 'UNLINK_USER';
export const UNLINK_USER_FAIL = 'UNLINK_USER_FAIL';
export const UNLINK_USER_SUCCESS = 'UNLINK_USER_SUCCESS';

export const USER_CONNECTION_DATA_FETCH = 'USER_CONNECTION_DATA_FETCH';
export const USER_CONNECTION_DATA_FETCH_FAIL = 'USER_CONNECTION_DATA_FETCH_FAIL';
export const USER_CONNECTION_DATA_FETCH_SUCCESS = 'USER_CONNECTION_DATA_FETCH_SUCCESS';

export const JETPACK_MODULES_LIST_FETCH = 'JETPACK_MODULES_LIST_FETCH';
export const JETPACK_MODULES_LIST_FETCH_FAIL = 'JETPACK_MODULES_LIST_FETCH_FAIL';
export const JETPACK_MODULES_LIST_RECEIVE = 'JETPACK_MODULES_LIST_RECEIVE';
export const JETPACK_MODULE_FETCH = 'JETPACK_MODULE_FETCH';
export const JETPACK_MODULE_FETCH_FAIL = 'JETPACK_MODULE_FETCH_FAIL';
export const JETPACK_MODULE_RECEIVE = 'JETPACK_MODULE_RECEIVE';
export const JETPACK_MODULE_ACTIVATE = 'JETPACK_MODULE_ACTIVATE';
export const JETPACK_MODULE_ACTIVATE_SUCCESS = 'JETPACK_MODULE_ACTIVATE_SUCCESS';
export const JETPACK_MODULE_ACTIVATE_FAIL = 'JETPACK_MODULE_ACTIVATE_FAIL';
export const JETPACK_MODULE_DEACTIVATE = 'JETPACK_MODULE_DEACTIVATE';
export const JETPACK_MODULE_DEACTIVATE_FAIL = 'JETPACK_MODULE_DEACTIVATE_FAIL';
export const JETPACK_MODULE_DEACTIVATE_SUCCESS = 'JETPACK_MODULE_DEACTIVATE_SUCCESS';
export const JETPACK_MODULE_UPDATE_OPTION = 'JETPACK_MODULE_UPDATE_OPTION';
export const JETPACK_MODULE_UPDATE_OPTION_FAIL = 'JETPACK_MODULE_UPDATE_OPTION_FAIL';
export const JETPACK_MODULE_UPDATE_OPTION_SUCCESS = 'JETPACK_MODULE_UPDATE_OPTION_SUCCESS';

export const JETPACK_CONNECTION_STATUS_FETCH = 'JETPACK_CONNECTION_STATUS_FETCH';

export const JUMPSTART_ACTIVATE = 'JUMPSTART_ACTIVATE';
export const JUMPSTART_ACTIVATE_FAIL = 'JUMPSTART_ACTIVATE_FAIL';
export const JUMPSTART_ACTIVATE_SUCCESS = 'JUMPSTART_ACTIVATE_SUCCESS';
export const JUMPSTART_SKIP = 'JUMPSTART_SKIP';
export const JUMPSTART_SKIP_FAIL = 'JUMPSTART_SKIP_FAIL';
export const JUMPSTART_SKIP_SUCCESS = 'JUMPSTART_SKIP_SUCCESS';

export const DASHBOARD_PROTECT_COUNT_FETCH = 'DASHBOARD_PROTECT_COUNT_FETCH';
export const DASHBOARD_PROTECT_COUNT_FETCH_FAIL = 'DASHBOARD_PROTECT_COUNT_FETCH_FAIL';
export const DASHBOARD_PROTECT_COUNT_FETCH_SUCCESS = 'DASHBOARD_PROTECT_COUNT_FETCH_SUCCESS';

export const RESET_OPTIONS = 'RESET_OPTIONS';
export const RESET_OPTIONS_FAIL = 'RESET_OPTIONS_FAIL';
export const RESET_OPTIONS_SUCCESS = 'RESET_OPTIONS_SUCCESS';

export const VAULTPRESS_SITE_DATA_FETCH = 'VAULTPRESS_SITE_DATA_FETCH';
export const VAULTPRESS_SITE_DATA_FETCH_FAIL = 'VAULTPRESS_SITE_DATA_FETCH_FAIL';
export const VAULTPRESS_SITE_DATA_FETCH_SUCCESS = 'VAULTPRESS_SITE_DATA_FETCH_SUCCESS';

export const MONITOR_LAST_DOWNTIME_FETCH = 'MONITOR_LAST_DOWNTIME_FETCH';
export const MONITOR_LAST_DOWNTIME_FETCH_FAIL = 'MONITOR_LAST_DOWNTIME_FETCH_FAIL';
export const MONITOR_LAST_DOWNTIME_FETCH_SUCCESS = 'MONITOR_LAST_DOWNTIME_FETCH_SUCCESS';

export const AKISMET_DATA_FETCH = 'AKISMET_DATA_FETCH';
export const AKISMET_DATA_FETCH_FAIL = 'AKISMET_DATA_FETCH_FAIL';
export const AKISMET_DATA_FETCH_SUCCESS = 'AKISMET_DATA_FETCH_SUCCESS';

export const PLUGIN_UPDATES_FETCH = 'PLUGIN_UPDATES_FETCH';
export const PLUGIN_UPDATES_FETCH_FAIL = 'PLUGIN_UPDATES_FETCH_FAIL';
export const PLUGIN_UPDATES_FETCH_SUCCESS = 'PLUGIN_UPDATES_FETCH_SUCCESS';

export const STATS_SWITCH_TAB = 'STATS_SWITCH_TAB';

export const JETPACK_SETTINGS_FETCH = 'JETPACK_SETTINGS_FETCH';
export const JETPACK_SETTINGS_FETCH_RECEIVE = 'JETPACK_SETTINGS_FETCH_RECEIVE';
export const JETPACK_SETTINGS_FETCH_FAIL = 'JETPACK_SETTINGS_FETCH_FAIL';
export const JETPACK_SETTING_UPDATE = 'JETPACK_SETTING_UPDATE';
export const JETPACK_SETTING_UPDATE_SUCCESS = 'JETPACK_SETTING_UPDATE_SUCCESS';
export const JETPACK_SETTING_UPDATE_FAIL = 'JETPACK_SETTING_UPDATE_FAIL';
