export const JETPACK_SET_INITIAL_STATE = 'JETPACK_SET_INITIAL_STATE';

export const JETPACK_MODULES_LIST_FETCH = 'JETPACK_MODULES_LIST_FETCH';
export const JETPACK_MODULES_LIST_FETCH_FAIL = 'JETPACK_MODULES_LIST_FETCH_FAIL';
export const JETPACK_MODULES_LIST_RECEIVE = 'JETPACK_MODULES_LIST_RECEIVE';
export const JETPACK_MODULE_FETCH = 'JETPACK_MODULE_FETCH';
export const JETPACK_MODULE_FETCH_FAIL = 'JETPACK_MODULE_FETCH_FAIL';
export const JETPACK_MODULE_RECEIVE = 'JETPACK_MODULE_RECEIVE';
export const JETPACK_MODULE_ACTIVATE = 'JETPACK_MODULE_ACTIVATE';
export const JETPACK_MODULE_ACTIVATE_SUCCESS = 'JETPACK_MODULE_ACTIVATE_SUCCESS';
export const JETPACK_MODULE_ACTIVATE_FAIL = 'JETPACK_MODULE_ACTIVATE_FAIL';
export const JETPACK_MODULE_DEACTIVATE = 'JETPACK_MODULE_DEACTIVATE';
export const JETPACK_MODULE_DEACTIVATE_FAIL = 'JETPACK_MODULE_DEACTIVATE_FAIL';
export const JETPACK_MODULE_DEACTIVATE_SUCCESS = 'JETPACK_MODULE_DEACTIVATE_SUCCESS';
