# Basic configuration for CodeClimate.
# This basic configuration can then be used and extended up in other repositories,
# or in this one, using the prepare step:
# https://docs.codeclimate.com/docs/configuring-the-prepare-step
#
# Here is how your codeclimate file extending Jetpack's one should look like:
# prepare:
# fetch:
#   - url: "https://raw.githubusercontent.com/automattic/jetpack/master/.github/codeclimate-base.yml"
#     path: "codeclimate-base.yml"
---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
    config:
      standard: "WordPress"
  phpmd:
    enabled: true
  eslint:
    enabled: true
    channel: "eslint-5"
    config:
      config: "/.eslintrc.js"
  scss-lint:
    enabled: true
  markdownlint:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.scss"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.php"
  - "**.md"
exclude_paths:
  - "**/.github/**"
  - "**/tests/**"
  - "**.png"
  - "**.jpg"
  - "**.gif"
  - "gulpfile.js"
  - "composer.lock"
  - ".phpcs.xml.dist"
  - "**.json"
  - "**.svnignore"
  - "**.travis.yml"
  - "**.gitignore"
  - "**.eslintrc.js"
  - "**.editorconfig"
  - "**.pot"
  - "**.txt"
  - "**-min.js"
  - "**-min.css"
  - "**.dist"
  - "**.sh"
