# This is used by the Gardening Action, in the triage job
"[Status] Needs Package Release":
- 'projects/packages/*'
- 'projects/packages/*/*'
- 'projects/packages/*/*/*'
- 'projects/packages/*/*/*/*'
