# Configuration for probot-stale - https://github.com/probot/stale

# Number of days of inactivity before a stale Issue or Pull Request is closed.
# Set to false to disable. If disabled, issues still need to be closed manually, but will remain marked as stale.
daysUntilClose: false

# Number of days of inactivity before an Issue or Pull Request becomes stale
daysUntilStale: 180 # 6 months

# Issues with these labels will never be considered stale
exemptLabels:
  - "[Pri] High"
  - "[Pri] BLOCKER"
  - "[Type] Good For Community"
  - "[Type] Good First Bug"
  - "FixTheFlows"

# Set to true to ignore issues in a project (defaults to false)
exemptProjects: true

# Set to true to ignore issues in a milestone (defaults to false)
exemptMilestones: false

# Label to use when marking an issue as stale
staleLabel: "[Status] Stale"

# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false

# Limit the number of actions per hour, from 1-30. Default is 30
limitPerRun: 2

# Optionally, specify configuration settings that are specific to just 'issues' or 'pulls':
issues:
  # Comment to post when marking an issue as stale. Set to `false` to disable
  markComment: >
    <p>This issue has been marked as stale. This happened because:</p>

    <ul>
      <li>It has been inactive in the past 6 months.</li>
      <li>It hasn’t been labeled `[Pri] Blocker`, `[Pri] High`.</li>
    </ul>

    <p>No further action is needed. But it's worth checking if this ticket has clear
    reproduction steps and it is still reproducible. Feel free to close this issue
    if you think it's not valid anymore — if you do, please add a brief
    explanation.</p>

pulls:
  # Number of days of inactivity before an Issue or Pull Request becomes stale
  daysUntilStale: 90 # 3 months
  markComment: >
    <p>This PR has been marked as stale. This happened because:</p>

    <ul>
      <li>It has been inactive in the past 3 months.</li>
      <li>It hasn’t been labeled `[Pri] Blocker`, `[Pri] High`.</li>
    </ul>

    <p>No further action is needed. But it's worth checking if this PR has clear
    testing instructions, is it up to date with master, and it is still valid.
    Feel free to close this issue if you think it's not valid anymore — if you
    do, please add a brief explanation.</p>
