<?php
/**
 * Script to build modules/photon-cdn/jetpack-manifest.php
 *
 * @package Jetpack
 */

// phpcs:disable WordPress.WP.AlternativeFunctions

// The repo root path.
$jetpack_path = dirname( __DIR__ ) . '/';

// Build an iterator over all files in the repo that match the regex in the RegexIterator.
$directory = new RecursiveDirectoryIterator( $jetpack_path );
$iterator  = new RecursiveIteratorIterator( $directory );
$regex     = new RegexIterator( $iterator, '/^.+\.(css|js)$/i', RecursiveRegexIterator::GET_MATCH );

$ignore_paths = array(
	'_inc/client/',
	'extensions/',
	'logs/',
	'node_modules/',
	'tests/',
	'tools/',
	'vendor/',
);

$manifest = array();
foreach ( $regex as $path_to_file => $value ) {
	$path_from_repo_root = str_replace( $jetpack_path, '', $path_to_file );

	// Ignore top-level files.
	if ( false === strpos( $path_from_repo_root, '/' ) ) {
		continue;
	}

	// Ignore explicit ignore list.
	foreach ( $ignore_paths as $ignore_path ) {
		if ( 0 === strpos( $path_from_repo_root, $ignore_path ) ) {
			continue 2;
		}
	}

	$manifest[] = $path_from_repo_root;
}

sort( $manifest );
$export = var_export( $manifest, true ); // phpcs:ignore WordPress.PHP.DevelopmentFunctions.error_log_var_export

file_put_contents(
	$jetpack_path . 'modules/photon-cdn/jetpack-manifest.php',
	"<?php
// This file is autogenerated by bin/build-asset-cdn-json.php

\$assets = $export;\n"
);
