export const VARIANTS_MAPPING = {
	'headline-medium': 'h1',
	'headline-small': 'h2',
	'headline-small-regular': 'h2',
	'title-medium': 'h3',
	'title-medium-semi-bold': 'h3',
	'title-small': 'h4',
	body: 'p',
	'body-small': 'p',
	'body-extra-small': 'p',
	'body-extra-small-bold': 'p',
	label: 'p',
} as const;

export const BOX_MODEL_VALUES = [
	'mt',
	'mr',
	'mb',
	'ml',
	'mx',
	'my',
	'm',
	'pt',
	'pr',
	'pb',
	'pl',
	'px',
	'py',
	'p',
] as const;
