name: "Send tests results to Slack"
description: "Send Slack notifications with test results."
branding:
  icon: 'activity'
  color: 'green'
inputs:
  github_token:
    description: "GitHub access token"
    required: true
    default: ${{ github.token }}
  slack_token:
    description: "Slack Bot access token"
    required: true
    default: ""
  slack_channel:
    description: "Slack channel ID where to send messages"
    required: true
    default: ""
runs:
  using: node16
  main: "dist/index.js"
