import { act, render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import DetailsPanel from '..';
import type { DetailsPanelProps } from '../../../types';

jest.mock( '@automattic/jetpack-components', () => ( {
	Button: ( { children, onClick } ) => <button onClick={ onClick }>{ children }</button>,
} ) );

const validDescription = '00:00 Intro\n00:10 Backups: getting started\n00:20 Summary';
const baseProps = {
	chapter: null,
	isAutoGeneratedChapter: false,
	updateError: null,
	filename: 'video.mp4',
	setAttributes: jest.fn(),
	isRequestingVideoData: false,
	videoBelongToSite: true,
};

const renderDetails = ( description: string, props: Partial< DetailsPanelProps > = {} ) =>
	render( <DetailsPanel { ...baseProps } attributes={ { description } } { ...props } /> );

describe( 'description chapter validation', () => {
	beforeEach( () => {
		jest.useFakeTimers();
	} );

	afterEach( () => {
		jest.clearAllTimers();
		jest.useRealTimers();
	} );

	it.each( [
		[ '00:00 Intro', 'At least three chapters are required.' ],
		[ '00:00 Intro\n00:10 Next', 'At least three chapters are required.' ],
		[ '00:01 Intro\n00:11 Next\n00:21 End', 'The first chapter must start at 0:00.' ],
		[ '00:00 Intro\n00:10\n00:20 End', 'Every chapter needs a title.' ],
		[ '00:00 Intro\n00:09 Next\n00:20 End', 'Chapters must be at least 10 seconds apart.' ],
		[
			'00:00 Intro\n00:10 Next\n00:10 End',
			'Chapters must be in ascending order without repeated timestamps.',
		],
	] )( 'explains why %s cannot be saved as chapters', ( description, message ) => {
		renderDetails( description );

		expect( screen.getByText( message ) ).toBeInTheDocument();
		expect( screen.getByRole( 'button', { name: 'chapter format' } ) ).toBeInTheDocument();
	} );

	it( 'shows every violated rule without repeating messages for multiple rows', () => {
		renderDetails( '00:01\n00:05' );

		expect( screen.getByText( 'At least three chapters are required.' ) ).toBeInTheDocument();
		expect( screen.getByText( 'The first chapter must start at 0:00.' ) ).toBeInTheDocument();
		expect( screen.getAllByText( 'Every chapter needs a title.' ) ).toHaveLength( 1 );
		expect( screen.getByText( 'Chapters must be at least 10 seconds apart.' ) ).toBeInTheDocument();
	} );

	it.each( [
		'',
		'A video description without chapters.',
		validDescription,
		'00:20 End\n00:00 Intro\n00:10 Next',
		'Intro - 0:00\nNext - 0:10\nEnd - 0:20',
		'(0:00:00) Intro\n(0:00:10) Next\n(0:00:20) End',
	] )( 'does not warn for supported descriptions: %s', description => {
		renderDetails( description );

		expect( screen.queryByRole( 'button', { name: 'chapter format' } ) ).not.toBeInTheDocument();
		expect( screen.getByRole( 'button', { name: 'Learn how' } ) ).toBeInTheDocument();
	} );

	it( 'updates the warning after edits and clears it after corrections or removing chapters', () => {
		const { rerender } = renderDetails( validDescription );
		const updateDescription = ( description: string ) => {
			rerender( <DetailsPanel { ...baseProps } attributes={ { description } } /> );
			act( () => jest.advanceTimersByTime( 3000 ) );
		};

		updateDescription( '00:00 Intro\n00:10 Next' );
		expect( screen.getByText( 'At least three chapters are required.' ) ).toBeInTheDocument();

		updateDescription( '00:00 Intro\n00:05 Next\n00:20 End' );
		expect( screen.queryByText( 'At least three chapters are required.' ) ).not.toBeInTheDocument();
		expect( screen.getByText( 'Chapters must be at least 10 seconds apart.' ) ).toBeInTheDocument();

		updateDescription( validDescription );
		expect( screen.queryByRole( 'button', { name: 'chapter format' } ) ).not.toBeInTheDocument();

		updateDescription( '00:00 Intro' );
		expect( screen.getByText( 'At least three chapters are required.' ) ).toBeInTheDocument();
		updateDescription( 'No chapters here.' );
		expect( screen.queryByRole( 'button', { name: 'chapter format' } ) ).not.toBeInTheDocument();
	} );

	it( 'preserves the format help dialog', async () => {
		const user = userEvent.setup( { advanceTimers: jest.advanceTimersByTime } );
		renderDetails( '00:00 Intro' );

		await user.click( screen.getByRole( 'button', { name: 'chapter format' } ) );
		expect( screen.getByRole( 'dialog', { name: 'Chapters in VideoPress' } ) ).toBeInTheDocument();
		await user.click( screen.getByRole( 'button', { name: 'Got it, thanks' } ) );
		expect( screen.queryByRole( 'dialog' ) ).not.toBeInTheDocument();
	} );

	it( 'keeps the uploaded VTT notice instead of description validation', () => {
		renderDetails( '00:00 Intro', {
			chapter: { src: 'manual-chapters.vtt', kind: 'chapters', label: 'Chapters', srcLang: 'en' },
		} );

		expect( screen.queryByText( 'At least three chapters are required.' ) ).not.toBeInTheDocument();
		expect(
			screen.getByText( /You already have chapter information on an attached VTT file/, {
				selector: 'p',
			} )
		).toBeInTheDocument();
	} );
} );
