module.exports = {
	root: true,
	parser: 'babel-eslint',
	// extends: [ 'wpcalypso/react', 'plugin:jsx-a11y/recommended', 'prettier', 'prettier/react' ],
	env: {
		browser: true,
		es6: true,
		mocha: true,
		node: true,
		jquery: true,
	},
	parserOptions: {
		ecmaVersion: 2019,
		ecmaFeatures: {
			jsx: true,
		},
	},
	plugins: [ 'jquery' ],
	rules: {
		// Disable noisy built in rules
		'jsdoc/require-jsdoc': 'off',
		'jsdoc/no-undefined-types': 'off',
		'jsdoc/newline-after-description': 'off',
		'jsdoc/check-tag-names': 'off',
		'no-extra-boolean-cast': 'off',
		'react-hooks/exhaustive-deps': 'off',
		'no-unused-vars': 'off',
		'no-unused-expressions': 'off',
		curly: 'off',
		'no-prototype-builtins': 'off',
		'no-redeclare': 'off',
		'no-shadow-restricted-names': 'off',
		'no-empty': 'off',
		eqeqeq: 'off',
		'no-console': 'off',
		'no-undef': 'off',

		// Let's get rid of jQuery
		'jquery/no-ajax': 2,
		'jquery/no-ajax-events': 2,
		'jquery/no-animate': 2,
		'jquery/no-attr': 2,
		'jquery/no-bind': 2,
		'jquery/no-class': 2,
		'jquery/no-clone': 2,
		'jquery/no-closest': 2,
		'jquery/no-css': 2,
		'jquery/no-data': 2,
		'jquery/no-deferred': 2,
		'jquery/no-delegate': 2,
		'jquery/no-each': 2,
		'jquery/no-extend': 2,
		'jquery/no-fade': 2,
		'jquery/no-filter': 2,
		'jquery/no-find': 2,
		'jquery/no-global-eval': 2,
		'jquery/no-grep': 2,
		'jquery/no-has': 2,
		'jquery/no-hide': 2,
		'jquery/no-html': 2,
		'jquery/no-in-array': 2,
		'jquery/no-is-array': 2,
		'jquery/no-is-function': 2,
		'jquery/no-is': 2,
		'jquery/no-load': 2,
		'jquery/no-map': 2,
		'jquery/no-merge': 2,
		'jquery/no-param': 2,
		'jquery/no-parent': 2,
		'jquery/no-parents': 2,
		'jquery/no-parse-html': 2,
		'jquery/no-prop': 2,
		'jquery/no-proxy': 2,
		'jquery/no-ready': 2,
		'jquery/no-serialize': 2,
		'jquery/no-show': 2,
		'jquery/no-size': 2,
		'jquery/no-sizzle': 2,
		'jquery/no-slide': 2,
		'jquery/no-submit': 2,
		'jquery/no-text': 2,
		'jquery/no-toggle': 2,
		'jquery/no-trigger': 2,
		'jquery/no-trim': 2,
		'jquery/no-val': 2,
		'jquery/no-when': 2,
		'jquery/no-wrap': 2,
	},
};
