comment: false
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 3%

ignore:
  - tests

github_checks:
  annotations: false

flag_management:
  default_rules:
    carryforward: true
