packages:
  - projects/*/*
  - '!projects/js-packages/jetpack-cli'
  - projects/plugins/*/tests/e2e
  - tools/cli
  - tools/e2e-commons
  - tools/js-tools
  - tools/performance
  - .github/files/coverage-munger

engineStrict: true
managePackageManagerVersions: false
preferWorkspacePackages: true

# Be strict about peer deps
autoInstallPeers: false
dedupePeerDependents: false
strictPeerDependencies: true

# No hoisting by default.
hoistPattern: []

# Silence this warning. Our `jetpack dependencies build-order` (also used by `jetpack build --all`) checks for cycles itself, plus it has a way to indicate that a dep is only for testing.
ignoreWorkspaceCycles: true

# Package compromise avoidance: let new releases age a day, and don't allow trust downgrades unless explicitly excepted.
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  # Packages we often want to immediately update after releasing them.
  - '@automattic/*'
  - '@woocommerce/*'
  - '@wordpress/*'
trustPolicy: no-downgrade
trustPolicyExclude:
  # https://github.com/paulmillr/chokidar/issues/1440
  - chokidar@4.0.3

  # Don't know why 5.1.0 had provenance but 5.1.1 doesn't. But both are over a year old and there's nothing suspicious in the diff. 🤷
  - reselect@5.1.1

  # Packages where newer majors have provenance but we're still on an older one.
  - '@octokit/endpoint@9.0.6'
  - '@octokit/plugin-paginate-rest@9.2.2'
  - '@oxc-parser/binding-darwin-arm64@0.78.0'
  - '@oxc-parser/binding-darwin-x64@0.78.0'
  - '@oxc-parser/binding-linux-arm64-gnu@0.78.0'
  - '@oxc-parser/binding-linux-arm64-musl@0.78.0'
  - '@oxc-parser/binding-linux-arm-gnueabihf@0.78.0'
  - '@oxc-parser/binding-linux-x64-gnu@0.78.0'
  - '@oxc-parser/binding-linux-x64-musl@0.78.0'
  - '@oxc-parser/binding-wasm32-wasi@0.78.0'
  - '@oxc-parser/binding-win32-arm64-msvc@0.78.0'
  - '@oxc-parser/binding-win32-x64-msvc@0.78.0'
  - rxjs@7.8.2
  - semver@6.3.1
  - svelte@4.2.19
  - undici@5.29.0
  - undici-types@6.21.0

# Package compromise avoidance: require dep build script approval.
strictDepBuilds: true
verifyDepsBeforeRun: install
allowBuilds:
  # Tries to download/install stuff if optional deps weren't installed.
  '@swc/core': false
  esbuild: false
  unrs-resolver: false
  # Attempt to show "remember to install other stuff" spam.
  svelte-preprocess: false
  # Attempt to show "support me" spam.
  core-js: false
  print-this: false

# Package compromise avoidance: Block odd protocols in subdeps
blockExoticSubdeps: true

# Dependencies needing patching.
patchedDependencies:
  # uuid up to v11 had CommonJS files with ESM content too.
  # No bug report, because it's already fixed in the latest versions.
  'uuid@<11': .pnpm-patches/uuid.patch

overrides:
  '@wordpress/is-shallow-equal': 'next'
