<?php
/**
 * Shared base for in-wp-admin pages that prompt WordPress.com Simple and WoA sites
 * to upgrade, or to transfer to WoA, before a hosting feature can run.
 *
 * @package automattic/jetpack-mu-wpcom
 */

namespace Automattic\Jetpack\Jetpack_Mu_Wpcom;

use Automattic\Jetpack\Constants;
use Automattic\Jetpack\WP_Build_Polyfills\WP_Build_Polyfills;

/**
 * Registers a hosting feature's admin page and its wp-build assets.
 *
 * Each page subclasses this, overriding the page constants and has_feature().
 */
abstract class WPCOM_Hosting_Feature_Page {

	/**
	 * Admin page slug. Matches the page the Jetpack plugin serves once the feature is live on
	 * WoA, so the URL survives a transfer.
	 */
	const MENU_SLUG = '';

	/**
	 * Page name for wp-build, as declared in routes/<page>/package.json.
	 *
	 * Deliberately not the menu slug: wp-build derives its own page slug and render
	 * function from this name.
	 */
	const WP_BUILD_PAGE = '';

	/**
	 * Render callback generated by wp-build in build/pages/<page>/page-wp-admin.php.
	 */
	const RENDER_CALLBACK = '';

	/**
	 * Document title of the page. A product name, so not translated.
	 */
	const PAGE_TITLE = '';

	/**
	 * Menu entry label. A product name, so not translated.
	 */
	const MENU_TITLE = '';

	/**
	 * `admin_menu` priority for register_page().
	 */
	const REGISTER_PRIORITY = 999998;

	/**
	 * Calypso flow that initiates the transfer, reports progress and returns here.
	 */
	const TRANSFER_FLOW_URL = 'https://wordpress.com/setup/transferring-hosted-site';

	/**
	 * Tracks context recorded for the WoA transfer.
	 */
	const TRANSFER_CONTEXT = 'jetpack_product_activation';

	/**
	 * Global the page's boot script reads its state from.
	 */
	const INITIAL_STATE_VAR = 'wpcomHostingFeatureInitialState';

	/**
	 * Site has no plan that includes the feature. Offer an upgrade.
	 */
	const STATE_UPGRADE = 'upgrade';

	/**
	 * A transfer to WoA is already running or queued. Offer nothing; report status.
	 */
	const STATE_IN_PROGRESS = 'in_progress';

	/**
	 * Site has the plan and can transfer. Offer activation.
	 */
	const STATE_ACTIVATE = 'activate';

	/**
	 * Whether each page registered its slug on this request, keyed by class.
	 *
	 * @var bool[]
	 */
	private static $owns_page = array();

	/**
	 * The screen ID displaced by alias_screen_id(), keyed by class.
	 *
	 * @var string[]
	 */
	private static $displaced_screen_id = array();

	/**
	 * Whether the site's plan includes the feature. Each page overrides this; the default
	 * offers the upgrade, the one prompt that is never wrong for a site of unknown plan.
	 *
	 * @return bool
	 */
	public static function has_feature() {
		return false;
	}

	/**
	 * Boot the page, loading the wp-build assets only on the page itself.
	 *
	 * @return void
	 */
	public static function init() {
		if ( ! static::should_register() ) {
			return;
		}

		// After Admin_Menu (1000) so a claimed slug is visible, and before wpcom_add_jetpack_submenu()
		// (999999), which hides the entry from the sidebar.
		add_action( 'admin_menu', array( static::class, 'register_page' ), self::REGISTER_PRIORITY );

		if ( ! static::is_page_request() ) {
			return;
		}

		self::load_wp_build();

		// wp-build's generated enqueue runs at the default priority 10; the alias is
		// scoped to that one pass so nothing else sees the rewritten screen.
		add_action( 'admin_enqueue_scripts', array( static::class, 'alias_screen_id' ), 9 );
		add_action( 'admin_enqueue_scripts', array( static::class, 'restore_screen_id' ), 11 );
		add_action( 'admin_enqueue_scripts', array( static::class, 'enqueue_initial_state' ), 20 );
	}

	/**
	 * Whether the site runs on WordPress.com's Atomic infrastructure.
	 *
	 * Read through Constants rather than `defined()` so tests can exercise both
	 * platforms in one process.
	 *
	 * @return bool
	 */
	public static function is_atomic() {
		return Constants::is_true( 'IS_ATOMIC' );
	}

	/**
	 * Whether this page should claim its slug at all.
	 *
	 * A plan that includes the feature only makes it live on Atomic infrastructure, so on
	 * WoA an entitled site already has it and this page steps aside. A Simple site is never
	 * Atomic, so the page always applies there.
	 *
	 * @return bool
	 */
	public static function should_register() {
		if ( ! self::is_atomic() ) {
			return true;
		}

		return ! static::has_feature();
	}

	/**
	 * Whether the current request targets this admin page.
	 *
	 * @return bool
	 */
	public static function is_page_request() {
		// admin-ajax.php is also `is_admin()`, and has no menu, screen or enqueue pass to set up.
		if ( ! is_admin() || 'admin.php' !== ( $GLOBALS['pagenow'] ?? '' ) ) {
			return false;
		}

		// phpcs:ignore WordPress.Security.NonceVerification.Recommended -- Read-only routing check; no form data is processed.
		return isset( $_GET['page'] ) && static::MENU_SLUG === sanitize_text_field( wp_unslash( $_GET['page'] ) );
	}

	/**
	 * Register the page, unless something else already serves the slug.
	 *
	 * @return void
	 */
	public static function register_page() {
		// A second entry under a slug someone else owns would leave two.
		if ( static::slug_is_claimed() ) {
			return;
		}

		self::$owns_page[ static::class ] = true;

		// build/build.php defines the render callback but only loads on this page's
		// own request, so elsewhere fall back rather than fataling.
		$callback = function_exists( static::RENDER_CALLBACK )
			? static::RENDER_CALLBACK
			: '__return_empty_string';

		add_submenu_page(
			'jetpack',
			static::PAGE_TITLE,
			static::MENU_TITLE,
			'manage_options',
			static::MENU_SLUG,
			$callback
		);
	}

	/**
	 * Whether this page registered its slug on this request.
	 *
	 * @return bool
	 */
	public static function owns_page() {
		return ! empty( self::$owns_page[ static::class ] );
	}

	/**
	 * Reset the registration state. Test seam; production sets this once per request.
	 *
	 * @return void
	 */
	public static function reset() {
		unset( self::$owns_page[ static::class ], self::$displaced_screen_id[ static::class ] );
	}

	/**
	 * Whether something has already registered this page's slug.
	 *
	 * Jetpack plugins serve their pages through `Admin_Menu` at `admin_menu` priority
	 * 1000 — before this page's own hook — so the entry is there to find.
	 *
	 * @return bool
	 */
	public static function slug_is_claimed() {
		global $submenu;

		if ( empty( $submenu['jetpack'] ) || ! is_array( $submenu['jetpack'] ) ) {
			return false;
		}

		foreach ( $submenu['jetpack'] as $item ) {
			if ( is_array( $item ) && isset( $item[2] ) && static::MENU_SLUG === $item[2] ) {
				return true;
			}
		}

		return false;
	}

	/**
	 * Load the wp-build generated asset registrations and the boot polyfills.
	 *
	 * `build/` is produced at release time, so an unbuilt checkout has none; bail
	 * quietly, since register_page() already falls back to an empty render.
	 *
	 * @return void
	 */
	public static function load_wp_build() {
		$wp_build_index = dirname( __DIR__, 3 ) . '/build/build.php';

		if ( ! file_exists( $wp_build_index ) ) {
			return;
		}

		require_once $wp_build_index;

		// Register polyfills for WP < 7.0 (must run before enqueue).
		WP_Build_Polyfills::register(
			'jetpack-mu-wpcom',
			array_merge(
				WP_Build_Polyfills::SCRIPT_HANDLES,
				WP_Build_Polyfills::MODULE_IDS
			)
		);
	}

	/**
	 * Make wp-build's enqueue check pass without changing the page URL.
	 *
	 * Its enqueue callback needs a screen ID of `<page>`, which the menu slug does not
	 * produce. Paired with restore_screen_id() so the rewritten ID never outlives the
	 * enqueue pass — `$screen->base`, the body class and the page-view tracker all keep
	 * reading the real one.
	 *
	 * @return void
	 */
	public static function alias_screen_id() {
		$screen = get_current_screen();

		if ( ! static::owns_page() || ! is_object( $screen ) ) {
			return;
		}

		self::$displaced_screen_id[ static::class ] = $screen->id;
		$screen->id                                 = static::WP_BUILD_PAGE;
	}

	/**
	 * Put back the screen ID displaced by alias_screen_id().
	 *
	 * @return void
	 */
	public static function restore_screen_id() {
		$screen = get_current_screen();

		if ( ! isset( self::$displaced_screen_id[ static::class ] ) || ! is_object( $screen ) ) {
			return;
		}

		$screen->id = self::$displaced_screen_id[ static::class ];
		unset( self::$displaced_screen_id[ static::class ] );
	}

	/**
	 * Hand the resolved state to the page's boot script.
	 *
	 * @return void
	 */
	public static function enqueue_initial_state() {
		$handle = static::WP_BUILD_PAGE . '-wp-admin-prerequisites';

		if ( ! static::owns_page() || ! wp_script_is( $handle, 'registered' ) ) {
			return;
		}

		// The menu's own capability gate keeps unauthorized users from reaching this hook at
		// all; restated here because get_status_for_site() is called directly rather than
		// through the wpcom endpoint that gates it.
		if ( ! current_user_can( 'manage_options' ) ) {
			return;
		}

		$blog_id = get_current_blog_id();
		$user_id = get_current_user_id();
		$domain  = wp_parse_url( home_url(), PHP_URL_HOST );
		$state   = static::get_state( $blog_id );

		// Only the activation prompt reads eligibility, and both lists come from the
		// same result, so resolve it once and only for that state.
		$eligibility = self::STATE_ACTIVATE === $state
			? self::get_eligibility( $blog_id, $user_id )
			: null;
		$warnings    = self::get_transfer_warnings( $eligibility );

		Common\wpcom_enqueue_tracking_scripts( $handle );

		wp_localize_script(
			$handle,
			self::INITIAL_STATE_VAR,
			array(
				'state'       => $state,
				'domain'      => $domain,
				// A null result means the library was unavailable, not that the site
				// failed a check; let the transfer flow reject it instead.
				'isEligible'  => null === $eligibility || ! empty( $eligibility['is_eligible'] ),
				'errors'      => self::get_transfer_errors( $eligibility ),
				'warnings'    => $warnings,
				'upgradeUrl'  => static::get_upgrade_url( $domain ),
				'activateUrl' => static::get_activate_url( $warnings ),
			)
		);
	}

	/**
	 * Whether a transfer to WoA is already underway.
	 *
	 * @param int $blog_id Blog ID.
	 * @return bool
	 */
	public static function is_transfer_in_progress( $blog_id ) {
		if ( ! function_exists( 'require_lib' ) ) {
			return false;
		}

		// These checks are only relevant for simple sites.
		if ( self::is_atomic() ) {
			return false;
		}

		require_lib( 'atomic' );

		if ( function_exists( '\A8C\Atomic\has_site_pending_automated_transfer' ) ) {
			// @phan-suppress-next-line PhanUndeclaredFunction -- wpcom-only; pending addition to stub-defs.php.
			if ( \A8C\Atomic\has_site_pending_automated_transfer( $blog_id ) ) {
				return true;
			}
		}

		if ( function_exists( '\A8C\Atomic\is_wpcom_atomic' ) ) {
			// Second argument includes pending/active/provisioned transfers.
			// @phan-suppress-next-line PhanUndeclaredFunction -- wpcom-only; pending addition to stub-defs.php.
			return (bool) \A8C\Atomic\is_wpcom_atomic( $blog_id, true );
		}

		return false;
	}

	/**
	 * Transfer eligibility for the site, or null when it cannot be determined.
	 *
	 * An in-progress transfer is reported as a `transfer_already_exists` error, so
	 * that state is checked first and never reaches here as a blocker.
	 *
	 * @param int $blog_id Blog ID.
	 * @param int $user_id User ID.
	 * @return array|null { is_eligible: bool, errors: array, warnings: array }
	 */
	public static function get_eligibility( $blog_id, $user_id ) {
		if ( ! function_exists( 'require_lib' ) ) {
			return null;
		}

		// These checks are only relevant for simple sites.
		if ( self::is_atomic() ) {
			return null;
		}

		require_lib( 'atomic' );

		if ( ! function_exists( '\A8C\Atomic\Eligibility\get_status_for_site' ) ) {
			return null;
		}

		// @phan-suppress-next-line PhanUndeclaredFunction -- wpcom-only; pending addition to stub-defs.php.
		return \A8C\Atomic\Eligibility\get_status_for_site( $blog_id, $user_id );
	}

	/**
	 * Resolve which prompt the page should show.
	 *
	 * @param int $blog_id Blog ID.
	 * @return string One of the STATE_* constants.
	 */
	public static function get_state( $blog_id ) {
		// On WoA the plan is the only question: the site is already on the
		// infrastructure that runs the feature, so there is nothing to transfer, and
		// should_register() has already stepped the page aside if it has the plan.
		if ( ! static::has_feature() || self::is_atomic() ) {
			$state = self::STATE_UPGRADE;
		} elseif ( self::is_transfer_in_progress( $blog_id ) ) {
			$state = self::STATE_IN_PROGRESS;
		} else {
			// Eligibility failures are explained by the activation prompt's own
			// confirmation step, so they do not get a state of their own.
			$state = self::STATE_ACTIVATE;
		}

		return $state;
	}

	/**
	 * Reasons a site cannot be transferred, in the shape the API returns them.
	 *
	 * The code is kept because the page maps it to its own copy; the API's message comes
	 * along as the fallback the page renders for codes it does not recognize.
	 *
	 * @param array|null $eligibility Result of get_eligibility().
	 * @return array[] Errors as { code, message }.
	 */
	public static function get_transfer_errors( $eligibility ) {
		$errors = array();

		if ( ! empty( $eligibility['errors'] ) && is_array( $eligibility['errors'] ) ) {
			foreach ( $eligibility['errors'] as $error ) {
				if ( empty( $error['code'] ) ) {
					continue;
				}

				$errors[] = array(
					'code'    => (string) $error['code'],
					'message' => isset( $error['message'] ) ? (string) $error['message'] : '',
				);
			}
		}

		return $errors;
	}

	/**
	 * Non-blocking warnings to confirm before a transfer starts.
	 *
	 * The API groups warnings by type; they are flattened here because the page
	 * renders one list and a PHP map would localize as a JSON array once empty.
	 *
	 * @param array|null $eligibility Result of get_eligibility().
	 * @return array[] Warnings in the API's own shape, minus the grouping.
	 */
	public static function get_transfer_warnings( $eligibility ) {
		$warnings = array();

		if ( ! empty( $eligibility['warnings'] ) && is_array( $eligibility['warnings'] ) ) {
			foreach ( $eligibility['warnings'] as $group ) {
				if ( ! is_array( $group ) ) {
					continue;
				}

				foreach ( $group as $warning ) {
					if ( empty( $warning['id'] ) ) {
						continue;
					}

					$warnings[] = array(
						'id'           => (string) $warning['id'],
						'description'  => isset( $warning['description'] ) ? (string) $warning['description'] : '',
						'domain_names' => ( ! empty( $warning['domain_names']['current'] ) && ! empty( $warning['domain_names']['new'] ) )
							? array(
								'current' => (string) $warning['domain_names']['current'],
								'new'     => (string) $warning['domain_names']['new'],
							)
							: null,
						'support_url'  => isset( $warning['support_url'] ) ? (string) $warning['support_url'] : '',
					);
				}
			}
		}

		return $warnings;
	}

	/**
	 * Checkout, with the Business plan already in the cart.
	 *
	 * `redirect_to` returns a buyer here to activate what they just bought, and
	 * `checkoutBackUrl` returns someone who backs out; without it checkout falls back to /plans.
	 * Checkout's "Empty cart" reads only `checkoutBackUrlDomains`, so it gets the same URL.
	 *
	 * @param string $domain Site domain.
	 * @return string
	 */
	public static function get_upgrade_url( $domain ) {
		$page_url = rawurlencode( static::get_page_url() );

		return add_query_arg(
			array(
				'redirect_to'            => $page_url,
				'checkoutBackUrl'        => $page_url,
				'checkoutBackUrlDomains' => $page_url,
			),
			'https://wordpress.com/checkout/' . rawurlencode( (string) $domain ) . '/business'
		);
	}

	/**
	 * This page's own address, for the round trips off to WordPress.com and back.
	 *
	 * @return string
	 */
	public static function get_page_url() {
		return admin_url( 'admin.php?page=' . static::MENU_SLUG );
	}

	/**
	 * Where this page will live once the transfer lands.
	 *
	 * Uses the new address from the address-change warning rather than trusting the old
	 * one to redirect, which may not have propagated when the flow sends the reader back.
	 *
	 * @param array[] $warnings Result of get_transfer_warnings().
	 * @return string
	 */
	public static function get_post_transfer_page_url( array $warnings ) {
		$page_url = static::get_page_url();

		foreach ( $warnings as $warning ) {
			$new_host = $warning['domain_names']['new'] ?? '';

			// A bare hostname only, so nothing in the payload can steer the scheme or path.
			if ( is_string( $new_host ) && filter_var( $new_host, FILTER_VALIDATE_DOMAIN, FILTER_FLAG_HOSTNAME ) ) {
				$parts = wp_parse_url( $page_url );

				return 'https://' . strtolower( $new_host ) . ( $parts['path'] ?? '' ) . ( isset( $parts['query'] ) ? '?' . $parts['query'] : '' );
			}
		}

		return $page_url;
	}

	/**
	 * URL of the Calypso flow that transfers the site and switches the feature on.
	 *
	 * The flow waits for the transfer to land before following `redirect_to`.
	 *
	 * @param array[] $warnings Result of get_transfer_warnings(), for the post-transfer address.
	 * @return string
	 */
	public static function get_activate_url( array $warnings = array() ) {
		return add_query_arg(
			array(
				'siteId'                    => get_current_blog_id(),
				'initiate_transfer_context' => self::TRANSFER_CONTEXT,
				'redirect_to'               => rawurlencode( static::get_post_transfer_page_url( $warnings ) ),
			),
			self::TRANSFER_FLOW_URL
		);
	}
}
