import os from 'os';
import { coerceConcurrency } from '../helpers/normalizeArgv.js';
import * as testCommand from './test.js';

export const command = 'coverage <group> [project...]';
export const describe = 'Run code coverage on a monorepo project';

/**
 * Options definition for the coverage subcommand.
 *
 * @param {object} yargs - The Yargs dependency.
 * @return {object} Yargs with the coverage command defined.
 */
export async function builder( yargs ) {
	return yargs
		.positional( 'group', {
			describe: 'Coverage group to run: "php" or "js".',
			type: 'string',
			choices: [ 'php', 'js' ],
		} )
		.positional( 'project', {
			describe: 'Project in the form of type/name, e.g. plugins/jetpack.',
			type: 'string',
		} )
		.option( 'all', {
			alias: 'a',
			type: 'boolean',
			description: 'Run coverage on everything.',
		} )
		.option( 'use-uncommitted-composer-lock', { type: 'boolean', hidden: true } )
		.option( 'no-use-uncommitted-composer-lock', {
			type: 'boolean',
			description: "Don't use uncommitted composer.lock files.",
		} )
		.option( 'concurrency', {
			type: 'number',
			description: 'Maximum number of test tasks to run at once. Ignored with `--verbose`.',
			default: os.availableParallelism(),
			coerce: coerceConcurrency,
		} )
		.option( 'html', { type: 'boolean', hidden: true } )
		.option( 'no-html', {
			type: 'boolean',
			description: 'Do not generate HTML reports.',
		} )
		.option( 'html-dir', {
			type: 'string',
			description:
				// prettier-ignore
				`Write HTML reports to this path instead of creating a new directory in ${ os.tmpdir() }.`,
		} )
		.option( 'artifacts-dir', {
			type: 'string',
			description: 'Directory for any artifacts generated by the tests.',
		} )
		.check( argv => {
			if ( argv.v ) {
				argv.concurrency = false;
			}
			return true;
		} );
}

/**
 * Pass args to the test command.
 *
 * @param {object} argv - The argv for the command line.
 */
export async function handler( argv ) {
	argv.test = `${ argv.group }-coverage`;
	argv.coverageGroup = argv.group;
	argv.isCoverage = true;
	await testCommand.handler( argv );
}
