export const RECEIVE_FILTERS = 'RECEIVE_FILTERS';
export const INVALIDATE_FILTERS = 'INVALIDATE_FILTERS';
export const SET_CURRENT_QUERY = 'SET_CURRENT_QUERY';
export const SET_SELECTED_RESPONSES = 'SET_SELECTED_RESPONSES';
export const SET_COUNTS = 'SET_COUNTS';
export const UPDATE_COUNTS_OPTIMISTICALLY = 'UPDATE_COUNTS_OPTIMISTICALLY';
export const INVALIDATE_COUNTS = 'INVALIDATE_COUNTS';
