<?php
/**
 * Jetpack Forms Page - @wordpress/build integration
 *
 * Integrates Jetpack Forms with WordPress admin using @wordpress/build's
 * single-page mode (page-wp-admin.php).
 *
 * @package automattic/jetpack-forms
 */

use Automattic\Jetpack\Assets;
use Automattic\Jetpack\Connection\Initial_State as Connection_Initial_State;
use Automattic\Jetpack\Forms\ContactForm\Contact_Form_Plugin;
use Automattic\Jetpack\Tracking;

// Load the generated build files (modules, scripts, styles, routes, pages).
require_once __DIR__ . '/build/index.php';

/**
 * Check if this is the Jetpack Forms boot page.
 *
 * @return bool
 */
function jetpack_forms_is_boot_page() {
	// phpcs:ignore WordPress.Security.NonceVerification.Recommended
	return isset( $_GET['page'] ) && 'jetpack-forms-wp-admin' === $_GET['page'];
}

/**
 * Register the Jetpack Forms menu item under the Jetpack menu.
 *
 * This creates a submenu item under Jetpack that links to the wp-admin integrated page.
 * We register at priority 5 to ensure our visible menu takes precedence over
 * the hidden one generated by page-wp-admin.php.
 */
function jetpack_forms_register_menu() {
	$page_url = admin_url( 'admin.php?page=jetpack-forms-wp-admin' );
	add_submenu_page(
		'jetpack',
		__( 'Jetpack Forms', 'jetpack-forms' ),
		__( 'Forms', 'jetpack-forms' ),
		'edit_pages',
		$page_url,
		null, // No callback needed - the build handles rendering
		4
	);
}
add_action( 'admin_menu', 'jetpack_forms_register_menu', 5 );

/**
 * Enqueue the Forms dashboard assets for the boot page.
 *
 * This loads the existing webpack-built dashboard bundle which will
 * mount into the container rendered by the @wordpress/boot route.
 */
function jetpack_forms_enqueue_dashboard_assets() {
	if ( ! jetpack_forms_is_boot_page() ) {
		return;
	}

	$script_handle = 'jp-forms-dashboard';

	Assets::register_script(
		$script_handle,
		'dist/dashboard/jetpack-forms-dashboard.js',
		__FILE__,
		array(
			'in_footer'    => true,
			'textdomain'   => 'jetpack-forms',
			'enqueue'      => true,
			'dependencies' => array( 'wp-api-fetch', 'wp-data', 'wp-core-data', 'wp-dom-ready' ),
		)
	);

	if ( Contact_Form_Plugin::can_use_analytics() ) {
		Tracking::register_tracks_functions_scripts( true );
	}

	// Adds Connection package initial state.
	Connection_Initial_State::render_script( $script_handle );

	// Preload Forms endpoints needed in dashboard context.
	$preload_params = array(
		'context'  => 'edit',
		'order'    => 'desc',
		'orderby'  => 'date',
		'page'     => 1,
		'per_page' => 20,
		'status'   => 'draft,publish',
	);
	ksort( $preload_params );
	$initial_responses_path        = add_query_arg( $preload_params, '/wp/v2/feedback' );
	$initial_responses_locale_path = add_query_arg(
		array_merge(
			$preload_params,
			array( '_locale' => 'user' )
		),
		'/wp/v2/feedback'
	);
	$filters_path                  = '/wp/v2/feedback/filters';
	$filters_locale_path           = add_query_arg( array( '_locale' => 'user' ), $filters_path );
	$preload_paths                 = array(
		'/wp/v2/types?context=view',
		'/wp/v2/feedback/config',
		'/wp/v2/feedback/integrations-metadata',
		'/wp/v2/feedback/counts',
		$filters_path,
		$filters_locale_path,
		$initial_responses_path,
		$initial_responses_locale_path,
	);
	$preload_data_raw              = array_reduce( $preload_paths, 'rest_preload_api_request', array() );

	// Normalize keys to match what apiFetch will request (without domain).
	$preload_data = array();
	foreach ( $preload_data_raw as $key => $value ) {
		$normalized_key                  = preg_replace( '#^https?://[^/]+/wp-json#', '', $key );
		$preload_data[ $normalized_key ] = $value;
	}

	wp_add_inline_script(
		$script_handle,
		sprintf(
			'wp.apiFetch.use( wp.apiFetch.createPreloadingMiddleware( %s ) );',
			wp_json_encode( $preload_data )
		),
		'before'
	);
}
add_action( 'admin_enqueue_scripts', 'jetpack_forms_enqueue_dashboard_assets' );

/**
 * Setup private APIs for bundled @wordpress modules.
 *
 * The boot package requires access to WordPress private APIs. We need to
 * opt-in our bundled modules before they're loaded.
 */
function jetpack_forms_setup_private_apis() {
	if ( ! jetpack_forms_is_boot_page() ) {
		return;
	}

	$base_url = plugins_url( 'build/', __FILE__ );
	?>
	<script>
		window.wp = window.wp || {};
		if ( window.wp.privateApis ) {
			delete window.wp.privateApis;
		}
	</script>
	<?php // phpcs:ignore WordPress.WP.EnqueuedResources.NonEnqueuedScript -- Needs to load before wp_enqueue_scripts runs. ?>
	<script src="<?php echo esc_url( $base_url . 'scripts/private-apis/index.min.js' ); ?>"></script>
	<script>
		( function() {
			function setupPrivateApis() {
				if ( ! window.wp || ! window.wp.privateApis ) {
					setTimeout( setupPrivateApis, 10 );
					return;
				}

				const ourPrivateApis = window.wp.privateApis;

				try {
					Object.defineProperty( window.wp, 'privateApis', {
						get: function() { return ourPrivateApis; },
						set: function() { /* Prevent overwrites */ },
						configurable: false
					} );
				} catch ( e ) {
					console.warn( 'Could not protect privateApis:', e );
				}

				const { __dangerousOptInToUnstableAPIsOnlyForCoreModules } = ourPrivateApis;
				const consent = 'I acknowledge private features are not for use in themes or plugins and doing so will break in the next version of WordPress.';

				__dangerousOptInToUnstableAPIsOnlyForCoreModules( consent, '@wordpress/route' );
				__dangerousOptInToUnstableAPIsOnlyForCoreModules( consent, '@wordpress/boot' );
				__dangerousOptInToUnstableAPIsOnlyForCoreModules( consent, '@wordpress/theme' );
			}

			setupPrivateApis();
		} )();
	</script>
	<?php
}
add_action( 'admin_head', 'jetpack_forms_setup_private_apis', 2 );
