/**
 * Components
 */
export {
	AbbreviatedValue,
	type AbbreviatedValueProps,
	MetricDelta,
	MetricTileGrid,
	MetricTileGridSkeleton,
	type MetricTileGridSkeletonProps,
	MetricList,
	type MetricListItem,
	type MetricListProps,
	MetricValue,
	MetricWithComparison,
	PeakDistribution,
	type PeakDistributionProps,
	ComparativeLineChart,
	type ComparativeLineChartSeries,
	ComparativeBarChart,
	type ComparativeBarChartProps,
	type ComparativeBarChartSeries,
	DonutChart,
	DonutChartSkeleton,
	Legend,
	ReportMetricWidget,
	MetricTabsChart,
	MetricTabsChartSkeleton,
	type MetricTab,
	type MetricTabDatum,
	type MetricTabsChartProps,
	type MetricTabsChartType,
	WidgetRoot,
	WidgetRootContext,
	useWidgetRootContext,
	type DonutChartData,
	type WidgetRootContextValue,
	type LegendItem,
	type SeriesStyle,
	type TooltipExtraSeries,
	LeaderboardChart,
	LeaderboardSkeleton,
	type LeaderboardChartProps,
	type LeaderboardChartData,
	type LeaderboardSkeletonProps,
	Leaderboard,
	type LeaderboardDrillDown,
	type LeaderboardProps,
	type LeaderboardRowInput,
	type LeaderboardStatus,
	type LegendLabels,
	LeaderboardLabel,
	type LeaderboardLabelProps,
	LeaderboardRow,
	buildLeaderboardRow,
	resolveLeaderboardRowAction,
	type LeaderboardRowAction,
	type LeaderboardRowActionOptions,
	type LeaderboardRowChartProps,
	type LeaderboardRowMedia,
	type LeaderboardRowProps,
	BarChart,
	BarChartSkeleton,
	type BarChartProps,
	type BarChartData,
	type BarChartStyle,
	WidgetLoadingOverlay,
	AdaptiveCalendarHeatmap,
	CalendarHeatmapPagerOverlay,
	CalendarHeatmapTooltip,
	type AdaptiveCalendarHeatmapChartProps,
	type AdaptiveCalendarHeatmapProps,
	type CalendarHeatmapPager,
	type CalendarHeatmapPagerOverlayProps,
	type CalendarHeatmapTooltipProps,
	MonthCalendarHeatmap,
	type MonthCalendarHeatmapProps,
	MonthlyHeatmap,
	type MonthlyHeatmapProps,
	type MonthlyHeatmapRow,
	type MonthlyHeatmapTarget,
	ChartEmptyState,
	type ChartEmptyStateProps,
	WidgetState,
	type WidgetStateProps,
	type WidgetStateError,
	type WidgetStateEmpty,
	WidgetBackLink,
	type WidgetBackLinkProps,
	WidgetFooter,
	type WidgetFooterProps,
	WidgetFooterLink,
	type WidgetFooterLinkProps,
	ReportLink,
	type ReportLinkProps,
	InfoTip,
	type InfoTipProps,
	PostTitleLink,
	POST_URL_SEARCH_PARAM,
	type PostTitleLinkProps,
	PostDetailLink,
	type PostDetailLinkProps,
	HighlightField,
	HighlightGroup,
	type HighlightFieldProps,
	type HighlightGroupProps,
	LeaderboardPostLabel,
	type LeaderboardPostLabelProps,
	PostHighlightCard,
	PostHighlightCardSkeleton,
	type PostHighlightCardMetric,
	type PostHighlightCardProps,
	VideoTitleLink,
	type VideoTitleLinkProps,
	SubscriberList,
	SubscriberListSkeleton,
	type SubscriberListItem,
	type SubscriberListProps,
	type SubscriberListSkeletonProps,
	SemiCircleChart,
	type SemiCircleChartData,
	DETAIL_HEADER_GLYPH_SIZE,
	DetailPageEmptyState,
	DetailPageLayout,
	DetailPageSection,
	DetailPageActions,
	DetailPageBreadcrumbs,
	DetailPageShell,
	useDetailPageCustomize,
	type DetailPageActionsProps,
	type DetailPageBreadcrumbsProps,
	type DetailPageCustomize,
	type DetailPageHeaderSlots,
	type DetailPageLayoutProps,
	type DetailPageSectionProps,
	type DetailPageShellProps,
	FeedbackModal,
	type FeedbackSource,
	PageNotice,
	type PageNoticeProps,
	PageOptionsMenu,
	type PageOptionsMenuProps,
	ResetLayoutAction,
	type ResetLayoutActionProps,
	LocationsGeoChart,
	type LocationsGeoChartProps,
	type LocationsGeoFocusCountry,
	type LocationsGeoMode,
	type LocationsGeoRow,
	ReportChartSection,
	ReportDrilldownTable,
	ReportLocationsMap,
	ReportPageLayout,
	ReportPageSection,
	ReportPageShell,
	ReportPageTabPanel,
	ReportPageTabs,
	ReportPerformanceChart,
	ReportRecordsTable,
	ReportThumbnail,
	REPORT_TITLE_LINK_CLASS_NAMES,
	useReportRetry,
	buildReportMetricSeries,
	type ReportChartMetric,
	type ReportChartSectionProps,
	type ReportDrilldownTableProps,
	type ReportLocationsMapProps,
	type ReportPageLayoutProps,
	type ReportPageSectionProps,
	type ReportPageShellProps,
	type ReportPageTab,
	type ReportPageTabPanelProps,
	type ReportPageTabsProps,
	type ReportPerformanceChartProps,
	type ReportRecordsTableProps,
	ExporterCsvAction,
	ReportCsvAction,
	type ReportCsvActionProps,
	ExporterCsvDownloadButton,
	ReportCsvDownloadButton,
	type ReportCsvDownloadButtonProps,
	useReportCsvExport,
	type UseReportCsvExportOptions,
	type UseReportCsvExportResult,
	WidgetDataTable,
	type WidgetDataTableProps,
	EarningsHistoryList,
	type EarningsHistoryListProps,
	flattenEarningsBreakdown,
	getEarningsStatus,
	getWordAdsHistoryFields,
	type EarningsHistoryRow,
	AnnualHighlightsSkeleton,
	GenericSkeleton,
	HeatmapSkeleton,
	MonthCalendarHeatmapSkeleton,
	MetricSparklineSkeleton,
	type MetricSparklineSkeletonProps,
	SkeletonRoot,
	type SkeletonRootProps,
} from './components';

/**
 * Report CSV exports
 */
export {
	aggregateAuthorRows,
	aggregateClickRows,
	aggregateSearchTermRows,
	aggregateUtmRows,
	annualInsightsCsvExporter,
	archivesCsvExporter,
	authorPostsCsvExporter,
	authorsCsvExporter,
	buildArchiveRows,
	buildLocationRows,
	clicksCsvExporter,
	commentsAuthorsCsvExporter,
	commentsPostsCsvExporter,
	EMAILS_REPORT_ROW_LIMIT,
	emailsCsvExporter,
	fileDownloadsCsvExporter,
	flattenReferrerRows,
	getArchiveGroupLabel,
	getArchiveTypeLabel,
	getAuthorName,
	getAuthorsReportQueryParams,
	getLocationsReportQueryParams,
	getLocationsReportSection,
	getLocationsScopeParams,
	getPostsReportQueryParams,
	getSummarizedReportQueryParams,
	getUtmDimensionLabel,
	getUtmDimensionOptions,
	getUtmReportQueryParams,
	getUtmReportSection,
	getVideosReportQueryParams,
	LOCATIONS_GEO_MODES,
	locationsCsvExporter,
	postsPagesCsvExporter,
	referrersCsvExporter,
	searchTermsCsvExporter,
	supportsLocationsCountryFilter,
	TAGS_REPORT_ROW_LIMIT,
	tagsCsvExporter,
	toCommentRows,
	utmCsvExporters,
	videosCsvExporter,
	type ArchiveRow,
	type AuthorRow,
	type ClickRow,
	type LocationRow,
	type LocationsReportSection,
	type LocationsScope,
	type ReferrerRecord,
	type SearchTermRow,
	type UtmReportRow,
	type UtmReportSection,
} from './report-exports';

/**
 * Constants
 */
export {
	DASHBOARD_PREFERENCES_SCOPE,
	DASHBOARD_SECTION_LAYOUTS_KEY,
	WIDGET_ROW_LIMIT,
} from './constants';

/**
 * Widget edit fields
 */
export type { ReportParamsFieldAttributes } from './fields';

/**
 * Helpers and utilities
 */
export {
	formatOrderMetric,
	getFormatByMetricKey,
	buildTimeSeriesChartData,
	type TimeSeriesData,
	calculateDelta,
	flagUrl,
	BOOKINGS_FILTER,
	PHYSICAL_PRODUCTS_FILTER,
	FULFILLED_ORDERS_FILTER,
	UNFULFILLED_ORDERS_FILTER,
	PAYMENT_STATUS_FILTERS,
	buildPaymentStatusData,
	type PaymentStatusData,
	buildSalesByUtmData,
	formatLegendLabels,
	formatDisplayLabel,
	buildCsv,
	buildCsvDateRangeFilename,
	saveCsv,
	type CsvColumn,
	type CsvDateRange,
	getCombinedPeriodMax,
	sharePercentage,
	describeError,
	summaryCount,
	toDay,
	defaultPeriodForInterval,
	buildMetricTab,
	siteChartFormatting,
	CHART_DISPLAY_CHART_TYPES,
	chartTypeAttributeField,
	type ChartDisplayChartType,
	CALENDAR_HEATMAP_CELL_GAP,
	CALENDAR_HEATMAP_HEADER_HEIGHT,
	computeCalendarHeatmapLayout,
	fitWeekColumns,
	compareOptionalNumbers,
	formatEmailRate,
	formatViewCount,
	getClicksRateSignals,
	getKnownEmailRate,
	getOpensRateSignals,
	isEmailRateKnown,
	type EmailRateSignals,
	MONTHS_IN_YEAR,
	monthOrder,
	type MonthKey,
	MONTHLY_HEATMAP_METRICS,
	monthlyHeatmapLabels,
	monthlyHeatmapMetricAttributeField,
	resolveMonthlyHeatmapMetric,
	type MonthlyHeatmapMetric,
	monthlyHeatmapLifeStart,
	monthRange,
	yearRange,
	type PeriodBounds,
	buildDenseDaySeries,
	resolveCalendarHeatmapGridStart,
	type CalendarHeatmapLayout,
	type CalendarHeatmapLayoutInput,
	type FitWeekColumnsInput,
	type CalendarHeatmapWindow,
} from './helpers';

/**
 * Hooks
 */
export {
	DashboardSectionProvider,
	useAttributesWithSearchFallback,
	useChartTheme,
	useDashboardOriginSearch,
	useElementSize,
	type ElementSize,
	useWidgetNavigationSearch,
	useSegmentStyles,
	useSeriesStyles,
	useStoredDetailLayout,
	useTrackCustomize,
	useTrackEvent,
	useTrackedDateRangeApply,
	useWidgetDrillDown,
} from './hooks';

/**
 * Widget components
 */
export {
	BookingOrderMetricWidget,
	BookingsByAttendanceWidget,
	BookingsRevenueByCustomerTypeWidget,
	BookingConversionRateWidget,
	ConversionRateWidget,
	CouponUseWidget,
	MetricComparisonWidget,
	RevenueByCustomerTypeWidget,
	NewVsReturningCustomerWidget,
	OrderMetricWidget,
	OrdersFulfillmentWidget,
	SalesByCouponWidget,
	TotalReturnsWidget,
	VisitorsByLocationWidget,
	SalesByDeviceWidget,
	SalesByUtmWidget,
	SessionsByDeviceWidget,
	TopPerformingProductLeaderboardWidget,
	type TopPerformingProductLeaderboardWidgetProps,
	TopPerformingProductsWidget,
	type TopPerformingProductsWidgetProps,
	TopPerformingBookingsWidget,
	type TopPerformingBookingsWidgetProps,
} from './widgets';

/**
 * Types
 */
export type {
	CountLabel,
	MetricKey,
	OrderMetricKey,
	OrderMetrics,
	OrdersSummary,
	DataFormat,
} from './types';

/**
 * Charts passthrough. Widgets must import chart components from here, never
 * from `@automattic/charts` directly: the toolkit bundles charts once instead
 * of once per widget, itself sourcing them from `@jetpack-premium-analytics/externals`.
 */
export {
	GeoChart,
	GlobalChartsProvider,
	GoogleDataTableColumnRoleType,
	HeatmapChart,
	HeatmapChartUnresponsive,
	Sparkline,
	buildCalendarHeatmapData,
	useCalendarHeatmapData,
	type DataPointDate,
	type GeoChartError,
	type GeoData,
	type HeatmapColumn,
	type GoogleDataTableColumn,
	type GoogleDataTableRow,
	type HeatmapTooltipData,
} from '@jetpack-premium-analytics/externals';

/**
 * UI passthrough. Widgets must import these from here, never from
 * `@jetpack-premium-analytics/ui` directly: the toolkit bundles the ui package
 * once instead of once per widget.
 */
export { safeHttpUrl, tagRowGlyph } from '@jetpack-premium-analytics/ui';
