/**
 * Components
 */
export {
	MetricDelta,
	MetricTileGrid,
	MetricTileGridSkeleton,
	type MetricTileGridSkeletonProps,
	MetricList,
	type MetricListItem,
	type MetricListProps,
	MetricValue,
	MetricWithComparison,
	PeakDistribution,
	type PeakDistributionProps,
	ComparativeLineChart,
	type ComparativeLineChartSeries,
	ComparativeBarChart,
	type ComparativeBarChartProps,
	type ComparativeBarChartSeries,
	DonutChart,
	DonutChartSkeleton,
	Legend,
	ReportMetricWidget,
	MetricTabsChart,
	MetricTabsChartSkeleton,
	type MetricTab,
	type MetricTabDatum,
	type MetricTabsChartProps,
	type MetricTabsChartType,
	WidgetRoot,
	WidgetRootContext,
	useWidgetRootContext,
	type DonutChartData,
	type WidgetRootContextValue,
	type LegendItem,
	type SeriesStyle,
	LeaderboardChart,
	LeaderboardSkeleton,
	type LeaderboardChartProps,
	type LeaderboardChartData,
	type LeaderboardSkeletonProps,
	type LegendLabels,
	LeaderboardLabel,
	type LeaderboardLabelProps,
	LeaderboardRow,
	buildLeaderboardRow,
	resolveLeaderboardRowAction,
	type LeaderboardRowAction,
	type LeaderboardRowActionOptions,
	type LeaderboardRowChartProps,
	type LeaderboardRowMedia,
	type LeaderboardRowProps,
	BarChart,
	BarChartSkeleton,
	type BarChartProps,
	type BarChartData,
	type BarChartStyle,
	WidgetLoadingOverlay,
	AdaptiveCalendarHeatmap,
	CalendarHeatmapPagerOverlay,
	CalendarHeatmapTooltip,
	type AdaptiveCalendarHeatmapChartProps,
	type AdaptiveCalendarHeatmapProps,
	type CalendarHeatmapPager,
	type CalendarHeatmapPagerOverlayProps,
	type CalendarHeatmapTooltipProps,
	ChartEmptyState,
	type ChartEmptyStateProps,
	WidgetState,
	type WidgetStateProps,
	type WidgetStateError,
	type WidgetStateEmpty,
	WidgetBackLink,
	type WidgetBackLinkProps,
	WidgetFooter,
	type WidgetFooterProps,
	ReportLink,
	type ReportLinkProps,
	PostTitleLink,
	POST_URL_SEARCH_PARAM,
	type PostTitleLinkProps,
	PostDetailLink,
	type PostDetailLinkProps,
	LeaderboardPostLabel,
	type LeaderboardPostLabelProps,
	PostHighlightCard,
	PostHighlightCardSkeleton,
	type PostHighlightCardMetric,
	type PostHighlightCardProps,
	VideoTitleLink,
	type VideoTitleLinkProps,
	SubscriberList,
	SubscriberListSkeleton,
	type SubscriberListItem,
	type SubscriberListProps,
	type SubscriberListSkeletonProps,
	SemiCircleChart,
	type SemiCircleChartData,
	DetailPageLayout,
	DetailPageSection,
	DetailPageShell,
	DetailPageTabPanel,
	DetailPageTabs,
	type DetailPageHeaderSlots,
	type DetailPageLayoutProps,
	type DetailPageSectionProps,
	type DetailPageShellProps,
	type DetailPageTab,
	type DetailPageTabPanelProps,
	type DetailPageTabsProps,
	ReportDrilldownTable,
	ReportErrorState,
	ReportPageLayout,
	ReportPageSection,
	ReportPageShell,
	ReportPageTabPanel,
	ReportPageTabs,
	ReportPerformanceChart,
	ReportRecordsTable,
	useReportRetry,
	buildReportMetricSeries,
	type ReportChartMetric,
	type ReportDrilldownTableProps,
	type ReportErrorStateProps,
	type ReportPageLayoutProps,
	type ReportPageSectionProps,
	type ReportPageShellProps,
	type ReportPageTab,
	type ReportPageTabPanelProps,
	type ReportPageTabsProps,
	type ReportPerformanceChartProps,
	type ReportRecordsTableProps,
	ReportCsvAction,
	type ReportCsvActionProps,
	ReportCsvDownloadButton,
	type ReportCsvDownloadButtonProps,
	RowsCsvDownloadButton,
	type RowsCsvDownloadButtonProps,
	useReportCsvExport,
	type UseReportCsvExportOptions,
	type UseReportCsvExportResult,
	WidgetDataTable,
	type WidgetDataTableProps,
	EARNINGS_HISTORY_VIEW,
	flattenEarningsBreakdown,
	getWordAdsHistoryFields,
	type EarningsHistoryRow,
	AnnualHighlightsSkeleton,
	GenericSkeleton,
	HeatmapSkeleton,
	MetricSparklineSkeleton,
	type MetricSparklineSkeletonProps,
	SkeletonRoot,
	type SkeletonRootProps,
} from './components';

/**
 * Constants
 */
export { COLOR_GRAY_100, WIDGET_ROW_LIMIT } from './constants';

/**
 * Widget edit fields
 */
export type { ReportParamsFieldAttributes } from './fields';

/**
 * Helpers and utilities
 */
export {
	formatOrderMetric,
	getFormatByMetricKey,
	buildTimeSeriesChartData,
	type TimeSeriesData,
	calculateDelta,
	flagUrl,
	BOOKINGS_FILTER,
	PHYSICAL_PRODUCTS_FILTER,
	FULFILLED_ORDERS_FILTER,
	UNFULFILLED_ORDERS_FILTER,
	PAYMENT_STATUS_FILTERS,
	buildPaymentStatusData,
	type PaymentStatusData,
	buildSalesByUtmData,
	formatLegendLabels,
	formatDisplayLabel,
	buildCsv,
	buildCsvDateRangeFilename,
	saveCsv,
	withComparisonColumns,
	type CsvColumn,
	type CsvDateRange,
	getCombinedPeriodMax,
	sharePercentage,
	getVideoKey,
	getVideoLabel,
	describeError,
	summaryCount,
	toDay,
	defaultPeriodForInterval,
	buildMetricTab,
	toChartDate,
	CHART_DISPLAY_CHART_TYPES,
	chartTypeAttributeField,
	type ChartDisplayChartType,
	CALENDAR_HEATMAP_CELL_GAP,
	CALENDAR_HEATMAP_HEADER_HEIGHT,
	computeCalendarHeatmapLayout,
	fitWeekColumns,
	formatViewCount,
	buildDenseDaySeries,
	resolveCalendarHeatmapGridStart,
	resolveCalendarHeatmapWindow,
	resolveCalendarHeatmapWindowDays,
	type CalendarHeatmapLayout,
	type CalendarHeatmapLayoutInput,
	type FitWeekColumnsInput,
	type CalendarHeatmapWindow,
	type CalendarHeatmapWindowBounds,
} from './helpers';

/**
 * Hooks
 */
export {
	useAttributesWithSearchFallback,
	useChartTheme,
	useElementSize,
	type ElementSize,
	useWidgetNavigationSearch,
	useSegmentStyles,
	useSeriesStyles,
	useViewportWidth,
	useWidgetDrillDown,
} from './hooks';

/**
 * Widget components
 */
export {
	BookingOrderMetricWidget,
	BookingsByAttendanceWidget,
	BookingsRevenueByCustomerTypeWidget,
	BookingConversionRateWidget,
	ConversionRateWidget,
	CouponUseWidget,
	MetricComparisonWidget,
	RevenueByCustomerTypeWidget,
	NewVsReturningCustomerWidget,
	OrderMetricWidget,
	OrdersFulfillmentWidget,
	SalesByCouponWidget,
	TotalReturnsWidget,
	VisitorsByLocationWidget,
	SalesByDeviceWidget,
	SalesByUtmWidget,
	SessionsByDeviceWidget,
	TopPerformingProductLeaderboardWidget,
	type TopPerformingProductLeaderboardWidgetProps,
	TopPerformingProductsWidget,
	type TopPerformingProductsWidgetProps,
	TopPerformingBookingsWidget,
	type TopPerformingBookingsWidgetProps,
} from './widgets';

/**
 * Types
 */
export type { MetricKey, OrderMetricKey, OrderMetrics, OrdersSummary, DataFormat } from './types';

/**
 * Charts passthrough. Widgets must import chart components from here, never
 * from `@automattic/charts` directly: the toolkit bundles charts once instead
 * of once per widget, itself sourcing them from `@jetpack-premium-analytics/externals`.
 */
export {
	GeoChart,
	GlobalChartsProvider,
	GoogleDataTableColumnRoleType,
	HeatmapChart,
	HeatmapChartUnresponsive,
	Sparkline,
	buildCalendarHeatmapData,
	type DataPointDate,
	type GeoChartError,
	type GeoData,
	type GoogleDataTableColumn,
	type GoogleDataTableRow,
	type HeatmapTooltipData,
} from '@jetpack-premium-analytics/externals';

/**
 * UI passthrough. Widgets must import these from here, never from
 * `@jetpack-premium-analytics/ui` directly: the toolkit bundles the ui package
 * once instead of once per widget.
 */
export { safeHttpUrl } from '@jetpack-premium-analytics/ui';
