<?php
/**
 * File holding the Coverage_Data_Loader class.
 *
 * @package automattic/jetpack-debug-helper
 */

namespace Automattic\Jetpack\Debug_Helper;

/**
 * The class that handles coverage data loading from a serialized file input.
 */
class Coverage_Data_Loader {

	const TEST_TABLE_NAME = 'jetpack_test_coverage_data';

	/**
	 * Requires a serialized coverage data object file generated by PHPUnit and
	 * stores the data in the database.
	 *
	 * @param String $file the file path that contains serialized PHPCOV data.
	 */
	public static function load_coverage_data( $file ) {
		global $wpdb;

		// Loading a serialized PHPCOV object requires returning it from a function.
		$coverage = ( function ( $file ) {
			return require $file;
		} )( $file );

		$data = array();
		foreach ( $coverage->lineCoverage() as $file => $lines ) {
			foreach ( $lines as $line => $testcases ) {
				if ( empty( $testcases ) ) {

					// This means no tests are covering this line.
					continue;
				}

				$data[] = array(
					'file' => $file,
					'line' => $line,
				);
			}
		}

		self::maybe_upsert_database();

		$sql = sprintf( 'INSERT IGNORE INTO `%s` (path, line) VALUES ', $wpdb->prefix . self::TEST_TABLE_NAME );

		foreach ( $data as $file ) {
			$sql .= sprintf( "( '%s', %d ),", $file['file'], $file['line'] );
		}

		$wpdb->query( rtrim( $sql, ',' ) ); // phpcs:ignore WordPress.DB -- We are preparing the query before this.
	}

	/**
	 * Uses the dbDelta function to either update, create, or leave the existing
	 * database in peace.
	 */
	protected static function maybe_upsert_database() {
		global $wpdb;

		$charset_collate = $wpdb->get_charset_collate();
		$table_name      = $wpdb->prefix . self::TEST_TABLE_NAME;

		$sql = array(
			sprintf(
				'CREATE TABLE IF NOT EXISTS `%s` (
 id int NOT NULL AUTO_INCREMENT,
 path varchar(255),
 line int,
 PRIMARY KEY (id),
 UNIQUE KEY `unique_path` (path, line)
 ) COLLATE %s',
				$table_name,
				$charset_collate
			),
		);

		require_once ABSPATH . 'wp-admin/includes/upgrade.php';
		dbDelta( $sql );
	}
}
