export const SET_CONNECTIONS = 'SET_CONNECTIONS';

export const ADD_CONNECTION = 'ADD_CONNECTION';

export const TOGGLE_CONNECTION = 'TOGGLE_CONNECTION';

export const DELETE_CONNECTION = 'DELETE_CONNECTION';

export const DELETING_CONNECTION = 'DELETING_CONNECTION';

export const UPDATE_CONNECTION = 'UPDATE_CONNECTION';

export const UPDATING_CONNECTION = 'UPDATING_CONNECTION';

export const SET_RECONNECTING_ACCOUNT = 'SET_RECONNECTING_ACCOUNT';

export const SET_KEYRING_RESULT = 'SET_KEYRING_RESULT';

export const TOGGLE_CONNECTIONS_MODAL = 'TOGGLE_CONNECTIONS_MODAL';

export const ADD_ABORT_CONTROLLER = 'ADD_ABORT_CONTROLLER';

export const REMOVE_ABORT_CONTROLLERS = 'REMOVE_ABORT_CONTROLLERS';

export const REQUEST_TYPE_DEFAULT = 'DEFAULT';

export const REQUEST_TYPE_REFRESH_CONNECTIONS = 'REFRESH_CONNECTIONS';

export const FETCH_POST_SHARE_STATUS = 'FETCH_POST_SHARE_STATUS' as const;

export const RECEIVE_POST_SHARE_STATUS = 'RECEIVE_POST_SHARE_STATUS' as const;

export const TOGGLE_SHARE_STATUS_MODAL = 'TOGGLE_SHARE_STATUS_MODAL' as const;

export const TOGGLE_SHARE_POST_MODAL = 'TOGGLE_SHARE_POST_MODAL' as const;

export const POLLING_FOR_POST_SHARE_STATUS = 'POLLING_FOR_POST_SHARE_STATUS' as const;
