export const SET_CONNECTIONS = 'SET_CONNECTIONS';

export const TOGGLE_CONNECTION = 'TOGGLE_CONNECTION';

export const DELETE_CONNECTION = 'DELETE_CONNECTION';

export const DELETING_CONNECTION = 'DELETING_CONNECTION';
