export const SET_CONNECTIONS = 'SET_CONNECTIONS';

export const ADD_CONNECTION = 'ADD_CONNECTION';

export const TOGGLE_CONNECTION = 'TOGGLE_CONNECTION';

export const DELETE_CONNECTION = 'DELETE_CONNECTION';

export const DELETING_CONNECTION = 'DELETING_CONNECTION';

export const UPDATE_CONNECTION = 'UPDATE_CONNECTION';

export const UPDATING_CONNECTION = 'UPDATING_CONNECTION';

export const SET_KEYRING_RESULT = 'SET_KEYRING_RESULT';

export const TOGGLE_CONNECTIONS_MODAL = 'TOGGLE_CONNECTIONS_MODAL';
