import { __ } from '@wordpress/i18n';

export const countries = [
	{
		code: 'US',
		label: '\ud83c\uddfa\ud83c\uddf8 +1',
		value: '+1',
		country: __( 'United States', 'jetpack-forms' ),
		flag: '\ud83c\uddfa\ud83c\uddf8',
	},
	{
		code: 'CA',
		label: '\ud83c\udde8\ud83c\udde6 +1',
		value: '+1',
		country: __( 'Canada', 'jetpack-forms' ),
		flag: '\ud83c\udde8\ud83c\udde6',
	},
	{
		code: 'BS',
		label: '\ud83c\udde7\ud83c\uddf8 +1242',
		value: '+1242',
		country: __( 'Bahamas', 'jetpack-forms' ),
		flag: '\ud83c\udde7\ud83c\uddf8',
	},
	{
		code: 'BB',
		label: '\ud83c\udde7\ud83c\udde7 +1246',
		value: '+1246',
		country: __( 'Barbados', 'jetpack-forms' ),
		flag: '\ud83c\udde7\ud83c\udde7',
	},
	{
		code: 'AI',
		label: '\ud83c\udde6\ud83c\uddee +1264',
		value: '+1264',
		country: __( 'Anguilla', 'jetpack-forms' ),
		flag: '\ud83c\udde6\ud83c\uddee',
	},
	{
		code: 'AG',
		label: '\ud83c\udde6\ud83c\uddec +1268',
		value: '+1268',
		country: __( 'Antigua and Barbuda', 'jetpack-forms' ),
		flag: '\ud83c\udde6\ud83c\uddec',
	},
	{
		code: 'VG',
		label: '\ud83c\uddfb\ud83c\uddec +1284',
		value: '+1284',
		country: __( 'British Virgin Islands', 'jetpack-forms' ),
		flag: '\ud83c\uddfb\ud83c\uddec',
	},
	{
		code: 'VI',
		label: '\ud83c\uddfb\ud83c\uddee +1340',
		value: '+1340',
		country: __( 'U.S. Virgin Islands', 'jetpack-forms' ),
		flag: '\ud83c\uddfb\ud83c\uddee',
	},
	{
		code: 'BM',
		label: '\ud83c\udde7\ud83c\uddf2 +1441',
		value: '+1441',
		country: __( 'Bermuda', 'jetpack-forms' ),
		flag: '\ud83c\udde7\ud83c\uddf2',
	},
	{
		code: 'GD',
		label: '\ud83c\uddec\ud83c\udde9 +1473',
		value: '+1473',
		country: __( 'Grenada', 'jetpack-forms' ),
		flag: '\ud83c\uddec\ud83c\udde9',
	},
	{
		code: 'TC',
		label: '\ud83c\uddf9\ud83c\udde8 +1649',
		value: '+1649',
		country: __( 'Turks and Caicos Islands', 'jetpack-forms' ),
		flag: '\ud83c\uddf9\ud83c\udde8',
	},
	{
		code: 'MS',
		label: '\ud83c\uddf2\ud83c\uddf8 +1664',
		value: '+1664',
		country: __( 'Montserrat', 'jetpack-forms' ),
		flag: '\ud83c\uddf2\ud83c\uddf8',
	},
	{
		code: 'MP',
		label: '\ud83c\uddf2\ud83c\uddf5 +1670',
		value: '+1670',
		country: __( 'Northern Mariana Islands', 'jetpack-forms' ),
		flag: '\ud83c\uddf2\ud83c\uddf5',
	},
	{
		code: 'GU',
		label: '\ud83c\uddec\ud83c\uddfa +1671',
		value: '+1671',
		country: __( 'Guam', 'jetpack-forms' ),
		flag: '\ud83c\uddec\ud83c\uddfa',
	},
	{
		code: 'AS',
		label: '\ud83c\udde6\ud83c\uddf8 +1684',
		value: '+1684',
		country: __( 'American Samoa', 'jetpack-forms' ),
		flag: '\ud83c\udde6\ud83c\uddf8',
	},
	{
		code: 'LC',
		label: '\ud83c\uddf1\ud83c\udde8 +1758',
		value: '+1758',
		country: __( 'Saint Lucia', 'jetpack-forms' ),
		flag: '\ud83c\uddf1\ud83c\udde8',
	},
	{
		code: 'DM',
		label: '\ud83c\udde9\ud83c\uddf2 +1767',
		value: '+1767',
		country: __( 'Dominica', 'jetpack-forms' ),
		flag: '\ud83c\udde9\ud83c\uddf2',
	},
	{
		code: 'VC',
		label: '\ud83c\uddfb\ud83c\udde8 +1784',
		value: '+1784',
		country: __( 'Saint Vincent and the Grenadines', 'jetpack-forms' ),
		flag: '\ud83c\uddfb\ud83c\udde8',
	},
	{
		code: 'DO',
		label: '\ud83c\udde9\ud83c\uddf4 +1849',
		value: '+1849',
		country: __( 'Dominican Republic', 'jetpack-forms' ),
		flag: '\ud83c\udde9\ud83c\uddf4',
	},
	{
		code: 'TT',
		label: '\ud83c\uddf9\ud83c\uddf9 +1868',
		value: '+1868',
		country: __( 'Trinidad and Tobago', 'jetpack-forms' ),
		flag: '\ud83c\uddf9\ud83c\uddf9',
	},
	{
		code: 'KN',
		label: '\ud83c\uddf0\ud83c\uddf3 +1869',
		value: '+1869',
		country: __( 'Saint Kitts and Nevis', 'jetpack-forms' ),
		flag: '\ud83c\uddf0\ud83c\uddf3',
	},
	{
		code: 'JM',
		label: '\ud83c\uddef\ud83c\uddf2 +1876',
		value: '+1876',
		country: __( 'Jamaica', 'jetpack-forms' ),
		flag: '\ud83c\uddef\ud83c\uddf2',
	},
	{
		code: 'PR',
		label: '\ud83c\uddf5\ud83c\uddf7 +1939',
		value: '+1939',
		country: __( 'Puerto Rico', 'jetpack-forms' ),
		flag: '\ud83c\uddf5\ud83c\uddf7',
	},
	{
		code: 'EG',
		label: '\ud83c\uddea\ud83c\uddec +20',
		value: '+20',
		country: __( 'Egypt', 'jetpack-forms' ),
		flag: '\ud83c\uddea\ud83c\uddec',
	},
	{
		code: 'MA',
		label: '\ud83c\uddf2\ud83c\udde6 +212',
		value: '+212',
		country: __( 'Morocco', 'jetpack-forms' ),
		flag: '\ud83c\uddf2\ud83c\udde6',
	},
	{
		code: 'DZ',
		label: '\ud83c\udde9\ud83c\uddff +213',
		value: '+213',
		country: __( 'Algeria', 'jetpack-forms' ),
		flag: '\ud83c\udde9\ud83c\uddff',
	},
	{
		code: 'TN',
		label: '\ud83c\uddf9\ud83c\uddf3 +216',
		value: '+216',
		country: __( 'Tunisia', 'jetpack-forms' ),
		flag: '\ud83c\uddf9\ud83c\uddf3',
	},
	{
		code: 'LY',
		label: '\ud83c\uddf1\ud83c\uddfe +218',
		value: '+218',
		country: __( 'Libya', 'jetpack-forms' ),
		flag: '\ud83c\uddf1\ud83c\uddfe',
	},
	{
		code: 'GM',
		label: '\ud83c\uddec\ud83c\uddf2 +220',
		value: '+220',
		country: __( 'Gambia', 'jetpack-forms' ),
		flag: '\ud83c\uddec\ud83c\uddf2',
	},
	{
		code: 'SN',
		label: '\ud83c\uddf8\ud83c\uddf3 +221',
		value: '+221',
		country: __( 'Senegal', 'jetpack-forms' ),
		flag: '\ud83c\uddf8\ud83c\uddf3',
	},
	{
		code: 'MR',
		label: '\ud83c\uddf2\ud83c\uddf7 +222',
		value: '+222',
		country: __( 'Mauritania', 'jetpack-forms' ),
		flag: '\ud83c\uddf2\ud83c\uddf7',
	},
	{
		code: 'ML',
		label: '\ud83c\uddf2\ud83c\uddf1 +223',
		value: '+223',
		country: __( 'Mali', 'jetpack-forms' ),
		flag: '\ud83c\uddf2\ud83c\uddf1',
	},
	{
		code: 'GN',
		label: '\ud83c\uddec\ud83c\uddf3 +224',
		value: '+224',
		country: __( 'Guinea', 'jetpack-forms' ),
		flag: '\ud83c\uddec\ud83c\uddf3',
	},
	{
		code: 'CI',
		label: '\ud83c\udde8\ud83c\uddee +225',
		value: '+225',
		country: __( "Côte d'Ivoire", 'jetpack-forms' ),
		flag: '\ud83c\udde8\ud83c\uddee',
	},
	{
		code: 'BF',
		label: '\ud83c\udde7\ud83c\uddeb +226',
		value: '+226',
		country: __( 'Burkina Faso', 'jetpack-forms' ),
		flag: '\ud83c\udde7\ud83c\uddeb',
	},
	{
		code: 'NE',
		label: '\ud83c\uddf3\ud83c\uddea +227',
		value: '+227',
		country: __( 'Niger', 'jetpack-forms' ),
		flag: '\ud83c\uddf3\ud83c\uddea',
	},
	{
		code: 'TG',
		label: '\ud83c\uddf9\ud83c\uddec +228',
		value: '+228',
		country: __( 'Togo', 'jetpack-forms' ),
		flag: '\ud83c\uddf9\ud83c\uddec',
	},
	{
		code: 'BJ',
		label: '\ud83c\udde7\ud83c\uddef +229',
		value: '+229',
		country: __( 'Benin', 'jetpack-forms' ),
		flag: '\ud83c\udde7\ud83c\uddef',
	},
	{
		code: 'MU',
		label: '\ud83c\uddf2\ud83c\uddfa +230',
		value: '+230',
		country: __( 'Mauritius', 'jetpack-forms' ),
		flag: '\ud83c\uddf2\ud83c\uddfa',
	},
	{
		code: 'LR',
		label: '\ud83c\uddf1\ud83c\uddf7 +231',
		value: '+231',
		country: __( 'Liberia', 'jetpack-forms' ),
		flag: '\ud83c\uddf1\ud83c\uddf7',
	},
	{
		code: 'SL',
		label: '\ud83c\uddf8\ud83c\uddf1 +232',
		value: '+232',
		country: __( 'Sierra Leone', 'jetpack-forms' ),
		flag: '\ud83c\uddf8\ud83c\uddf1',
	},
	{
		code: 'GH',
		label: '\ud83c\uddec\ud83c\udded +233',
		value: '+233',
		country: __( 'Ghana', 'jetpack-forms' ),
		flag: '\ud83c\uddec\ud83c\udded',
	},
	{
		code: 'NG',
		label: '\ud83c\uddf3\ud83c\uddec +234',
		value: '+234',
		country: __( 'Nigeria', 'jetpack-forms' ),
		flag: '\ud83c\uddf3\ud83c\uddec',
	},
	{
		code: 'TD',
		label: '\ud83c\uddf9\ud83c\udde9 +235',
		value: '+235',
		country: __( 'Chad', 'jetpack-forms' ),
		flag: '\ud83c\uddf9\ud83c\udde9',
	},
	{
		code: 'CF',
		label: '\ud83c\udde8\ud83c\uddeb +236',
		value: '+236',
		country: __( 'Central African Republic', 'jetpack-forms' ),
		flag: '\ud83c\udde8\ud83c\uddeb',
	},
	{
		code: 'CM',
		label: '\ud83c\udde8\ud83c\uddf2 +237',
		value: '+237',
		country: __( 'Cameroon', 'jetpack-forms' ),
		flag: '\ud83c\udde8\ud83c\uddf2',
	},
	{
		code: 'CV',
		label: '\ud83c\udde8\ud83c\uddfb +238',
		value: '+238',
		country: __( 'Cape Verde', 'jetpack-forms' ),
		flag: '\ud83c\udde8\ud83c\uddfb',
	},
	{
		code: 'ST',
		label: '\ud83c\uddf8\ud83c\uddf9 +239',
		value: '+239',
		country: __( 'São Tomé and Príncipe', 'jetpack-forms' ),
		flag: '\ud83c\uddf8\ud83c\uddf9',
	},
	{
		code: 'GQ',
		label: '\ud83c\uddec\ud83c\uddf6 +240',
		value: '+240',
		country: __( 'Equatorial Guinea', 'jetpack-forms' ),
		flag: '\ud83c\uddec\ud83c\uddf6',
	},
	{
		code: 'GA',
		label: '\ud83c\uddec\ud83c\udde6 +241',
		value: '+241',
		country: __( 'Gabon', 'jetpack-forms' ),
		flag: '\ud83c\uddec\ud83c\udde6',
	},
	{
		code: 'CG',
		label: '\ud83c\udde8\ud83c\uddec +242',
		value: '+242',
		country: __( 'Congo - Brazzaville', 'jetpack-forms' ),
		flag: '\ud83c\udde8\ud83c\uddec',
	},
	{
		code: 'CD',
		label: '\ud83c\udde8\ud83c\udde9 +243',
		value: '+243',
		country: __( 'Congo - Kinshasa', 'jetpack-forms' ),
		flag: '\ud83c\udde8\ud83c\udde9',
	},
	{
		code: 'AO',
		label: '\ud83c\udde6\ud83c\uddf4 +244',
		value: '+244',
		country: __( 'Angola', 'jetpack-forms' ),
		flag: '\ud83c\udde6\ud83c\uddf4',
	},
	{
		code: 'GW',
		label: '\ud83c\uddec\ud83c\uddfc +245',
		value: '+245',
		country: __( 'Guinea-Bissau', 'jetpack-forms' ),
		flag: '\ud83c\uddec\ud83c\uddfc',
	},
	{
		code: 'IO',
		label: '\ud83c\uddee\ud83c\uddf4 +246',
		value: '+246',
		country: __( 'British Indian Ocean Territory', 'jetpack-forms' ),
		flag: '\ud83c\uddee\ud83c\uddf4',
	},
	{
		code: 'SC',
		label: '\ud83c\uddf8\ud83c\udde8 +248',
		value: '+248',
		country: __( 'Seychelles', 'jetpack-forms' ),
		flag: '\ud83c\uddf8\ud83c\udde8',
	},
	{
		code: 'SD',
		label: '\ud83c\uddf8\ud83c\udde9 +249',
		value: '+249',
		country: __( 'Sudan', 'jetpack-forms' ),
		flag: '\ud83c\uddf8\ud83c\udde9',
	},
	{
		code: 'RW',
		label: '\ud83c\uddf7\ud83c\uddfc +250',
		value: '+250',
		country: __( 'Rwanda', 'jetpack-forms' ),
		flag: '\ud83c\uddf7\ud83c\uddfc',
	},
	{
		code: 'ET',
		label: '\ud83c\uddea\ud83c\uddf9 +251',
		value: '+251',
		country: __( 'Ethiopia', 'jetpack-forms' ),
		flag: '\ud83c\uddea\ud83c\uddf9',
	},
	{
		code: 'SO',
		label: '\ud83c\uddf8\ud83c\uddf4 +252',
		value: '+252',
		country: __( 'Somalia', 'jetpack-forms' ),
		flag: '\ud83c\uddf8\ud83c\uddf4',
	},
	{
		code: 'DJ',
		label: '\ud83c\udde9\ud83c\uddef +253',
		value: '+253',
		country: __( 'Djibouti', 'jetpack-forms' ),
		flag: '\ud83c\udde9\ud83c\uddef',
	},
	{
		code: 'KE',
		label: '\ud83c\uddf0\ud83c\uddea +254',
		value: '+254',
		country: __( 'Kenya', 'jetpack-forms' ),
		flag: '\ud83c\uddf0\ud83c\uddea',
	},
	{
		code: 'TZ',
		label: '\ud83c\uddf9\ud83c\uddff +255',
		value: '+255',
		country: __( 'Tanzania', 'jetpack-forms' ),
		flag: '\ud83c\uddf9\ud83c\uddff',
	},
	{
		code: 'UG',
		label: '\ud83c\uddfa\ud83c\uddec +256',
		value: '+256',
		country: __( 'Uganda', 'jetpack-forms' ),
		flag: '\ud83c\uddfa\ud83c\uddec',
	},
	{
		code: 'BI',
		label: '\ud83c\udde7\ud83c\uddee +257',
		value: '+257',
		country: __( 'Burundi', 'jetpack-forms' ),
		flag: '\ud83c\udde7\ud83c\uddee',
	},
	{
		code: 'MZ',
		label: '\ud83c\uddf2\ud83c\uddff +258',
		value: '+258',
		country: __( 'Mozambique', 'jetpack-forms' ),
		flag: '\ud83c\uddf2\ud83c\uddff',
	},
	{
		code: 'ZM',
		label: '\ud83c\uddff\ud83c\uddf2 +260',
		value: '+260',
		country: __( 'Zambia', 'jetpack-forms' ),
		flag: '\ud83c\uddff\ud83c\uddf2',
	},
	{
		code: 'MG',
		label: '\ud83c\uddf2\ud83c\uddec +261',
		value: '+261',
		country: __( 'Madagascar', 'jetpack-forms' ),
		flag: '\ud83c\uddf2\ud83c\uddec',
	},
	{
		code: 'YT',
		label: '\ud83c\uddfe\ud83c\uddf9 +262',
		value: '+262',
		country: __( 'Mayotte', 'jetpack-forms' ),
		flag: '\ud83c\uddfe\ud83c\uddf9',
	},
	{
		code: 'RE',
		label: '\ud83c\uddf7\ud83c\uddea +262',
		value: '+262',
		country: __( 'Réunion', 'jetpack-forms' ),
		flag: '\ud83c\uddf7\ud83c\uddea',
	},
	{
		code: 'ZW',
		label: '\ud83c\uddff\ud83c\uddfc +263',
		value: '+263',
		country: __( 'Zimbabwe', 'jetpack-forms' ),
		flag: '\ud83c\uddff\ud83c\uddfc',
	},
	{
		code: 'NA',
		label: '\ud83c\uddf3\ud83c\udde6 +264',
		value: '+264',
		country: __( 'Namibia', 'jetpack-forms' ),
		flag: '\ud83c\uddf3\ud83c\udde6',
	},
	{
		code: 'MW',
		label: '\ud83c\uddf2\ud83c\uddfc +265',
		value: '+265',
		country: __( 'Malawi', 'jetpack-forms' ),
		flag: '\ud83c\uddf2\ud83c\uddfc',
	},
	{
		code: 'LS',
		label: '\ud83c\uddf1\ud83c\uddf8 +266',
		value: '+266',
		country: __( 'Lesotho', 'jetpack-forms' ),
		flag: '\ud83c\uddf1\ud83c\uddf8',
	},
	{
		code: 'BW',
		label: '\ud83c\udde7\ud83c\uddfc +267',
		value: '+267',
		country: __( 'Botswana', 'jetpack-forms' ),
		flag: '\ud83c\udde7\ud83c\uddfc',
	},
	{
		code: 'SZ',
		label: '\ud83c\uddf8\ud83c\uddff +268',
		value: '+268',
		country: __( 'Eswatini', 'jetpack-forms' ),
		flag: '\ud83c\uddf8\ud83c\uddff',
	},
	{
		code: 'KM',
		label: '\ud83c\uddf0\ud83c\uddf2 +269',
		value: '+269',
		country: __( 'Comoros', 'jetpack-forms' ),
		flag: '\ud83c\uddf0\ud83c\uddf2',
	},
	{
		code: 'ZA',
		label: '\ud83c\uddff\ud83c\udde6 +27',
		value: '+27',
		country: __( 'South Africa', 'jetpack-forms' ),
		flag: '\ud83c\uddff\ud83c\udde6',
	},
	{
		code: 'SH',
		label: '\ud83c\uddf8\ud83c\udded +290',
		value: '+290',
		country: __( 'Saint Helena', 'jetpack-forms' ),
		flag: '\ud83c\uddf8\ud83c\udded',
	},
	{
		code: 'ER',
		label: '\ud83c\uddea\ud83c\uddf7 +291',
		value: '+291',
		country: __( 'Eritrea', 'jetpack-forms' ),
		flag: '\ud83c\uddea\ud83c\uddf7',
	},
	{
		code: 'AW',
		label: '\ud83c\udde6\ud83c\uddfc +297',
		value: '+297',
		country: __( 'Aruba', 'jetpack-forms' ),
		flag: '\ud83c\udde6\ud83c\uddfc',
	},
	{
		code: 'FO',
		label: '\ud83c\uddeb\ud83c\uddf4 +298',
		value: '+298',
		country: __( 'Faroe Islands', 'jetpack-forms' ),
		flag: '\ud83c\uddeb\ud83c\uddf4',
	},
	{
		code: 'GL',
		label: '\ud83c\uddec\ud83c\uddf1 +299',
		value: '+299',
		country: __( 'Greenland', 'jetpack-forms' ),
		flag: '\ud83c\uddec\ud83c\uddf1',
	},
	{
		code: 'GR',
		label: '\ud83c\uddec\ud83c\uddf7 +30',
		value: '+30',
		country: __( 'Greece', 'jetpack-forms' ),
		flag: '\ud83c\uddec\ud83c\uddf7',
	},
	{
		code: 'NL',
		label: '\ud83c\uddf3\ud83c\uddf1 +31',
		value: '+31',
		country: __( 'Netherlands', 'jetpack-forms' ),
		flag: '\ud83c\uddf3\ud83c\uddf1',
	},
	{
		code: 'BE',
		label: '\ud83c\udde7\ud83c\uddea +32',
		value: '+32',
		country: __( 'Belgium', 'jetpack-forms' ),
		flag: '\ud83c\udde7\ud83c\uddea',
	},
	{
		code: 'FR',
		label: '\ud83c\uddeb\ud83c\uddf7 +33',
		value: '+33',
		country: __( 'France', 'jetpack-forms' ),
		flag: '\ud83c\uddeb\ud83c\uddf7',
	},
	{
		code: 'ES',
		label: '\ud83c\uddea\ud83c\uddf8 +34',
		value: '+34',
		country: __( 'Spain', 'jetpack-forms' ),
		flag: '\ud83c\uddea\ud83c\uddf8',
	},
	{
		code: 'KY',
		label: '\ud83c\uddf0\ud83c\uddfe +345',
		value: '+345',
		country: __( 'Cayman Islands', 'jetpack-forms' ),
		flag: '\ud83c\uddf0\ud83c\uddfe',
	},
	{
		code: 'GI',
		label: '\ud83c\uddec\ud83c\uddee +350',
		value: '+350',
		country: __( 'Gibraltar', 'jetpack-forms' ),
		flag: '\ud83c\uddec\ud83c\uddee',
	},
	{
		code: 'PT',
		label: '\ud83c\uddf5\ud83c\uddf9 +351',
		value: '+351',
		country: __( 'Portugal', 'jetpack-forms' ),
		flag: '\ud83c\uddf5\ud83c\uddf9',
	},
	{
		code: 'LU',
		label: '\ud83c\uddf1\ud83c\uddfa +352',
		value: '+352',
		country: __( 'Luxembourg', 'jetpack-forms' ),
		flag: '\ud83c\uddf1\ud83c\uddfa',
	},
	{
		code: 'IE',
		label: '\ud83c\uddee\ud83c\uddea +353',
		value: '+353',
		country: __( 'Ireland', 'jetpack-forms' ),
		flag: '\ud83c\uddee\ud83c\uddea',
	},
	{
		code: 'IS',
		label: '\ud83c\uddee\ud83c\uddf8 +354',
		value: '+354',
		country: __( 'Iceland', 'jetpack-forms' ),
		flag: '\ud83c\uddee\ud83c\uddf8',
	},
	{
		code: 'AL',
		label: '\ud83c\udde6\ud83c\uddf1 +355',
		value: '+355',
		country: __( 'Albania', 'jetpack-forms' ),
		flag: '\ud83c\udde6\ud83c\uddf1',
	},
	{
		code: 'MT',
		label: '\ud83c\uddf2\ud83c\uddf9 +356',
		value: '+356',
		country: __( 'Malta', 'jetpack-forms' ),
		flag: '\ud83c\uddf2\ud83c\uddf9',
	},
	{
		code: 'CY',
		label: '\ud83c\udde8\ud83c\uddfe +357',
		value: '+357',
		country: __( 'Cyprus', 'jetpack-forms' ),
		flag: '\ud83c\udde8\ud83c\uddfe',
	},
	{
		code: 'FI',
		label: '\ud83c\uddeb\ud83c\uddee +358',
		value: '+358',
		country: __( 'Finland', 'jetpack-forms' ),
		flag: '\ud83c\uddeb\ud83c\uddee',
	},
	{
		code: 'BG',
		label: '\ud83c\udde7\ud83c\uddec +359',
		value: '+359',
		country: __( 'Bulgaria', 'jetpack-forms' ),
		flag: '\ud83c\udde7\ud83c\uddec',
	},
	{
		code: 'HU',
		label: '\ud83c\udded\ud83c\uddfa +36',
		value: '+36',
		country: __( 'Hungary', 'jetpack-forms' ),
		flag: '\ud83c\udded\ud83c\uddfa',
	},
	{
		code: 'LT',
		label: '\ud83c\uddf1\ud83c\uddf9 +370',
		value: '+370',
		country: __( 'Lithuania', 'jetpack-forms' ),
		flag: '\ud83c\uddf1\ud83c\uddf9',
	},
	{
		code: 'LV',
		label: '\ud83c\uddf1\ud83c\uddfb +371',
		value: '+371',
		country: __( 'Latvia', 'jetpack-forms' ),
		flag: '\ud83c\uddf1\ud83c\uddfb',
	},
	{
		code: 'EE',
		label: '\ud83c\uddea\ud83c\uddea +372',
		value: '+372',
		country: __( 'Estonia', 'jetpack-forms' ),
		flag: '\ud83c\uddea\ud83c\uddea',
	},
	{
		code: 'MD',
		label: '\ud83c\uddf2\ud83c\udde9 +373',
		value: '+373',
		country: __( 'Moldova', 'jetpack-forms' ),
		flag: '\ud83c\uddf2\ud83c\udde9',
	},
	{
		code: 'AM',
		label: '\ud83c\udde6\ud83c\uddf2 +374',
		value: '+374',
		country: __( 'Armenia', 'jetpack-forms' ),
		flag: '\ud83c\udde6\ud83c\uddf2',
	},
	{
		code: 'BY',
		label: '\ud83c\udde7\ud83c\uddfe +375',
		value: '+375',
		country: __( 'Belarus', 'jetpack-forms' ),
		flag: '\ud83c\udde7\ud83c\uddfe',
	},
	{
		code: 'AD',
		label: '\ud83c\udde6\ud83c\udde9 +376',
		value: '+376',
		country: __( 'Andorra', 'jetpack-forms' ),
		flag: '\ud83c\udde6\ud83c\udde9',
	},
	{
		code: 'MC',
		label: '\ud83c\uddf2\ud83c\udde8 +377',
		value: '+377',
		country: __( 'Monaco', 'jetpack-forms' ),
		flag: '\ud83c\uddf2\ud83c\udde8',
	},
	{
		code: 'SM',
		label: '\ud83c\uddf8\ud83c\uddf2 +378',
		value: '+378',
		country: __( 'San Marino', 'jetpack-forms' ),
		flag: '\ud83c\uddf8\ud83c\uddf2',
	},
	{
		code: 'VA',
		label: '\ud83c\uddfb\ud83c\udde6 +379',
		value: '+379',
		country: __( 'Vatican City', 'jetpack-forms' ),
		flag: '\ud83c\uddfb\ud83c\udde6',
	},
	{
		code: 'UA',
		label: '\ud83c\uddfa\ud83c\udde6 +380',
		value: '+380',
		country: __( 'Ukraine', 'jetpack-forms' ),
		flag: '\ud83c\uddfa\ud83c\udde6',
	},
	{
		code: 'RS',
		label: '\ud83c\uddf7\ud83c\uddf8 +381',
		value: '+381',
		country: __( 'Serbia', 'jetpack-forms' ),
		flag: '\ud83c\uddf7\ud83c\uddf8',
	},
	{
		code: 'ME',
		label: '\ud83c\uddf2\ud83c\uddea +382',
		value: '+382',
		country: __( 'Montenegro', 'jetpack-forms' ),
		flag: '\ud83c\uddf2\ud83c\uddea',
	},
	{
		code: 'XK',
		label: '\ud83c\uddfd\ud83c\uddf0 +383',
		value: '+383',
		country: __( 'Kosovo', 'jetpack-forms' ),
		flag: '\ud83c\uddfd\ud83c\uddf0',
	},
	{
		code: 'HR',
		label: '\ud83c\udded\ud83c\uddf7 +385',
		value: '+385',
		country: __( 'Croatia', 'jetpack-forms' ),
		flag: '\ud83c\udded\ud83c\uddf7',
	},
	{
		code: 'SI',
		label: '\ud83c\uddf8\ud83c\uddee +386',
		value: '+386',
		country: __( 'Slovenia', 'jetpack-forms' ),
		flag: '\ud83c\uddf8\ud83c\uddee',
	},
	{
		code: 'BA',
		label: '\ud83c\udde7\ud83c\udde6 +387',
		value: '+387',
		country: __( 'Bosnia and Herzegovina', 'jetpack-forms' ),
		flag: '\ud83c\udde7\ud83c\udde6',
	},
	{
		code: 'MK',
		label: '\ud83c\uddf2\ud83c\uddf0 +389',
		value: '+389',
		country: __( 'North Macedonia', 'jetpack-forms' ),
		flag: '\ud83c\uddf2\ud83c\uddf0',
	},
	{
		code: 'IT',
		label: '\ud83c\uddee\ud83c\uddf9 +39',
		value: '+39',
		country: __( 'Italy', 'jetpack-forms' ),
		flag: '\ud83c\uddee\ud83c\uddf9',
	},
	{
		code: 'RO',
		label: '\ud83c\uddf7\ud83c\uddf4 +40',
		value: '+40',
		country: __( 'Romania', 'jetpack-forms' ),
		flag: '\ud83c\uddf7\ud83c\uddf4',
	},
	{
		code: 'CH',
		label: '\ud83c\udde8\ud83c\udded +41',
		value: '+41',
		country: __( 'Switzerland', 'jetpack-forms' ),
		flag: '\ud83c\udde8\ud83c\udded',
	},
	{
		code: 'CZ',
		label: '\ud83c\udde8\ud83c\uddff +420',
		value: '+420',
		country: __( 'Czech Republic', 'jetpack-forms' ),
		flag: '\ud83c\udde8\ud83c\uddff',
	},
	{
		code: 'SK',
		label: '\ud83c\uddf8\ud83c\uddf0 +421',
		value: '+421',
		country: __( 'Slovakia', 'jetpack-forms' ),
		flag: '\ud83c\uddf8\ud83c\uddf0',
	},
	{
		code: 'LI',
		label: '\ud83c\uddf1\ud83c\uddee +423',
		value: '+423',
		country: __( 'Liechtenstein', 'jetpack-forms' ),
		flag: '\ud83c\uddf1\ud83c\uddee',
	},
	{
		code: 'AT',
		label: '\ud83c\udde6\ud83c\uddf9 +43',
		value: '+43',
		country: __( 'Austria', 'jetpack-forms' ),
		flag: '\ud83c\udde6\ud83c\uddf9',
	},
	{
		code: 'IM',
		label: '\ud83c\uddee\ud83c\uddf2 +44',
		value: '+44',
		country: __( 'Isle of Man', 'jetpack-forms' ),
		flag: '\ud83c\uddee\ud83c\uddf2',
	},
	{
		code: 'GG',
		label: '\ud83c\uddec\ud83c\uddec +44',
		value: '+44',
		country: __( 'Guernsey', 'jetpack-forms' ),
		flag: '\ud83c\uddec\ud83c\uddec',
	},
	{
		code: 'JE',
		label: '\ud83c\uddef\ud83c\uddea +44',
		value: '+44',
		country: __( 'Jersey', 'jetpack-forms' ),
		flag: '\ud83c\uddef\ud83c\uddea',
	},
	{
		code: 'GB',
		label: '\ud83c\uddec\ud83c\udde7 +44',
		value: '+44',
		country: __( 'United Kingdom', 'jetpack-forms' ),
		flag: '\ud83c\uddec\ud83c\udde7',
	},
	{
		code: 'DK',
		label: '\ud83c\udde9\ud83c\uddf0 +45',
		value: '+45',
		country: __( 'Denmark', 'jetpack-forms' ),
		flag: '\ud83c\udde9\ud83c\uddf0',
	},
	{
		code: 'SE',
		label: '\ud83c\uddf8\ud83c\uddea +46',
		value: '+46',
		country: __( 'Sweden', 'jetpack-forms' ),
		flag: '\ud83c\uddf8\ud83c\uddea',
	},
	{
		code: 'NO',
		label: '\ud83c\uddf3\ud83c\uddf4 +47',
		value: '+47',
		country: __( 'Norway', 'jetpack-forms' ),
		flag: '\ud83c\uddf3\ud83c\uddf4',
	},
	{
		code: 'SJ',
		label: '\ud83c\uddf8\ud83c\uddef +47',
		value: '+47',
		country: __( 'Svalbard and Jan Mayen', 'jetpack-forms' ),
		flag: '\ud83c\uddf8\ud83c\uddef',
	},
	{
		code: 'PL',
		label: '\ud83c\uddf5\ud83c\uddf1 +48',
		value: '+48',
		country: __( 'Poland', 'jetpack-forms' ),
		flag: '\ud83c\uddf5\ud83c\uddf1',
	},
	{
		code: 'DE',
		label: '\ud83c\udde9\ud83c\uddea +49',
		value: '+49',
		country: __( 'Germany', 'jetpack-forms' ),
		flag: '\ud83c\udde9\ud83c\uddea',
	},
	{
		code: 'FK',
		label: '\ud83c\uddeb\ud83c\uddf0 +500',
		value: '+500',
		country: __( 'Falkland Islands', 'jetpack-forms' ),
		flag: '\ud83c\uddeb\ud83c\uddf0',
	},
	{
		code: 'GS',
		label: '\ud83c\uddec\ud83c\uddf8 +500',
		value: '+500',
		country: __( 'South Georgia and the South Sandwich Islands', 'jetpack-forms' ),
		flag: '\ud83c\uddec\ud83c\uddf8',
	},
	{
		code: 'BZ',
		label: '\ud83c\udde7\ud83c\uddff +501',
		value: '+501',
		country: __( 'Belize', 'jetpack-forms' ),
		flag: '\ud83c\udde7\ud83c\uddff',
	},
	{
		code: 'GT',
		label: '\ud83c\uddec\ud83c\uddf9 +502',
		value: '+502',
		country: __( 'Guatemala', 'jetpack-forms' ),
		flag: '\ud83c\uddec\ud83c\uddf9',
	},
	{
		code: 'SV',
		label: '\ud83c\uddf8\ud83c\uddfb +503',
		value: '+503',
		country: __( 'El Salvador', 'jetpack-forms' ),
		flag: '\ud83c\uddf8\ud83c\uddfb',
	},
	{
		code: 'HN',
		label: '\ud83c\udded\ud83c\uddf3 +504',
		value: '+504',
		country: __( 'Honduras', 'jetpack-forms' ),
		flag: '\ud83c\udded\ud83c\uddf3',
	},
	{
		code: 'NI',
		label: '\ud83c\uddf3\ud83c\uddee +505',
		value: '+505',
		country: __( 'Nicaragua', 'jetpack-forms' ),
		flag: '\ud83c\uddf3\ud83c\uddee',
	},
	{
		code: 'CR',
		label: '\ud83c\udde8\ud83c\uddf7 +506',
		value: '+506',
		country: __( 'Costa Rica', 'jetpack-forms' ),
		flag: '\ud83c\udde8\ud83c\uddf7',
	},
	{
		code: 'PA',
		label: '\ud83c\uddf5\ud83c\udde6 +507',
		value: '+507',
		country: __( 'Panama', 'jetpack-forms' ),
		flag: '\ud83c\uddf5\ud83c\udde6',
	},
	{
		code: 'PM',
		label: '\ud83c\uddf5\ud83c\uddf2 +508',
		value: '+508',
		country: __( 'Saint Pierre and Miquelon', 'jetpack-forms' ),
		flag: '\ud83c\uddf5\ud83c\uddf2',
	},
	{
		code: 'HT',
		label: '\ud83c\udded\ud83c\uddf9 +509',
		value: '+509',
		country: __( 'Haiti', 'jetpack-forms' ),
		flag: '\ud83c\udded\ud83c\uddf9',
	},
	{
		code: 'PE',
		label: '\ud83c\uddf5\ud83c\uddea +51',
		value: '+51',
		country: __( 'Peru', 'jetpack-forms' ),
		flag: '\ud83c\uddf5\ud83c\uddea',
	},
	{
		code: 'MX',
		label: '\ud83c\uddf2\ud83c\uddfd +52',
		value: '+52',
		country: __( 'Mexico', 'jetpack-forms' ),
		flag: '\ud83c\uddf2\ud83c\uddfd',
	},
	{
		code: 'CU',
		label: '\ud83c\udde8\ud83c\uddfa +53',
		value: '+53',
		country: __( 'Cuba', 'jetpack-forms' ),
		flag: '\ud83c\udde8\ud83c\uddfa',
	},
	{
		code: 'AR',
		label: '\ud83c\udde6\ud83c\uddf7 +54',
		value: '+54',
		country: __( 'Argentina', 'jetpack-forms' ),
		flag: '\ud83c\udde6\ud83c\uddf7',
	},
	{
		code: 'BR',
		label: '\ud83c\udde7\ud83c\uddf7 +55',
		value: '+55',
		country: __( 'Brazil', 'jetpack-forms' ),
		flag: '\ud83c\udde7\ud83c\uddf7',
	},
	{
		code: 'CL',
		label: '\ud83c\udde8\ud83c\uddf1 +56',
		value: '+56',
		country: __( 'Chile', 'jetpack-forms' ),
		flag: '\ud83c\udde8\ud83c\uddf1',
	},
	{
		code: 'CO',
		label: '\ud83c\udde8\ud83c\uddf4 +57',
		value: '+57',
		country: __( 'Colombia', 'jetpack-forms' ),
		flag: '\ud83c\udde8\ud83c\uddf4',
	},
	{
		code: 'VE',
		label: '\ud83c\uddfb\ud83c\uddea +58',
		value: '+58',
		country: __( 'Venezuela', 'jetpack-forms' ),
		flag: '\ud83c\uddfb\ud83c\uddea',
	},
	{
		code: 'BL',
		label: '\ud83c\udde7\ud83c\uddf1 +590',
		value: '+590',
		country: __( 'Saint Barthélemy', 'jetpack-forms' ),
		flag: '\ud83c\udde7\ud83c\uddf1',
	},
	{
		code: 'MF',
		label: '\ud83c\uddf2\ud83c\uddeb +590',
		value: '+590',
		country: __( 'Saint Martin', 'jetpack-forms' ),
		flag: '\ud83c\uddf2\ud83c\uddeb',
	},
	{
		code: 'GP',
		label: '\ud83c\uddec\ud83c\uddf5 +590',
		value: '+590',
		country: __( 'Guadeloupe', 'jetpack-forms' ),
		flag: '\ud83c\uddec\ud83c\uddf5',
	},
	{
		code: 'BO',
		label: '\ud83c\udde7\ud83c\uddf4 +591',
		value: '+591',
		country: __( 'Bolivia', 'jetpack-forms' ),
		flag: '\ud83c\udde7\ud83c\uddf4',
	},
	{
		code: 'GY',
		label: '\ud83c\uddec\ud83c\uddfe +592',
		value: '+592',
		country: __( 'Guyana', 'jetpack-forms' ),
		flag: '\ud83c\uddec\ud83c\uddfe',
	},
	{
		code: 'EC',
		label: '\ud83c\uddea\ud83c\udde8 +593',
		value: '+593',
		country: __( 'Ecuador', 'jetpack-forms' ),
		flag: '\ud83c\uddea\ud83c\udde8',
	},
	{
		code: 'GF',
		label: '\ud83c\uddec\ud83c\uddeb +594',
		value: '+594',
		country: __( 'French Guiana', 'jetpack-forms' ),
		flag: '\ud83c\uddec\ud83c\uddeb',
	},
	{
		code: 'PY',
		label: '\ud83c\uddf5\ud83c\uddfe +595',
		value: '+595',
		country: __( 'Paraguay', 'jetpack-forms' ),
		flag: '\ud83c\uddf5\ud83c\uddfe',
	},
	{
		code: 'MQ',
		label: '\ud83c\uddf2\ud83c\uddf6 +596',
		value: '+596',
		country: __( 'Martinique', 'jetpack-forms' ),
		flag: '\ud83c\uddf2\ud83c\uddf6',
	},
	{
		code: 'SR',
		label: '\ud83c\uddf8\ud83c\uddf7 +597',
		value: '+597',
		country: __( 'Suriname', 'jetpack-forms' ),
		flag: '\ud83c\uddf8\ud83c\uddf7',
	},
	{
		code: 'UY',
		label: '\ud83c\uddfa\ud83c\uddfe +598',
		value: '+598',
		country: __( 'Uruguay', 'jetpack-forms' ),
		flag: '\ud83c\uddfa\ud83c\uddfe',
	},
	{
		code: 'MY',
		label: '\ud83c\uddf2\ud83c\uddfe +60',
		value: '+60',
		country: __( 'Malaysia', 'jetpack-forms' ),
		flag: '\ud83c\uddf2\ud83c\uddfe',
	},
	{
		code: 'CC',
		label: '\ud83c\udde8\ud83c\udde8 +61',
		value: '+61',
		country: __( 'Cocos (Keeling) Islands', 'jetpack-forms' ),
		flag: '\ud83c\udde8\ud83c\udde8',
	},
	{
		code: 'AU',
		label: '\ud83c\udde6\ud83c\uddfa +61',
		value: '+61',
		country: __( 'Australia', 'jetpack-forms' ),
		flag: '\ud83c\udde6\ud83c\uddfa',
	},
	{
		code: 'CX',
		label: '\ud83c\udde8\ud83c\uddfd +61',
		value: '+61',
		country: __( 'Christmas Island', 'jetpack-forms' ),
		flag: '\ud83c\udde8\ud83c\uddfd',
	},
	{
		code: 'ID',
		label: '\ud83c\uddee\ud83c\udde9 +62',
		value: '+62',
		country: __( 'Indonesia', 'jetpack-forms' ),
		flag: '\ud83c\uddee\ud83c\udde9',
	},
	{
		code: 'PH',
		label: '\ud83c\uddf5\ud83c\udded +63',
		value: '+63',
		country: __( 'Philippines', 'jetpack-forms' ),
		flag: '\ud83c\uddf5\ud83c\udded',
	},
	{
		code: 'NZ',
		label: '\ud83c\uddf3\ud83c\uddff +64',
		value: '+64',
		country: __( 'New Zealand', 'jetpack-forms' ),
		flag: '\ud83c\uddf3\ud83c\uddff',
	},
	{
		code: 'SG',
		label: '\ud83c\uddf8\ud83c\uddec +65',
		value: '+65',
		country: __( 'Singapore', 'jetpack-forms' ),
		flag: '\ud83c\uddf8\ud83c\uddec',
	},
	{
		code: 'TH',
		label: '\ud83c\uddf9\ud83c\udded +66',
		value: '+66',
		country: __( 'Thailand', 'jetpack-forms' ),
		flag: '\ud83c\uddf9\ud83c\udded',
	},
	{
		code: 'TL',
		label: '\ud83c\uddf9\ud83c\uddf1 +670',
		value: '+670',
		country: __( 'Timor-Leste', 'jetpack-forms' ),
		flag: '\ud83c\uddf9\ud83c\uddf1',
	},
	{
		code: 'NF',
		label: '\ud83c\uddf3\ud83c\uddeb +672',
		value: '+672',
		country: __( 'Norfolk Island', 'jetpack-forms' ),
		flag: '\ud83c\uddf3\ud83c\uddeb',
	},
	{
		code: 'BN',
		label: '\ud83c\udde7\ud83c\uddf3 +673',
		value: '+673',
		country: __( 'Brunei', 'jetpack-forms' ),
		flag: '\ud83c\udde7\ud83c\uddf3',
	},
	{
		code: 'NR',
		label: '\ud83c\uddf3\ud83c\uddf7 +674',
		value: '+674',
		country: __( 'Nauru', 'jetpack-forms' ),
		flag: '\ud83c\uddf3\ud83c\uddf7',
	},
	{
		code: 'PG',
		label: '\ud83c\uddf5\ud83c\uddec +675',
		value: '+675',
		country: __( 'Papua New Guinea', 'jetpack-forms' ),
		flag: '\ud83c\uddf5\ud83c\uddec',
	},
	{
		code: 'TO',
		label: '\ud83c\uddf9\ud83c\uddf4 +676',
		value: '+676',
		country: __( 'Tonga', 'jetpack-forms' ),
		flag: '\ud83c\uddf9\ud83c\uddf4',
	},
	{
		code: 'SB',
		label: '\ud83c\uddf8\ud83c\udde7 +677',
		value: '+677',
		country: __( 'Solomon Islands', 'jetpack-forms' ),
		flag: '\ud83c\uddf8\ud83c\udde7',
	},
	{
		code: 'VU',
		label: '\ud83c\uddfb\ud83c\uddfa +678',
		value: '+678',
		country: __( 'Vanuatu', 'jetpack-forms' ),
		flag: '\ud83c\uddfb\ud83c\uddfa',
	},
	{
		code: 'FJ',
		label: '\ud83c\uddeb\ud83c\uddef +679',
		value: '+679',
		country: __( 'Fiji', 'jetpack-forms' ),
		flag: '\ud83c\uddeb\ud83c\uddef',
	},
	{
		code: 'PW',
		label: '\ud83c\uddf5\ud83c\uddfc +680',
		value: '+680',
		country: __( 'Palau', 'jetpack-forms' ),
		flag: '\ud83c\uddf5\ud83c\uddfc',
	},
	{
		code: 'WF',
		label: '\ud83c\uddfc\ud83c\uddeb +681',
		value: '+681',
		country: __( 'Wallis and Futuna', 'jetpack-forms' ),
		flag: '\ud83c\uddfc\ud83c\uddeb',
	},
	{
		code: 'CK',
		label: '\ud83c\udde8\ud83c\uddf0 +682',
		value: '+682',
		country: __( 'Cook Islands', 'jetpack-forms' ),
		flag: '\ud83c\udde8\ud83c\uddf0',
	},
	{
		code: 'NU',
		label: '\ud83c\uddf3\ud83c\uddfa +683',
		value: '+683',
		country: __( 'Niue', 'jetpack-forms' ),
		flag: '\ud83c\uddf3\ud83c\uddfa',
	},
	{
		code: 'WS',
		label: '\ud83c\uddfc\ud83c\uddf8 +685',
		value: '+685',
		country: __( 'Samoa', 'jetpack-forms' ),
		flag: '\ud83c\uddfc\ud83c\uddf8',
	},
	{
		code: 'KI',
		label: '\ud83c\uddf0\ud83c\uddee +686',
		value: '+686',
		country: __( 'Kiribati', 'jetpack-forms' ),
		flag: '\ud83c\uddf0\ud83c\uddee',
	},
	{
		code: 'NC',
		label: '\ud83c\uddf3\ud83c\udde8 +687',
		value: '+687',
		country: __( 'New Caledonia', 'jetpack-forms' ),
		flag: '\ud83c\uddf3\ud83c\udde8',
	},
	{
		code: 'TV',
		label: '\ud83c\uddf9\ud83c\uddfb +688',
		value: '+688',
		country: __( 'Tuvalu', 'jetpack-forms' ),
		flag: '\ud83c\uddf9\ud83c\uddfb',
	},
	{
		code: 'PF',
		label: '\ud83c\uddf5\ud83c\uddeb +689',
		value: '+689',
		country: __( 'French Polynesia', 'jetpack-forms' ),
		flag: '\ud83c\uddf5\ud83c\uddeb',
	},
	{
		code: 'TK',
		label: '\ud83c\uddf9\ud83c\uddf0 +690',
		value: '+690',
		country: __( 'Tokelau', 'jetpack-forms' ),
		flag: '\ud83c\uddf9\ud83c\uddf0',
	},
	{
		code: 'FM',
		label: '\ud83c\uddeb\ud83c\uddf2 +691',
		value: '+691',
		country: __( 'Micronesia', 'jetpack-forms' ),
		flag: '\ud83c\uddeb\ud83c\uddf2',
	},
	{
		code: 'MH',
		label: '\ud83c\uddf2\ud83c\udded +692',
		value: '+692',
		country: __( 'Marshall Islands', 'jetpack-forms' ),
		flag: '\ud83c\uddf2\ud83c\udded',
	},
	{
		code: 'RU',
		label: '\ud83c\uddf7\ud83c\uddfa +7',
		value: '+7',
		country: __( 'Russia', 'jetpack-forms' ),
		flag: '\ud83c\uddf7\ud83c\uddfa',
	},
	{
		code: 'KZ',
		label: '\ud83c\uddf0\ud83c\uddff +77',
		value: '+77',
		country: __( 'Kazakhstan', 'jetpack-forms' ),
		flag: '\ud83c\uddf0\ud83c\uddff',
	},
	{
		code: 'JP',
		label: '\ud83c\uddef\ud83c\uddf5 +81',
		value: '+81',
		country: __( 'Japan', 'jetpack-forms' ),
		flag: '\ud83c\uddef\ud83c\uddf5',
	},
	{
		code: 'KR',
		label: '\ud83c\uddf0\ud83c\uddf7 +82',
		value: '+82',
		country: __( 'South Korea', 'jetpack-forms' ),
		flag: '\ud83c\uddf0\ud83c\uddf7',
	},
	{
		code: 'VN',
		label: '\ud83c\uddfb\ud83c\uddf3 +84',
		value: '+84',
		country: __( 'Vietnam', 'jetpack-forms' ),
		flag: '\ud83c\uddfb\ud83c\uddf3',
	},
	{
		code: 'KP',
		label: '\ud83c\uddf0\ud83c\uddf5 +850',
		value: '+850',
		country: __( 'North Korea', 'jetpack-forms' ),
		flag: '\ud83c\uddf0\ud83c\uddf5',
	},
	{
		code: 'HK',
		label: '\ud83c\udded\ud83c\uddf0 +852',
		value: '+852',
		country: __( 'Hong Kong', 'jetpack-forms' ),
		flag: '\ud83c\udded\ud83c\uddf0',
	},
	{
		code: 'MO',
		label: '\ud83c\uddf2\ud83c\uddf4 +853',
		value: '+853',
		country: __( 'Macao', 'jetpack-forms' ),
		flag: '\ud83c\uddf2\ud83c\uddf4',
	},
	{
		code: 'KH',
		label: '\ud83c\uddf0\ud83c\udded +855',
		value: '+855',
		country: __( 'Cambodia', 'jetpack-forms' ),
		flag: '\ud83c\uddf0\ud83c\udded',
	},
	{
		code: 'LA',
		label: '\ud83c\uddf1\ud83c\udde6 +856',
		value: '+856',
		country: __( 'Laos', 'jetpack-forms' ),
		flag: '\ud83c\uddf1\ud83c\udde6',
	},
	{
		code: 'CN',
		label: '\ud83c\udde8\ud83c\uddf3 +86',
		value: '+86',
		country: __( 'China', 'jetpack-forms' ),
		flag: '\ud83c\udde8\ud83c\uddf3',
	},
	{
		code: 'PN',
		label: '\ud83c\uddf5\ud83c\uddf3 +872',
		value: '+872',
		country: __( 'Pitcairn Islands', 'jetpack-forms' ),
		flag: '\ud83c\uddf5\ud83c\uddf3',
	},
	{
		code: 'BD',
		label: '\ud83c\udde7\ud83c\udde9 +880',
		value: '+880',
		country: __( 'Bangladesh', 'jetpack-forms' ),
		flag: '\ud83c\udde7\ud83c\udde9',
	},
	{
		code: 'TW',
		label: '\ud83c\uddf9\ud83c\uddfc +886',
		value: '+886',
		country: __( 'Taiwan', 'jetpack-forms' ),
		flag: '\ud83c\uddf9\ud83c\uddfc',
	},
	{
		code: 'TR',
		label: '\ud83c\uddf9\ud83c\uddf7 +90',
		value: '+90',
		country: __( 'Turkey', 'jetpack-forms' ),
		flag: '\ud83c\uddf9\ud83c\uddf7',
	},
	{
		code: 'IN',
		label: '\ud83c\uddee\ud83c\uddf3 +91',
		value: '+91',
		country: __( 'India', 'jetpack-forms' ),
		flag: '\ud83c\uddee\ud83c\uddf3',
	},
	{
		code: 'PK',
		label: '\ud83c\uddf5\ud83c\uddf0 +92',
		value: '+92',
		country: __( 'Pakistan', 'jetpack-forms' ),
		flag: '\ud83c\uddf5\ud83c\uddf0',
	},
	{
		code: 'AF',
		label: '\ud83c\udde6\ud83c\uddeb +93',
		value: '+93',
		country: __( 'Afghanistan', 'jetpack-forms' ),
		flag: '\ud83c\udde6\ud83c\uddeb',
	},
	{
		code: 'LK',
		label: '\ud83c\uddf1\ud83c\uddf0 +94',
		value: '+94',
		country: __( 'Sri Lanka', 'jetpack-forms' ),
		flag: '\ud83c\uddf1\ud83c\uddf0',
	},
	{
		code: 'MM',
		label: '\ud83c\uddf2\ud83c\uddf2 +95',
		value: '+95',
		country: __( 'Myanmar', 'jetpack-forms' ),
		flag: '\ud83c\uddf2\ud83c\uddf2',
	},
	{
		code: 'MV',
		label: '\ud83c\uddf2\ud83c\uddfb +960',
		value: '+960',
		country: __( 'Maldives', 'jetpack-forms' ),
		flag: '\ud83c\uddf2\ud83c\uddfb',
	},
	{
		code: 'LB',
		label: '\ud83c\uddf1\ud83c\udde7 +961',
		value: '+961',
		country: __( 'Lebanon', 'jetpack-forms' ),
		flag: '\ud83c\uddf1\ud83c\udde7',
	},
	{
		code: 'JO',
		label: '\ud83c\uddef\ud83c\uddf4 +962',
		value: '+962',
		country: __( 'Jordan', 'jetpack-forms' ),
		flag: '\ud83c\uddef\ud83c\uddf4',
	},
	{
		code: 'SY',
		label: '\ud83c\uddf8\ud83c\uddfe +963',
		value: '+963',
		country: __( 'Syria', 'jetpack-forms' ),
		flag: '\ud83c\uddf8\ud83c\uddfe',
	},
	{
		code: 'IQ',
		label: '\ud83c\uddee\ud83c\uddf6 +964',
		value: '+964',
		country: __( 'Iraq', 'jetpack-forms' ),
		flag: '\ud83c\uddee\ud83c\uddf6',
	},
	{
		code: 'KW',
		label: '\ud83c\uddf0\ud83c\uddfc +965',
		value: '+965',
		country: __( 'Kuwait', 'jetpack-forms' ),
		flag: '\ud83c\uddf0\ud83c\uddfc',
	},
	{
		code: 'SA',
		label: '\ud83c\uddf8\ud83c\udde6 +966',
		value: '+966',
		country: __( 'Saudi Arabia', 'jetpack-forms' ),
		flag: '\ud83c\uddf8\ud83c\udde6',
	},
	{
		code: 'YE',
		label: '\ud83c\uddfe\ud83c\uddea +967',
		value: '+967',
		country: __( 'Yemen', 'jetpack-forms' ),
		flag: '\ud83c\uddfe\ud83c\uddea',
	},
	{
		code: 'OM',
		label: '\ud83c\uddf4\ud83c\uddf2 +968',
		value: '+968',
		country: __( 'Oman', 'jetpack-forms' ),
		flag: '\ud83c\uddf4\ud83c\uddf2',
	},
	{
		code: 'PS',
		label: '\ud83c\uddf5\ud83c\uddf8 +970',
		value: '+970',
		country: __( 'Palestine', 'jetpack-forms' ),
		flag: '\ud83c\uddf5\ud83c\uddf8',
	},
	{
		code: 'AE',
		label: '\ud83c\udde6\ud83c\uddea +971',
		value: '+971',
		country: __( 'United Arab Emirates', 'jetpack-forms' ),
		flag: '\ud83c\udde6\ud83c\uddea',
	},
	{
		code: 'IL',
		label: '\ud83c\uddee\ud83c\uddf1 +972',
		value: '+972',
		country: __( 'Israel', 'jetpack-forms' ),
		flag: '\ud83c\uddee\ud83c\uddf1',
	},
	{
		code: 'BH',
		label: '\ud83c\udde7\ud83c\udded +973',
		value: '+973',
		country: __( 'Bahrain', 'jetpack-forms' ),
		flag: '\ud83c\udde7\ud83c\udded',
	},
	{
		code: 'QA',
		label: '\ud83c\uddf6\ud83c\udde6 +974',
		value: '+974',
		country: __( 'Qatar', 'jetpack-forms' ),
		flag: '\ud83c\uddf6\ud83c\udde6',
	},
	{
		code: 'BT',
		label: '\ud83c\udde7\ud83c\uddf9 +975',
		value: '+975',
		country: __( 'Bhutan', 'jetpack-forms' ),
		flag: '\ud83c\udde7\ud83c\uddf9',
	},
	{
		code: 'MN',
		label: '\ud83c\uddf2\ud83c\uddf3 +976',
		value: '+976',
		country: __( 'Mongolia', 'jetpack-forms' ),
		flag: '\ud83c\uddf2\ud83c\uddf3',
	},
	{
		code: 'NP',
		label: '\ud83c\uddf3\ud83c\uddf5 +977',
		value: '+977',
		country: __( 'Nepal', 'jetpack-forms' ),
		flag: '\ud83c\uddf3\ud83c\uddf5',
	},
	{
		code: 'IR',
		label: '\ud83c\uddee\ud83c\uddf7 +98',
		value: '+98',
		country: __( 'Iran', 'jetpack-forms' ),
		flag: '\ud83c\uddee\ud83c\uddf7',
	},
	{
		code: 'TJ',
		label: '\ud83c\uddf9\ud83c\uddef +992',
		value: '+992',
		country: __( 'Tajikistan', 'jetpack-forms' ),
		flag: '\ud83c\uddf9\ud83c\uddef',
	},
	{
		code: 'TM',
		label: '\ud83c\uddf9\ud83c\uddf2 +993',
		value: '+993',
		country: __( 'Turkmenistan', 'jetpack-forms' ),
		flag: '\ud83c\uddf9\ud83c\uddf2',
	},
	{
		code: 'AZ',
		label: '\ud83c\udde6\ud83c\uddff +994',
		value: '+994',
		country: __( 'Azerbaijan', 'jetpack-forms' ),
		flag: '\ud83c\udde6\ud83c\uddff',
	},
	{
		code: 'GE',
		label: '\ud83c\uddec\ud83c\uddea +995',
		value: '+995',
		country: __( 'Georgia', 'jetpack-forms' ),
		flag: '\ud83c\uddec\ud83c\uddea',
	},
	{
		code: 'KG',
		label: '\ud83c\uddf0\ud83c\uddec +996',
		value: '+996',
		country: __( 'Kyrgyzstan', 'jetpack-forms' ),
		flag: '\ud83c\uddf0\ud83c\uddec',
	},
	{
		code: 'UZ',
		label: '\ud83c\uddfa\ud83c\uddff +998',
		value: '+998',
		country: __( 'Uzbekistan', 'jetpack-forms' ),
		flag: '\ud83c\uddfa\ud83c\uddff',
	},
];
