import { getRedirectUrl } from '@automattic/jetpack-components';
import { Attachment } from '@wordpress/core-data';

export const FEATURED_IMAGE_STILL_LOADING = 'featured-image-still-loading';

export type ImageType = 'custom' | 'featured' | 'default' | 'none';

const getMediaSourceUrl = ( media: Attachment ) => {
	return media?.media_details?.sizes?.large?.source_url || media?.source_url;
};

export const getImageId = (
	imageType: ImageType,
	customImageId: number | null,
	featuredImageId: number | null,
	defaultImageId: number | null
) => {
	if ( imageType === 'custom' && customImageId ) {
		return customImageId;
	}

	if ( imageType === 'default' && defaultImageId ) {
		return defaultImageId;
	}

	if ( imageType === 'featured' && featuredImageId ) {
		return featuredImageId;
	}

	return featuredImageId || defaultImageId;
};

const hasNoValidImage = (
	imageType: ImageType,
	customImageId: number | null,
	featuredImageId: number | null,
	defaultImageId: number | null
) => {
	// No image type selected
	if ( imageType === 'none' ) {
		return true;
	}

	// Custom image selected but no image provided
	if ( imageType === 'custom' && ! customImageId ) {
		return true;
	}

	// Default image selected but no valid default image
	if ( imageType === 'default' && ! defaultImageId ) {
		return true;
	}

	// Featured image type (or null/undefined) but no featured image and no valid default fallback
	if ( ( imageType ?? 'featured' ) === 'featured' && ! featuredImageId && ! defaultImageId ) {
		return true;
	}

	return false;
};

export const calculateImageUrl = (
	imageType: ImageType,
	customImageId: number | null,
	featuredImageId: number | null,
	defaultImageId: number | null,
	getMedia: ( id: number | null ) => Attachment | null | undefined
) => {
	if ( hasNoValidImage( imageType, customImageId, featuredImageId, defaultImageId ) ) {
		return null;
	}

	const usedImageId = getImageId( imageType, customImageId, featuredImageId, defaultImageId );

	const media = getMedia( usedImageId );
	// undefined means the entity record hasn't been fetched yet (still loading).
	// null means the resolution finished but the attachment doesn't exist (deleted).
	if ( media === undefined ) {
		return FEATURED_IMAGE_STILL_LOADING;
	}
	if ( ! media ) {
		return null;
	}
	return getMediaSourceUrl( media );
};

/**
 * Returns the URL to the image generated by the Social Image Generator.
 *
 * @param {string} token - The token for the image.
 * @return - The URL to the image.
 */
export function getSigImageUrl( token: string ) {
	return token ? getRedirectUrl( 'sigenerate', { query: `t=${ token }` } ) : '';
}
