export const siteWithSecurityPlanResponseBody = {
	ID: 12345678,
	name: 'My awesome Jetpack mock site',
	description: 'Just another mocking WordPress site',
	URL: 'https://mock-site.com',
	options: {
		timezone: '',
		gmt_offset: 0,
		blog_public: 0,
		login_url: 'https://mock-site.com/wp-login.php',
		admin_url: 'https://mock-site.com/wp-admin/',
	},
	plan: {
		product_id: 2017,
		product_slug: 'jetpack_security_t1_monthly',
		product_name: 'Jetpack Security (10GB)',
		product_name_short: 'Security (10GB)',
		expired: false,
		billing_period: 'Monthly',
		user_is_owner: true,
		is_free: false,
		license_key: '',
		features: {
			active: [
				'google-analytics',
				'security-settings',
				'advanced-seo',
				'upload-video-files',
				'video-hosting',
				'wordads-jetpack',
				'akismet',
				'send-a-message',
				'whatsapp-button',
				'social-previews',
				'donations',
				'core/audio',
				'republicize',
				'premium-content/container',
				'support',
			],
			available: {
				'security-settings': [
					'jetpack_free',
					'jetpack_premium',
					'jetpack_business',
					'jetpack_personal',
					'jetpack_premium_monthly',
					'jetpack_business_monthly',
					'jetpack_personal_monthly',
					'jetpack_security_daily',
					'jetpack_security_daily_monthly',
					'jetpack_security_realtime',
					'jetpack_security_realtime_monthly',
					'jetpack_complete',
					'jetpack_complete_monthly',
					'jetpack_security_t1_yearly',
					'jetpack_security_t2_yearly',
					'jetpack_security_t2_monthly',
				],
				'advanced-seo': [
					'jetpack_free',
					'jetpack_premium',
					'jetpack_business',
					'jetpack_personal',
					'jetpack_premium_monthly',
					'jetpack_business_monthly',
					'jetpack_personal_monthly',
					'jetpack_security_daily',
					'jetpack_security_daily_monthly',
					'jetpack_security_realtime',
					'jetpack_security_realtime_monthly',
					'jetpack_complete',
					'jetpack_complete_monthly',
					'jetpack_security_t1_yearly',
					'jetpack_security_t2_yearly',
					'jetpack_security_t2_monthly',
				],
				'upload-video-files': [
					'jetpack_free',
					'jetpack_premium',
					'jetpack_business',
					'jetpack_personal',
					'jetpack_premium_monthly',
					'jetpack_business_monthly',
					'jetpack_personal_monthly',
					'jetpack_security_daily',
					'jetpack_security_daily_monthly',
					'jetpack_security_realtime',
					'jetpack_security_realtime_monthly',
					'jetpack_complete',
					'jetpack_complete_monthly',
					'jetpack_security_t1_yearly',
					'jetpack_security_t2_yearly',
					'jetpack_security_t2_monthly',
				],
				akismet: [
					'jetpack_free',
					'jetpack_premium',
					'jetpack_business',
					'jetpack_personal',
					'jetpack_premium_monthly',
					'jetpack_business_monthly',
					'jetpack_personal_monthly',
					'jetpack_security_daily',
					'jetpack_security_daily_monthly',
					'jetpack_security_realtime',
					'jetpack_security_realtime_monthly',
					'jetpack_complete',
					'jetpack_complete_monthly',
					'jetpack_security_t1_yearly',
					'jetpack_security_t2_yearly',
					'jetpack_security_t2_monthly',
				],
				'send-a-message': [
					'jetpack_free',
					'jetpack_premium',
					'jetpack_business',
					'jetpack_personal',
					'jetpack_premium_monthly',
					'jetpack_business_monthly',
					'jetpack_personal_monthly',
					'jetpack_security_daily',
					'jetpack_security_daily_monthly',
					'jetpack_security_realtime',
					'jetpack_security_realtime_monthly',
					'jetpack_complete',
					'jetpack_complete_monthly',
					'jetpack_security_t1_yearly',
					'jetpack_security_t2_yearly',
					'jetpack_security_t2_monthly',
				],
				'whatsapp-button': [
					'jetpack_free',
					'jetpack_premium',
					'jetpack_business',
					'jetpack_personal',
					'jetpack_premium_monthly',
					'jetpack_business_monthly',
					'jetpack_personal_monthly',
					'jetpack_security_daily',
					'jetpack_security_daily_monthly',
					'jetpack_security_realtime',
					'jetpack_security_realtime_monthly',
					'jetpack_complete',
					'jetpack_complete_monthly',
					'jetpack_security_t1_yearly',
					'jetpack_security_t2_yearly',
					'jetpack_security_t2_monthly',
				],
				'social-previews': [
					'jetpack_free',
					'jetpack_premium',
					'jetpack_business',
					'jetpack_personal',
					'jetpack_premium_monthly',
					'jetpack_business_monthly',
					'jetpack_personal_monthly',
					'jetpack_security_daily',
					'jetpack_security_daily_monthly',
					'jetpack_security_realtime',
					'jetpack_security_realtime_monthly',
					'jetpack_complete',
					'jetpack_complete_monthly',
					'jetpack_security_t1_yearly',
					'jetpack_security_t2_yearly',
					'jetpack_security_t2_monthly',
				],
				'google-analytics': [
					'jetpack_premium',
					'jetpack_business',
					'jetpack_premium_monthly',
					'jetpack_business_monthly',
					'jetpack_security_daily',
					'jetpack_security_daily_monthly',
					'jetpack_security_realtime',
					'jetpack_security_realtime_monthly',
					'jetpack_complete',
					'jetpack_complete_monthly',
					'jetpack_security_t1_yearly',
					'jetpack_security_t2_yearly',
					'jetpack_security_t2_monthly',
				],
				'video-hosting': [
					'jetpack_premium',
					'jetpack_business',
					'jetpack_premium_monthly',
					'jetpack_business_monthly',
					'jetpack_security_daily',
					'jetpack_security_daily_monthly',
					'jetpack_security_realtime',
					'jetpack_security_realtime_monthly',
					'jetpack_complete',
					'jetpack_complete_monthly',
					'jetpack_security_t1_yearly',
					'jetpack_security_t2_yearly',
					'jetpack_security_t2_monthly',
				],
				'wordads-jetpack': [
					'jetpack_premium',
					'jetpack_business',
					'jetpack_premium_monthly',
					'jetpack_business_monthly',
					'jetpack_security_daily',
					'jetpack_security_daily_monthly',
					'jetpack_security_realtime',
					'jetpack_security_realtime_monthly',
					'jetpack_complete',
					'jetpack_complete_monthly',
					'jetpack_security_t1_yearly',
					'jetpack_security_t2_yearly',
					'jetpack_security_t2_monthly',
				],
				'vaultpress-backups': [
					'jetpack_premium',
					'jetpack_business',
					'jetpack_premium_monthly',
					'jetpack_business_monthly',
				],
				'vaultpress-backup-archive': [
					'jetpack_premium',
					'jetpack_business',
					'jetpack_premium_monthly',
					'jetpack_business_monthly',
				],
				'vaultpress-storage-space': [
					'jetpack_premium',
					'jetpack_business',
					'jetpack_premium_monthly',
					'jetpack_business_monthly',
				],
				'vaultpress-automated-restores': [
					'jetpack_premium',
					'jetpack_business',
					'jetpack_premium_monthly',
					'jetpack_business_monthly',
				],
				'simple-payments': [
					'jetpack_premium',
					'jetpack_business',
					'jetpack_premium_monthly',
					'jetpack_business_monthly',
					'jetpack_security_daily',
					'jetpack_security_daily_monthly',
					'jetpack_security_realtime',
					'jetpack_security_realtime_monthly',
					'jetpack_complete',
					'jetpack_complete_monthly',
				],
				calendly: [
					'jetpack_premium',
					'jetpack_business',
					'jetpack_premium_monthly',
					'jetpack_business_monthly',
				],
				opentable: [
					'jetpack_premium',
					'jetpack_business',
					'jetpack_premium_monthly',
					'jetpack_business_monthly',
				],
				donations: [
					'jetpack_premium',
					'jetpack_business',
					'jetpack_personal',
					'jetpack_premium_monthly',
					'jetpack_business_monthly',
					'jetpack_personal_monthly',
					'jetpack_security_daily',
					'jetpack_security_daily_monthly',
					'jetpack_security_realtime',
					'jetpack_security_realtime_monthly',
					'jetpack_complete',
					'jetpack_complete_monthly',
					'jetpack_security_t1_yearly',
					'jetpack_security_t2_yearly',
					'jetpack_security_t2_monthly',
				],
				'core/video': [
					'jetpack_premium',
					'jetpack_business',
					'jetpack_premium_monthly',
					'jetpack_business_monthly',
				],
				'core/cover': [
					'jetpack_premium',
					'jetpack_business',
					'jetpack_premium_monthly',
					'jetpack_business_monthly',
				],
				'core/audio': [
					'jetpack_premium',
					'jetpack_business',
					'jetpack_personal',
					'jetpack_premium_monthly',
					'jetpack_business_monthly',
					'jetpack_personal_monthly',
					'jetpack_security_daily',
					'jetpack_security_daily_monthly',
					'jetpack_security_realtime',
					'jetpack_security_realtime_monthly',
					'jetpack_complete',
					'jetpack_complete_monthly',
					'jetpack_security_t1_yearly',
					'jetpack_security_t2_yearly',
					'jetpack_security_t2_monthly',
				],
				republicize: [
					'jetpack_premium',
					'jetpack_business',
					'jetpack_premium_monthly',
					'jetpack_business_monthly',
					'jetpack_security_daily',
					'jetpack_security_daily_monthly',
					'jetpack_security_realtime',
					'jetpack_security_realtime_monthly',
					'jetpack_complete',
					'jetpack_complete_monthly',
					'jetpack_security_t1_yearly',
					'jetpack_security_t2_yearly',
					'jetpack_security_t2_monthly',
				],
				'premium-content/container': [
					'jetpack_premium',
					'jetpack_business',
					'jetpack_personal',
					'jetpack_premium_monthly',
					'jetpack_business_monthly',
					'jetpack_personal_monthly',
					'jetpack_security_daily',
					'jetpack_security_daily_monthly',
					'jetpack_security_realtime',
					'jetpack_security_realtime_monthly',
					'jetpack_complete',
					'jetpack_complete_monthly',
					'jetpack_security_t1_yearly',
					'jetpack_security_t2_yearly',
					'jetpack_security_t2_monthly',
				],
				support: [
					'jetpack_premium',
					'jetpack_business',
					'jetpack_personal',
					'jetpack_premium_monthly',
					'jetpack_business_monthly',
					'jetpack_personal_monthly',
					'jetpack_security_daily',
					'jetpack_security_daily_monthly',
					'jetpack_security_realtime',
					'jetpack_security_realtime_monthly',
					'jetpack_complete',
					'jetpack_complete_monthly',
					'jetpack_security_t1_yearly',
					'jetpack_security_t2_yearly',
					'jetpack_security_t2_monthly',
				],
				'premium-themes': [ 'jetpack_business', 'jetpack_business_monthly' ],
				'vaultpress-security-scanning': [ 'jetpack_business', 'jetpack_business_monthly' ],
				polldaddy: [ 'jetpack_business', 'jetpack_business_monthly' ],
			},
		},
	},
};
