import { SortDirection, SupportedLayouts, View } from '@wordpress/dataviews';
import { __ } from '@wordpress/i18n';
import {
	code as fileIcon,
	color as themeIcon,
	plugins as pluginIcon,
	shield as shieldIcon,
	wordpress as coreIcon,
} from '@wordpress/icons';

export const THREAT_STATUSES: { value: string; label: string; variant?: 'success' | 'warning' }[] =
	[
		{ value: 'current', label: __( 'Active', 'jetpack-components' ), variant: 'warning' },
		{ value: 'fixed', label: __( 'Fixed', 'jetpack-components' ), variant: 'success' },
		{ value: 'ignored', label: __( 'Ignored', 'jetpack-components' ) },
	];

export const THREAT_TYPES = [
	{ value: 'plugins', label: __( 'Plugin', 'jetpack-components' ) },
	{ value: 'themes', label: __( 'Theme', 'jetpack-components' ) },
	{ value: 'core', label: __( 'WordPress', 'jetpack-components' ) },
	{ value: 'file', label: __( 'File', 'jetpack-components' ) },
	{ value: '', label: __( 'Unknown', 'jetpack-components' ) },
];

export const THREAT_ICONS = {
	plugins: pluginIcon,
	themes: themeIcon,
	core: coreIcon,
	file: fileIcon,
	default: shieldIcon,
};

export const THREAT_FIELD_TITLE = 'title';
export const THREAT_FIELD_DESCRIPTION = 'description';
export const THREAT_FIELD_ICON = 'icon';
export const THREAT_FIELD_STATUS = 'status';
export const THREAT_FIELD_TYPE = 'type';
export const THREAT_FIELD_EXTENSION = 'extension';
export const THREAT_FIELD_PLUGIN = 'plugin';
export const THREAT_FIELD_THEME = 'theme';
export const THREAT_FIELD_SEVERITY = 'severity';
export const THREAT_FIELD_SIGNATURE = 'signature';
export const THREAT_FIELD_FIRST_DETECTED = 'first-detected';
export const THREAT_FIELD_FIXED_ON = 'fixed-on';
export const THREAT_FIELD_AUTO_FIX = 'auto-fix';

/**
 * DataViews fields relevant to vulnerable extension threats.
 * Example: Threat results generated by the free Protect Report feature.
 */
export const VULNERABILITY_FIELDS = [
	THREAT_FIELD_TITLE,
	THREAT_FIELD_DESCRIPTION,
	THREAT_FIELD_ICON,
	THREAT_FIELD_TYPE,
	THREAT_FIELD_EXTENSION,
	THREAT_FIELD_PLUGIN,
	THREAT_FIELD_THEME,
];

/**
 * DataViews fields related to threats.
 * Example: Threat results detected by Jetpack Scan.
 */
export const THREAT_FIELDS = [
	THREAT_FIELD_TITLE,
	THREAT_FIELD_DESCRIPTION,
	THREAT_FIELD_ICON,
	THREAT_FIELD_STATUS,
	THREAT_FIELD_TYPE,
	THREAT_FIELD_EXTENSION,
	THREAT_FIELD_PLUGIN,
	THREAT_FIELD_THEME,
	THREAT_FIELD_SEVERITY,
	THREAT_FIELD_SIGNATURE,
	THREAT_FIELD_FIRST_DETECTED,
	THREAT_FIELD_FIXED_ON,
	THREAT_FIELD_AUTO_FIX,
];

export const THREAT_ACTION_FIX = 'fix';
export const THREAT_ACTION_IGNORE = 'ignore';
export const THREAT_ACTION_UNIGNORE = 'unignore';

/**
 * Default values for SupportedLayouts
 */
const BASE_VIEW: Omit< View, 'type' > = {
	sort: {
		field: 'severity',
		direction: 'desc' as SortDirection,
	},
	search: '',
	page: 1,
	perPage: 20,
};

/**
 * DataView default layouts.
 *
 * This property provides layout information about the view types that are active. If empty, enables all layout types (see “Layout Types”) with empty layout data.
 *
 * @see https://developer.wordpress.org/block-editor/reference-guides/packages/packages-dataviews/#defaultlayouts-record-string-view
 */
export const DEFAULT_LAYOUTS: SupportedLayouts = {
	table: {
		...BASE_VIEW,
		fields: [ THREAT_FIELD_SEVERITY, THREAT_FIELD_AUTO_FIX ],
		titleField: THREAT_FIELD_TITLE,
		descriptionField: THREAT_FIELD_DESCRIPTION,
		showMedia: false,
	},
	list: {
		...BASE_VIEW,
		fields: [
			THREAT_FIELD_SEVERITY,
			THREAT_FIELD_TYPE,
			THREAT_FIELD_EXTENSION,
			THREAT_FIELD_SIGNATURE,
		],
		titleField: THREAT_FIELD_TITLE,
		mediaField: THREAT_FIELD_ICON,
		showMedia: true,
	},
};
