export const SITE_REWIND_POLICIES_GET = 'SITE_REWIND_POLICIES_GET';
export const SITE_REWIND_POLICIES_GET_FAILED = 'SITE_REWIND_POLICIES_GET_FAILED';
export const SITE_REWIND_POLICIES_GET_SUCCESS = 'SITE_REWIND_POLICIES_GET_SUCCESS';
export const SITE_REWIND_SIZE_GET = 'SITE_REWIND_SIZE_GET';
export const SITE_REWIND_SIZE_GET_FAILED = 'SITE_REWIND_SIZE_GET_FAILED';
export const SITE_REWIND_SIZE_GET_SUCCESS = 'SITE_REWIND_SIZE_GET_SUCCESS';
