name: Bug Report
description: Report issues with one of our products.
labels: [ 'Needs triage', '[Type] Bug' ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for contributing to Jetpack!
        Pick a clear title ("Sharing: Facebook button missing") and proceed.

        __Avoid using image hosting services such as Cloudup, Droplr, Imgur, etc., to link to media.__
        Instead, attach screenshot(s) or recording(s) directly in any of the text areas below: click, then drag and drop.
  - type: dropdown
    id: plugin-type
    attributes:
      label: Impacted plugin
      description: Multiple selection is supported. If you experienced the issue on WordPress.com, please select "Jetpack".
      options:
        - Jetpack
        - Backup
        - Boost
        - Beta
        - Debug Helper
        - Protect
        - Search
        - Social
        - Super Cache
        - VaultPress
        - None / Other
      multiple: true
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: A clear and concise description of what you expected to happen.
      placeholder: |
        eg. Post should be liked.
  - type: textarea
    id: actual
    attributes:
      label: What actually happened
      placeholder: |
        eg. Clicking the button does nothing visibly.
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: (You may select more than one)
      options:
        - Google Chrome/Chromium
        - Mozilla Firefox
        - Microsoft Edge
        - Apple Safari
        - iOS Safari
        - Android Chrome
      multiple: true
  - type: textarea
    id: other
    attributes:
      label: Other information
      placeholder: Screenshots, additional logs, notes, etc.
  - type: markdown
    attributes:
      value: |
        ---
        ## Additional context

        The following section is optional. If you're an Automattician, you should be able to fill it in. If not, please scroll to the bottom and submit the issue.
  - type: dropdown
    id: site-type
    attributes:
      label: Platform (Simple, Atomic, or both?)
      description: (You may select more than one)
      options:
        - Simple
        - Atomic
        - Self-hosted
      multiple: true
  - type: markdown
    attributes:
      value: |
        ## Issue severity

        Please provide details around how often the issue is reproducible & how many users are affected.
  - type: dropdown
    id: reproducibility
    attributes:
      label: Reproducibility
      options:
        - Consistent
        - Intermittent
        - Once
    validations:
      required: true
  - type: dropdown
    id: users-affected
    attributes:
      label: Severity
      description: How many users are impacted? A guess is fine.
      options:
        - One
        - Some (< 50%)
        - Most (> 50%)
        - All
  - type: dropdown
    id: workarounds
    attributes:
      label: Available workarounds?
      options:
        - No and the platform is unusable
        - No but the platform is still usable
        - Yes, difficult to implement
        - Yes, easy to implement
        - There is no user impact
  - type: textarea
    id: workarounds-detail
    attributes:
      label: Workaround details
      description: If you are aware of a workaround, please describe it below.
      placeholder: |
        e.g. There is an alternative way to access this setting in the sidebar, but it's not readily apparent.
