name: Bug Report
description: Report issues with one of our products.
labels: [ '[Type] Bug' ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for contributing to Jetpack!
        Pick a clear title ("Sharing: add new Facebook button") and proceed.
  - type: dropdown
    id: plugin-type
    attributes:
      label: Impacted plugin
      description: Multiple selection is supported.
      options:
        - Jetpack
        - Backup
        - Boost
        - Beta
        - Debug Helper
        - Protect
        - Search
        - Social
        - VaultPress
        - None / Other
      multiple: true
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: A clear and concise description of what you expected to happen.
      placeholder: |
        eg. Post should be liked.
  - type: textarea
    id: actual
    attributes:
      label: What actually happened
      placeholder: |
        eg. Clicking the button does nothing visibly.
  - type: textarea
    id: other
    attributes:
      label: Other information
      placeholder: Screenshots, additional logs, notes, etc.
  - type: markdown
    attributes:
      value: |
        ---
        ## Issue severity

        Please provide details around how often the issue is reproducible & how many users are affected.
  - type: dropdown
    id: reproducibility
    attributes:
      label: Reproducibility
      options:
        - Consistent
        - Intermittent
        - Once
    validations:
      required: true
  - type: dropdown
    id: users-affected
    attributes:
      label: Severity
      description: How many users are impacted? A guess is fine.
      options:
        - One
        - Some (< 50%)
        - Most (> 50%)
        - All
  - type: dropdown
    id: workarounds
    attributes:
      label: Available workarounds?
      options:
        - No and the platform is unusable
        - No but the platform is still usable
        - Yes, difficult to implement
        - Yes, easy to implement
        - There is no user impact
  - type: textarea
    id: workarounds-detail
    attributes:
      label: Workaround details
      description: If you are aware of a workaround, please describe it below.
      placeholder: |
        e.g. There is an alternative way to access this setting in the sidebar, but it's not readily apparent.
  - type: markdown
    attributes:
      value: |
        ---
        ## Additional context

        Please provide whatever additional information you have available to you. If not, please scroll to the bottom and submit the issue.
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: Multiple selection is supported.
      options:
        - Windows
        - macOS
        - Linux
        - Android
        - iOS
        - Other
      multiple: true
  - type: input
    id: os_version
    attributes:
      label: OS Version
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Multiple selection is supported.
      options:
        - Chrome/Chromium
        - Firefox
        - Microsoft Edge
        - Microsoft Edge (legacy)
        - Safari
        - Other / Not applicable
      multiple: true
    validations:
      required: true
  - type: input
    attributes:
      label: Browser Version(s)
