export const JETPACK_CONNECTION_STATUS_FETCH = 'JETPACK_CONNECTION_STATUS_FETCH';
export const JETPACK_CONNECTION_TEST_FETCH = 'JETPACK_CONNECTION_TEST_FETCH';

export const CONNECT_URL_FETCH = 'CONNECT_URL_FETCH';
export const CONNECT_URL_FETCH_FAIL = 'CONNECT_URL_FETCH_FAIL';
export const CONNECT_URL_FETCH_SUCCESS = 'CONNECT_URL_FETCH_SUCCESS';

export const DISCONNECT_SITE = 'DISCONNECT_SITE';
export const DISCONNECT_SITE_FAIL = 'DISCONNECT_SITE_FAIL';
export const DISCONNECT_SITE_SUCCESS = 'DISCONNECT_SITE_SUCCESS';

export const SITE_RECONNECT = 'SITE_RECONNECT';
export const SITE_RECONNECT_SUCCESS = 'SITE_RECONNECT_SUCCESS';
export const SITE_RECONNECT_FAIL = 'SITE_RECONNECT_FAIL';

export const USER_CONNECTION_DATA_FETCH = 'USER_CONNECTION_DATA_FETCH';
export const USER_CONNECTION_DATA_FETCH_FAIL = 'USER_CONNECTION_DATA_FETCH_FAIL';
export const USER_CONNECTION_DATA_FETCH_SUCCESS = 'USER_CONNECTION_DATA_FETCH_SUCCESS';

export const AUTH_USER_IN_PLACE = 'AUTH_USER_IN_PLACE';
export const AUTH_USER_IN_PLACE_SUCCESS = 'AUTH_USER_IN_PLACE_SUCCESS';

export const UNLINK_USER = 'UNLINK_USER';
export const UNLINK_USER_FAIL = 'UNLINK_USER_FAIL';
export const UNLINK_USER_SUCCESS = 'UNLINK_USER_SUCCESS';