const sampleCategories = [
	{
		ID: 14067,
		name: 'AI',
		slug: 'ai',
		description: '',
		post_count: 1,
		feed_url: 'https://yoursitehere.wordpress.com/category/technology/ai/feed/',
		parent: 6,
	},
	{
		ID: 757687150,
		name: 'ChatGPT',
		slug: 'chatgpt',
		description: '',
		post_count: 0,
		feed_url: 'https://yoursitehere.wordpress.com/category/technology/ai/chatgpt/feed/',
		parent: 14067,
	},
	{
		ID: 3737,
		name: 'Fashion',
		slug: 'fashion',
		description: '',
		post_count: 2,
		feed_url: 'https://yoursitehere.wordpress.com/category/fashion/feed/',
		parent: 0,
	},
	{
		ID: 18,
		name: 'Music',
		slug: 'music',
		description: '',
		post_count: 0,
		feed_url: 'https://yoursitehere.wordpress.com/category/music/feed/',
		parent: 0,
	},
	{
		ID: 24357,
		name: 'Politico',
		slug: 'politico',
		description: '',
		post_count: 0,
		feed_url: 'https://yoursitehere.wordpress.com/category/politico/feed/',
		parent: 0,
	},
	{
		ID: 6,
		name: 'Technology',
		slug: 'technology',
		description: '',
		post_count: 1,
		feed_url: 'https://yoursitehere.wordpress.com/category/technology/feed/',
		parent: 0,
	},
	{
		ID: 1,
		name: 'Uncategorized',
		slug: 'uncategorized',
		description: '',
		post_count: 29,
		feed_url: 'https://yoursitehere.wordpress.com/category/uncategorized/feed/',
		parent: 0,
	},
];

export default sampleCategories;
