import { defineConfig } from 'tsup';

export default defineConfig( {
	entry: [
		'src/index.ts',
		'src/components/bar-chart/index.ts',
		'src/components/line-chart/index.ts',
		'src/components/pie-chart/index.ts',
		'src/components/pie-semi-circle-chart/index.ts',
		'src/components/bar-list-chart/index.ts',
		'src/components/leaderboard-chart/index.ts',
		'src/components/conversion-funnel-chart/index.ts',
		'src/components/tooltip/index.ts',
		'src/components/legend/index.ts',
		'src/hooks/index.ts',
		'src/providers/index.ts',
		'src/visx/text/index.ts',
		'src/visx/legend/index.ts',
		'src/visx/group/index.ts',
	],
	clean: true,
	splitting: false,
	sourcemap: true,
	dts: true,
	minify: true,
	format: [ 'esm', 'cjs' ],
	outDir: 'dist',
	loader: {
		'.jpg': 'file',
		'.gif': 'file',
		'.scss': 'file',
		'.svg': 'file',
		'.png': 'file',
	},
} );
