<?php
// autoload_packages.php generated by automattic/autoloader
//
// From your project (WordPress Plugin or Theme) inclide this file with.
// In a plugin
// require_once . plugin_dir_path( __FILE__ ) . '/vendor/autoload_packages.php';


if ( ! function_exists( 'jetpack_enqueue_package' ) ) {
	global $jetpack_packages;

	if ( ! is_array( $jetpack_packages ) ) {
		$jetpack_packages = array();
	}
	/**
	 * Adds the version of a package to the $jetpack_packages global array so that
	 * the autoloader is able to find it.
	 *
	 * @param $class_name
	 * @param $version
	 * @param $path
	 */
	function jetpack_enqueue_package( $class_name, $version, $path ) {
		global $jetpack_packages;
		if ( ! isset( $jetpack_packages[ $class_name ] )
			 || version_compare( $jetpack_packages[ $class_name ] ['version'], $version, '<' )
		) {
			$jetpack_packages[ $class_name ] = array(
				'version' => $version,
				'path'    => $path,
			);
		}
	}

	// Add the autoloader
	spl_autoload_register(
		function ( $class_name ) {
			global $jetpack_packages;

			if ( isset( $jetpack_packages[ $class_name ] ) ) {

				if ( function_exists( 'did_action' ) && ! did_action( 'plugins_loaded' ) ) {
					_doing_it_wrong(
						$class_name,
						'Not all plugins have loaded yet but we requested the class ' . $class_name,
						$jetpack_packages[ $class_name ]['version']
					);
				}

				if ( file_exists( $jetpack_packages[ $class_name ]['path'] ) ) {
					require_once $jetpack_packages[ $class_name ]['path'];
				}
			}
		}
	);
}

$class_map = require_once dirname( __FILE__ ) . '/composer/autoload_classmap_package.php';

foreach ( $class_map as $class_name => $map ) {
	jetpack_enqueue_package( $class_name, $map['version'], $map['path'] );
}
