export const SET_CONNECTIONS = 'SET_CONNECTIONS' as const;

export const ADD_CONNECTION = 'ADD_CONNECTION' as const;

export const TOGGLE_CONNECTION = 'TOGGLE_CONNECTION' as const;

export const DELETE_CONNECTION = 'DELETE_CONNECTION' as const;

export const DELETING_CONNECTION = 'DELETING_CONNECTION' as const;

export const UPDATE_CONNECTION = 'UPDATE_CONNECTION' as const;

export const UPDATING_CONNECTION = 'UPDATING_CONNECTION' as const;

export const SET_RECONNECTING_ACCOUNT = 'SET_RECONNECTING_ACCOUNT' as const;

export const SET_KEYRING_RESULT = 'SET_KEYRING_RESULT' as const;

export const TOGGLE_CONNECTIONS_MODAL = 'TOGGLE_CONNECTIONS_MODAL' as const;

export const ADD_ABORT_CONTROLLER = 'ADD_ABORT_CONTROLLER' as const;

export const REMOVE_ABORT_CONTROLLERS = 'REMOVE_ABORT_CONTROLLERS' as const;

export const REQUEST_TYPE_DEFAULT = 'DEFAULT' as const;

export const REQUEST_TYPE_REFRESH_CONNECTIONS = 'REFRESH_CONNECTIONS' as const;

export const CUSTOMIZE_CONNECTION = 'CUSTOMIZE_CONNECTION' as const;

export const FETCH_POST_SHARE_STATUS = 'FETCH_POST_SHARE_STATUS' as const;

export const RECEIVE_POST_SHARE_STATUS = 'RECEIVE_POST_SHARE_STATUS' as const;

export const POLLING_FOR_POST_SHARE_STATUS = 'POLLING_FOR_POST_SHARE_STATUS' as const;

export const TOGGLE_UNIFIED_MODAL = 'TOGGLE_UNIFIED_MODAL' as const;

export const SET_UNIFIED_MODAL_INITIAL_PATH = 'SET_UNIFIED_MODAL_INITIAL_PATH' as const;

export const SET_UNIFIED_MODAL_SCREEN_LOCK = 'SET_UNIFIED_MODAL_SCREEN_LOCK' as const;

export const SET_UNIFIED_MODAL_DATA = 'SET_UNIFIED_MODAL_DATA' as const;

export const SET_IS_SHARING_CURRENT_POST = 'SET_IS_SHARING_CURRENT_POST' as const;

export const SET_IS_SCHEDULING_SHARES = 'SET_IS_SCHEDULING_SHARES' as const;

export const START_RENDERING_MESSAGES = 'START_RENDERING_MESSAGES' as const;

export const RECEIVE_RENDERED_MESSAGES = 'RECEIVE_RENDERED_MESSAGES' as const;

export const FINISH_RENDERING_MESSAGES = 'FINISH_RENDERING_MESSAGES' as const;

export const SET_TRAFFIC_INTERVAL = 'SET_TRAFFIC_INTERVAL' as const;

export const FETCH_TRAFFIC_REFERRERS = 'FETCH_TRAFFIC_REFERRERS' as const;

export const RECEIVE_TRAFFIC_REFERRERS = 'RECEIVE_TRAFFIC_REFERRERS' as const;

export const RECEIVE_TRAFFIC_REFERRERS_ERROR = 'RECEIVE_TRAFFIC_REFERRERS_ERROR' as const;

export const FETCHING_KEYRING_RESULT = 'FETCHING_KEYRING_RESULT' as const;

export const START_CONNECTION_FLOW = 'START_CONNECTION_FLOW' as const;

export const SELECT_CONNECTION_FLOW_PLATFORM = 'SELECT_CONNECTION_FLOW_PLATFORM' as const;

export const GO_TO_PREVIOUS_CONNECTION_FLOW_STEP = 'GO_TO_PREVIOUS_CONNECTION_FLOW_STEP' as const;

export const GO_TO_NEXT_CONNECTION_FLOW_STEP = 'GO_TO_NEXT_CONNECTION_FLOW_STEP' as const;

export const SET_CONNECTION_FLOW_INPUT = 'SET_CONNECTION_FLOW_INPUT' as const;

export const SET_CONNECTION_FLOW_REQUEST_ID = 'SET_CONNECTION_FLOW_REQUEST_ID' as const;

export const SET_CONNECTION_FLOW_ERROR = 'SET_CONNECTION_FLOW_ERROR' as const;

export const FAIL_CONNECTION_FLOW_AUTHORIZATION = 'FAIL_CONNECTION_FLOW_AUTHORIZATION' as const;

export const CANCEL_CONNECTION_FLOW = 'CANCEL_CONNECTION_FLOW' as const;
