name: Auto-release

on:
  push:
    tags:
      - 'v?[0-9]+.[0-9]+'
      - 'v?[0-9]+.[0-9]+-*'
      - 'v?[0-9]+.[0-9]+.[0-9]+'
      - 'v?[0-9]+.[0-9]+.[0-9]+-*'
      - 'v?[0-9]+.[0-9]+.[0-9]+.[0-9]+'
      - 'v?[0-9]+.[0-9]+.[0-9]+.[0-9]+-*'
    branches:
      - 'trunk'

jobs:
  publish:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./.github/files/autorelease.sh
