<?php
/**
 * Bundled YouTube fixtures backing the Studio import mock mode.
 *
 * DELETABLE: this file only exists while the `videopress_import_mock_mode`
 * filter (default true) serves the Studio import flow from canned data. It is
 * deleted wholesale when the real WPCOM-proxied YouTube listing lands — see
 * Import_Rest_Controller for the routes that consume it.
 *
 * Shape:
 * - connection: the mock Keyring identity ({ account_name, profile_image }).
 * - videos: ~25 listing items ordered newest-first, each mirroring what the
 *   YouTube Data API v3 exposes for the user's own uploads: external_id,
 *   title, description, tags[], duration_seconds, privacy
 *   (public|unlisted|private), published_at (ISO 8601), and thumbnails
 *   (default|high|maxres — maxres is null for low-resolution sources, as it
 *   is on the real API).
 *
 * @package automattic/jetpack-videopress
 */

return array(
	'connection' => array(
		'account_name'  => 'Lens & Latitude',
		'profile_image' => 'https://yt3.ggpht.com/mock/lens-and-latitude=s240-c-k-c0x00ffffff-no-rj',
	),
	'videos'     => array(
		array(
			'external_id'      => 'k3xPn0qLmA1',
			'title'            => 'Packing for 6 Months in the Andes | What\'s in My Bag',
			'description'      => 'Every item I carry for half a year above 3,000 meters, and the three things I mailed home after week one.',
			'tags'             => array( 'travel', 'packing', 'andes', 'gear', 'long term travel' ),
			'duration_seconds' => 1245,
			'privacy'          => 'public',
			'published_at'     => '2026-05-18T14:00:00Z',
			'thumbnails'       => array(
				'default' => 'https://i.ytimg.com/vi/k3xPn0qLmA1/default.jpg',
				'high'    => 'https://i.ytimg.com/vi/k3xPn0qLmA1/hqdefault.jpg',
				'maxres'  => 'https://i.ytimg.com/vi/k3xPn0qLmA1/maxresdefault.jpg',
			),
		),
		array(
			'external_id'      => 'Zt8vWy2RbQ4',
			'title'            => 'Sunrise Timelapse Over Lake Titicaca (4K)',
			'description'      => 'Three hours compressed into three minutes from the ferry dock at Copacabana. No music, just wind and water.',
			'tags'             => array( 'timelapse', '4k', 'bolivia', 'lake titicaca' ),
			'duration_seconds' => 187,
			'privacy'          => 'public',
			'published_at'     => '2026-04-29T11:30:00Z',
			'thumbnails'       => array(
				'default' => 'https://i.ytimg.com/vi/Zt8vWy2RbQ4/default.jpg',
				'high'    => 'https://i.ytimg.com/vi/Zt8vWy2RbQ4/hqdefault.jpg',
				'maxres'  => 'https://i.ytimg.com/vi/Zt8vWy2RbQ4/maxresdefault.jpg',
			),
		),
		array(
			'external_id'      => 'Qw7eR5tY6u2',
			'title'            => 'How I Plan Multi-Country Train Routes',
			'description'      => 'My full research workflow for stitching together rail passes, night trains, and border connections without a travel agent.',
			'tags'             => array( 'trains', 'travel planning', 'rail pass', 'itinerary' ),
			'duration_seconds' => 964,
			'privacy'          => 'public',
			'published_at'     => '2026-04-02T16:45:00Z',
			'thumbnails'       => array(
				'default' => 'https://i.ytimg.com/vi/Qw7eR5tY6u2/default.jpg',
				'high'    => 'https://i.ytimg.com/vi/Qw7eR5tY6u2/hqdefault.jpg',
				'maxres'  => 'https://i.ytimg.com/vi/Qw7eR5tY6u2/maxresdefault.jpg',
			),
		),
		array(
			'external_id'      => 'Ab1Cd2Ef3G4',
			'title'            => 'Street Food Tour: La Paz on $10 a Day',
			'description'      => 'Salteñas at dawn, api con pastel at midnight, and everything the Mercado Lanza ladies made me try in between.',
			'tags'             => array( 'street food', 'la paz', 'bolivia', 'budget travel', 'food tour' ),
			'duration_seconds' => 1421,
			'privacy'          => 'public',
			'published_at'     => '2026-03-15T13:15:00Z',
			'thumbnails'       => array(
				'default' => 'https://i.ytimg.com/vi/Ab1Cd2Ef3G4/default.jpg',
				'high'    => 'https://i.ytimg.com/vi/Ab1Cd2Ef3G4/hqdefault.jpg',
				'maxres'  => 'https://i.ytimg.com/vi/Ab1Cd2Ef3G4/maxresdefault.jpg',
			),
		),
		array(
			'external_id'      => 'Hj5Kl6Mn7P8',
			'title'            => 'Drone B-Roll Reel — Patagonia',
			'description'      => 'Unlisted reel for collaborators: raw aerial clips from Torres del Paine and El Chaltén, graded flat.',
			'tags'             => array( 'drone', 'b-roll', 'patagonia', 'stock footage' ),
			'duration_seconds' => 243,
			'privacy'          => 'unlisted',
			'published_at'     => '2026-02-27T09:00:00Z',
			'thumbnails'       => array(
				'default' => 'https://i.ytimg.com/vi/Hj5Kl6Mn7P8/default.jpg',
				'high'    => 'https://i.ytimg.com/vi/Hj5Kl6Mn7P8/hqdefault.jpg',
				'maxres'  => 'https://i.ytimg.com/vi/Hj5Kl6Mn7P8/maxresdefault.jpg',
			),
		),
		array(
			'external_id'      => 'Xy9Zw8Vu7T6',
			'title'            => 'Q&A: Cameras, Visas, and Burnout',
			'description'      => 'A long, honest livestream replay answering the questions you keep sending: what I shoot with, how I handle visa runs, and the months I almost quit.',
			'tags'             => array( 'q&a', 'livestream', 'travel vlogging', 'burnout' ),
			'duration_seconds' => 2710,
			'privacy'          => 'public',
			'published_at'     => '2026-02-08T19:00:00Z',
			'thumbnails'       => array(
				'default' => 'https://i.ytimg.com/vi/Xy9Zw8Vu7T6/default.jpg',
				'high'    => 'https://i.ytimg.com/vi/Xy9Zw8Vu7T6/hqdefault.jpg',
				'maxres'  => 'https://i.ytimg.com/vi/Xy9Zw8Vu7T6/maxresdefault.jpg',
			),
		),
		array(
			'external_id'      => 'Lm4No3Pq2R1',
			'title'            => 'Crossing the Salar de Uyuni by Bicycle',
			'description'      => 'Two days, one salt flat, zero shade. The most surreal ride of my life, including the night we camped on the salt.',
			'tags'             => array( 'cycling', 'salar de uyuni', 'bolivia', 'bikepacking', 'adventure' ),
			'duration_seconds' => 1876,
			'privacy'          => 'public',
			'published_at'     => '2026-01-19T15:20:00Z',
			'thumbnails'       => array(
				'default' => 'https://i.ytimg.com/vi/Lm4No3Pq2R1/default.jpg',
				'high'    => 'https://i.ytimg.com/vi/Lm4No3Pq2R1/hqdefault.jpg',
				'maxres'  => 'https://i.ytimg.com/vi/Lm4No3Pq2R1/maxresdefault.jpg',
			),
		),
		array(
			'external_id'      => 'St6Uv7Wx8Y9',
			'title'            => 'Raw Clip: Market Morning in Cusco',
			'description'      => 'Private archive: uncut handheld walk through San Pedro market, saved for a future longform edit.',
			'tags'             => array( 'raw footage', 'cusco', 'peru', 'market' ),
			'duration_seconds' => 402,
			'privacy'          => 'private',
			'published_at'     => '2026-01-04T08:10:00Z',
			'thumbnails'       => array(
				'default' => 'https://i.ytimg.com/vi/St6Uv7Wx8Y9/default.jpg',
				'high'    => 'https://i.ytimg.com/vi/St6Uv7Wx8Y9/hqdefault.jpg',
				'maxres'  => 'https://i.ytimg.com/vi/St6Uv7Wx8Y9/maxresdefault.jpg',
			),
		),
		array(
			'external_id'      => 'De2Fg3Hi4J5',
			'title'            => 'My Complete Video Editing Workflow (2026)',
			'description'      => 'From SD card to published video: ingest, proxies, rough cut, color, and the folder structure that keeps me sane on the road.',
			'tags'             => array( 'editing', 'workflow', 'tutorial', 'video production' ),
			'duration_seconds' => 1594,
			'privacy'          => 'public',
			'published_at'     => '2025-12-11T17:00:00Z',
			'thumbnails'       => array(
				'default' => 'https://i.ytimg.com/vi/De2Fg3Hi4J5/default.jpg',
				'high'    => 'https://i.ytimg.com/vi/De2Fg3Hi4J5/hqdefault.jpg',
				'maxres'  => 'https://i.ytimg.com/vi/De2Fg3Hi4J5/maxresdefault.jpg',
			),
		),
		array(
			'external_id'      => 'Kl8Mn9Op0Q1',
			'title'            => '48 Hours in Valparaíso',
			'description'      => 'Funiculars, street art, and a poetry reading in Pablo Neruda\'s living room. Chile\'s strangest city in one weekend.',
			'tags'             => array( 'valparaiso', 'chile', 'city guide', 'weekend trip' ),
			'duration_seconds' => 1102,
			'privacy'          => 'public',
			'published_at'     => '2025-11-23T12:00:00Z',
			'thumbnails'       => array(
				'default' => 'https://i.ytimg.com/vi/Kl8Mn9Op0Q1/default.jpg',
				'high'    => 'https://i.ytimg.com/vi/Kl8Mn9Op0Q1/hqdefault.jpg',
				'maxres'  => 'https://i.ytimg.com/vi/Kl8Mn9Op0Q1/maxresdefault.jpg',
			),
		),
		array(
			'external_id'      => 'Rs3Tu4Vw5X6',
			'title'            => 'Hiking the W Trek Solo — Full Documentary',
			'description'      => 'Five days alone in Torres del Paine, filmed entirely on one camera and one battery bank. The full story, weather tantrums included.',
			'tags'             => array( 'hiking', 'w trek', 'patagonia', 'documentary', 'solo travel' ),
			'duration_seconds' => 3648,
			'privacy'          => 'public',
			'published_at'     => '2025-11-02T18:30:00Z',
			'thumbnails'       => array(
				'default' => 'https://i.ytimg.com/vi/Rs3Tu4Vw5X6/default.jpg',
				'high'    => 'https://i.ytimg.com/vi/Rs3Tu4Vw5X6/hqdefault.jpg',
				'maxres'  => 'https://i.ytimg.com/vi/Rs3Tu4Vw5X6/maxresdefault.jpg',
			),
		),
		array(
			'external_id'      => 'Yz7Ab8Cd9E0',
			'title'            => 'Gear Fail: What Broke After a Year on the Road',
			'description'      => 'The tripod that snapped, the mic that drowned, and the one cheap accessory that outlived everything else.',
			'tags'             => array( 'gear review', 'travel gear', 'camera gear', 'honest review' ),
			'duration_seconds' => 733,
			'privacy'          => 'public',
			'published_at'     => '2025-10-14T14:45:00Z',
			'thumbnails'       => array(
				'default' => 'https://i.ytimg.com/vi/Yz7Ab8Cd9E0/default.jpg',
				'high'    => 'https://i.ytimg.com/vi/Yz7Ab8Cd9E0/hqdefault.jpg',
				'maxres'  => 'https://i.ytimg.com/vi/Yz7Ab8Cd9E0/maxresdefault.jpg',
			),
		),
		array(
			'external_id'      => 'Fg1Hi2Jk3L4',
			'title'            => 'Ambient Rain on a Tin Roof — 1 Hour Loop',
			'description'      => 'Recorded during a storm in the cloud forest near Coroico. Unlisted because it\'s really just for me to fall asleep to.',
			'tags'             => array( 'ambient', 'rain sounds', 'sleep', 'white noise' ),
			'duration_seconds' => 3600,
			'privacy'          => 'unlisted',
			'published_at'     => '2025-09-26T22:00:00Z',
			'thumbnails'       => array(
				'default' => 'https://i.ytimg.com/vi/Fg1Hi2Jk3L4/default.jpg',
				'high'    => 'https://i.ytimg.com/vi/Fg1Hi2Jk3L4/hqdefault.jpg',
				'maxres'  => 'https://i.ytimg.com/vi/Fg1Hi2Jk3L4/maxresdefault.jpg',
			),
		),
		array(
			'external_id'      => 'Mn5Op6Qr7S8',
			'title'            => 'Border Crossing Tips Nobody Tells You',
			'description'      => 'Exit stamps, fake "fees", onward ticket checks, and why I always keep two photocopies of everything.',
			'tags'             => array( 'border crossing', 'travel tips', 'visas', 'south america' ),
			'duration_seconds' => 846,
			'privacy'          => 'public',
			'published_at'     => '2025-09-05T10:30:00Z',
			'thumbnails'       => array(
				'default' => 'https://i.ytimg.com/vi/Mn5Op6Qr7S8/default.jpg',
				'high'    => 'https://i.ytimg.com/vi/Mn5Op6Qr7S8/hqdefault.jpg',
				'maxres'  => 'https://i.ytimg.com/vi/Mn5Op6Qr7S8/maxresdefault.jpg',
			),
		),
		array(
			'external_id'      => 'Tu9Vw0Xy1Z2',
			'title'            => 'Cooking Ceviche With a Fisherman in Paracas',
			'description'      => 'Don Ernesto has made ceviche on this beach for forty years. He let me film the whole thing, lime-burned hands and all.',
			'tags'             => array( 'ceviche', 'peru', 'cooking', 'food', 'paracas' ),
			'duration_seconds' => 1287,
			'privacy'          => 'public',
			'published_at'     => '2025-08-17T13:00:00Z',
			'thumbnails'       => array(
				'default' => 'https://i.ytimg.com/vi/Tu9Vw0Xy1Z2/default.jpg',
				'high'    => 'https://i.ytimg.com/vi/Tu9Vw0Xy1Z2/hqdefault.jpg',
				'maxres'  => 'https://i.ytimg.com/vi/Tu9Vw0Xy1Z2/maxresdefault.jpg',
			),
		),
		array(
			'external_id'      => 'Cd3Ef4Gh5I6',
			'title'            => 'Behind the Scenes: Filming in High Wind',
			'description'      => 'Unlisted BTS for the Patagonia documentary: every windbreak trick I know, and the shot that cost me a lens hood.',
			'tags'             => array( 'behind the scenes', 'filmmaking', 'wind', 'patagonia' ),
			'duration_seconds' => 519,
			'privacy'          => 'unlisted',
			'published_at'     => '2025-07-30T16:15:00Z',
			'thumbnails'       => array(
				'default' => 'https://i.ytimg.com/vi/Cd3Ef4Gh5I6/default.jpg',
				'high'    => 'https://i.ytimg.com/vi/Cd3Ef4Gh5I6/hqdefault.jpg',
				'maxres'  => null,
			),
		),
		array(
			'external_id'      => 'Jk7Lm8No9P0',
			'title'            => 'The Cheapest Room I\'ve Ever Booked',
			'description'      => 'Four dollars a night in Sucre. You get what you pay for, and somehow also a rooster.',
			'tags'             => array( 'budget travel', 'hostel', 'bolivia', 'accommodation' ),
			'duration_seconds' => 654,
			'privacy'          => 'public',
			'published_at'     => '2025-07-09T11:45:00Z',
			'thumbnails'       => array(
				'default' => 'https://i.ytimg.com/vi/Jk7Lm8No9P0/default.jpg',
				'high'    => 'https://i.ytimg.com/vi/Jk7Lm8No9P0/hqdefault.jpg',
				'maxres'  => 'https://i.ytimg.com/vi/Jk7Lm8No9P0/maxresdefault.jpg',
			),
		),
		array(
			'external_id'      => 'Qr1St2Uv3W4',
			'title'            => 'Night Bus Survival Guide',
			'description'      => 'Seat picking, snack strategy, and the earplug ranking video the bus companies don\'t want you to see.',
			'tags'             => array( 'night bus', 'travel tips', 'south america', 'budget travel' ),
			'duration_seconds' => 921,
			'privacy'          => 'public',
			'published_at'     => '2025-06-18T09:30:00Z',
			'thumbnails'       => array(
				'default' => 'https://i.ytimg.com/vi/Qr1St2Uv3W4/default.jpg',
				'high'    => 'https://i.ytimg.com/vi/Qr1St2Uv3W4/hqdefault.jpg',
				'maxres'  => 'https://i.ytimg.com/vi/Qr1St2Uv3W4/maxresdefault.jpg',
			),
		),
		array(
			'external_id'      => 'Xy5Za6Bc7D8',
			'title'            => 'Colca Canyon Condors in Slow Motion',
			'description'      => 'Andean condors riding thermals at Cruz del Cóndor, shot at 120fps from the canyon rim.',
			'tags'             => array( 'condor', 'colca canyon', 'peru', 'wildlife', 'slow motion' ),
			'duration_seconds' => 318,
			'privacy'          => 'public',
			'published_at'     => '2025-05-28T15:00:00Z',
			'thumbnails'       => array(
				'default' => 'https://i.ytimg.com/vi/Xy5Za6Bc7D8/default.jpg',
				'high'    => 'https://i.ytimg.com/vi/Xy5Za6Bc7D8/hqdefault.jpg',
				'maxres'  => null,
			),
		),
		array(
			'external_id'      => 'Ef9Gh0Ij1K2',
			'title'            => 'One Year of Travel: The Honest Numbers',
			'description'      => 'Every sol, peso, and boliviano accounted for: twelve months of spending, income, and what I\'d budget differently.',
			'tags'             => array( 'travel budget', 'cost of travel', 'finances', 'year in review' ),
			'duration_seconds' => 1745,
			'privacy'          => 'public',
			'published_at'     => '2025-05-06T14:00:00Z',
			'thumbnails'       => array(
				'default' => 'https://i.ytimg.com/vi/Ef9Gh0Ij1K2/default.jpg',
				'high'    => 'https://i.ytimg.com/vi/Ef9Gh0Ij1K2/hqdefault.jpg',
				'maxres'  => 'https://i.ytimg.com/vi/Ef9Gh0Ij1K2/maxresdefault.jpg',
			),
		),
		array(
			'external_id'      => 'Lm3No4Pq5R6',
			'title'            => 'Test Upload — Color Profile Check',
			'description'      => 'Private test clip to compare S-Log3 conversion between editors. Not meant for humans.',
			'tags'             => array( 'test', 'color grading', 'slog3' ),
			'duration_seconds' => 62,
			'privacy'          => 'private',
			'published_at'     => '2025-04-15T20:05:00Z',
			'thumbnails'       => array(
				'default' => 'https://i.ytimg.com/vi/Lm3No4Pq5R6/default.jpg',
				'high'    => 'https://i.ytimg.com/vi/Lm3No4Pq5R6/hqdefault.jpg',
				'maxres'  => null,
			),
		),
		array(
			'external_id'      => 'St7Uv8Wx9Y0',
			'title'            => 'Learning Quechua Greetings From Locals',
			'description'      => 'Allillanchu! Market vendors in Pisac taught me the basics and laughed at my accent. Fair.',
			'tags'             => array( 'quechua', 'language', 'peru', 'culture' ),
			'duration_seconds' => 587,
			'privacy'          => 'public',
			'published_at'     => '2025-03-22T12:30:00Z',
			'thumbnails'       => array(
				'default' => 'https://i.ytimg.com/vi/St7Uv8Wx9Y0/default.jpg',
				'high'    => 'https://i.ytimg.com/vi/St7Uv8Wx9Y0/hqdefault.jpg',
				'maxres'  => 'https://i.ytimg.com/vi/St7Uv8Wx9Y0/maxresdefault.jpg',
			),
		),
		array(
			'external_id'      => 'Za1Bc2De3F4',
			'title'            => 'Rooftop Tent vs Hostels: 30-Day Cost Test',
			'description'      => 'I split a month between a borrowed rooftop tent and dorm beds, tracked every expense, and only regretted one of them.',
			'tags'             => array( 'rooftop tent', 'hostels', 'comparison', 'budget travel', 'vanlife' ),
			'duration_seconds' => 1310,
			'privacy'          => 'public',
			'published_at'     => '2025-02-27T17:40:00Z',
			'thumbnails'       => array(
				'default' => 'https://i.ytimg.com/vi/Za1Bc2De3F4/default.jpg',
				'high'    => 'https://i.ytimg.com/vi/Za1Bc2De3F4/hqdefault.jpg',
				'maxres'  => 'https://i.ytimg.com/vi/Za1Bc2De3F4/maxresdefault.jpg',
			),
		),
		array(
			'external_id'      => 'Gh5Ij6Kl7M8',
			'title'            => 'First Attempt at Astrophotography in Atacama',
			'description'      => 'The driest desert on Earth has the clearest sky I\'ve ever pointed a camera at. Mistakes were made; stars were captured.',
			'tags'             => array( 'astrophotography', 'atacama', 'chile', 'night sky', 'milky way' ),
			'duration_seconds' => 892,
			'privacy'          => 'public',
			'published_at'     => '2025-02-03T21:15:00Z',
			'thumbnails'       => array(
				'default' => 'https://i.ytimg.com/vi/Gh5Ij6Kl7M8/default.jpg',
				'high'    => 'https://i.ytimg.com/vi/Gh5Ij6Kl7M8/hqdefault.jpg',
				'maxres'  => null,
			),
		),
		array(
			'external_id'      => 'No9Pq0Rs1T2',
			'title'            => 'Channel Trailer — Lens & Latitude',
			'description'      => 'Slow travel, honest budgets, and the occasional rooster. New videos most Thursdays.',
			'tags'             => array( 'channel trailer', 'travel', 'introduction' ),
			'duration_seconds' => 96,
			'privacy'          => 'public',
			'published_at'     => '2024-12-30T10:00:00Z',
			'thumbnails'       => array(
				'default' => 'https://i.ytimg.com/vi/No9Pq0Rs1T2/default.jpg',
				'high'    => 'https://i.ytimg.com/vi/No9Pq0Rs1T2/hqdefault.jpg',
				'maxres'  => 'https://i.ytimg.com/vi/No9Pq0Rs1T2/maxresdefault.jpg',
			),
		),
	),
);
