export const RECEIVE_INTEGRATIONS = 'RECEIVE_INTEGRATIONS';
export const INVALIDATE_INTEGRATIONS = 'INVALIDATE_INTEGRATIONS';
export const SET_INTEGRATIONS_LOADING = 'SET_INTEGRATIONS_LOADING';
export const SET_INTEGRATIONS_ERROR = 'SET_INTEGRATIONS_ERROR';
