<?php // phpcs:ignore WordPress.Files.FileName.InvalidClassFileName -- Feature entry file, named after the feature, also holds the AI_Launchpad bootstrap class.
/**
 * AI Launchpad: an AI-tailored onboarding tasklist on a top-level wp-admin page.
 *
 * @package automattic/jetpack-mu-wpcom
 */

namespace Automattic\Jetpack\Jetpack_Mu_Wpcom;

use Automattic\Jetpack\Connection\Initial_State as Connection_Initial_State;
use Automattic\Jetpack\WP_Build_Polyfills\WP_Build_Polyfills;

// helpers.php defines the shared option reader the listeners depend on, so it
// loads first. The REST controller and completion listeners self-register on
// their own hooks (rest_api_init / init) at load time, and must run on every
// request regardless of which admin page is showing.
require_once __DIR__ . '/helpers.php';
require_once __DIR__ . '/eligibility.php';
require_once __DIR__ . '/class-ai-launchpad-memberships.php';
require_once __DIR__ . '/class-ai-launchpad-rest.php';
require_once __DIR__ . '/class-ai-launchpad-listeners.php';
require_once __DIR__ . '/class-ai-launchpad-theme-listener.php';
require_once __DIR__ . '/class-ai-launchpad-social-listener.php';
require_once __DIR__ . '/class-ai-launchpad-subscribers-listener.php';
require_once __DIR__ . '/class-ai-launchpad-about-page-listener.php';
require_once __DIR__ . '/class-ai-launchpad-dev-enable.php';

/**
 * Registers the AI Launchpad admin page and its wp-build assets.
 */
class AI_Launchpad {

	/**
	 * Admin page slug. The `-wp-admin` suffix is the wp-build convention for
	 * pages that integrate with the standard wp-admin chrome: the generated
	 * page PHP only enqueues its assets when `$_GET['page']` matches
	 * `<page-id>-wp-admin`.
	 */
	const MENU_SLUG = 'ai-launchpad-wp-admin';

	/**
	 * Render callback generated by wp-build in build/pages/ai-launchpad/page-wp-admin.php.
	 */
	const RENDER_CALLBACK = 'jetpack_mu_wpcom_ai_launchpad_wp_admin_render_page';

	/**
	 * Initialize the feature.
	 */
	public static function init() {
		add_action( 'admin_menu', array( __CLASS__, 'register_menu' ) );

		if ( ! self::is_ai_launchpad_request() ) {
			return;
		}

		self::load_wp_build();
		self::fix_boot_import_map_ordering();
		add_action( 'admin_enqueue_scripts', array( __CLASS__, 'enqueue_jwt_initial_state' ), 20 );
	}

	/**
	 * Whether the current request targets the AI Launchpad admin page.
	 *
	 * @return bool
	 */
	private static function is_ai_launchpad_request() {
		// phpcs:ignore WordPress.Security.NonceVerification.Recommended
		return is_admin() && isset( $_GET['page'] ) && self::MENU_SLUG === $_GET['page'];
	}

	/**
	 * Whether the current site is eligible for the AI Launchpad.
	 *
	 * MVP gate: paid plan, not already AI-onboarded, and explicitly enabled for
	 * the site via the `wpcom_ai_launchpad_enabled` option (set per-site over
	 * wp-cli). Replaces the earlier automattician/blog-sticker check, which did
	 * not work on Atomic: `is_automattician()` is undefined there and blog
	 * stickers require the wpcom sandbox. The option works identically on Simple
	 * and Atomic and is context-independent (admin, REST, and CLI agree).
	 *
	 * @return bool
	 */
	public static function is_eligible() {
		static $eligible = null;

		if ( null === $eligible ) {
			// Cheapest gate first: the per-site option disqualifies the vast
			// majority of sites with a single option read, before the more
			// expensive purchases lookup in has_paid_plan() runs on every admin
			// page. Memoized since the result is stable for the request.
			$eligible = self::is_enabled_for_site()
				&& ! self::was_ai_onboarded()
				&& self::has_paid_plan();
		}

		return $eligible;
	}

	/**
	 * Whether the site has a paid plan (bundle purchase).
	 *
	 * @return bool
	 */
	private static function has_paid_plan() {
		if ( ! function_exists( 'wpcom_get_site_purchases' ) ) {
			return false;
		}

		$bundles = wp_list_filter( wpcom_get_site_purchases(), array( 'product_type' => 'bundle' ) );

		return ! empty( $bundles );
	}

	/**
	 * Whether the site already went through an AI onboarding flow.
	 *
	 * @return bool
	 */
	private static function was_ai_onboarded() {
		return get_option( 'site_intent' ) === 'ai-assembler' || get_option( 'site_creation_flow' ) === 'ai-site-builder';
	}

	/**
	 * Whether the AI Launchpad has been explicitly enabled for this site.
	 *
	 * Set per-site with `wp option update wpcom_ai_launchpad_enabled 1`.
	 *
	 * @return bool
	 */
	private static function is_enabled_for_site() {
		return (bool) get_option( 'wpcom_ai_launchpad_enabled' );
	}

	/**
	 * Register the top-level admin menu item for eligible users.
	 */
	public static function register_menu() {
		if ( ! self::is_eligible() ) {
			return;
		}

		// The render callback only exists when build/build.php has been loaded,
		// which happens on the AI Launchpad page itself. On other admin screens
		// the menu just needs a registered slug.
		$callback = function_exists( self::RENDER_CALLBACK )
			? self::RENDER_CALLBACK
			: '__return_empty_string';

		add_menu_page(
			/** "AI Launchpad" is a product name, do not translate. */
			'AI Launchpad',
			'AI Launchpad',
			'manage_options',
			self::MENU_SLUG,
			$callback,
			'dashicons-list-view'
		);
	}

	/**
	 * Load the wp-build generated asset registrations and the boot polyfills.
	 */
	private static function load_wp_build() {
		$wp_build_index = dirname( __DIR__, 3 ) . '/build/build.php';

		if ( ! file_exists( $wp_build_index ) ) {
			return;
		}

		require_once $wp_build_index;

		// Register polyfills for WP < 7.0 (must run before enqueue).
		WP_Build_Polyfills::register(
			'jetpack-mu-wpcom',
			array_merge(
				WP_Build_Polyfills::SCRIPT_HANDLES,
				WP_Build_Polyfills::MODULE_IDS
			)
		);
	}

	/**
	 * Attach the JWT preconditions to the page's prerequisites script:
	 * `JP_CONNECTION_INITIAL_STATE` (apiNonce + siteSuffix for requestJwt())
	 * and `Jetpack_Editor_Initial_State.wpcomBlogId`.
	 */
	public static function enqueue_jwt_initial_state() {
		$handle = self::MENU_SLUG . '-prerequisites';

		if ( ! wp_script_is( $handle, 'registered' ) ) {
			return;
		}

		Connection_Initial_State::render_script( $handle );

		wp_localize_script(
			$handle,
			'Jetpack_Editor_Initial_State',
			array(
				'wpcomBlogId' => get_wpcom_blog_id(),
			)
		);
	}

	/**
	 * Fix import map ordering for the wp-build boot script.
	 *
	 * In wp-admin, _wp_footer_scripts (classic scripts) and print_import_map
	 * both hook into admin_print_footer_scripts at priority 10, but
	 * _wp_footer_scripts is registered first. This causes the inline
	 * import("@wordpress/boot") to execute before the import map exists.
	 *
	 * This fix moves the import() call from the classic inline script to a
	 * <script type="module"> printed at priority 20 (after the import map).
	 *
	 * @todo Remove once @wordpress/build ships with the loader.js fix upstream
	 *       (WordPress/gutenberg#76870) and Jetpack updates the dependency.
	 */
	private static function fix_boot_import_map_ordering() {
		$handle = self::MENU_SLUG . '-prerequisites';

		add_action(
			'admin_enqueue_scripts',
			static function () use ( $handle ) {
				$data = wp_scripts()->get_data( $handle, 'after' );
				if ( empty( $data ) ) {
					return;
				}

				// Find and extract the import("@wordpress/boot") inline script.
				$boot_script = null;
				$remaining   = array();
				foreach ( $data as $line ) {
					if ( strpos( $line, '@wordpress/boot' ) !== false ) {
						$boot_script = $line;
					} else {
						$remaining[] = $line;
					}
				}

				if ( $boot_script === null ) {
					return;
				}

				// Remove from the classic script handle.
				wp_scripts()->add_data( $handle, 'after', $remaining );

				// Re-emit as a module script after the import map.
				add_action(
					'admin_print_footer_scripts',
					static function () use ( $boot_script ) {
						wp_print_inline_script_tag( $boot_script, array( 'type' => 'module' ) );
					},
					20
				);
			},
			PHP_INT_MAX
		);
	}
}
