<?php // phpcs:ignore WordPress.Files.FileName.InvalidClassFileName -- Feature entry file, named after the feature, also holds the AI_Launchpad bootstrap class.
/**
 * AI Launchpad: an AI-tailored onboarding tasklist on a top-level wp-admin page.
 *
 * @package automattic/jetpack-mu-wpcom
 */

namespace Automattic\Jetpack\Jetpack_Mu_Wpcom;

use Automattic\Jetpack\Connection\Initial_State as Connection_Initial_State;
use Automattic\Jetpack\WP_Build_Polyfills\WP_Build_Polyfills;

// helpers.php defines the shared option reader the listeners depend on, so it loads first.
require_once __DIR__ . '/helpers.php';
require_once __DIR__ . '/eligibility.php';
require_once __DIR__ . '/class-ai-launchpad-memberships.php';
require_once __DIR__ . '/class-ai-launchpad-rest.php';
require_once __DIR__ . '/class-ai-launchpad-listeners.php';
require_once __DIR__ . '/class-ai-launchpad-theme-listener.php';
require_once __DIR__ . '/class-ai-launchpad-social-listener.php';
require_once __DIR__ . '/class-ai-launchpad-subscribers-listener.php';
require_once __DIR__ . '/class-ai-launchpad-subscribe-block-listener.php';
require_once __DIR__ . '/class-ai-launchpad-about-page-listener.php';
require_once __DIR__ . '/class-ai-launchpad-gallery-page-listener.php';
require_once __DIR__ . '/class-ai-launchpad-first-post-listener.php';
require_once __DIR__ . '/class-ai-launchpad-dev-enable.php';

/**
 * Registers the AI Launchpad admin page and its wp-build assets.
 */
class AI_Launchpad {

	/**
	 * Admin page slug. The `-wp-admin` suffix is the wp-build convention for pages that integrate with wp-admin chrome.
	 */
	const MENU_SLUG = 'site-setup-wp-admin';

	/**
	 * Render callback generated by wp-build in build/pages/site-setup/page-wp-admin.php.
	 */
	const RENDER_CALLBACK = 'jetpack_mu_wpcom_site_setup_wp_admin_render_page';

	/**
	 * Initialize the feature.
	 */
	public static function init() {
		add_action( 'admin_menu', array( __CLASS__, 'register_menu' ) );

		if ( ! self::is_ai_launchpad_request() ) {
			return;
		}

		self::load_wp_build();
		self::fix_boot_import_map_ordering();
		add_action( 'admin_enqueue_scripts', array( __CLASS__, 'enqueue_jwt_initial_state' ), 20 );
	}

	/**
	 * Whether the current request targets the AI Launchpad admin page.
	 *
	 * @return bool
	 */
	private static function is_ai_launchpad_request() {
		// phpcs:ignore WordPress.Security.NonceVerification.Recommended
		return is_admin() && isset( $_GET['page'] ) && self::MENU_SLUG === $_GET['page'];
	}

	/**
	 * Whether the current site is eligible for the AI Launchpad.
	 *
	 * Gate: not already AI-onboarded, not dismissed (skipping the wizard dismisses it, reverting the site
	 * to the regular launchpad), and explicitly enabled for the site via the `wpcom_ai_launchpad_enabled`
	 * option. The paid-plan requirement is temporarily lifted (see below).
	 *
	 * @return bool
	 */
	public static function is_eligible() {
		static $eligible = null;

		if ( null === $eligible ) {
			// TEMPORARY: the paid-plan gate is lifted so the AI Launchpad is available on all plans, including free.
			// Revert this commit to re-require a paid bundle (the removed has_paid_plan() check).
			$eligible = self::is_enabled_for_site()
				&& ! self::was_ai_onboarded()
				&& ! get_option( \AI_Launchpad_REST::OPTION_DISMISSED );
		}

		return $eligible;
	}

	/**
	 * Whether the site already went through an AI onboarding flow.
	 *
	 * @return bool
	 */
	private static function was_ai_onboarded() {
		return get_option( 'site_intent' ) === 'ai-assembler' || get_option( 'site_creation_flow' ) === 'ai-site-builder';
	}

	/**
	 * Whether the AI Launchpad has been explicitly enabled for this site.
	 *
	 * Set per-site with `wp option update wpcom_ai_launchpad_enabled 1`.
	 *
	 * @return bool
	 */
	private static function is_enabled_for_site() {
		return (bool) get_option( 'wpcom_ai_launchpad_enabled' );
	}

	/**
	 * Register the top-level admin menu item for eligible users.
	 */
	public static function register_menu() {
		if ( ! self::is_eligible() ) {
			return;
		}

		// Once every task is done, drop the launchpad from the sidebar. Separate from eligibility on purpose — the
		// enable option stays set, so re-tailoring or a reset brings it back. Reads the latched flag, no rebuild.
		if ( get_option( \AI_Launchpad_REST::OPTION_COMPLETED ) ) {
			return;
		}

		// The render callback only exists once build/build.php is loaded, which happens on the AI Launchpad page itself.
		$callback = function_exists( self::RENDER_CALLBACK )
			? self::RENDER_CALLBACK
			: '__return_empty_string';

		// The "border" glyph from @wordpress/icons — the same icon the launchpad list uses for a to-do task.
		$icon = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path fill="#fff" d="m6.6 15.6-1.2.8c.6.9 1.3 1.6 2.2 2.2l.8-1.2c-.7-.5-1.3-1.1-1.8-1.8zM5.5 12c0-.4 0-.9.1-1.3l-1.5-.3c0 .5-.1 1.1-.1 1.6s.1 1.1.2 1.6l1.5-.3c-.2-.4-.2-.9-.2-1.3zm11.9-3.6 1.2-.8c-.6-.9-1.3-1.6-2.2-2.2l-.8 1.2c.7.5 1.3 1.1 1.8 1.8zM5.3 7.6l1.2.8c.5-.7 1.1-1.3 1.8-1.8l-.7-1.3c-.9.6-1.7 1.4-2.3 2.3zm14.5 2.8-1.5.3c.1.4.1.8.1 1.3s0 .9-.1 1.3l1.5.3c.1-.5.2-1 .2-1.6s-.1-1.1-.2-1.6zM12 18.5c-.4 0-.9 0-1.3-.1l-.3 1.5c.5.1 1 .2 1.6.2s1.1-.1 1.6-.2l-.3-1.5c-.4.1-.9.1-1.3.1zm3.6-1.1.8 1.2c.9-.6 1.6-1.3 2.2-2.2l-1.2-.8c-.5.7-1.1 1.3-1.8 1.8zM10.4 4.2l.3 1.5c.4-.1.8-.1 1.3-.1s.9 0 1.3.1l.3-1.5c-.5-.1-1.1-.2-1.6-.2s-1.1.1-1.6.2z"/></svg>';

		add_menu_page(
			__( 'Site Setup', 'jetpack-mu-wpcom' ),
			__( 'Site Setup', 'jetpack-mu-wpcom' ),
			'manage_options',
			self::MENU_SLUG,
			$callback,
			'data:image/svg+xml;base64,' . base64_encode( $icon ), // phpcs:ignore WordPress.PHP.DiscouragedPHPFunctions.obfuscation_base64_encode -- Encoding an inline SVG for the menu icon data URI.
			2.01
		);
	}

	/**
	 * Load the wp-build generated asset registrations and the boot polyfills.
	 */
	private static function load_wp_build() {
		$wp_build_index = dirname( __DIR__, 3 ) . '/build/build.php';

		if ( ! file_exists( $wp_build_index ) ) {
			return;
		}

		require_once $wp_build_index;

		// Register polyfills for WP < 7.0 (must run before enqueue).
		WP_Build_Polyfills::register(
			'jetpack-mu-wpcom',
			array_merge(
				WP_Build_Polyfills::SCRIPT_HANDLES,
				WP_Build_Polyfills::MODULE_IDS
			)
		);
	}

	/**
	 * Attach the JWT preconditions to the page's prerequisites script:
	 * `JP_CONNECTION_INITIAL_STATE` (apiNonce + siteSuffix for requestJwt())
	 * and `Jetpack_Editor_Initial_State.wpcomBlogId`.
	 */
	public static function enqueue_jwt_initial_state() {
		$handle = self::MENU_SLUG . '-prerequisites';

		if ( ! wp_script_is( $handle, 'registered' ) ) {
			return;
		}

		Connection_Initial_State::render_script( $handle );

		wp_localize_script(
			$handle,
			'Jetpack_Editor_Initial_State',
			array(
				'wpcomBlogId' => get_wpcom_blog_id(),
			)
		);
	}

	/**
	 * Fix import map ordering for the wp-build boot script.
	 *
	 * In wp-admin both _wp_footer_scripts and print_import_map hook admin_print_footer_scripts at priority 10, but
	 * _wp_footer_scripts runs first, so the inline import("@wordpress/boot") executes before the import map exists.
	 * This moves the import() call to a <script type="module"> printed at priority 20, after the import map.
	 *
	 * @todo Remove once @wordpress/build ships the loader.js fix upstream
	 *       (WordPress/gutenberg#76870) and Jetpack updates the dependency.
	 */
	private static function fix_boot_import_map_ordering() {
		$handle = self::MENU_SLUG . '-prerequisites';

		add_action(
			'admin_enqueue_scripts',
			static function () use ( $handle ) {
				$data = wp_scripts()->get_data( $handle, 'after' );
				if ( empty( $data ) ) {
					return;
				}

				$boot_script = null;
				$remaining   = array();
				foreach ( $data as $line ) {
					if ( strpos( $line, '@wordpress/boot' ) !== false ) {
						$boot_script = $line;
					} else {
						$remaining[] = $line;
					}
				}

				if ( $boot_script === null ) {
					return;
				}

				wp_scripts()->add_data( $handle, 'after', $remaining );

				// Re-emit as a module script after the import map.
				add_action(
					'admin_print_footer_scripts',
					static function () use ( $boot_script ) {
						wp_print_inline_script_tag( $boot_script, array( 'type' => 'module' ) );
					},
					20
				);
			},
			PHP_INT_MAX
		);
	}
}
