import {
	MY_JETPACK_SECTION_HELP,
	MY_JETPACK_SECTION_OVERVIEW,
	MY_JETPACK_SECTION_PRODUCTS,
} from './constants';

export type MyJetpackSection =
	| typeof MY_JETPACK_SECTION_OVERVIEW
	| typeof MY_JETPACK_SECTION_PRODUCTS
	| typeof MY_JETPACK_SECTION_HELP;
