import {
	MY_JETPACK_SECTION_FEATURES,
	MY_JETPACK_SECTION_HELP,
	MY_JETPACK_SECTION_OVERVIEW,
} from './constants';

export type MyJetpackSection =
	| typeof MY_JETPACK_SECTION_OVERVIEW
	| typeof MY_JETPACK_SECTION_FEATURES
	| typeof MY_JETPACK_SECTION_HELP;
