export const SEARCH_DASHBOARD_TAB_SETTINGS = 'settings';
export const SEARCH_DASHBOARD_TAB_PLAN_USAGE = 'plan-usage';

export const DEFAULT_SEARCH_DASHBOARD_TAB = SEARCH_DASHBOARD_TAB_SETTINGS;

export const SEARCH_DASHBOARD_TABS = [
	SEARCH_DASHBOARD_TAB_SETTINGS,
	SEARCH_DASHBOARD_TAB_PLAN_USAGE,
];
