#!/usr/bin/env bash

# Create a PR to fix outdated lock files on trunk.
#
# This is run if .github/files/check-lock-files.sh has failed, leaving the
# regenerated lock files in the working tree.

set -eo pipefail

BASE="$PWD"
BRANCH=update/pnpm_and_composer_lock_files

. "$BASE/tools/includes/changelogger.sh"

TMP=$( git -c core.quotepath=off diff --name-only -- 'pnpm-lock.yaml' '**/pnpm-lock.yaml' 'composer.lock' '**/composer.lock' )
if [[ -z "$TMP" ]]; then
	# This really shouldn't trigger in CI, but let's keep it for manual runs.
	echo '::notice::No lock file changes, so not creating a PR.'
	exit 0
fi
mapfile -t FILES <<<"$TMP"

if git -c protocol.version=2 fetch --no-tags --prune --no-recurse-submodules --depth=1 origin "$BRANCH" >/dev/null 2>&1; then
	if git diff --quiet --exit-code "origin/$BRANCH" -- "${FILES[@]}"; then
		echo "::notice::Branch $BRANCH already exists and is up to date with these changes."
		exit 0
	fi
	HAS_BRANCH=true
else
	HAS_BRANCH=false
fi

# Use -B instead of -b so it resets the branch to HEAD instead of failing when the branch exists.
git checkout -B "$BRANCH"
git add -- "${FILES[@]}"

# Add change files for any projects with lock file changes.
for DIR in $(printf '%s\n' "${FILES[@]}" | sed -nE 's!^(projects/[^/]+/[^/]+)/.*!\1!p' | sort -u); do
	cd "$DIR"
	changelogger_add 'Update lock file.' '' --filename=update-lock-files
	CHANGES_DIR="$(jq -r '.extra.changelogger["changes-dir"] // "changelog"' composer.json)"
	git add "$CHANGES_DIR"
	cd "$BASE"
done

git commit -m 'Update lock files'

if $HAS_BRANCH; then
	echo "::notice::Updating existing branch '$BRANCH'."
	git push --force-with-lease origin "$BRANCH"
else
	echo "::notice::Creating branch '$BRANCH' and its PR."
	git push origin "$BRANCH"
	if ! gh pr create --base trunk --title 'Lint: Update outdated lock files' --body 'A lock file on trunk is out of date, probably due to a conflict between recently merged PRs. This PR was automatically generated by the "Lock files are up to date" linting job. If closed it will be recreated the next time the job fails on trunk.' --label '[Status] Needs Review' --reviewer Automattic/jetpack-monorepo; then
		git push --delete origin "$BRANCH"
		exit 1
	fi
fi
