# Jetpack Approvers need to review changes to the monorepo itself.
# These areas are reserved to ensure we're all on the same page and not putting in one-off solutions without conversation.
- name: Monorepo itself
  paths:
   - '!projects/**'
   - '!pnpm-lock.yaml'
   - '!docs/**'
  teams:
   - jetpack-approvers

# Jetpack Approvers review the Sync and Connection packages.
# These are reserved due to the critical nature to the entire ecosystem and that small bugs can have big consequences.
- name: Sync and Connection packages
  paths:
   - 'projects/packages/sync/**'
   - 'projects/packages/connection/**'
  teams:
   - jetpack-approvers
