# Jetpack Approvers need to review changes to the monorepo itself.
# These areas are reserved to ensure we're all on the same page and not putting in one-off solutions without conversation.
  paths:
   - '!projects/**'
   - '!pnpm-lock.yaml'
   - '!docs/**'
  teams:
   - jetpack-approvers

# Everyone who can approve anything can merge pnpm.lock and docs.
- name: pnpm lockfile, composer files
  paths:
   - 'pnpm-lock.yaml'
   - 'projects/plugins/*/composer.lock'
   - 'projects/plugins/*/composer.json'
   - 'projects/plugins/*/changelog/*'
  teams:
   # Unfortunately this list need to be maintaned manually...
   # yamato-backup-and-security is the group that consists of both yamato-scan and yamato-backup teams.
   - avengers
   - caribou
   - heart-of-gold
   - jetpack-approvers
   - jetpack-reach
   - red
   - yamato-backup-and-security
   - '@CGastrell'
   - '@ice9js'

# Jetpack Approvers review the Jetpack plugin and all packages, except for those with specific team ownership.
- name: Jetpack and packages
  paths:
   - 'projects/packages/sync/**'
   - 'projects/packages/connection/**'
  teams:
   - jetpack-approvers


# The Avengers team reviews changes to the CRM plugin,
# and can add dependencies to the monorepo's lock file.
- name: CRM
  paths:
    - 'projects/plugins/crm/**'
    - '!projects/plugins/*/composer.lock'
    - '!projects/plugins/*/composer.json'
    - '!projects/plugins/*/changelog/*'
  teams:
    - avengers
    - jetpack-approvers

# The Caribou team reviews changes to the Migration plugin and its Import package,
# and can add dependencies to the monorepo's lock file.
- name: Migration
  paths:
    - 'projects/packages/import/**'
    - 'projects/plugins/migration/**'
    - '!projects/plugins/*/composer.lock'
    - '!projects/plugins/*/composer.json'
    - '!projects/plugins/*/changelog/*'
  teams:
    - caribou
    - jetpack-approvers

# The Backup team reviews changes to the VaultPress and Backup plugin,
# and can add dependencies to the monorepo's lock file.
- name: VaultPress & Backup
  paths:
   - 'projects/packages/backup/**'
   - 'projects/plugins/vaultpress/**'
   - 'projects/plugins/backup/**'
   - '!projects/plugins/*/composer.lock'
   - '!projects/plugins/*/composer.json'
   - '!projects/plugins/*/changelog/*'
  teams:
   - yamato-backup
   - jetpack-approvers

# The Scan team reviews changes to the protect plugin, the WAF package, etc,
# and can add dependencies to the monorepo's lock file.
- name: Scan
  paths:
    - 'projects/packages/waf/**'
    - 'projects/plugins/protect/**'
    - '!projects/plugins/*/composer.lock'
    - '!projects/plugins/*/composer.json'
    - '!projects/plugins/*/changelog/*'
  teams:
    - yamato-scan
    - jetpack-approvers

# The Heart of Gold team reviews changes to the Boost or Super Cache plugin,
# and can add dependencies to the monorepo's lock file.
- name: Boost
  paths:
   - 'projects/plugins/boost/**'
   - 'projects/plugins/super-cache/**'
   - 'projects/js-packages/image-guide/**'
   - 'projects/js-packages/svelte-data-sync-client/**'
   - 'projects/packages/wp-js-data-sync/**'
   - '!projects/plugins/*/composer.lock'
   - '!projects/plugins/*/composer.json'
   - '!projects/plugins/*/changelog/*'
  teams:
   - heart-of-gold
   - jetpack-approvers
   - '@donnchawp'

# The Red team reviews changes to the Search plugin, and the Search package.
- name: Search
  paths:
   - 'projects/plugins/search/**'
   - 'projects/packages/search/**'
   - '!projects/plugins/*/composer.lock'
   - '!projects/plugins/*/composer.json'
   - '!projects/plugins/*/changelog/*'
  teams:
   - red
   - jetpack-approvers

# The Red team reviews changes to the Stats and its Admin package.
- name: Stats
  paths:
   - 'projects/packages/stats/**'
   - 'projects/packages/stats-admin/**'
   - '!projects/plugins/*/composer.lock'
   - '!projects/plugins/*/composer.json'
   - '!projects/plugins/*/changelog/*'
  teams:
   - red
   - jetpack-approvers

# The Reach team reviews changes to the Social plugin, and the Publicize package.
- name: Social
  paths:
   - 'projects/plugins/social/**'
   - 'projects/packages/publicize/**'
   - 'projects/js-packages/publicize-components/**'
   - '!projects/plugins/*/composer.lock'
   - '!projects/plugins/*/composer.json'
   - '!projects/plugins/*/changelog/*'
  teams:
   - jetpack-reach
   - jetpack-approvers

# The Crowdsignal team reviews changes to the Forms package.
- name: Forms
  paths:
    - 'projects/packages/forms/**'
    - '!projects/plugins/*/composer.lock'
    - '!projects/plugins/*/composer.json'
    - '!projects/plugins/*/changelog/*'
  teams:
    - '@CGastrell'
    - '@ice9js'
    - jetpack-approvers
