# Jetpack Approvers need to review changes to the monorepo itself.
- name: Monorepo itself
  paths:
   - '!projects/**'
   - '!pnpm-lock.yaml'
  teams:
   - jetpack-approvers

# Everyone who can approve anything can merge pnpm.lock.
- name: pnpm lockfile
  paths:
   - 'pnpm-lock.yaml'
  teams:
   # Unfortunately this list need to be maintaned manually...
   # yamato-backup-and-security is the group that consists of both yamato-scan and yamato-backup teams.
   - jetpack-approvers
   - yamato-backup-and-security
   - heart-of-gold
   - jetpack-search
   - jetpack-reach

# Jetpack Approvers review the Jetpack plugin and all packages, except for those with specific team ownership.
- name: Jetpack and packages
  paths:
   - 'projects/packages/**'
   - 'projects/plugins/jetpack/**'
   # Exclude packages managed by other teams, which are covered by other blocks below.
   - '!projects/packages/backup/**'
   - '!projects/packages/search/**'
   - '!projects/packages/publicize/**'
   - '!projects/packages/waf/**'
  teams:
   - jetpack-approvers

# The Backup team reviews changes to the VaultPress and Backup plugin,
# and can add dependencies to the monorepo's lock file.
- name: VaultPress & Backup, and Scan
  paths:
   - 'projects/packages/backup/**'
   - 'projects/plugins/vaultpress/**'
   - 'projects/plugins/backup/**'
  teams:
   - yamato-backup
   - jetpack-approvers

# The Scan team reviews changes to the protect plugin, the WAF package, etc,
# and can add dependencies to the monorepo's lock file.
- name: VaultPress & Backup, and Scan
  paths:
    - 'projects/packages/waf/**'
    - 'projects/plugins/protect/**'
  teams:
    - yamato-scan
    - jetpack-approvers

# The Boost team reviews changes to the Boost plugin,
# and can add dependencies to the monorepo's lock file.
- name: Boost
  paths:
   - 'projects/plugins/boost/**'
  teams:
   - heart-of-gold
   - jetpack-approvers

# The Search team reviews changes to the Search plugin, and the Search package.
- name: Search
  paths:
   - 'projects/plugins/search/**'
   - 'projects/packages/search/**'
  teams:
   - jetpack-search
   - jetpack-approvers

# The Reach team reviews changes to the Social plugin, and the Publicize package.
- name: Social
  paths:
   - 'projects/plugins/social/**'
   - 'projects/packages/publicize/**'
  teams:
   - jetpack-reach
   - jetpack-approvers

# Jetpack Approvers review everything that hasn't been specifically assigned above.
# This needs to be last.
- name: Default to Jetpack Approvers
  paths: unmatched
  teams:
   - jetpack-approvers
