<?php
/**
 * Manifest Generator.
 *
 * @package automattic/jetpack-autoloader
 */

// phpcs:disable WordPress.PHP.DevelopmentFunctions.error_log_var_export

namespace Automattic\Jetpack\Autoloader;

/**
 * Class ManifestGenerator.
 */
class ManifestGenerator {

	/**
	 * Builds a manifest file for the given autoloader type.
	 *
	 * @param string $autoloaderType The type of autoloader to build a manifest for.
	 * @param string $fileName The filename of the manifest.
	 * @param array  $content The manifest content to generate using.
	 *
	 * @return string|null $manifestFile
	 * @throws \InvalidArgumentException When an invalid autoloader type is given.
	 */
	public static function buildManifest( $autoloaderType, $fileName, $content ) {
		if ( empty( $content ) ) {
			return null;
		}

		switch ( $autoloaderType ) {
			case 'classmap':
			case 'files':
				return self::buildStandardManifest( $fileName, $content );
			case 'psr-4':
				return self::buildPsr4Manifest( $fileName, $content );
		}

		throw new \InvalidArgumentException( 'An invalid manifest type of ' . $autoloaderType . ' was passed!' );
	}

	/**
	 * Builds the contents for the standard manifest file.
	 *
	 * @param string $fileName The filename we are building.
	 * @param array  $manifestData The formatted data for the manifest.
	 *
	 * @return string|null $manifestFile
	 */
	private static function buildStandardManifest( $fileName, $manifestData ) {
		$fileContent = PHP_EOL;
		foreach ( $manifestData as $key => $data ) {
			$key             = var_export( $key, true );
			$versionCode     = var_export( $data['version'], true );
			$packageCode     = var_export( isset( $data['package'] ) ? $data['package'] : '', true );
			$constraintsCode = self::exportConstraints( isset( $data['constraints'] ) ? $data['constraints'] : array() );
			$fileContent    .= <<<MANIFEST_CODE
	$key => array(
		'version'     => $versionCode,
		'path'        => {$data['path']},
		'package'     => $packageCode,
		'constraints' => $constraintsCode
	),
MANIFEST_CODE;
			$fileContent    .= PHP_EOL;
		}

		return self::buildFile( $fileName, $fileContent );
	}

	/**
	 * Builds the contents for the PSR-4 manifest file.
	 *
	 * @param string $fileName The filename we are building.
	 * @param array  $namespaces The formatted PSR-4 data for the manifest.
	 *
	 * @return string|null $manifestFile
	 */
	private static function buildPsr4Manifest( $fileName, $namespaces ) {
		$fileContent = PHP_EOL;
		foreach ( $namespaces as $namespace => $data ) {
			$namespaceCode   = var_export( $namespace, true );
			$versionCode     = var_export( $data['version'], true );
			$pathCode        = 'array( ' . implode( ', ', $data['path'] ) . ' )';
			$packageCode     = var_export( isset( $data['package'] ) ? $data['package'] : '', true );
			$constraintsCode = self::exportConstraints( isset( $data['constraints'] ) ? $data['constraints'] : array() );
			$fileContent    .= <<<MANIFEST_CODE
	$namespaceCode => array(
		'version'     => $versionCode,
		'path'        => $pathCode,
		'package'     => $packageCode,
		'constraints' => $constraintsCode
	),
MANIFEST_CODE;
			$fileContent    .= PHP_EOL;
		}

		return self::buildFile( $fileName, $fileContent );
	}

	/**
	 * Exports a constraints array as a PHP array literal string.
	 *
	 * @param array $constraints The constraint strings to export.
	 *
	 * @return string The PHP code representing the array.
	 */
	private static function exportConstraints( $constraints ) {
		if ( empty( $constraints ) ) {
			return 'array()';
		}

		$items = array();
		foreach ( $constraints as $constraint ) {
			$items[] = var_export( $constraint, true );
		}

		return 'array( ' . implode( ', ', $items ) . ' )';
	}

	/**
	 * Generate the PHP that will be used in the file.
	 *
	 * @param string $fileName The filename we are building.
	 * @param string $content The content to be written into the file.
	 *
	 * @return string $fileContent
	 */
	private static function buildFile( $fileName, $content ) {
		return <<<INCLUDE_FILE
<?php

// This file `$fileName` was auto generated by automattic/jetpack-autoloader.

\$vendorDir = dirname(__DIR__);
\$baseDir   = dirname(\$vendorDir);

return array($content);

INCLUDE_FILE;
	}
}
