name: "Read tool versions"
description: "Read tool versions from .github/versions.sh."
outputs:
  php-version:
    description: "The PHP version."
    value: ${{ steps.versions.outputs.php-version }}
  composer-version:
    description: "The composer version."
    value: ${{ steps.versions.outputs.composer-version }}
  node-version:
    description: "The Node version."
    value: ${{ steps.versions.outputs.node-version }}
  pnpm-version:
    description: "The pnpm version."
    value: ${{ steps.versions.outputs.pnpm-version }}
runs:
  using: composite
  steps:
    - name: "Output"
      id: versions
      shell: bash
      run: |
        . .github/versions.sh
        echo "::set-output name=php-version::$PHP_VERSION"
        echo "::set-output name=composer-version::$COMPOSER_VERSION"
        echo "::set-output name=node-version::$NODE_VERSION"
        echo "::set-output name=pnpm-version::$PNPM_VERSION"
