export type ProductCategory =
	| 'recommended'
	| 'security'
	| 'growth'
	| 'performance'
	| 'management'
	| 'create';

export type JetpackProductWithCard =
	| 'ai'
	| 'jetpack-ai'
	| 'anti-spam'
	| 'backup'
	| 'boost'
	| 'crm'
	| 'scan'
	| 'search'
	| 'social'
	| 'stats'
	| 'videopress';

export type JetpackProductWithoutCard =
	| 'complete'
	| 'creator'
	| 'extras'
	| 'newsletter'
	| 'protect'
	| 'related-posts'
	| 'security'
	| 'site-accelerator';

export type JetpackProductSlug = JetpackProductWithCard | JetpackProductWithoutCard;

export type JetpackModuleSlug =
	| 'account-protection'
	| 'blaze'
	| 'blocks'
	| 'carousel'
	| 'comment-likes'
	| 'comments'
	| 'contact-form'
	| 'copy-post'
	| 'custom-content-types'
	| 'google-fonts'
	| 'gravatar-hovercards'
	| 'infinite-scroll'
	| 'json-api'
	| 'latex'
	| 'likes'
	| 'markdown'
	| 'monitor'
	| 'notes'
	| 'photon'
	| 'photon-cdn'
	| 'post-by-email'
	| 'post-list'
	| 'protect'
	| 'publicize'
	| 'related-posts'
	| 'search'
	| 'seo-tools'
	| 'sharedaddy'
	| 'shortcodes'
	| 'shortlinks'
	| 'sitemaps'
	| 'sso'
	| 'stats'
	| 'subscriptions'
	| 'tiled-gallery'
	| 'vaultpress'
	| 'verification-tools'
	| 'videopress'
	| 'waf'
	| 'widget-visibility'
	| 'widgets'
	| 'woocommerce-analytics'
	| 'wordads';
