import { __ } from '@wordpress/i18n';

export const europeanUnionCountries = [
	__( 'Austria', 'jetpack-forms' ),
	__( 'Belgium', 'jetpack-forms' ),
	__( 'Bulgaria', 'jetpack-forms' ),
	__( 'Croatia', 'jetpack-forms' ),
	__( 'Cyprus', 'jetpack-forms' ),
	__( 'Czechia', 'jetpack-forms' ),
	__( 'Denmark', 'jetpack-forms' ),
	__( 'Estonia', 'jetpack-forms' ),
	__( 'Finland', 'jetpack-forms' ),
	__( 'France', 'jetpack-forms' ),
	__( 'Germany', 'jetpack-forms' ),
	__( 'Greece', 'jetpack-forms' ),
	__( 'Hungary', 'jetpack-forms' ),
	__( 'Ireland', 'jetpack-forms' ),
	__( 'Italy', 'jetpack-forms' ),
	__( 'Latvia', 'jetpack-forms' ),
	__( 'Lithuania', 'jetpack-forms' ),
	__( 'Luxembourg', 'jetpack-forms' ),
	__( 'Malta', 'jetpack-forms' ),
	__( 'Netherlands', 'jetpack-forms' ),
	__( 'Poland', 'jetpack-forms' ),
	__( 'Portugal', 'jetpack-forms' ),
	__( 'Romania', 'jetpack-forms' ),
	__( 'Slovakia', 'jetpack-forms' ),
	__( 'Slovenia', 'jetpack-forms' ),
	__( 'Spain', 'jetpack-forms' ),
	__( 'Sweden', 'jetpack-forms' ),
];

export const usStates = [
	__( 'Alabama', 'jetpack-forms' ),
	__( 'Alaska', 'jetpack-forms' ),
	__( 'Arizona', 'jetpack-forms' ),
	__( 'Arkansas', 'jetpack-forms' ),
	__( 'California', 'jetpack-forms' ),
	__( 'Colorado', 'jetpack-forms' ),
	__( 'Connecticut', 'jetpack-forms' ),
	__( 'Delaware', 'jetpack-forms' ),
	__( 'Florida', 'jetpack-forms' ),
	__( 'Georgia', 'jetpack-forms' ),
	__( 'Hawaii', 'jetpack-forms' ),
	__( 'Idaho', 'jetpack-forms' ),
	__( 'Illinois', 'jetpack-forms' ),
	__( 'Indiana', 'jetpack-forms' ),
	__( 'Iowa', 'jetpack-forms' ),
	__( 'Kansas', 'jetpack-forms' ),
	__( 'Kentucky', 'jetpack-forms' ),
	__( 'Louisiana', 'jetpack-forms' ),
	__( 'Maine', 'jetpack-forms' ),
	__( 'Maryland', 'jetpack-forms' ),
	__( 'Massachusetts', 'jetpack-forms' ),
	__( 'Michigan', 'jetpack-forms' ),
	__( 'Minnesota', 'jetpack-forms' ),
	__( 'Mississippi', 'jetpack-forms' ),
	__( 'Missouri', 'jetpack-forms' ),
	__( 'Montana', 'jetpack-forms' ),
	__( 'Nebraska', 'jetpack-forms' ),
	__( 'Nevada', 'jetpack-forms' ),
	__( 'New Hampshire', 'jetpack-forms' ),
	__( 'New Jersey', 'jetpack-forms' ),
	__( 'New Mexico', 'jetpack-forms' ),
	__( 'New York', 'jetpack-forms' ),
	__( 'North Carolina', 'jetpack-forms' ),
	__( 'North Dakota', 'jetpack-forms' ),
	__( 'Ohio', 'jetpack-forms' ),
	__( 'Oklahoma', 'jetpack-forms' ),
	__( 'Oregon', 'jetpack-forms' ),
	__( 'Pennsylvania', 'jetpack-forms' ),
	__( 'Rhode Island', 'jetpack-forms' ),
	__( 'South Carolina', 'jetpack-forms' ),
	__( 'South Dakota', 'jetpack-forms' ),
	__( 'Tennessee', 'jetpack-forms' ),
	__( 'Texas', 'jetpack-forms' ),
	__( 'Utah', 'jetpack-forms' ),
	__( 'Vermont', 'jetpack-forms' ),
	__( 'Virginia', 'jetpack-forms' ),
	__( 'Washington', 'jetpack-forms' ),
	__( 'West Virginia', 'jetpack-forms' ),
	__( 'Wisconsin', 'jetpack-forms' ),
	__( 'Wyoming', 'jetpack-forms' ),
	__( 'District of Columbia', 'jetpack-forms' ),
	__( 'American Samoa', 'jetpack-forms' ),
	__( 'Guam', 'jetpack-forms' ),
	__( 'Northern Mariana Islands', 'jetpack-forms' ),
	__( 'Puerto Rico', 'jetpack-forms' ),
	__( 'United States Minor Outlying Islands', 'jetpack-forms' ),
	__( 'Virgin Islands, U.S.', 'jetpack-forms' ),
];

export const usStatesShort = [
	'AL',
	'AK',
	'AZ',
	'AR',
	'CA',
	'CO',
	'CT',
	'DE',
	'FL',
	'GA',
	'HI',
	'ID',
	'IL',
	'IN',
	'IA',
	'KS',
	'KY',
	'LA',
	'ME',
	'MD',
	'MA',
	'MI',
	'MN',
	'MS',
	'MO',
	'MT',
	'NE',
	'NV',
	'NH',
	'NJ',
	'NM',
	'NY',
	'NC',
	'ND',
	'OH',
	'OK',
	'OR',
	'PA',
	'RI',
	'SC',
	'SD',
	'TN',
	'TX',
	'UT',
	'VT',
	'VA',
	'WA',
	'WV',
	'WI',
	'WY',
	'DC',
	'AS',
	'GU',
	'MP',
	'PR',
	'UM',
	'VI',
];

export const currencies = [
	__( 'Australian Dollar', 'jetpack-forms' ),
	__( 'British Pound', 'jetpack-forms' ),
	__( 'Canadian Dollar', 'jetpack-forms' ),
	__( 'Chinese Yuan', 'jetpack-forms' ),
	__( 'Euro', 'jetpack-forms' ),
	__( 'Japanese Yen', 'jetpack-forms' ),
	__( 'New Zealand Dollar', 'jetpack-forms' ),
	__( 'Swedish Krona', 'jetpack-forms' ),
	__( 'Swiss Franc', 'jetpack-forms' ),
	__( 'US Dollar', 'jetpack-forms' ),
];
