<?php // phpcs:ignore WordPress.Files.FileName.InvalidClassFileName -- Feature entry file, named after the feature, also holds the WPCOM_Scan bootstrap class.
/**
 * An in-wp-admin Protect page for WordPress.com Simple and WoA sites.
 * Prompts for a plan upgrade or activation of Scan.
 *
 * @package automattic/jetpack-mu-wpcom
 */

namespace Automattic\Jetpack\Jetpack_Mu_Wpcom;

require_once __DIR__ . '/../wpcom-hosting-feature-page/class-wpcom-hosting-feature-page.php';

/**
 * Registers the Protect admin page and its wp-build assets.
 */
class WPCOM_Scan extends WPCOM_Hosting_Feature_Page {

	/**
	 * The slug a WoA site's Protect page is expected to take over once Scan is live.
	 */
	const MENU_SLUG = 'jetpack-protect';

	/**
	 * As declared in routes/wpcom-scan/package.json.
	 */
	const WP_BUILD_PAGE = 'wpcom-scan';

	/**
	 * Generated by wp-build in build/pages/wpcom-scan/page-wp-admin.php.
	 */
	const RENDER_CALLBACK = 'jetpack_mu_wpcom_wpcom_scan_wp_admin_render_page';

	/**
	 * Product name, do not translate.
	 */
	const PAGE_TITLE = 'Jetpack Protect';

	/**
	 * Product name, do not translate.
	 */
	const MENU_TITLE = 'Protect';

	/**
	 * Whether the site's plan gives it access to Scan.
	 *
	 * SCAN_SELF_SERVE, not SCAN: SCAN also covers Personal and Premium plans, which run scans
	 * without exposing Scan's UI. It is also what the dashboard's Scan page gates on.
	 *
	 * @return bool
	 */
	public static function has_feature() {
		if ( ! function_exists( 'wpcom_site_has_feature' ) || ! defined( '\WPCOM_Features::SCAN_SELF_SERVE' ) ) {
			return false;
		}

		// Called without a blog ID.
		// WoA sites would pass the local blog ID, which is not the WordPress.com blog ID.
		// wpcom resolves the current site.
		return (bool) wpcom_site_has_feature( \WPCOM_Features::SCAN_SELF_SERVE );
	}
}

add_action( 'init', array( WPCOM_Scan::class, 'init' ) );
