/**
 * External dependencies
 */
import { act, renderHook, waitFor } from '@testing-library/react';
/**
 * Internal dependencies
 */
import { useSyncMedia } from '../index';
/**
 * Types
 */
import type {
	VideoBlockAttributes,
	VideoBlockSetAttributesProps,
} from '../../../blocks/video/types';

const mockUseSelect = jest.fn();
const mockUseDispatch = jest.fn();
const mockUseVideoData = jest.fn();
const mockUseMediaDataUpdate = jest.fn();
const mockUseVideoPosterData = jest.fn();
const mockUploadTrackForGuid = jest.fn();
const mockValidateChapters = jest.fn();
const mockGenerateChaptersFile = jest.fn();

const invalidateResolution = jest.fn();

jest.mock( '@wordpress/block-editor', () => ( { store: 'block-editor-store' } ) );
jest.mock( '@wordpress/core-data', () => ( { store: 'core-store' } ) );
jest.mock( '@wordpress/editor', () => ( { store: 'editor-store' } ) );

jest.mock( '@wordpress/data', () => ( {
	useSelect: ( ...args: unknown[] ) => mockUseSelect( ...args ),
	useDispatch: ( ...args: unknown[] ) => mockUseDispatch( ...args ),
} ) );

jest.mock( '../../use-video-data', () => ( {
	__esModule: true,
	default: ( ...args: unknown[] ) => mockUseVideoData( ...args ),
} ) );

jest.mock( '../../use-video-data-update', () => ( {
	__esModule: true,
	default: ( ...args: unknown[] ) => mockUseMediaDataUpdate( ...args ),
} ) );

jest.mock( '../../use-video-poster-data', () => ( {
	useVideoPosterData: ( ...args: unknown[] ) => mockUseVideoPosterData( ...args ),
} ) );

jest.mock( '../../../../lib/video-tracks', () => ( {
	...jest.requireActual( '../../../../lib/video-tracks' ),
	uploadTrackForGuid: ( ...args: unknown[] ) => mockUploadTrackForGuid( ...args ),
	isAutogeneratedChapterFile: jest.fn(),
} ) );

jest.mock( '../../../../lib/url', () => ( {
	getVideoPressUrl: () => 'https://videopress.com/v/guid123',
} ) );

jest.mock( '../../../../utils/video-chapters/extract-video-chapters', () => ( {
	__esModule: true,
	default: () => [ { title: 'Intro', startTime: '00:00' } ],
} ) );

jest.mock( '../../../../utils/video-chapters/generate-chapters-file', () => ( {
	__esModule: true,
	default: ( ...args: unknown[] ) => mockGenerateChaptersFile( ...args ),
} ) );

jest.mock( '../../../../utils/video-chapters/validate-chapters', () => ( {
	__esModule: true,
	default: ( ...args: unknown[] ) => mockValidateChapters( ...args ),
} ) );

const updateMediaHandler = jest.fn();

const baseAttributes: VideoBlockAttributes = {
	id: 123,
	guid: 'guid123',
	description: 'Chapter 1\n00:00 Intro',
	tracks: [],
};

/**
 * Find the setAttributes call that wrote a `tracks` value, if any.
 *
 * @param {jest.Mock} setAttributes - The setAttributes spy.
 * @return {Array|undefined} The matching call arguments, or undefined.
 */
function findTracksCall( setAttributes: jest.MockedFunction< VideoBlockSetAttributesProps > ) {
	return setAttributes.mock.calls.find(
		( [ arg ] ) => arg && Object.prototype.hasOwnProperty.call( arg, 'tracks' )
	);
}

/**
 * Render the hook through a save transition so the block-attributes => media
 * sync effect fires with `isOverwriteChapterAllowed` already settled to true.
 *
 * @return {object} The renderHook result and the setAttributes spy.
 */
function renderThroughSave() {
	const setAttributes = jest.fn() as jest.MockedFunction< VideoBlockSetAttributesProps >;

	/*
	 * First render: a save is in progress (no transition yet). This also lets
	 * the chapter-detection effect flip `isOverwriteChapterAllowed` to true.
	 */
	mockUseSelect.mockReturnValue( true );
	const utils = renderHook( () => useSyncMedia( baseAttributes, setAttributes ) );

	// Second render: saving has finished -> postHasBeenJustSaved becomes true.
	mockUseSelect.mockReturnValue( false );
	utils.rerender();

	return { ...utils, setAttributes };
}

beforeEach( () => {
	jest.clearAllMocks();

	mockUseSelect.mockReturnValue( false );
	mockUseDispatch.mockReturnValue( {
		invalidateResolution,
		__unstableMarkNextChangeAsNotPersistent: jest.fn(),
	} );
	mockUseVideoData.mockReturnValue( {
		videoData: {},
		isRequestingVideoData: false,
		videoBelongToSite: true,
	} );
	updateMediaHandler.mockResolvedValue( undefined );
	mockUseMediaDataUpdate.mockReturnValue( updateMediaHandler );
	mockUseVideoPosterData.mockReturnValue( { isGeneratingPoster: false } );
	mockValidateChapters.mockReturnValue( true );
	mockGenerateChaptersFile.mockReturnValue( {} );
} );

describe( 'useSyncMedia auto-generated chapter upload', () => {
	it( 'stores the normalized track from a structured upload response and invalidates the embed', async () => {
		mockUploadTrackForGuid.mockResolvedValue( {
			src: 'https://videos.files.wordpress.com/guid123/chapters.vtt',
			kind: 'chapters',
			srclang: 'en',
			label: 'English (auto-generated)',
		} );

		const { setAttributes } = renderThroughSave();

		await waitFor( () => expect( invalidateResolution ).toHaveBeenCalled() );

		const tracksCall = findTracksCall( setAttributes );
		expect( tracksCall ).toBeDefined();
		expect( tracksCall[ 0 ].tracks[ 0 ] ).toMatchObject( {
			kind: 'chapters',
			srcLang: 'en',
			src: 'https://videos.files.wordpress.com/guid123/chapters.vtt',
		} );
	} );

	it( 'short-circuits and surfaces an error when the upload resolves to a non-string error envelope', async () => {
		mockUploadTrackForGuid.mockResolvedValue( { error: 'upload_failed', message: 'nope' } );

		const { setAttributes, result } = renderThroughSave();

		await waitFor( () => expect( mockUploadTrackForGuid ).toHaveBeenCalled() );

		/*
		 * The failed upload must not be stored as a track src, and the embed
		 * resolution must not be invalidated.
		 */
		expect( findTracksCall( setAttributes ) ).toBeUndefined();
		expect( invalidateResolution ).not.toHaveBeenCalled();

		// The failure is surfaced to the consumer rather than silently dropped.
		await waitFor( () => expect( result.current.error ).toBeInstanceOf( Error ) );
		expect( result.current.error?.message ).toBe( 'nope' );
	} );

	it( 'surfaces an error when the upload rejects', async () => {
		mockUploadTrackForGuid.mockRejectedValue( new Error( 'network down' ) );

		const { setAttributes, result } = renderThroughSave();

		await waitFor( () => expect( result.current.error ).toBeInstanceOf( Error ) );
		expect( result.current.error?.message ).toBe( 'network down' );
		expect( findTracksCall( setAttributes ) ).toBeUndefined();
	} );

	it( 'passes the real video duration (ms) to the chapters file generator', async () => {
		mockUseVideoData.mockReturnValue( {
			videoData: { duration: 90000 },
			isRequestingVideoData: false,
			videoBelongToSite: true,
		} );
		mockUploadTrackForGuid.mockResolvedValue(
			'https://videos.files.wordpress.com/guid123/track.vtt'
		);

		renderThroughSave();

		await waitFor( () => expect( mockGenerateChaptersFile ).toHaveBeenCalled() );

		// The regenerated VTT's last cue must end at the real video end, not
		// the generator's 999:59:59 sentinel — matching the syncChapters output.
		expect( mockGenerateChaptersFile ).toHaveBeenCalledWith( baseAttributes.description, 90000 );
	} );

	it( 'falls back to the generator sentinel when the video duration is unknown', async () => {
		mockUploadTrackForGuid.mockResolvedValue(
			'https://videos.files.wordpress.com/guid123/track.vtt'
		);

		renderThroughSave();

		await waitFor( () => expect( mockGenerateChaptersFile ).toHaveBeenCalled() );

		expect( mockGenerateChaptersFile ).toHaveBeenCalledWith(
			baseAttributes.description,
			undefined
		);
	} );

	it( 'stores the uploaded track and invalidates the embed when the upload resolves to a string', async () => {
		mockUploadTrackForGuid.mockResolvedValue(
			'https://videos.files.wordpress.com/guid123/track.vtt'
		);

		const { setAttributes } = renderThroughSave();

		await waitFor( () => expect( invalidateResolution ).toHaveBeenCalled() );

		const tracksCall = findTracksCall( setAttributes );
		expect( tracksCall ).toBeDefined();
		expect( tracksCall[ 0 ].tracks[ 0 ].src ).toBe(
			'https://videos.files.wordpress.com/guid123/track.vtt'
		);
	} );
} );

describe( 'useSyncMedia embed invalidation', () => {
	/**
	 * Render a save transition with an empty description, so the auto-generated
	 * chapter branch is skipped and the field-based invalidation path runs.
	 *
	 * @param {VideoBlockAttributes} attributes - Block attributes to sync.
	 * @return {object} The renderHook result.
	 */
	function renderSaveWithoutChapters( attributes: VideoBlockAttributes ) {
		const setAttributes = jest.fn() as jest.MockedFunction< VideoBlockSetAttributesProps >;

		mockUseSelect.mockReturnValue( true );
		const utils = renderHook( () => useSyncMedia( attributes, setAttributes ) );

		mockUseSelect.mockReturnValue( false );
		utils.rerender();

		return utils;
	}

	it( 'refreshes the player when the rating changes', async () => {
		/*
		 * Raising or lowering the rating adds or removes the age gate, but the
		 * rating is not part of the embed URL, so without an explicit
		 * invalidation the cached preview keeps rendering the stale gate.
		 */
		renderSaveWithoutChapters( { ...baseAttributes, description: '', rating: 'G' } );

		await waitFor( () =>
			expect( invalidateResolution ).toHaveBeenCalledWith( 'getEmbedPreview', [
				'https://videopress.com/v/guid123',
			] )
		);
	} );

	it( 'leaves the player alone for fields the embed does not depend on', async () => {
		renderSaveWithoutChapters( { ...baseAttributes, description: '', duration: 42 } );

		await waitFor( () => expect( updateMediaHandler ).toHaveBeenCalled() );

		// Settle the very promise the hook hangs its invalidation off, so a
		// missing call is a real absence and not an assertion that ran early.
		await act( async () => {
			await updateMediaHandler.mock.results[ 0 ].value;
		} );

		expect( invalidateResolution ).not.toHaveBeenCalled();
	} );
} );
