name: "Repo Gardening"
description: "Assign, manage milestones, for issues and PRs."
inputs:
  github_token:
    description: "GitHub access token"
    required: true
    default: ""
  slack_token:
    description: "Slack Bot access token"
    required: true
    default: ""
  slack_design_channel:
    description: "Slack channel ID where messages for the Design team will be sent"
    required: true
    default: ""
runs:
  using: node12
  main: "src/index.js"
