name: "Repo Gardening"
description: "Assign, manage milestones, for issues and PRs."
inputs:
  github_token:
    description: "GitHub access token"
    required: true
    default: ""
runs:
  using: node12
  main: "src/index.js"
