export const JETPACK_SET_INITIAL_STATE = 'JETPACK_SET_INITIAL_STATE';

export const CONNECT_URL_FETCH = 'CONNECT_URL_FETCH';
export const CONNECT_URL_FETCH_FAIL = 'CONNECT_URL_FETCH_FAIL';
export const CONNECT_URL_FETCH_SUCCESS = 'CONNECT_URL_FETCH_SUCCESS';

export const DISCONNECT_SITE = 'DISCONNECT_SITE';
export const DISCONNECT_SITE_FAIL = 'DISCONNECT_SITE_FAIL';
export const DISCONNECT_SITE_SUCCESS = 'DISCONNECT_SITE_SUCCESS';

export const AUTH_USER_IN_PLACE = 'AUTH_USER_IN_PLACE';
export const AUTH_USER_IN_PLACE_SUCCESS = 'AUTH_USER_IN_PLACE_SUCCESS';

export const UNLINK_USER = 'UNLINK_USER';
export const UNLINK_USER_FAIL = 'UNLINK_USER_FAIL';
export const UNLINK_USER_SUCCESS = 'UNLINK_USER_SUCCESS';

export const USER_CONNECTION_DATA_FETCH = 'USER_CONNECTION_DATA_FETCH';
export const USER_CONNECTION_DATA_FETCH_FAIL = 'USER_CONNECTION_DATA_FETCH_FAIL';
export const USER_CONNECTION_DATA_FETCH_SUCCESS = 'USER_CONNECTION_DATA_FETCH_SUCCESS';

export const SITE_RECONNECT = 'SITE_RECONNECT';
export const SITE_RECONNECT_SUCCESS = 'SITE_RECONNECT_SUCCESS';
export const SITE_RECONNECT_FAIL = 'SITE_RECONNECT_FAIL';

export const USER_TRACKING_SETTINGS_FETCH = 'USER_TRACKING_SETTINGS_FETCH';
export const USER_TRACKING_SETTINGS_FETCH_FAIL = 'USER_TRACKING_SETTINGS_FETCH_FAIL';
export const USER_TRACKING_SETTINGS_FETCH_SUCCESS = 'USER_TRACKING_SETTINGS_FETCH_SUCCESS';
export const USER_TRACKING_SETTINGS_UPDATE = 'USER_TRACKING_SETTINGS_UPDATE';
export const USER_TRACKING_SETTINGS_UPDATE_FAIL = 'USER_TRACKING_SETTINGS_UPDATE_FAIL';
export const USER_TRACKING_SETTINGS_UPDATE_SUCCESS = 'USER_TRACKING_SETTINGS_UPDATE_SUCCESS';

export const JETPACK_MODULES_LIST_FETCH = 'JETPACK_MODULES_LIST_FETCH';
export const JETPACK_MODULES_LIST_FETCH_FAIL = 'JETPACK_MODULES_LIST_FETCH_FAIL';
export const JETPACK_MODULES_LIST_RECEIVE = 'JETPACK_MODULES_LIST_RECEIVE';
export const JETPACK_MODULE_FETCH = 'JETPACK_MODULE_FETCH';
export const JETPACK_MODULE_FETCH_FAIL = 'JETPACK_MODULE_FETCH_FAIL';
export const JETPACK_MODULE_RECEIVE = 'JETPACK_MODULE_RECEIVE';
export const JETPACK_MODULE_ACTIVATE = 'JETPACK_MODULE_ACTIVATE';
export const JETPACK_MODULE_ACTIVATE_SUCCESS = 'JETPACK_MODULE_ACTIVATE_SUCCESS';
export const JETPACK_MODULE_ACTIVATE_FAIL = 'JETPACK_MODULE_ACTIVATE_FAIL';
export const JETPACK_MODULE_DEACTIVATE = 'JETPACK_MODULE_DEACTIVATE';
export const JETPACK_MODULE_DEACTIVATE_FAIL = 'JETPACK_MODULE_DEACTIVATE_FAIL';
export const JETPACK_MODULE_DEACTIVATE_SUCCESS = 'JETPACK_MODULE_DEACTIVATE_SUCCESS';
export const JETPACK_MODULE_UPDATE_OPTIONS = 'JETPACK_MODULE_UPDATE_OPTIONS';
export const JETPACK_MODULE_UPDATE_OPTIONS_FAIL = 'JETPACK_MODULE_UPDATE_OPTIONS_FAIL';
export const JETPACK_MODULE_UPDATE_OPTIONS_SUCCESS = 'JETPACK_MODULE_UPDATE_OPTIONS_SUCCESS';

export const JETPACK_CONNECTION_STATUS_FETCH = 'JETPACK_CONNECTION_STATUS_FETCH';

export const JETPACK_CONNECTION_TEST_FETCH = 'JETPACK_CONNECTION_TEST_FETCH';

export const JETPACK_SITE_CONNECTED_PLUGINS_FETCH = 'JETPACK_SITE_CONNECTED_PLUGINS_FETCH';
export const JETPACK_SITE_CONNECTED_PLUGINS_FETCH_RECEIVE =
	'JETPACK_SITE_CONNECTED_PLUGINS_FETCH_RECEIVE';
export const JETPACK_SITE_CONNECTED_PLUGINS_FETCH_FAIL =
	'JETPACK_SITE_CONNECTED_PLUGINS_FETCH_FAIL';

export const DASHBOARD_PROTECT_COUNT_FETCH = 'DASHBOARD_PROTECT_COUNT_FETCH';
export const DASHBOARD_PROTECT_COUNT_FETCH_FAIL = 'DASHBOARD_PROTECT_COUNT_FETCH_FAIL';
export const DASHBOARD_PROTECT_COUNT_FETCH_SUCCESS = 'DASHBOARD_PROTECT_COUNT_FETCH_SUCCESS';

export const RESET_OPTIONS = 'RESET_OPTIONS';
export const RESET_OPTIONS_FAIL = 'RESET_OPTIONS_FAIL';
export const RESET_OPTIONS_SUCCESS = 'RESET_OPTIONS_SUCCESS';

export const VAULTPRESS_SITE_DATA_FETCH = 'VAULTPRESS_SITE_DATA_FETCH';
export const VAULTPRESS_SITE_DATA_FETCH_FAIL = 'VAULTPRESS_SITE_DATA_FETCH_FAIL';
export const VAULTPRESS_SITE_DATA_FETCH_SUCCESS = 'VAULTPRESS_SITE_DATA_FETCH_SUCCESS';

export const AKISMET_DATA_FETCH = 'AKISMET_DATA_FETCH';
export const AKISMET_DATA_FETCH_FAIL = 'AKISMET_DATA_FETCH_FAIL';
export const AKISMET_DATA_FETCH_SUCCESS = 'AKISMET_DATA_FETCH_SUCCESS';

export const AKISMET_KEY_CHECK_FETCH = 'AKISMET_KEY_CHECK_FETCH';
export const AKISMET_KEY_CHECK_FETCH_FAIL = 'AKISMET_KEY_CHECK_FETCH_FAIL';
export const AKISMET_KEY_CHECK_FETCH_SUCCESS = 'AKISMET_KEY_CHECK_FETCH_SUCCESS';

export const PLUGIN_UPDATES_FETCH = 'PLUGIN_UPDATES_FETCH';
export const PLUGIN_UPDATES_FETCH_FAIL = 'PLUGIN_UPDATES_FETCH_FAIL';
export const PLUGIN_UPDATES_FETCH_SUCCESS = 'PLUGIN_UPDATES_FETCH_SUCCESS';

export const STATS_SWITCH_TAB = 'STATS_SWITCH_TAB';
export const STATS_DATA_FETCH = 'STATS_DATA_FETCH';
export const STATS_DATA_FETCH_FAIL = 'STATS_DATA_FETCH_FAIL';
export const STATS_DATA_FETCH_SUCCESS = 'STATS_DATA_FETCH_SUCCESS';

export const JETPACK_PRODUCTS_FETCH = 'JETPACK_PRODUCTS_FETCH';
export const JETPACK_PRODUCTS_FETCH_RECEIVE = 'JETPACK_PRODUCTS_FETCH_RECEIVE';
export const JETPACK_PRODUCTS_FETCH_FAIL = 'JETPACK_PRODUCTS_FETCH_FAIL';

export const JETPACK_SITE_PRODUCTS_FETCH = 'JETPACK_SITE_PRODUCTS_FETCH';
export const JETPACK_SITE_PRODUCTS_FETCH_FAIL = 'JETPACK_SITE_PRODUCTS_FETCH_FAIL';
export const JETPACK_SITE_PRODUCTS_FETCH_RECEIVE = 'JETPACK_SITE_PRODUCTS_FETCH_RECEIVE';

export const JETPACK_SETTINGS_FETCH = 'JETPACK_SETTINGS_FETCH';
export const JETPACK_SETTINGS_FETCH_RECEIVE = 'JETPACK_SETTINGS_FETCH_RECEIVE';
export const JETPACK_SETTINGS_FETCH_FAIL = 'JETPACK_SETTINGS_FETCH_FAIL';
export const JETPACK_SETTING_UPDATE = 'JETPACK_SETTING_UPDATE';
export const JETPACK_SETTING_UPDATE_SUCCESS = 'JETPACK_SETTING_UPDATE_SUCCESS';
export const JETPACK_SETTING_UPDATE_FAIL = 'JETPACK_SETTING_UPDATE_FAIL';
export const JETPACK_SETTINGS_UPDATE = 'JETPACK_SETTINGS_UPDATE';
export const JETPACK_SETTINGS_UPDATE_FAIL = 'JETPACK_SETTINGS_UPDATE_FAIL';
export const JETPACK_SETTINGS_UPDATE_SUCCESS = 'JETPACK_SETTINGS_UPDATE_SUCCESS';
export const JETPACK_SETTINGS_SET_UNSAVED_FLAG = 'JETPACK_SETTINGS_SET_UNSAVED_FLAG';
export const JETPACK_SETTINGS_CLEAR_UNSAVED_FLAG = 'JETPACK_SETTINGS_CLEAR_UNSAVED_FLAG';

export const JETPACK_SITE_DATA_FETCH = 'JETPACK_SITE_DATA_FETCH';
export const JETPACK_SITE_DATA_FETCH_RECEIVE = 'JETPACK_SITE_DATA_FETCH_RECEIVE';
export const JETPACK_SITE_DATA_FETCH_FAIL = 'JETPACK_SITE_DATA_FETCH_FAIL';
export const JETPACK_SITE_BENEFITS_FETCH = 'JETPACK_SITE_BENEFITS_FETCH';
export const JETPACK_SITE_BENEFITS_FETCH_RECEIVE = 'JETPACK_SITE_BENEFITS_FETCH_RECEIVE';
export const JETPACK_SITE_BENEFITS_FETCH_FAIL = 'JETPACK_SITE_BENEFITS_FETCH_FAIL';
export const JETPACK_SITE_FEATURES_FETCH = 'JETPACK_SITE_FEATURES_FETCH';
export const JETPACK_SITE_FEATURES_FETCH_RECEIVE = 'JETPACK_SITE_FEATURES_FETCH_RECEIVE';
export const JETPACK_SITE_FEATURES_FETCH_FAIL = 'JETPACK_SITE_FEATURES_FETCH_FAIL';
export const JETPACK_SITE_PLANS_FETCH = 'JETPACK_SITE_PLANS_FETCH';
export const JETPACK_SITE_PLANS_FETCH_RECEIVE = 'JETPACK_SITE_PLANS_FETCH_RECEIVE';
export const JETPACK_SITE_PLANS_FETCH_FAIL = 'JETPACK_SITE_PLANS_FETCH_FAIL';
export const JETPACK_SITE_PURCHASES_FETCH = 'JETPACK_SITE_PURCHASES_FETCH';
export const JETPACK_SITE_PURCHASES_FETCH_RECEIVE = 'JETPACK_SITE_PURCHASES_FETCH_RECEIVE';
export const JETPACK_SITE_PURCHASES_FETCH_FAIL = 'JETPACK_SITE_PURCHASES_FETCH_FAIL';

export const JETPACK_SETUP_WIZARD_QUESTIONNAIRE_FETCH = 'JETPACK_SETUP_WIZARD_QUESTIONNAIRE_FETCH';
export const JETPACK_SETUP_WIZARD_QUESTIONNAIRE_FETCH_RECEIVE =
	'JETPACK_SETUP_WIZARD_QUESTIONNAIRE_FETCH_RECEIVE';
export const JETPACK_SETUP_WIZARD_QUESTIONNAIRE_FETCH_FAIL =
	'JETPACK_SETUP_WIZARD_QUESTIONNAIRE_FETCH_FAIL';
export const JETPACK_SETUP_WIZARD_QUESTIONNAIRE_UPDATE =
	'JETPACK_SETUP_WIZARD_QUESTIONNAIRE_UPDATE';
export const JETPACK_SETUP_WIZARD_QUESTIONNAIRE_SAVE = 'JETPACK_SETUP_WIZARD_QUESTIONNAIRE_SAVE';
export const JETPACK_SETUP_WIZARD_QUESTIONNAIRE_SAVE_SUCCESS =
	'JETPACK_SETUP_WIZARD_QUESTIONNAIRE_SAVE_SUCCESS';
export const JETPACK_SETUP_WIZARD_QUESTIONNAIRE_SAVE_FAIL =
	'JETPACK_SETUP_WIZARD_QUESTIONNAIRE_SAVE_FAIL';
export const JETPACK_SETUP_WIZARD_STATUS_UPDATE = 'JETPACK_SETUP_WIZARD_STATUS_UPDATE';
export const JETPACK_SETUP_WIZARD_STATUS_UPDATE_SUCCESS =
	'JETPACK_SETUP_WIZARD_STATUS_UPDATE_SUCCESS';
export const JETPACK_SETUP_WIZARD_STATUS_UPDATE_FAIL = 'JETPACK_SETUP_WIZARD_STATUS_UPDATE_FAIL';

export const JETPACK_RECOMMENDATIONS_DATA_ADD_SELECTED_RECOMMENDATION =
	'JETPACK_RECOMMENDATIONS_DATA_ADD_SELECTED_RECOMMENDATION';
export const JETPACK_RECOMMENDATIONS_DATA_ADD_SKIPPED_RECOMMENDATION =
	'JETPACK_RECOMMENDATIONS_DATA_ADD_SKIPPED_RECOMMENDATION';
export const JETPACK_RECOMMENDATIONS_DATA_FETCH = 'JETPACK_RECOMMENDATIONS_DATA_FETCH';
export const JETPACK_RECOMMENDATIONS_DATA_FETCH_RECEIVE =
	'JETPACK_RECOMMENDATIONS_DATA_FETCH_RECEIVE';
export const JETPACK_RECOMMENDATIONS_DATA_FETCH_FAIL = 'JETPACK_RECOMMENDATIONS_DATA_FETCH_FAIL';
export const JETPACK_RECOMMENDATIONS_DATA_UPDATE = 'JETPACK_RECOMMENDATIONS_DATA_UPDATE';
export const JETPACK_RECOMMENDATIONS_DATA_SAVE = 'JETPACK_RECOMMENDATIONS_DATA_SAVE';
export const JETPACK_RECOMMENDATIONS_DATA_SAVE_SUCCESS =
	'JETPACK_RECOMMENDATIONS_DATA_SAVE_SUCCESS';
export const JETPACK_RECOMMENDATIONS_DATA_SAVE_FAIL = 'JETPACK_RECOMMENDATIONS_DATA_SAVE_FAIL';
export const JETPACK_RECOMMENDATIONS_STEP_UPDATE = 'JETPACK_RECOMMENDATIONS_STEP_UPDATE';
export const JETPACK_RECOMMENDATIONS_STEP_UPDATE_SUCCESS =
	'JETPACK_RECOMMENDATIONS_STEP_UPDATE_SUCCESS';
export const JETPACK_RECOMMENDATIONS_STEP_UPDATE_FAIL = 'JETPACK_RECOMMENDATIONS_STEP_UPDATE_FAIL';
export const JETPACK_RECOMMENDATIONS_UPSELL_FETCH = 'JETPACK_RECOMMENDATIONS_UPSELL_FETCH';
export const JETPACK_RECOMMENDATIONS_UPSELL_FETCH_RECEIVE =
	'JETPACK_RECOMMENDATIONS_UPSELL_FETCH_RECEIVE';
export const JETPACK_RECOMMENDATIONS_UPSELL_FETCH_FAIL =
	'JETPACK_RECOMMENDATIONS_UPSELL_FETCH_FAIL';

export const JETPACK_ACTION_NOTICES_DISMISS = 'JETPACK_ACTION_NOTICES_DISMISS';

export const JETPACK_NOTICES_DISPATCH_TYPE = 'JETPACK_NOTICES_DISPATCH_TYPE';
export const JETPACK_NOTICES_DISMISS = 'JETPACK_NOTICES_DISMISS';
export const JETPACK_NOTICES_DISMISS_FAIL = 'JETPACK_NOTICES_DISMISS_FAIL';
export const JETPACK_NOTICES_DISMISS_SUCCESS = 'JETPACK_NOTICES_DISMISS_SUCCESS';

export const JETPACK_PLUGINS_DATA_FETCH = 'JETPACK_PLUGINS_DATA_FETCH';
export const JETPACK_PLUGINS_DATA_FETCH_RECEIVE = 'JETPACK_PLUGINS_DATA_FETCH_RECEIVE';
export const JETPACK_PLUGINS_DATA_FETCH_FAIL = 'JETPACK_PLUGINS_DATA_FETCH_FAIL';

export const JETPACK_SEARCH_TERM = 'JETPACK_SEARCH_TERM';
export const JETPACK_SEARCH_FOCUS = 'JETPACK_SEARCH_FOCUS';
export const JETPACK_SEARCH_BLUR = 'JETPACK_SEARCH_BLUR';

export const SET_PLAN_DURATION = 'SET_PLAN_DURATION';

export const JETPACK_MARKETING_SUBMIT_DISCONNECT_SURVEY =
	'JETPACK_MARKETING_SUBMIT_DISCONNECT_SURVEY';
export const JETPACK_MARKETING_SUBMIT_DISCONNECT_SURVEY_SUCCESS =
	'JETPACK_MARKETING_SUBMIT_DISCONNECT_SURVEY_SUCCESS';
export const JETPACK_MARKETING_SUBMIT_DISCONNECT_SURVEY_FAIL =
	'JETPACK_MARKETING_SUBMIT_DISCONNECT_SURVEY_FAIL';

export const DEV_CARD_DISPLAY = 'DEV_CARD_DISPLAY';
export const DEV_CARD_HIDE = 'DEV_CARD_HIDE';
export const MOCK_SWITCH_USER_PERMISSIONS = 'MOCK_SWITCH_USER_PERMISSIONS';
export const MOCK_SWITCH_THREATS = 'MOCK_SWITCH_THREATS';

export const REWIND_STATUS_FETCH = 'REWIND_STATUS_FETCH';
export const REWIND_STATUS_FETCH_RECEIVE = 'REWIND_STATUS_FETCH_RECEIVE';
export const REWIND_STATUS_FETCH_FAIL = 'REWIND_STATUS_FETCH_FAIL';

export const MOCK_SWITCH_REWIND_STATE = 'MOCK_SWITCH_REWIND_STATE';

export const SCAN_STATUS_FETCH = 'SCAN_STATUS_FETCH';
export const SCAN_STATUS_FETCH_RECEIVE = 'SCAN_STATUS_FETCH_RECEIVE';
export const SCAN_STATUS_FETCH_FAIL = 'SCAN_STATUS_FETCH_FAIL';

export const MOCK_SWITCH_SCAN_STATE = 'MOCK_SWITCH_SCAN_STATE';

export const JETPACK_SITE_VERIFY_GOOGLE_STATUS_FETCH = 'JETPACK_SITE_VERIFY_GOOGLE_STATUS_FETCH';
export const JETPACK_SITE_VERIFY_GOOGLE_STATUS_FETCH_FAIL =
	'JETPACK_SITE_VERIFY_GOOGLE_STATUS_FETCH_FAIL';
export const JETPACK_SITE_VERIFY_GOOGLE_STATUS_FETCH_SUCCESS =
	'JETPACK_SITE_VERIFY_GOOGLE_STATUS_FETCH_SUCCESS';

export const JETPACK_SITE_VERIFY_GOOGLE_VERIFY_FETCH = 'JETPACK_SITE_VERIFY_GOOGLE_VERIFY_FETCH';
export const JETPACK_SITE_VERIFY_GOOGLE_VERIFY_FETCH_FAIL =
	'JETPACK_SITE_VERIFY_GOOGLE_VERIFY_FETCH_FAIL';
export const JETPACK_SITE_VERIFY_GOOGLE_VERIFY_FETCH_SUCCESS =
	'JETPACK_SITE_VERIFY_GOOGLE_VERIFY_FETCH_SUCCESS';
export const JETPACK_SITE_VERIFY_GOOGLE_REQUEST = 'JETPACK_SITE_VERIFY_GOOGLE_REQUEST';
export const JETPACK_SITE_VERIFY_GOOGLE_REQUEST_SUCCESS =
	'JETPACK_SITE_VERIFY_GOOGLE_REQUEST_SUCCESS';
export const JETPACK_SITE_VERIFY_GOOGLE_REQUEST_FAIL = 'JETPACK_SITE_VERIFY_GOOGLE_REQUEST_FAIL';

export const SITE_CHECKLIST_RECEIVE = 'SITE_CHECKLIST_RECEIVE';
export const SITE_CHECKLIST_REQUEST = 'SITE_CHECKLIST_REQUEST';

export const JETPACK_MOBILE_LOGIN_SEND_LOGIN_EMAIL = 'JETPACK_MOBILE_LOGIN_SEND_LOGIN_EMAIL';
export const JETPACK_MOBILE_LOGIN_SEND_LOGIN_EMAIL_SUCCESS =
	'JETPACK_MOBILE_LOGIN_SEND_LOGIN_EMAIL_SUCCESS';
export const JETPACK_MOBILE_LOGIN_SEND_LOGIN_EMAIL_FAIL =
	'JETPACK_MOBILE_LOGIN_SEND_LOGIN_EMAIL_FAIL';

export const JETPACK_LICENSING_ERROR_UPDATE = 'JETPACK_LICENSING_ERROR_UPDATE';
