name: "Deepen to merge-base"
description: "Deepens a checkout to the merge-base with another branch."
inputs:
  head:
    description: "Branch (or other git refspec) to be checked out."
    default: ${{ github.event.pull_request.head.sha }}
  branch:
    description: "Branch (or other git refspec) to deepen with respect to."
    default: ${{ github.event.pull_request.base.sha }}
  initial-depth:
    description: "Initial depth to check out."
    default: 10
outputs:
  merge-base:
    description: "The merge-base sha found."
    value: ${{ steps.end.outputs.merge-base }}
runs:
  using: composite
  steps:
    - name: "Deepen"
      shell: bash
      run: |
        depth=${{ inputs.initial-depth }}
        echo "::group::Initial fetch to $depth"
        /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=$depth origin ${{ inputs.head }} ${{ inputs.branch }}
        echo "::endgroup::"
        while ! /usr/bin/git merge-base ${{ inputs.head }} ${{ inputs.branch }} >/dev/null 2>&1; do
          depth=$((depth * 2))
          echo "::group::Deepen to $depth"
          /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=$depth origin ${{ inputs.head }} ${{ inputs.branch }}
          echo "::endgroup::"
        done
    - name: "Check out new head"
      shell: bash
      run: /usr/bin/git checkout ${{ inputs.head }}
    - name: "Output"
      id: end
      shell: bash
      run: |
        MERGE_BASE=$( /usr/bin/git merge-base HEAD ${{ inputs.branch }} )
        echo "Merge base is $MERGE_BASE"
        echo "::set-output name=merge-base::$MERGE_BASE"

