name: Npmjs auto-publisher

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - uses: actions/setup-node@v6
        with:
          # NPM version shouldn't matter, just use the LTS.
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'

      - name: Publish
        run: |
          npm install -g npm@latest
          npm publish --access public
