name: "Test report dispatch"
description: "Trigger a test report workflow in jetpack-e2e-report repo actions"
inputs:
  token:
    required: true
    description: "The user token used to authenticate the dispatch call."
  report_name:
    required: false
    description: "The name of the report to group multiple runs under."

runs:
  using: composite
  steps:
    - name: Trigger test report workflow
      shell: bash
      env:
        TOKEN: ${{ inputs.token }}
        PR_TITLE: ${{ github.event.pull_request.title }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
      run: |
        if [ "$GITHUB_EVENT_NAME" == pull_request ]; then
        	BRANCH=$GITHUB_HEAD_REF
          EVENT_NAME="$PR_NUMBER: $PR_TITLE"
        else
        	BRANCH=${GITHUB_REF:11}
          EVENT_NAME="Run $GITHUB_RUN_ID"
        fi

        curl -X POST https://api.github.com/repos/automattic/jetpack-e2e-reports/dispatches \
        -H "Accept: application/vnd.github.v3+json" \
        -u "user:$TOKEN" \
        --data "{\"event_type\": \"$EVENT_NAME\",
        \"client_payload\": {
        \"repository\": \"$GITHUB_REPOSITORY\",
        \"run_id\": \"$GITHUB_RUN_ID\",
        \"run_number\": \"$GITHUB_RUN_NUMBER\",
        \"branch\": \"$BRANCH\",
        \"pr_title\": \"$PR_TITLE\",
        \"pr_number\": \"$PR_NUMBER\"
        }}"
