// Map of eslint-plugin-es rules to MDN compat-data paths.
// Values are either a path, an array of paths, true to always enable the rule, or false to always disable it.
module.exports = {
	// ES2021
	'no-logical-assignment-operators': [
		'javascript.operators.logical_and_assignment',
		'javascript.operators.logical_nullish_assignment',
		'javascript.operators.logical_or_assignment',
	],
	'no-numeric-separators': 'javascript.grammar.numeric_separators',
	'no-promise-any': [ 'javascript.builtins.AggregateError', 'javascript.builtins.Promise.any' ],
	'no-weakrefs': [ 'javascript.builtins.WeakRef', 'javascript.builtins.FinalizationRegistry' ],

	// ES2020
	'no-bigint': [
		'javascript.builtins.BigInt',
		'javascript.builtins.BigInt64Array',
		'javascript.builtins.BigUint64Array',
	],
	'no-dynamic-import': 'javascript.statements.import.dynamic_import',
	'no-export-ns-from': 'javascript.statements.export.namespace',
	'no-global-this': 'javascript.builtins.globalThis',
	'no-import-meta': 'javascript.statements.import_meta',
	'no-nullish-coalescing-operators': 'javascript.operators.nullish_coalescing',
	'no-optional-chaining': 'javascript.operators.optional_chaining',
	'no-promise-all-settled': 'javascript.builtins.Promise.allSettled',

	// ES2019
	'no-json-superset': 'javascript.builtins.JSON.json_superset',
	'no-object-fromentries': 'javascript.builtins.Object.fromEntries',
	'no-optional-catch-binding': 'javascript.statements.try_catch.optional_catch_binding',
	'no-regexp-unicode-property-escapes-2019': false, // No support data in MDN separate from no-regexp-unicode-property-escapes?

	// ES2018
	'no-async-iteration': [
		'javascript.operators.async_generator_function',
		'javascript.statements.async_generator_function',
	],
	'no-malformed-template-literals':
		'javascript.grammar.template_literals.template_literal_revision',
	'no-regexp-lookbehind-assertions': 'javascript.builtins.RegExp.lookbehind_assertion',
	'no-regexp-named-capture-groups': 'javascript.builtins.RegExp.named_capture_groups',
	'no-regexp-s-flag': 'javascript.builtins.RegExp.dotAll',
	'no-regexp-unicode-property-escapes': 'javascript.builtins.RegExp.property_escapes',
	'no-rest-spread-properties': [
		'javascript.operators.object_initializer.spread_properties',
		'javascript.operators.spread.spread_in_object_literals',
	],

	// ES2017
	'no-async-functions': [
		'javascript.operators.async_function',
		'javascript.statements.async_function',
	],
	'no-atomics': 'javascript.builtins.Atomics',
	'no-object-entries': 'javascript.builtins.Object.entries',
	'no-object-getownpropertydescriptors': 'javascript.builtins.Object.getOwnPropertyDescriptors',
	'no-object-values': 'javascript.builtins.Object.values',
	'no-shared-array-buffer': 'javascript.builtins.SharedArrayBuffer',
	'no-trailing-function-commas': [
		'javascript.grammar.trailing_commas.trailing_commas_in_functions',
		'javascript.functions.arrow_functions.trailing_comma',
		'javascript.operators.function.trailing_comma',
		'javascript.operators.generator_function.trailing_comma',
		'javascript.statements.function.trailing_comma_in_parameters',
		'javascript.statements.generator_function.trailing_comma_in_parameters',
	],

	// ES2016
	'no-exponential-operators': 'javascript.operators.exponentiation',

	// ES2015
	'no-array-from': 'javascript.builtins.Array.from',
	'no-array-of': 'javascript.builtins.Array.of',
	'no-arrow-functions': 'javascript.functions.arrow_functions',
	'no-binary-numeric-literals': 'javascript.grammar.binary_numeric_literals',
	'no-block-scoped-functions': 'javascript.functions.block_level_functions',
	'no-block-scoped-variables': [ 'javascript.statements.const', 'javascript.statements.let' ],
	'no-classes': 'javascript.classes',
	'no-computed-properties': [
		'javascript.operators.object_initializer.computed_property_names',
		'javascript.operators.destructuring.computed_property_names',
		'javascript.functions.get.computed_property_names',
		'javascript.functions.set.computed_property_names',
	],
	'no-default-parameters': 'javascript.functions.default_parameters',
	'no-destructuring': 'javascript.operators.destructuring',
	'no-for-of-loops': 'javascript.statements.for_of',
	'no-generators': [
		'javascript.operators.generator_function',
		'javascript.statements.generator_function',
	],
	'no-map': 'javascript.builtins.Map',
	'no-math-acosh': 'javascript.builtins.Math.acosh',
	'no-math-asinh': 'javascript.builtins.Math.asinh',
	'no-math-atanh': 'javascript.builtins.Math.atanh',
	'no-math-cbrt': 'javascript.builtins.Math.cbrt',
	'no-math-clz32': 'javascript.builtins.Math.clz32',
	'no-math-cosh': 'javascript.builtins.Math.cosh',
	'no-math-expm1': 'javascript.builtins.Math.expm1',
	'no-math-fround': 'javascript.builtins.Math.fround',
	'no-math-hypot': 'javascript.builtins.Math.hypot',
	'no-math-imul': 'javascript.builtins.Math.imul',
	'no-math-log10': 'javascript.builtins.Math.log10',
	'no-math-log1p': 'javascript.builtins.Math.log1p',
	'no-math-log2': 'javascript.builtins.Math.log2',
	'no-math-sign': 'javascript.builtins.Math.sign',
	'no-math-sinh': 'javascript.builtins.Math.sinh',
	'no-math-tanh': 'javascript.builtins.Math.tanh',
	'no-math-trunc': 'javascript.builtins.Math.trunc',
	'no-modules': [ 'javascript.statements.import', 'javascript.statements.export' ],
	'no-new-target': 'javascript.operators.new_target',
	'no-number-epsilon': 'javascript.builtins.Number.EPSILON',
	'no-number-isfinite': 'javascript.builtins.Number.isFinite',
	'no-number-isinteger': 'javascript.builtins.Number.isInteger',
	'no-number-isnan': 'javascript.builtins.Number.isNaN',
	'no-number-issafeinteger': 'javascript.builtins.Number.isSafeInteger',
	'no-number-maxsafeinteger': 'javascript.builtins.Number.MAX_SAFE_INTEGER',
	'no-number-minsafeinteger': 'javascript.builtins.Number.MIN_SAFE_INTEGER',
	'no-number-parsefloat': 'javascript.builtins.Number.parseFloat',
	'no-number-parseint': 'javascript.builtins.Number.parseInt',
	'no-object-assign': 'javascript.builtins.Object.assign',
	'no-object-getownpropertysymbols': 'javascript.builtins.Object.getOwnPropertySymbols',
	'no-object-is': 'javascript.builtins.Object.is',
	'no-object-setprototypeof': 'javascript.builtins.Object.setPrototypeOf',
	'no-object-super-properties': 'javascript.operators.super',
	'no-octal-numeric-literals': 'javascript.grammar.octal_numeric_literals',
	'no-promise': 'javascript.builtins.Promise',
	'no-property-shorthands': [
		'javascript.grammar.shorthand_object_literals',
		'javascript.operators.object_initializer.shorthand_method_names',
		'javascript.operators.object_initializer.shorthand_property_names',
	],
	'no-proxy': 'javascript.builtins.Proxy',
	'no-reflect': 'javascript.builtins.Reflect',
	'no-regexp-u-flag': 'javascript.builtins.RegExp.unicode',
	'no-regexp-y-flag': 'javascript.builtins.RegExp.sticky',
	'no-rest-parameters': 'javascript.functions.rest_parameters',
	'no-set': 'javascript.builtins.Set',
	'no-spread-elements': [
		'javascript.operators.spread.spread_in_arrays',
		'javascript.operators.spread.spread_in_function_calls',
	],
	'no-string-fromcodepoint': 'javascript.builtins.String.fromCodePoint',
	'no-string-raw': 'javascript.builtins.String.raw',
	'no-subclassing-builtins': false, // No support data.
	'no-symbol': 'javascript.builtins.Symbol',
	'no-template-literals': 'javascript.grammar.template_literals',
	'no-typed-arrays': [
		'javascript.builtins.Int8Array',
		'javascript.builtins.Uint8Array',
		'javascript.builtins.Uint8ClampedArray',
		'javascript.builtins.Int16Array',
		'javascript.builtins.Uint16Array',
		'javascript.builtins.Int32Array',
		'javascript.builtins.Uint32Array',
		'javascript.builtins.Float32Array',
		'javascript.builtins.Float64Array',
		'javascript.builtins.DataView',
	],
	'no-unicode-codepoint-escapes': [
		'javascript.grammar.unicode_point_escapes',
		'javascript.builtins.String.unicode_code_point_escapes',
	],
	'no-weak-map': 'javascript.builtins.WeakMap',
	'no-weak-set': 'javascript.builtins.WeakSet',

	// ES5
	'no-accessor-properties': 'javascript.operators.property_accessors',
	'no-array-isarray': 'javascript.builtins.Array.isArray',
	'no-date-now': 'javascript.builtins.Date.now',
	'no-json': 'javascript.builtins.JSON',
	'no-keyword-properties': false, // No support data.
	'no-object-defineproperties': 'javascript.builtins.Object.defineProperties',
	'no-object-defineproperty': 'javascript.builtins.Object.defineProperty',
	'no-object-freeze': 'javascript.builtins.Object.freeze',
	'no-object-getownpropertydescriptor': 'javascript.builtins.Object.getOwnPropertyDescriptor',
	'no-object-getownpropertynames': 'javascript.builtins.Object.getOwnPropertyNames',
	'no-object-getprototypeof': 'javascript.builtins.Object.getPrototypeOf',
	'no-object-isextensible': 'javascript.builtins.Object.isExtensible',
	'no-object-isfrozen': 'javascript.builtins.Object.isFrozen',
	'no-object-issealed': 'javascript.builtins.Object.isSealed',
	'no-object-keys': 'javascript.builtins.Object.keys',
	'no-object-preventextensions': 'javascript.builtins.Object.preventExtensions',
	'no-object-seal': 'javascript.builtins.Object.seal',
	'no-trailing-commas': [
		'javascript.grammar.trailing_commas',
		'javascript.grammar.trailing_commas.trailing_commas_in_object_literals',
	],
};
