/**
 * External dependencies
 */
import { QueryClientProvider } from '@tanstack/react-query';
import {
	Button,
	DropZone,
	Modal,
	Notice,
	__experimentalConfirmDialog as ConfirmDialog, // eslint-disable-line @wordpress/no-unsafe-wp-apis
} from '@wordpress/components';
import { useCallback, useEffect, useMemo, useReducer, useRef, useState } from '@wordpress/element';
import { __, isRTL, sprintf } from '@wordpress/i18n';
import { chevronLeft, chevronRight, plus, upload } from '@wordpress/icons';
import debugFactory from 'debug';
/**
 * Internal dependencies
 */
import { fetchTrackContentForGuid, SUPPORTED_CAPTION_FORMATS } from '../../lib/video-tracks';
import { CAPTION_TRACK_META } from '../../lib/video-tracks/caption-tracks';
import {
	captionBlocksToCues,
	getCaptionCueValidationErrors,
	parseCaptionTextInput,
	parseTimestampToSeconds,
	serializeCuesToWebVtt,
} from '../../lib/video-tracks/cues';
import {
	canonicalizeLanguageTag,
	formatLanguageTagForDisplay,
	getManualLanguageTagFromTrackKey,
	getLanguageDisplayName,
	getSiteLanguageTag,
} from '../../lib/video-tracks/language';
import { registerCaptionCueBlock } from './caption-cue-block';
import { CaptionEditorContext } from './caption-editor-context';
import CaptionPreviewPlayer from './caption-preview-player';
import ManualEditor from './manual-editor';
import { createCaptionManagerQueryClient } from './query-client';
import {
	buildCaptionTrackPayload,
	buildTrackRows,
	createCueBlock,
	createCueBlocksFromCaptionTrack,
	createCueBlocksFromTrackText,
	createEmptyCueBlocks,
	DEFAULT_KIND,
	emptyManualTrack,
	emptyUploadForm,
	findCaptionTrackForManualTrack,
	getCueValidationNoticeMessage,
	getManualTrackFromCaptionTrack,
	getSourceTrackFromCaptionTrack,
	getTrackKey,
	getTrackLanguageName,
	isAcceptedTrackFile,
	isAutoGeneratedTrack,
	isListableCaptionTrack,
	isMatchingSubtitleTrackLanguage,
	isSubtitleTrackKind,
	SUPPORTED_CAPTION_FORMATS_LABEL,
} from './track-helpers';
import TrackList from './track-list';
import UploadWorkspace from './upload-workspace';
import { useCaptionTracks } from './use-caption-tracks';
import { useTrackMutations } from './use-track-mutations';
import { useVideoTracks } from './use-video-tracks';
import {
	hasUnsavedManualEdits,
	initialWorkspaceState,
	workspaceReducer,
} from './workspace-reducer';
import './style.scss';
/**
 * Types
 */
import type { CaptionPreviewPlayerHandle } from './caption-preview-player';
import type { ManualTrack, NoticeState } from './track-helpers';
import type { TrackListBusy } from './track-list';
import type { CaptionManagerModalProps } from './types';
import type { SavedCaptionTrack } from '../../lib/video-tracks/caption-tracks';
import type { VideoTextTrack } from '../../lib/video-tracks/types';
import type { ReactElement } from 'react';

const debug = debugFactory( 'videopress:caption-manager-modal' );

type ConfirmationState = {
	message: string;
	confirmLabel: string;
	onConfirm: () => void;
};

/**
 * Shared VideoPress caption manager modal.
 *
 * The outer component owns the environment (query client, cue block
 * registration); the inner one owns the modal itself.
 *
 * @param props - Component props (see {@link CaptionManagerModalProps}).
 * @return Caption manager modal.
 */
export default function CaptionManagerModal( props: CaptionManagerModalProps ): ReactElement {
	const [ queryClient ] = useState( createCaptionManagerQueryClient );
	/*
	 * Register on first mount rather than at import time, so bundles that
	 * merely import the modal don't mutate the global block registry.
	 * A lazy state initializer runs the (idempotent) registration exactly once.
	 */
	useState( registerCaptionCueBlock );

	return (
		<QueryClientProvider client={ queryClient }>
			<CaptionManagerModalInner { ...props } />
		</QueryClientProvider>
	);
}

/**
 * The caption manager modal shell: owns the workspace state machine, notices,
 * confirmations, and the mutation flows, and composes the track list, upload
 * form, and manual editor views.
 *
 * @param props                - Component props.
 * @param props.isOpen         - Whether the modal is open.
 * @param props.guid           - VideoPress GUID.
 * @param props.title          - Optional video title.
 * @param props.videoSrc       - Optional preview video source.
 * @param props.poster         - Optional preview poster image.
 * @param props.isPrivate      - Whether the video is private, so previews need a playback token.
 * @param props.tracks         - Track list already known to the host.
 * @param props.onClose        - Close handler.
 * @param props.onTracksChange - Called with the updated track list.
 * @return The modal, or null while closed.
 */
function CaptionManagerModalInner( {
	isOpen,
	guid,
	title,
	videoSrc,
	poster,
	isPrivate,
	tracks = [],
	onClose,
	onTracksChange,
}: CaptionManagerModalProps ): ReactElement | null {
	const addTrackButtonRef = useRef< HTMLButtonElement >( null );
	const playerRef = useRef< CaptionPreviewPlayerHandle >( null );
	const pendingFocusClientIdRef = useRef< string | null >( null );
	// Monotonic id source for workspace instances; see workspace-reducer.ts.
	const requestIdRef = useRef( 0 );
	const nextRequestId = useCallback( () => {
		requestIdRef.current += 1;
		return requestIdRef.current;
	}, [] );

	const [ workspace, dispatch ] = useReducer( workspaceReducer, initialWorkspaceState );
	const workspaceRef = useRef( workspace );
	workspaceRef.current = workspace;
	const [ notice, setNotice ] = useState< NoticeState >( null );
	const [ confirmation, setConfirmation ] = useState< ConfirmationState | null >( null );
	const [ currentTime, setCurrentTime ] = useState( 0 );
	const currentTimeRef = useRef( 0 );

	const handleCurrentTimeChange = useCallback( ( seconds: number ) => {
		currentTimeRef.current = seconds;
		setCurrentTime( seconds );
	}, [] );

	// Editor-wide bits the cue blocks can't receive as props; see caption-editor-context.ts.
	const editorContext = useMemo(
		() => ( {
			getCurrentTime: () => currentTimeRef.current,
			pendingFocusClientIdRef,
		} ),
		[]
	);

	const { managedTracks, setManagedTracks, previewAspectRatio } = useVideoTracks( {
		guid,
		isOpen,
		tracks,
		onError: () =>
			setNotice( {
				status: 'error',
				message: __(
					'Couldn’t load the latest track list for this video. It may be incomplete.',
					'jetpack-videopress-pkg'
				),
			} ),
	} );
	const { captionTracks, setCaptionTracks, isLoadingCaptionTracks, invalidateCaptionTracks } =
		useCaptionTracks( {
			guid,
			isOpen,
			onError: () =>
				setNotice( {
					status: 'error',
					message: __(
						'Couldn’t load saved subtitle drafts. Any existing drafts may not appear.',
						'jetpack-videopress-pkg'
					),
				} ),
		} );

	const {
		isSavingUpload,
		isSavingCaptionTrack,
		isPublishing,
		deletingTrackKey,
		downloadingTrackKey,
		uploadSubtitleFile,
		publishManualTrack,
		saveCaptionTrackRecord,
		deleteManagedTrack,
		deleteDraftTrack,
		downloadTrack,
	} = useTrackMutations( {
		guid,
		managedTracks,
		setManagedTracks,
		setCaptionTracks,
		invalidateCaptionTracks,
		onTracksChange,
		setNotice,
	} );

	// Reset to the track list whenever the modal opens.
	useEffect( () => {
		if ( isOpen ) {
			dispatch( { type: 'RESET', requestId: nextRequestId() } );
			setNotice( null );
			setConfirmation( null );
		}
	}, [ isOpen, nextRequestId ] );

	/*
	 * Place initial focus deliberately: the "Add track" button in the list view
	 * (the editor workspaces focus their own container on mount), so opening
	 * the modal never grabs the close button.
	 */
	useEffect( () => {
		if ( isOpen && workspace.view === 'tracks' ) {
			addTrackButtonRef.current?.focus();
		}
	}, [ isOpen, workspace.view ] );

	const visibleCaptionTracks = useMemo(
		() => captionTracks.filter( isListableCaptionTrack ),
		[ captionTracks ]
	);
	const visibleManagedTracks = useMemo(
		() => managedTracks.filter( track => isSubtitleTrackKind( track.kind ) ),
		[ managedTracks ]
	);

	/*
	 * Local caption-track drafts that aren't yet published to VideoPress. These
	 * join the same track list as the managed tracks, marked with a Draft badge.
	 */
	const draftCaptionTracks = useMemo(
		() =>
			visibleCaptionTracks.filter(
				captionTrack =>
					captionTrack.status === 'draft' &&
					! visibleManagedTracks.some( track =>
						isMatchingSubtitleTrackLanguage(
							track,
							captionTrack.meta[ CAPTION_TRACK_META.srcLang ]
						)
					)
			),
		[ visibleCaptionTracks, visibleManagedTracks ]
	);

	const trackRows = useMemo(
		() => buildTrackRows( visibleManagedTracks, draftCaptionTracks ),
		[ visibleManagedTracks, draftCaptionTracks ]
	);

	/*
	 * Default language for a new track: the site language, unless a track already
	 * exists for it — then leave the picker empty so the user chooses a free one.
	 */
	const defaultLanguageTag = useMemo( () => {
		const usedTags = new Set< string >();
		visibleManagedTracks.forEach( track => {
			const tag =
				getManualLanguageTagFromTrackKey( track.srcLang ) ||
				canonicalizeLanguageTag( track.srcLang );
			if ( tag ) {
				usedTags.add( tag );
			}
		} );
		visibleCaptionTracks.forEach( captionTrack => {
			const tag = captionTrack.meta[ CAPTION_TRACK_META.srcLang ];
			if ( tag ) {
				usedTags.add( tag );
			}
		} );

		const siteLanguage = getSiteLanguageTag();
		return usedTags.has( siteLanguage ) ? '' : siteLanguage;
	}, [ visibleManagedTracks, visibleCaptionTracks ] );

	const editorCues = useMemo(
		() => ( workspace.view === 'manual' ? captionBlocksToCues( workspace.cueBlocks ) : [] ),
		[ workspace ]
	);

	/*
	 * Parse each cue's timestamps once per cue change so the per-timeupdate
	 * lookups below compare plain numbers instead of re-parsing the strings.
	 */
	const cueRanges = useMemo(
		() =>
			editorCues.map( cue => ( {
				start: parseTimestampToSeconds( cue.startTime ),
				end: parseTimestampToSeconds( cue.endTime ),
				text: cue.text,
			} ) ),
		[ editorCues ]
	);

	const activeCueText = useMemo( () => {
		const activeCue = cueRanges.find(
			( { start, end } ) =>
				start !== null && end !== null && currentTime >= start && currentTime <= end
		);
		return activeCue?.text;
	}, [ cueRanges, currentTime ] );

	const cueStartTimes = useMemo(
		() =>
			cueRanges
				.map( ( { start } ) => start )
				.filter( ( start ): start is number => start !== null )
				.sort( ( a, b ) => a - b ),
		[ cueRanges ]
	);

	const resetToTrackList = useCallback( () => {
		dispatch( { type: 'RESET', requestId: nextRequestId() } );
		setNotice( null );
	}, [ nextRequestId ] );

	/*
	 * Run an action behind a discard confirmation when the manual editor holds
	 * unsaved work; otherwise run it directly.
	 */
	const confirmDiscardThen = useCallback( ( action: () => void ) => {
		if ( ! hasUnsavedManualEdits( workspaceRef.current ) ) {
			action();
			return;
		}

		setConfirmation( {
			message: __( 'Discard unsaved subtitle changes?', 'jetpack-videopress-pkg' ),
			confirmLabel: __( 'Discard', 'jetpack-videopress-pkg' ),
			onConfirm: action,
		} );
	}, [] );

	const handleRequestClose = useCallback(
		() => confirmDiscardThen( onClose ),
		[ confirmDiscardThen, onClose ]
	);

	const handleBackToTracks = useCallback(
		() => confirmDiscardThen( resetToTrackList ),
		[ confirmDiscardThen, resetToTrackList ]
	);

	const loadTrackText = useCallback(
		async ( track: VideoTextTrack ) => {
			const content = await fetchTrackContentForGuid( track, guid );
			if ( ! content ) {
				throw new Error( 'Track content was empty.' );
			}
			return createCueBlocksFromTrackText( content );
		},
		[ guid ]
	);

	const startManualTrack = useCallback(
		async ( sourceTrack: VideoTextTrack | null = null ) => {
			const requestId = nextRequestId();
			const nextManualTrack: ManualTrack = sourceTrack
				? {
						kind: isAutoGeneratedTrack( sourceTrack ) ? DEFAULT_KIND : sourceTrack.kind,
						srcLang: getManualLanguageTagFromTrackKey( sourceTrack.srcLang ),
						label: sourceTrack.label || formatLanguageTagForDisplay( sourceTrack.srcLang ),
				  }
				: emptyManualTrack( defaultLanguageTag );
			const matchingCaptionTrack = findCaptionTrackForManualTrack(
				captionTracks,
				nextManualTrack,
				sourceTrack
			);

			dispatch( {
				type: 'OPEN_MANUAL',
				requestId,
				track: nextManualTrack,
				sourceTrack,
				captionTrackId: matchingCaptionTrack?.id,
				cueBlocks: matchingCaptionTrack
					? createCueBlocksFromCaptionTrack( matchingCaptionTrack )
					: createEmptyCueBlocks(),
				isLoadingContent: ! matchingCaptionTrack && !! sourceTrack,
			} );
			setNotice( null );

			if ( matchingCaptionTrack || ! sourceTrack ) {
				return;
			}

			try {
				const loadedBlocks = await loadTrackText( sourceTrack );
				dispatch( { type: 'SEED_CUE_BLOCKS', requestId, cueBlocks: loadedBlocks } );
			} catch ( error ) {
				debug( 'fetch caption track text error', error );
				dispatch( { type: 'CONTENT_LOAD_FAILED', requestId } );
				// Only surface the failure if this workspace is still the current one.
				if ( requestIdRef.current === requestId ) {
					setNotice( {
						status: 'error',
						message: __(
							'Unable to load subtitle content. You can try again from the track list or start from an empty subtitle track.',
							'jetpack-videopress-pkg'
						),
					} );
				}
			}
		},
		[ captionTracks, defaultLanguageTag, loadTrackText, nextRequestId ]
	);

	const startStoredCaptionTrack = useCallback(
		( captionTrack: SavedCaptionTrack ) => {
			dispatch( {
				type: 'OPEN_MANUAL',
				requestId: nextRequestId(),
				track: getManualTrackFromCaptionTrack( captionTrack ),
				sourceTrack: getSourceTrackFromCaptionTrack( captionTrack, managedTracks ),
				captionTrackId: captionTrack.id,
				cueBlocks: createCueBlocksFromCaptionTrack( captionTrack ),
				isLoadingContent: false,
			} );
			setNotice( null );
		},
		[ managedTracks, nextRequestId ]
	);

	const startUploadTrack = useCallback(
		( sourceTrack: VideoTextTrack | null = null, file: File | null = null ) => {
			dispatch( {
				type: 'OPEN_UPLOAD',
				requestId: nextRequestId(),
				mode: sourceTrack ? 'replace' : 'add',
				replacingTrack: sourceTrack,
				form: sourceTrack
					? {
							kind: sourceTrack.kind,
							srcLang: formatLanguageTagForDisplay( sourceTrack.srcLang ),
							label: sourceTrack.label,
							tmpFile: file,
					  }
					: { ...emptyUploadForm( defaultLanguageTag ), tmpFile: file },
			} );
			setNotice( null );
		},
		[ defaultLanguageTag, nextRequestId ]
	);

	const startTextImportTrack = useCallback( () => {
		dispatch( {
			type: 'OPEN_MANUAL',
			requestId: nextRequestId(),
			track: emptyManualTrack( defaultLanguageTag ),
			sourceTrack: null,
			captionTrackId: undefined,
			cueBlocks: createEmptyCueBlocks(),
			isLoadingContent: false,
			isTextImportOpen: true,
		} );
		setNotice( null );
	}, [ defaultLanguageTag, nextRequestId ] );

	const handleCaptionFileDrop = useCallback(
		( files: File[] ) => {
			const file = files[ 0 ] ?? null;
			if ( ! file ) {
				return;
			}

			if ( ! isAcceptedTrackFile( file, SUPPORTED_CAPTION_FORMATS ) ) {
				setNotice( {
					status: 'error',
					message: sprintf(
						/* translators: %s: comma-separated list of accepted subtitle file extensions. */
						__( 'Accepted formats: %s.', 'jetpack-videopress-pkg' ),
						SUPPORTED_CAPTION_FORMATS_LABEL
					),
				} );
				return;
			}

			// Dropping a file switches to upload mode; confirm so it can't discard unsaved cue edits.
			confirmDiscardThen( () => startUploadTrack( null, file ) );
		},
		[ confirmDiscardThen, startUploadTrack ]
	);

	const submitUploadForm = useCallback( async () => {
		const current = workspaceRef.current;
		if ( current.view !== 'upload' ) {
			return;
		}
		const { form, mode, replacingTrack } = current;

		if ( ! form.tmpFile ) {
			setNotice( {
				status: 'error',
				message: __( 'Select a subtitle file before saving.', 'jetpack-videopress-pkg' ),
			} );
			return;
		}

		if ( ! isAcceptedTrackFile( form.tmpFile, SUPPORTED_CAPTION_FORMATS ) ) {
			setNotice( {
				status: 'error',
				message: sprintf(
					/* translators: %s: comma-separated list of supported subtitle file extensions. */
					__( 'Supported subtitle formats: %s.', 'jetpack-videopress-pkg' ),
					SUPPORTED_CAPTION_FORMATS_LABEL
				),
			} );
			return;
		}

		const canonicalSrcLang = canonicalizeLanguageTag( form.srcLang );
		const srcLang =
			mode === 'replace' && replacingTrack
				? canonicalSrcLang ?? replacingTrack.srcLang
				: canonicalSrcLang;

		if ( ! srcLang ) {
			setNotice( {
				status: 'error',
				message: __( 'Choose a subtitle language.', 'jetpack-videopress-pkg' ),
			} );
			return;
		}

		const existingTrack = managedTracks.find(
			track => isMatchingSubtitleTrackLanguage( track, srcLang ) && ! isAutoGeneratedTrack( track )
		);

		if ( mode === 'add' && existingTrack ) {
			setNotice( {
				status: 'error',
				message: __(
					'A subtitle track already exists for that language. Use Replace file on the existing track to upload a new file.',
					'jetpack-videopress-pkg'
				),
			} );
			return;
		}

		const outcome = await uploadSubtitleFile( {
			trackToUpload: {
				kind: form.kind,
				srcLang,
				label: form.label.trim(),
				tmpFile: form.tmpFile,
			},
			trackToUpdate: mode === 'replace' ? replacingTrack : null,
		} );

		if ( outcome === 'failed' ) {
			return;
		}

		resetToTrackList();
		setNotice(
			outcome === 'cleanup-failed'
				? {
						status: 'error',
						message: __(
							'Subtitle track uploaded, but the previous language’s track couldn’t be removed and may still appear.',
							'jetpack-videopress-pkg'
						),
				  }
				: {
						status: 'success',
						message: __( 'Subtitle track uploaded.', 'jetpack-videopress-pkg' ),
				  }
		);
	}, [ managedTracks, resetToTrackList, uploadSubtitleFile ] );

	const saveDraft = useCallback( async () => {
		const current = workspaceRef.current;
		if ( current.view !== 'manual' ) {
			return;
		}

		const payload = buildCaptionTrackPayload( {
			status: 'draft',
			guid,
			manualTrack: current.track,
			sourceTrack: current.sourceTrack,
			cueBlocks: current.cueBlocks,
			captionTrackId: current.captionTrackId,
			captionTracks,
		} );
		if ( ! payload ) {
			setNotice( {
				status: 'error',
				message: __( 'Choose a subtitle language.', 'jetpack-videopress-pkg' ),
			} );
			return;
		}

		const saved = await saveCaptionTrackRecord( payload );
		if ( saved ) {
			// The editor now matches what was saved, so it's no longer dirty.
			dispatch( {
				type: 'MARK_SAVED',
				requestId: current.requestId,
				captionTrackId: saved.id,
			} );
		}
	}, [ captionTracks, guid, saveCaptionTrackRecord ] );

	const publishTrack = useCallback( async () => {
		const current = workspaceRef.current;
		if ( current.view !== 'manual' ) {
			return;
		}

		const canonicalSrcLang = canonicalizeLanguageTag( current.track.srcLang );
		if ( ! canonicalSrcLang ) {
			setNotice( {
				status: 'error',
				message: __( 'Choose a subtitle language.', 'jetpack-videopress-pkg' ),
			} );
			return;
		}

		const cueValidationErrors = getCaptionCueValidationErrors( current.cueBlocks );
		if ( cueValidationErrors.length ) {
			setNotice( {
				status: 'error',
				message: getCueValidationNoticeMessage( cueValidationErrors[ 0 ] ),
			} );
			return;
		}

		const cues = captionBlocksToCues( current.cueBlocks );
		if ( ! cues.length ) {
			setNotice( {
				status: 'error',
				message: __( 'Add at least one subtitle cue before publishing.', 'jetpack-videopress-pkg' ),
			} );
			return;
		}

		const payload = buildCaptionTrackPayload( {
			status: 'publish',
			guid,
			manualTrack: current.track,
			sourceTrack: current.sourceTrack,
			cueBlocks: current.cueBlocks,
			captionTrackId: current.captionTrackId,
			captionTracks,
		} );
		if ( ! payload ) {
			return;
		}

		const vtt = serializeCuesToWebVtt( cues );
		const filename = `${ canonicalSrcLang }-${ current.track.kind }.vtt`.replace(
			/[^a-z0-9._-]/gi,
			'-'
		);

		/*
		 * Resolve the managed track this publish updates: the (non-generated)
		 * track the editor was opened from, or the existing manual track for the
		 * target language. Auto-generated tracks are never updated in place.
		 */
		const openedFromTrack = current.sourceTrack;
		const sourceTrackMatch =
			openedFromTrack && ! isAutoGeneratedTrack( openedFromTrack )
				? managedTracks.find( track => getTrackKey( track ) === getTrackKey( openedFromTrack ) ) ??
				  null
				: null;
		const manualTrackMatch =
			managedTracks.find(
				track =>
					isMatchingSubtitleTrackLanguage( track, canonicalSrcLang ) &&
					! isAutoGeneratedTrack( track )
			) ?? null;

		const requestId = current.requestId;
		const outcome = await publishManualTrack( {
			trackToUpload: {
				kind: current.track.kind,
				srcLang: canonicalSrcLang,
				label: current.track.label.trim(),
				tmpFile: new File( [ vtt ], filename, { type: 'text/vtt' } ),
			},
			trackToUpdate: sourceTrackMatch || manualTrackMatch,
			captionTrackPayload: payload,
		} );

		if ( outcome !== 'published' && outcome !== 'cleanup-failed' ) {
			return;
		}

		// A late-resolving publish must not wipe an editor the user has since started.
		if ( workspaceRef.current.requestId !== requestId ) {
			return;
		}

		resetToTrackList();
		setNotice(
			outcome === 'cleanup-failed'
				? {
						status: 'error',
						message: __(
							'Subtitles published, but the previous language’s track couldn’t be removed and may still appear.',
							'jetpack-videopress-pkg'
						),
				  }
				: {
						status: 'success',
						message: __( 'Subtitles published.', 'jetpack-videopress-pkg' ),
				  }
		);
	}, [ captionTracks, guid, managedTracks, publishManualTrack, resetToTrackList ] );

	const importCaptionText = useCallback( ( mode: 'append' | 'replace' ): boolean => {
		const current = workspaceRef.current;
		if ( current.view !== 'manual' ) {
			return false;
		}

		const cues = parseCaptionTextInput( current.textImportValue );
		if ( ! cues.length ) {
			setNotice( {
				status: 'error',
				message: __( 'Paste subtitle text before importing.', 'jetpack-videopress-pkg' ),
			} );
			return false;
		}

		dispatch( { type: 'IMPORT_CUES', mode, cueBlocks: cues.map( createCueBlock ) } );
		setNotice( {
			status: 'success',
			message: __( 'Subtitle text imported.', 'jetpack-videopress-pkg' ),
		} );
		return true;
	}, [] );

	const requestDeleteTrack = useCallback(
		( track: VideoTextTrack ) => {
			setConfirmation( {
				message: sprintf(
					/* translators: %s: subtitle track language or label. */
					__( 'Delete the %s subtitle track? This cannot be undone.', 'jetpack-videopress-pkg' ),
					track.label || formatLanguageTagForDisplay( track.srcLang )
				),
				confirmLabel: __( 'Delete', 'jetpack-videopress-pkg' ),
				onConfirm: () => void deleteManagedTrack( track ),
			} );
		},
		[ deleteManagedTrack ]
	);

	const requestDeleteDraft = useCallback(
		( captionTrack: SavedCaptionTrack ) => {
			const draft = getManualTrackFromCaptionTrack( captionTrack );
			setConfirmation( {
				message: sprintf(
					/* translators: %s: subtitle track language or label. */
					__( 'Delete the %s subtitle draft? This cannot be undone.', 'jetpack-videopress-pkg' ),
					draft.label || getTrackLanguageName( draft.srcLang )
				),
				confirmLabel: __( 'Delete', 'jetpack-videopress-pkg' ),
				onConfirm: () => void deleteDraftTrack( captionTrack ),
			} );
		},
		[ deleteDraftTrack ]
	);

	/*
	 * Whether the manual editor is updating a track that's already published for
	 * this language: publishing overwrites the live track (so the button reads
	 * "Update"), and saving a draft alongside it doesn't make sense.
	 */
	const isUpdatingPublishedTrack = useMemo(
		() =>
			workspace.view === 'manual' &&
			visibleManagedTracks.some(
				track =>
					isMatchingSubtitleTrackLanguage(
						track,
						canonicalizeLanguageTag( workspace.track.srcLang ) ?? ''
					) && ! isAutoGeneratedTrack( track )
			),
		[ workspace, visibleManagedTracks ]
	);

	const isEditorView = workspace.view !== 'tracks';
	const isLoadingTrackText = workspace.view === 'manual' && workspace.isLoadingContent;

	const getEditorHeading = () => {
		if ( workspace.view === 'upload' ) {
			return workspace.mode === 'replace'
				? __( 'Replace subtitle file', 'jetpack-videopress-pkg' )
				: __( 'Upload subtitle file', 'jetpack-videopress-pkg' );
		}

		if ( workspace.view === 'manual' ) {
			return workspace.sourceTrack || workspace.captionTrackId
				? __( 'Edit subtitle track', 'jetpack-videopress-pkg' )
				: __( 'New subtitle track', 'jetpack-videopress-pkg' );
		}

		return '';
	};

	const manualLanguageName =
		workspace.view === 'manual' && workspace.track.srcLang
			? getLanguageDisplayName( workspace.track.srcLang )
			: '';
	const videoTitle = title || __( 'VideoPress video', 'jetpack-videopress-pkg' );
	const modalHeaderTitle = manualLanguageName
		? sprintf(
				/* translators: 1: video title. 2: current subtitle language name. */
				__( 'Manage subtitles for %1$s: %2$s', 'jetpack-videopress-pkg' ),
				videoTitle,
				manualLanguageName
		  )
		: sprintf(
				/* translators: %s: video title. */
				__( 'Manage subtitles for %s', 'jetpack-videopress-pkg' ),
				videoTitle
		  );

	const trackListBusy: TrackListBusy = ( () => {
		if ( deletingTrackKey ) {
			return { action: 'delete', key: deletingTrackKey };
		}
		if ( downloadingTrackKey ) {
			return { action: 'download', key: downloadingTrackKey };
		}
		if ( isSavingUpload ) {
			return { action: 'upload' };
		}
		if ( isPublishing ) {
			return { action: 'publish' };
		}
		return null;
	} )();

	const previewPanel = (
		<CaptionPreviewPlayer
			ref={ playerRef }
			guid={ guid }
			videoSrc={ videoSrc }
			poster={ poster }
			isPrivate={ isPrivate }
			previewAspectRatio={ previewAspectRatio }
			activeCueText={ activeCueText }
			onCurrentTimeChange={ handleCurrentTimeChange }
		/>
	);

	return isOpen ? (
		<CaptionEditorContext.Provider value={ editorContext }>
			<Modal
				title={ modalHeaderTitle }
				onRequestClose={ handleRequestClose }
				className="videopress-caption-manager"
				focusOnMount={ false }
			>
				<DropZone
					label={ __( 'Drop a subtitle file to upload', 'jetpack-videopress-pkg' ) }
					onFilesDrop={ handleCaptionFileDrop }
				/>

				<div className="videopress-caption-manager__action-bar">
					<div className="videopress-caption-manager__action-bar-start">
						<h3 className="videopress-caption-manager__action-bar-title">
							{ isEditorView
								? getEditorHeading()
								: __( 'Subtitle tracks', 'jetpack-videopress-pkg' ) }
						</h3>
						{ isLoadingTrackText && (
							<span className="videopress-caption-manager__status">
								{ __( 'Loading subtitle content…', 'jetpack-videopress-pkg' ) }
							</span>
						) }
					</div>
					<div className="videopress-caption-manager__action-buttons">
						{ isEditorView ? (
							<>
								<Button
									variant="secondary"
									icon={ isRTL() ? chevronRight : chevronLeft }
									onClick={ handleBackToTracks }
									disabled={ isPublishing || isSavingCaptionTrack }
								>
									{ __( 'Back to tracks', 'jetpack-videopress-pkg' ) }
								</Button>
								{ workspace.view === 'manual' && (
									<>
										{ ! workspace.isTextImportOpen && (
											<Button
												variant="secondary"
												onClick={ () => {
													dispatch( { type: 'SET_TEXT_IMPORT_OPEN', isOpen: true } );
													setNotice( null );
												} }
											>
												{ __( 'Paste text', 'jetpack-videopress-pkg' ) }
											</Button>
										) }
										{ ! isUpdatingPublishedTrack && (
											<Button
												variant="secondary"
												onClick={ () => void saveDraft() }
												isBusy={ isSavingCaptionTrack }
												disabled={ isSavingCaptionTrack || isPublishing || isLoadingTrackText }
											>
												{ __( 'Save draft', 'jetpack-videopress-pkg' ) }
											</Button>
										) }
										<Button
											variant="primary"
											onClick={ () => void publishTrack() }
											isBusy={ isPublishing }
											disabled={ isSavingCaptionTrack || isPublishing || isLoadingTrackText }
										>
											{ isUpdatingPublishedTrack
												? __( 'Update', 'jetpack-videopress-pkg' )
												: __( 'Publish', 'jetpack-videopress-pkg' ) }
										</Button>
									</>
								) }
							</>
						) : (
							<>
								<Button
									ref={ addTrackButtonRef }
									variant="secondary"
									icon={ plus }
									onClick={ () => void startManualTrack() }
									disabled={ isPublishing || isSavingCaptionTrack }
								>
									{ __( 'Add track', 'jetpack-videopress-pkg' ) }
								</Button>
								<Button
									variant="secondary"
									onClick={ startTextImportTrack }
									disabled={ isPublishing || isSavingCaptionTrack }
								>
									{ __( 'Paste transcript', 'jetpack-videopress-pkg' ) }
								</Button>
								<Button
									variant="secondary"
									icon={ upload }
									onClick={ () => startUploadTrack() }
									disabled={ isPublishing || isSavingCaptionTrack }
								>
									{ __( 'Upload subtitle file', 'jetpack-videopress-pkg' ) }
								</Button>
							</>
						) }
					</div>
				</div>

				{ notice && (
					<Notice status={ notice.status } isDismissible={ false }>
						{ notice.message }
					</Notice>
				) }

				<div
					className={ `videopress-caption-manager__workspace videopress-caption-manager__workspace--${
						isEditorView ? 'editor' : 'tracks'
					}` }
				>
					{ workspace.view === 'tracks' && (
						<section className="videopress-caption-manager__tracks">
							<TrackList
								rows={ trackRows }
								isLoading={ isLoadingCaptionTracks }
								emptyMessage={ __(
									'No subtitle tracks have been added to this video yet.',
									'jetpack-videopress-pkg'
								) }
								busy={ trackListBusy }
								onEditManaged={ track => void startManualTrack( track ) }
								onReplaceManaged={ track => startUploadTrack( track ) }
								onDownloadManaged={ track => void downloadTrack( track ) }
								onDeleteManaged={ requestDeleteTrack }
								onEditDraft={ startStoredCaptionTrack }
								onDeleteDraft={ requestDeleteDraft }
							/>
						</section>
					) }

					{ workspace.view === 'upload' && (
						<section className="videopress-caption-manager__editor">
							<UploadWorkspace
								workspace={ workspace }
								isSaving={ isSavingUpload }
								previewPanel={ previewPanel }
								onLanguageChange={ ( tag, displayName ) => {
									dispatch( { type: 'SET_UPLOAD_LANGUAGE', srcLang: tag, label: displayName } );
									setNotice( null );
								} }
								onFileChange={ file => {
									dispatch( { type: 'SET_UPLOAD_FILE', file } );
									setNotice( null );
								} }
								onCancelReplace={ () => startUploadTrack() }
								onSubmit={ () => void submitUploadForm() }
							/>
						</section>
					) }

					{ workspace.view === 'manual' && (
						<section className="videopress-caption-manager__editor">
							<ManualEditor
								workspace={ workspace }
								playerRef={ playerRef }
								previewPanel={ previewPanel }
								cueStartTimes={ cueStartTimes }
								hasCues={ editorCues.length > 0 }
								onLanguageChange={ ( tag, displayName ) => {
									dispatch( { type: 'SET_MANUAL_LANGUAGE', srcLang: tag, label: displayName } );
									setNotice( null );
								} }
								onCueBlocksChange={ cueBlocks => dispatch( { type: 'SET_CUE_BLOCKS', cueBlocks } ) }
								onTextImportOpenChange={ importOpen => {
									dispatch( { type: 'SET_TEXT_IMPORT_OPEN', isOpen: importOpen } );
									setNotice( null );
								} }
								onTextImportValueChange={ value => {
									dispatch( { type: 'SET_TEXT_IMPORT_VALUE', value } );
									setNotice( null );
								} }
								onImportText={ importCaptionText }
							/>
						</section>
					) }
				</div>

				<ConfirmDialog
					isOpen={ !! confirmation }
					onConfirm={ () => {
						const pending = confirmation;
						setConfirmation( null );
						pending?.onConfirm();
					} }
					onCancel={ () => setConfirmation( null ) }
					confirmButtonText={ confirmation?.confirmLabel }
				>
					{ confirmation?.message }
				</ConfirmDialog>
			</Modal>
		</CaptionEditorContext.Provider>
	) : null;
}
