<?php
/**
 * WPCom Tracking for WP Admin Page Views.
 *
 * @package automattic/jetpack-mu-wpcom
 */

namespace Automattic\Jetpack\Jetpack_Mu_Wpcom\Wpcom_Wpadmin_Page_View;

use WPCOMSH_Support_Session_Detect;

/**
 * Bump a Tracks stat for every wp-admin page view not generated by an Automattician.
 * This is possibly interesting on its own but will also be used as part of an
 * initiative to understand how much supply we're offering for live chat demand.
 * See https://nosaraproject.wordpress.com/2015/03/06/live-chat-stats/
 */
function wpcom_nosara_track_admin_page_views() {
	if ( do_not_track_a11ns() ) {
		return;
	}

	$is_simple_site = defined( 'IS_WPCOM' ) && IS_WPCOM;
	$is_atomic_site = ! $is_simple_site;

	global $current_user, $current_blog, $current_screen;

	if (
		! $current_user instanceof \WP_User ||
		! $current_screen instanceof \WP_Screen
	) {
		return;
	}

	$blog_id    = null;
	$user_types = array();

	if ( $is_simple_site ) {
		if ( ! $current_blog instanceof \WP_Site ) {
			return;
		}

		$blog_id    = $current_blog->blog_id;
		$user_types = \WPCOM_User::get_types();
	}

	if ( $is_atomic_site ) {
		$blog_id    = _wpcom_get_current_blog_id();
		$user_types = wpcom_atomic_get_user_types();
	}
	?>
	<script type="text/javascript">
		var _admin_pv_props = {
			from_page: '<?php echo esc_js( $current_screen->id ); ?>',
			is_block_editor: '<?php echo $current_screen->is_block_editor ? 'true' : 'false'; ?>',
			source: 'wp-admin',
			blog_id: '<?php echo esc_js( (string) $blog_id ); ?>',
			user_type: '<?php echo esc_js( implode( ',', $user_types ) ); ?>'
		};
		_tkq = window._tkq || [];
		_tkq.push( [ 'identifyUser', <?php echo (int) $current_user->ID; ?>, '<?php echo esc_js( $current_user->user_login ); ?>' ] );
		_tkq.push( [ 'recordEvent', 'wpcom_admin_page_view', _admin_pv_props ] );
	</script>
	<?php
}
add_action( 'admin_footer', __NAMESPACE__ . '\wpcom_nosara_track_admin_page_views' );

/**
 * Track non-calypso Customizer views if the user is linked from the frontend.
 */
function wpcom_maybe_track_customizer() {
	// not when the Customizer is loaded in Calypso
	if ( isset( $_GET['calypso'] ) ) { // phpcs:ignore WordPress.Security.NonceVerification.Recommended
		return;
	}

	// links from frontend
	if ( isset( $_GET['url'] ) ) { // phpcs:ignore WordPress.Security.NonceVerification.Recommended
		return wpcom_track_customizer_from_frontend();
	}

	// standard wp-admin
	wpcom_nosara_track_admin_page_views();
}

/**
 * Since links to the Customizer from the frontend aren't properly wp-admin (no wp-admin chrome,
 * you return to the frontend after closing), they shouldn't be counted as wp-admin views.
 */
function wpcom_track_customizer_from_frontend() {
	global $current_user;

	// Since we view so many screens to offer support and do feature dev, I think it's best not to count us.
	if ( do_not_track_a11ns() ) {
		return;
	}
	?>
	<script type="text/javascript">
		_tkq = window._tkq || [];
		_tkq.push( [ 'identifyUser', <?php echo (int) $current_user->ID; ?>, '<?php echo esc_js( $current_user->user_login ); ?>' ] );
		_tkq.push( [ 'recordEvent', 'wpcom_customize_loaded_from_frontend' ] );
	</script>
	<?php
}
add_action( 'customize_controls_print_footer_scripts', __NAMESPACE__ . '\wpcom_maybe_track_customizer' );

/**
 * Determine if the current user should not be tracked.
 *
 * @return bool
 */
function do_not_track_a11ns() {
	$is_simple_site = defined( 'IS_WPCOM' ) && IS_WPCOM;

	if ( $is_simple_site ) {
		return is_automattician() || is_network_admin();
	}

	return wpcom_atomic_maybe_is_a11n();
}

/**
 * Check if the user might be an a11n on Atomic sites.
 *
 * @return bool
 */
function wpcom_atomic_maybe_is_a11n() {
	$is_proxy_atomic    = defined( 'AT_PROXIED_REQUEST' ) && AT_PROXIED_REQUEST;
	$is_support_session = WPCOMSH_Support_Session_Detect::is_probably_support_session();

	return $is_proxy_atomic && ! $is_support_session;
}

/**
 * Retrieves the user types for Atomic sites.
 *
 * @return array An array of user types.
 */
function wpcom_atomic_get_user_types() {
	$user_types = array();

	if ( get_account_age_in_days() <= 14 ) {
		$user_types[] = 'New User';
	}

	$subscriptions = wpcomsh_get_wpcom_active_subscriptions();
	if ( count( $subscriptions ) > 0 ) {
		$user_types[] = 'Paid';
	}

	if ( wpcom_site_has_feature( \WPCOM_Features::PRIORITY_SUPPORT ) ) {
		$user_types[] = 'Business';
	}

	return $user_types;
}

/**
 * Calculate the number of days since the current user registered their account.
 *
 * @global WP_User $current_user The current user object.
 *
 * @return float The age of the account in days.
 */
function get_account_age_in_days() {
	global $current_user;

	return ( time() - strtotime( $current_user->user_registered ) ) / DAY_IN_SECONDS;
}

// Everything is decided at shutdown: what the response turned out to be is only knowable once its
// headers have settled, and admin_init has by then populated the user types. Registered here
// rather than from a current_screen callback because another callback on that hook can fatal at an
// earlier priority, which would lose the failed request this event exists to count.
if ( defined( 'IS_WPCOM' ) && IS_WPCOM && defined( 'WP_ADMIN' ) && WP_ADMIN ) {
	add_action( 'shutdown', __NAMESPACE__ . '\wpcom_admin_screen_record' );
}

/**
 * Whether wpcom_admin_page_view could also have reported this request. An exclusion on one side
 * but not the other makes the coverage percentage a measure of the disagreement between the two
 * events rather than of the tracking gap.
 *
 * @param \WP_Screen|null $screen The screen WordPress resolved for this request, if any.
 * @return bool
 */
function wpcom_admin_screen_is_countable( $screen ) {
	// Atomic's only server-side delivery is a blocking 1s HTTP request per page view, which is
	// too expensive to run on every admin screen.
	if ( ! defined( 'IS_WPCOM' ) || ! IS_WPCOM ) {
		return false;
	}

	if ( ! $screen instanceof \WP_Screen ) {
		return false;
	}

	// Not is_admin(): it defers to the screen we were just handed, which reports itself as being
	// in the admin for every set_current_screen() caller, REST endpoints included.
	if ( ! defined( 'WP_ADMIN' ) || ! WP_ADMIN ) {
		return false;
	}

	// admin-ajax.php defines WP_ADMIN, and REST endpoints resolve a screen to simulate an admin
	// context. Neither renders a page.
	if ( wp_doing_ajax() || ( defined( 'REST_REQUEST' ) && REST_REQUEST ) ) {
		return false;
	}

	if ( ! is_user_logged_in() ) {
		return false;
	}

	if ( ! wpcom_admin_screen_has_client_counterpart( $screen->id, $_GET ) ) { // phpcs:ignore WordPress.Security.NonceVerification.Recommended
		return false;
	}

	return ! do_not_track_a11ns();
}

/**
 * Whether wpcom_admin_page_view had any chance to run on this screen.
 *
 * Some screens never fire admin_footer, which the client event hangs off: media-upload.php goes
 * through wp_iframe(), async-upload.php and press-this.php render their own output and exit, the
 * dashboard index-*stuff fragments answer background requests, and the Customizer has its own
 * footer hook, which wpcom_maybe_track_customizer() answers only for a request that is neither a
 * Calypso frame nor a link in from the frontend. Excluding these by route rather than by response
 * headers matters because an error on one of them is re-sent as HTML by wp_die(). Counting a
 * screen the client event cannot reach would depress the ratio instead of measuring it.
 *
 * @param string $screen_id The resolved screen id.
 * @param array  $query     Query parameters, as in $_GET.
 * @return bool
 */
function wpcom_admin_screen_has_client_counterpart( $screen_id, array $query ) {
	// admin.php skips admin-header.php for a noheader request, so nothing reaches admin_footer
	// either. The importers poll in this shape.
	if ( isset( $query['noheader'] ) ) {
		return false;
	}

	// Not IFRAME_REQUEST: update.php and the install screens define that too, and do reach
	// admin_footer through iframe_footer().
	if ( in_array(
		$screen_id,
		array( 'media-upload', 'async-upload', 'press-this', 'index-hotstuff', 'index-yourstuff' ),
		true
	) ) {
		return false;
	}

	if ( 'customize' === $screen_id ) {
		return ! isset( $query['calypso'] ) && ! isset( $query['url'] );
	}

	return true;
}

/**
 * Whether the response the request produced was actually an admin screen.
 *
 * A redirect renders nothing and the screen it points at records itself, so counting both would
 * inflate the denominator on every admin POST. A download (export.php) or a bare fragment
 * (async-upload.php) resolves a screen and then exits without an admin footer, so the client
 * event never fires for it and counting it would depress the ratio the same way.
 *
 * @param string[] $headers Response headers, as returned by headers_list().
 * @return bool
 */
function wpcom_admin_screen_rendered( array $headers ) {
	$content_type = null;

	foreach ( $headers as $header ) {
		if ( 0 === stripos( $header, 'location:' ) ) {
			return false;
		}

		if ( 0 === stripos( $header, 'content-disposition:' ) && false !== stripos( $header, 'attachment' ) ) {
			return false;
		}

		if ( 0 === stripos( $header, 'content-type:' ) ) {
			$content_type = strtolower( ltrim( substr( $header, strlen( 'content-type:' ) ) ) );
		}
	}

	// A response that never got as far as a Content-Type is still countable: an early wp_die() or
	// a fatal is precisely the traffic this event exists to measure.
	if ( null === $content_type ) {
		return true;
	}

	return 0 === strpos( $content_type, 'text/html' ) || 0 === strpos( $content_type, 'application/xhtml+xml' );
}

/**
 * Record one Tracks event per rendered admin screen.
 *
 * @return void
 */
function wpcom_admin_screen_record() {
	// A request that fataled before the admin includes loaded has no screen to attribute anyway.
	if ( ! function_exists( 'get_current_screen' ) ) {
		return;
	}

	$screen = get_current_screen();
	if ( ! wpcom_admin_screen_is_countable( $screen ) ) {
		return;
	}

	if ( ! wpcom_admin_screen_rendered( headers_list() ) ) {
		return;
	}

	global $current_blog;
	if ( ! $current_blog instanceof \WP_Site ) {
		return;
	}

	// Called instead of wpcom_record_tracks_event() because that helper tests for
	// tracks_record_event() before require_lib() has had a chance to define it, and so drops
	// events whenever nothing else loaded the lib first.
	require_lib( 'tracks/client' );

	// tracks_record_event() falls back to a blocking one-second pixel request when the async spool
	// or its daemon is missing, which is the same per-page-view cost that keeps this event off
	// Atomic. Drop the event rather than let a Tracks outage slow every admin screen.
	// @phan-suppress-next-line PhanUndeclaredClassMethod -- WPCOM_Tracks_Client is wpcom-only and not yet carried in .phan/stubs/wpcom-stubs.php.
	if ( ! class_exists( 'WPCOM_Tracks_Client' ) || ! \WPCOM_Tracks_Client::can_do_async() ) {
		return;
	}

	// Property names and value shapes are copied from wpcom_admin_page_view so that the two
	// events join per screen without a translation step in the query.
	tracks_record_event(
		wp_get_current_user(),
		'wpcom_admin_screen',
		array(
			'from_page'       => $screen->id,
			'is_block_editor' => $screen->is_block_editor ? 'true' : 'false',
			'source'          => 'wp-admin',
			'blog_id'         => (string) $current_blog->blog_id,
			'user_type'       => implode( ',', \WPCOM_User::get_types() ),
		)
	);
}
