<?php
/**
 * Various hotfixes to WordPress.com
 *
 * @package automattic/jetpack-mu-wpcom
 */

/**
 * Hotfix for a Gutenberg 19.8.0 bug preventing lower-capability users from editing pages.
 * See: p1734525664059729-slack-C02FMH4G8
 * See: https://github.com/WordPress/gutenberg/issues/68053#issuecomment-2550730705
 */
add_filter(
	'register_post_type_args',
	function ( $args ) {
		if ( current_user_can( 'manage_options' ) ) {
			// Admins still need default_rendering_mode for the site editor to select the correct default template.
			// See: p1736989403607879-slack-C02FMH4G8
			return $args;
		}

		unset( $args['default_rendering_mode'] );
		return $args;
	},
	20
);

/**
 * Hotfix for a {Gutenberg 20.0.0, WP 6.7.x} bug causing the Content block to output truncated HTML.
 * See: https://github.com/WordPress/gutenberg/issues/68614
 */
if (
	// WordPress 6.7.x contains the buggy remove_serialized_parent_block() function.
	version_compare( get_bloginfo( 'version' ), '6.8', '<' ) ) {

	add_filter(
		'the_content',
		function ( $content ) {
			if ( has_filter( 'the_content', 'remove_serialized_parent_block' ) ) {
				// We will revert the content manipulation done in https://github.com/WordPress/gutenberg/pull/67272.

				// Reverts https://github.com/WordPress/gutenberg/pull/67272/files#diff-611d9e2b5a9b00eb2fbe68d044eccb195759a422e36f525186d43d752bee3d71R65-R68
				remove_filter( 'the_content', 'remove_serialized_parent_block', 8 );

				// Reverts https://github.com/WordPress/gutenberg/pull/67272/files#diff-611d9e2b5a9b00eb2fbe68d044eccb195759a422e36f525186d43d752bee3d71R57-R63
				return remove_serialized_parent_block( $content );
			}
			return $content;
		},
		1
	);
}

/**
 * Overrides the `wp-block-editor` script with a hotfix to prevent a performance issue present in
 * Gutenberg v19.0, v20.0, and v20.1 (see https://github.com/WordPress/gutenberg/issues/68875).
 *
 * Our custom script has been generated by applying the fix introduced in Gutenberg v20.2
 * (see https://github.com/WordPress/gutenberg/pull/68898) in a local Gutenberg environment and
 * running `npm run build` to extract the fixed `wp-block-editor` script.
 *
 * @param WP_Scripts $scripts WP_Scripts instance.
 */
function wpcom_fix_performance_issue_block_editor_v19_9_v20_0_v20_1( $scripts ) {
	if ( ! defined( 'GUTENBERG_VERSION' ) ) {
		return;
	}

	if ( ! in_array( GUTENBERG_VERSION, array( '19.9.0', '20.0.0', '20.1.0' ), true ) ) {
		return;
	}

	$path         = gutenberg_dir_path() . 'build/block-editor/index.min.js';
	$handle       = 'wp-block-editor';
	$asset_file   = substr( $path, 0, - ( strlen( '.js' ) ) ) . '.asset.php';
	$asset        = file_exists( $asset_file ) ? require $asset_file : null;
	$dependencies = $asset['dependencies'] ?? array();
	$version      = $asset['version'] ?? GUTENBERG_VERSION;
	gutenberg_override_script(
		$scripts,
		$handle,
		plugins_url( 'wp-block-editor-' . GUTENBERG_VERSION . '-hotfix.min.js', __FILE__ ),
		$dependencies,
		$version,
		true
	);
}
add_action( 'wp_default_scripts', 'wpcom_fix_performance_issue_block_editor_v19_9_v20_0_v20_1', 11 );
