name: "Assign Issues"
description: "Assigns an issue to a PR author and add a label"
inputs:
  token:
    description: "GitHub access token"
    required: true
    default: ""
runs:
  using: node12
  main: "src/index.js"
