#!/usr/bin/env bash

# Start in the right folder.
root_dir="$(dirname "${BASH_SOURCE[0]}")/.."
cd "$root_dir"

# Define some paths.
src_svg_dir=src/svg
dest_svg_dir=build/svg-clean
config_file=tools/svgo.config.mjs

# Make dir if it doesn't exist.
mkdir -p "$dest_svg_dir"

# Optimize SVGs
npx svgo --config="$config_file" -f "$src_svg_dir" -o "$dest_svg_dir" -q

for i in "$dest_svg_dir"/*.svg; do
	# Add <g> to SVG innards.
	sed -E -i.bak 's|(>)(.*)(</svg>)|\1<g>\2</g>\3|' "$i" && rm "$i.bak"
done

# Output.
echo "Created optimized SVGs in '$dest_svg_dir'."
