#!/usr/bin/env bash

# Start in the right folder.
root_dir="$(dirname "${BASH_SOURCE[0]}")/.."
cd "$root_dir"

# Define some paths.
src_svg_dir=build/svg-clean
src_sprite_dir=src/svg-sprite
src_css_dir=src/css
dest_sprite_dir=build/svg-sprite
dest_sprite_filename="$dest_sprite_dir"/social-logos.svg

# Make dir if it doesn't exist.
mkdir -p "$dest_sprite_dir"

# Ensure consistent sort order.
LC_COLLATE=C

# Generate SVG sprite file.
npx svgstore -o "$dest_sprite_filename" --inline "$src_svg_dir"/*.svg

# Make SVG more conformant.
sed -E -i.bak 's|<svg><defs/>|<svg xmlns="http://www.w3.org/2000/svg">|' "$dest_sprite_filename" && rm "$dest_sprite_filename.bak"

# Copy example files.
cp "$src_sprite_dir/"* "$dest_sprite_dir"

# Inject SVG into example file.
sed -i.bak "s|{{SVG_HERE}}|$(cat "$dest_sprite_filename")|" "$dest_sprite_dir/example.html" && rm "$dest_sprite_dir/example.html.bak"

# Output.
echo "Created SVG sprite file in '$dest_sprite_dir'."
