jest.mock( '@wordpress/api-fetch', () => jest.fn() );
jest.mock( '../../get-media-token', () => jest.fn() );
jest.mock( 'debug', () => () => jest.fn() );

const getVideoTracksModule = async () => {
	Object.defineProperty( window, 'videoPressEditorState', {
		configurable: true,
		value: { siteType: 'simple' },
	} );

	return import( '..' );
};

const getApiFetchMock = async () => ( await import( '@wordpress/api-fetch' ) ).default as jest.Mock;

const getMediaTokenMock = async () =>
	( await import( '../../get-media-token' ) ).default as jest.Mock;

describe( 'video-tracks', () => {
	beforeEach( () => {
		jest.resetModules();
		jest.clearAllMocks();
	} );

	it( 'flattens legacy nested track responses', async () => {
		const { flattenVideoTracks } = await getVideoTracksModule();

		expect(
			flattenVideoTracks( {
				captions: {
					en: {
						src: 'english.vtt',
						label: 'English',
					},
				},
			} )
		).toEqual( [
			{
				kind: 'captions',
				label: 'English',
				src: 'english.vtt',
				srcLang: 'en',
			},
		] );
	} );

	it( 'flattens wpcom/v2 track list responses with track ids', async () => {
		const { flattenVideoTracks } = await getVideoTracksModule();

		expect(
			flattenVideoTracks( {
				tracks: [
					{
						track_id: 'track-1',
						kind: 'captions',
						src_lang: 'en-US',
						label: 'English',
						download_url: 'english.vtt',
						source: 'manual',
						status: 'ready',
						is_auto_generated: false,
						is_auto_synced: true,
						is_draft: true,
					},
				],
			} )
		).toEqual( [
			{
				id: 'track-1',
				downloadUrl: 'english.vtt',
				kind: 'captions',
				isAutoGenerated: false,
				isAutoSynced: true,
				isDraft: true,
				label: 'English',
				source: 'manual',
				src: 'english.vtt',
				srcLang: 'en-US',
				status: 'ready',
			},
		] );
	} );

	it( 'fetches tracks with backend-provided supported formats', async () => {
		const apiFetch = await getApiFetchMock();
		apiFetch.mockResolvedValue( {
			text: () =>
				Promise.resolve(
					JSON.stringify( {
						tracks: [
							{
								track_id: 'track-1',
								kind: 'captions',
								srclang: 'en',
								label: 'English',
								download_url: 'english.vtt',
							},
						],
						supported_formats: {
							vtt: 'WebVTT',
							srt: 'SubRip',
						},
					} )
				),
		} );
		const { fetchTrackListForGuid } = await getVideoTracksModule();

		await expect( fetchTrackListForGuid( 'abc123' ) ).resolves.toEqual( {
			tracks: [
				{
					id: 'track-1',
					downloadUrl: 'english.vtt',
					kind: 'captions',
					label: 'English',
					src: 'english.vtt',
					srcLang: 'en',
				},
			],
			supportedFormats: [ '.vtt', '.srt' ],
		} );
	} );

	it( 'uploads tracks to the wpcom/v2 filedata field', async () => {
		const apiFetch = await getApiFetchMock();
		const file = new File( [ 'WEBVTT' ], 'english.vtt', { type: 'text/vtt' } );
		apiFetch.mockResolvedValue( {
			text: () => Promise.resolve( '{}' ),
		} );
		const { uploadTrackForGuid } = await getVideoTracksModule();

		await uploadTrackForGuid(
			{
				kind: 'captions',
				srcLang: 'en',
				label: 'English',
				tmpFile: file,
			},
			'abc123'
		);

		expect( apiFetch ).toHaveBeenCalledWith(
			expect.objectContaining( {
				apiNamespace: 'wpcom/v2',
				formData: [
					[ 'kind', 'captions' ],
					[ 'srclang', 'en' ],
					[ 'label', 'English' ],
					[ 'filedata', file ],
				],
				global: true,
				method: 'POST',
				path: '/videopress/videos/abc123/tracks',
				parse: false,
			} )
		);
	} );

	it( 'throws structured wpcom/v2 errors from non-OK JSON responses', async () => {
		const apiFetch = await getApiFetchMock();
		const file = new File( [ 'WEBVTT' ], 'english.vtt', { type: 'text/vtt' } );
		apiFetch.mockResolvedValue( {
			ok: false,
			status: 415,
			statusText: 'Unsupported Media Type',
			text: () =>
				Promise.resolve(
					JSON.stringify( {
						code: 'unsupported_caption_format',
						message: 'Unsupported caption format.',
					} )
				),
		} );
		const { uploadTrackForGuid } = await getVideoTracksModule();

		await expect(
			uploadTrackForGuid(
				{
					kind: 'captions',
					srcLang: 'en',
					label: 'English',
					tmpFile: file,
				},
				'abc123'
			)
		).rejects.toMatchObject( {
			code: 'unsupported_caption_format',
			message: 'Unsupported caption format.',
			status: 415,
		} );
	} );

	it( 'throws a fallback error from non-OK empty wpcom/v2 responses', async () => {
		const apiFetch = await getApiFetchMock();
		const file = new File( [ 'WEBVTT' ], 'english.vtt', { type: 'text/vtt' } );
		apiFetch.mockResolvedValue( {
			ok: false,
			status: 500,
			statusText: 'Server Error',
			text: () => Promise.resolve( '' ),
		} );
		const { uploadTrackForGuid } = await getVideoTracksModule();

		await expect(
			uploadTrackForGuid(
				{
					kind: 'captions',
					srcLang: 'en',
					label: 'English',
					tmpFile: file,
				},
				'abc123'
			)
		).rejects.toMatchObject( {
			code: 'videopress_track_request_failed',
			message: 'Server Error',
			status: 500,
		} );
	} );

	it( 'normalizes an uploaded track response with fallback metadata', async () => {
		const { normalizeVideoTextTrackResponse } = await getVideoTracksModule();

		expect(
			normalizeVideoTextTrackResponse(
				{
					data: {
						track_id: 'track-1',
						src: 'uploaded.vtt',
					},
				},
				{
					kind: 'captions',
					srcLang: 'en',
					label: 'English',
				}
			)
		).toEqual( {
			id: 'track-1',
			kind: 'captions',
			label: 'English',
			src: 'uploaded.vtt',
			srcLang: 'en',
		} );
	} );

	it( 'deletes wpcom/v2 tracks by track id', async () => {
		const apiFetch = await getApiFetchMock();
		apiFetch.mockResolvedValue( {
			text: () => Promise.resolve( '{}' ),
		} );
		const { deleteTrackForGuid } = await getVideoTracksModule();

		await deleteTrackForGuid(
			{
				id: 'track-1',
				kind: 'captions',
				srcLang: 'en',
			},
			'abc123'
		);

		expect( apiFetch ).toHaveBeenCalledWith(
			expect.objectContaining( {
				apiNamespace: 'wpcom/v2',
				global: true,
				method: 'DELETE',
				path: '/videopress/videos/abc123/tracks/track-1',
				parse: false,
			} )
		);
	} );

	it( 'reads wpcom/v2 track content from the content response field', async () => {
		const apiFetch = await getApiFetchMock();
		apiFetch.mockResolvedValue( {
			text: () => Promise.resolve( JSON.stringify( { content: 'WEBVTT\n\nCaption text.' } ) ),
		} );
		const { fetchTrackContentForGuid } = await getVideoTracksModule();

		await expect(
			fetchTrackContentForGuid(
				{
					id: 'track-1',
					kind: 'captions',
					srcLang: 'en',
					label: 'English',
					src: 'english.vtt',
				},
				'abc123'
			)
		).resolves.toBe( 'WEBVTT\n\nCaption text.' );

		expect( apiFetch ).toHaveBeenCalledWith(
			expect.objectContaining( {
				apiNamespace: 'wpcom/v2',
				global: true,
				method: 'GET',
				path: '/videopress/videos/abc123/tracks/track-1/content',
				parse: false,
			} )
		);
	} );

	it( 'updates wpcom/v2 track content by track id', async () => {
		const apiFetch = await getApiFetchMock();
		apiFetch.mockResolvedValue( {
			text: () => Promise.resolve( '{}' ),
		} );
		const { updateTrackContentForGuid } = await getVideoTracksModule();

		await updateTrackContentForGuid(
			{
				id: 'track-1',
				kind: 'captions',
				srcLang: 'en',
				label: 'English',
			},
			'abc123',
			'WEBVTT'
		);

		expect( apiFetch ).toHaveBeenCalledWith(
			expect.objectContaining( {
				apiNamespace: 'wpcom/v2',
				body: JSON.stringify( { content: 'WEBVTT', format: 'vtt' } ),
				global: true,
				headers: { 'Content-Type': 'application/json' },
				method: 'PUT',
				path: '/videopress/videos/abc123/tracks/track-1/content',
				parse: false,
			} )
		);
	} );

	describe( 'isAutogeneratedChapterFile', () => {
		const okResponse = ( body: string ) => ( {
			ok: true,
			status: 200,
			text: () => Promise.resolve( body ),
		} );

		it( 'returns false when no file URL is provided', async () => {
			const { isAutogeneratedChapterFile } = await getVideoTracksModule();

			await expect( isAutogeneratedChapterFile( '' ) ).resolves.toBe( false );
		} );

		it( 'detects the auto-generated marker in a public file', async () => {
			const fetchMock = jest
				.fn()
				.mockResolvedValue( okResponse( 'WEBVTT\n\nvideopress-chapters-auto-generated' ) );
			global.fetch = fetchMock;
			const { isAutogeneratedChapterFile } = await getVideoTracksModule();

			await expect(
				isAutogeneratedChapterFile( 'https://example.com/chapters.vtt', { guid: 'abc123' } )
			).resolves.toBe( true );
			expect( fetchMock ).toHaveBeenCalledWith( 'https://example.com/chapters.vtt' );
		} );

		it( 'returns false when the marker is absent', async () => {
			const fetchMock = jest.fn().mockResolvedValue( okResponse( 'WEBVTT\n\nJust a caption.' ) );
			global.fetch = fetchMock;
			const { isAutogeneratedChapterFile } = await getVideoTracksModule();

			await expect(
				isAutogeneratedChapterFile( 'https://example.com/chapters.vtt', { guid: 'abc123' } )
			).resolves.toBe( false );
		} );

		it( 'requests a playback token for private files', async () => {
			const getMediaToken = await getMediaTokenMock();
			getMediaToken.mockResolvedValue( { token: 'tok', blogId: 1 } );
			const fetchMock = jest
				.fn()
				.mockResolvedValue( okResponse( 'videopress-chapters-auto-generated' ) );
			global.fetch = fetchMock;
			const { isAutogeneratedChapterFile } = await getVideoTracksModule();

			await expect(
				isAutogeneratedChapterFile( 'https://example.com/chapters.vtt', {
					guid: 'abc123',
					isPrivate: true,
				} )
			).resolves.toBe( true );

			expect( getMediaToken ).toHaveBeenCalledWith( 'playback', { guid: 'abc123' } );
			expect( fetchMock ).toHaveBeenCalledWith(
				'https://example.com/chapters.vtt?metadata_token=tok'
			);
		} );

		it( 'retries with a token when a public request is forbidden', async () => {
			const getMediaToken = await getMediaTokenMock();
			getMediaToken.mockResolvedValue( { token: 'tok', blogId: 1 } );
			const fetchMock = jest
				.fn()
				.mockResolvedValueOnce( { ok: false, status: 403 } )
				.mockResolvedValueOnce( okResponse( 'videopress-chapters-auto-generated' ) );
			global.fetch = fetchMock;
			const { isAutogeneratedChapterFile } = await getVideoTracksModule();

			await expect(
				isAutogeneratedChapterFile( 'https://example.com/chapters.vtt', { guid: 'abc123' } )
			).resolves.toBe( true );

			expect( fetchMock ).toHaveBeenCalledTimes( 2 );
			expect( fetchMock ).toHaveBeenLastCalledWith(
				'https://example.com/chapters.vtt?metadata_token=tok'
			);
		} );

		it( 'returns false when the request fails', async () => {
			const fetchMock = jest.fn().mockResolvedValue( { ok: false, status: 500 } );
			global.fetch = fetchMock;
			const { isAutogeneratedChapterFile } = await getVideoTracksModule();

			await expect(
				isAutogeneratedChapterFile( 'https://example.com/chapters.vtt', { guid: 'abc123' } )
			).resolves.toBe( false );
		} );
	} );

	describe( 'updateTrackForGuid', () => {
		it( 'patches wpcom/v2 track metadata by track id', async () => {
			const apiFetch = await getApiFetchMock();
			apiFetch.mockResolvedValue( { text: () => Promise.resolve( '{}' ) } );
			const { updateTrackForGuid } = await getVideoTracksModule();

			await updateTrackForGuid(
				{ id: 'track-1', kind: 'captions', srcLang: 'en', label: 'English' },
				'abc123'
			);

			expect( apiFetch ).toHaveBeenCalledWith(
				expect.objectContaining( {
					apiNamespace: 'wpcom/v2',
					body: JSON.stringify( { kind: 'captions', srclang: 'en', label: 'English' } ),
					global: true,
					headers: { 'Content-Type': 'application/json' },
					method: 'PATCH',
					path: '/videopress/videos/abc123/tracks/track-1',
					parse: false,
				} )
			);
		} );

		it( 'throws when the track id cannot be resolved', async () => {
			const apiFetch = await getApiFetchMock();
			apiFetch.mockResolvedValue( {
				text: () => Promise.resolve( JSON.stringify( { tracks: [] } ) ),
			} );
			const { updateTrackForGuid } = await getVideoTracksModule();

			await expect(
				updateTrackForGuid( { kind: 'captions', srcLang: 'fr', label: 'French' }, 'abc123' )
			).rejects.toThrow( 'Track ID is required to update track metadata.' );
		} );
	} );
} );
