jest.mock( '@wordpress/api-fetch', () => jest.fn() );
jest.mock( '../../get-media-token', () => jest.fn() );
jest.mock( '../../fetch-video-item', () => ( { fetchVideoItem: jest.fn() } ) );
jest.mock( 'debug', () => () => jest.fn() );

declare const global: typeof globalThis & { fetch: jest.MockedFunction< typeof fetch > };

const getVideoTracksModule = async () => {
	Object.defineProperty( window, 'videoPressEditorState', {
		configurable: true,
		value: { siteType: 'simple' },
	} );

	return import( '..' );
};

const getApiFetchMock = async () =>
	( await import( '@wordpress/api-fetch' ) ).default as unknown as jest.Mock;

const getMediaTokenMock = async () =>
	( await import( '../../get-media-token' ) ).default as jest.Mock;

const getFetchVideoItemMock = async () =>
	( await import( '../../fetch-video-item' ) ).fetchVideoItem as jest.Mock;

describe( 'video-tracks', () => {
	beforeEach( () => {
		jest.resetModules();
		jest.clearAllMocks();
	} );

	it( 'flattens legacy nested track responses', async () => {
		const { flattenVideoTracks } = await getVideoTracksModule();

		expect(
			flattenVideoTracks( {
				captions: {
					en: {
						src: 'english.vtt',
						label: 'English',
					},
				},
			} )
		).toEqual( [
			{
				kind: 'captions',
				label: 'English',
				src: 'english.vtt',
				srcLang: 'en',
			},
		] );
	} );

	it( 'flattens array track responses with ids', async () => {
		const { flattenVideoTracks } = await getVideoTracksModule();

		expect(
			flattenVideoTracks( {
				tracks: [
					{
						track_id: 'track-1',
						kind: 'captions',
						src_lang: 'en-US',
						label: 'English',
						download_url: 'english.vtt',
						source: 'manual',
						status: 'ready',
						is_auto_generated: false,
						is_auto_synced: true,
						is_draft: true,
					},
				],
			} )
		).toEqual( [
			{
				id: 'track-1',
				downloadUrl: 'english.vtt',
				kind: 'captions',
				isAutoGenerated: false,
				isAutoSynced: true,
				isDraft: true,
				label: 'English',
				source: 'manual',
				src: 'english.vtt',
				srcLang: 'en-US',
				status: 'ready',
			},
		] );
	} );

	it( 'uploads tracks to the v1 tracks endpoint in the vtt field', async () => {
		const apiFetch = await getApiFetchMock();
		const file = new File( [ 'WEBVTT' ], 'english.vtt', { type: 'text/vtt' } );
		apiFetch.mockResolvedValue( {
			json: () => Promise.resolve( 'video_captions_en.vtt' ),
		} );
		const { uploadTrackForGuid } = await getVideoTracksModule();

		await expect(
			uploadTrackForGuid(
				{
					kind: 'captions',
					srcLang: 'en',
					label: 'English',
					tmpFile: file,
				},
				'abc123'
			)
		).resolves.toBe( 'video_captions_en.vtt' );

		expect( apiFetch ).toHaveBeenCalledWith(
			expect.objectContaining( {
				apiNamespace: 'rest/v1.1',
				formData: [
					[ 'kind', 'captions' ],
					[ 'srclang', 'en' ],
					[ 'label', 'English' ],
					[ 'vtt', file ],
				],
				global: true,
				method: 'POST',
				path: '/videos/abc123/tracks',
				parse: false,
			} )
		);
	} );

	it( 'normalizes an uploaded track response with fallback metadata', async () => {
		const { normalizeVideoTextTrackResponse } = await getVideoTracksModule();

		expect(
			normalizeVideoTextTrackResponse(
				{
					data: {
						track_id: 'track-1',
						src: 'uploaded.vtt',
					},
				},
				{
					kind: 'captions',
					srcLang: 'en',
					label: 'English',
				}
			)
		).toEqual( {
			id: 'track-1',
			kind: 'captions',
			label: 'English',
			src: 'uploaded.vtt',
			srcLang: 'en',
		} );
	} );

	it( 'deletes v1 tracks by kind and language', async () => {
		const apiFetch = await getApiFetchMock();
		apiFetch.mockResolvedValue( {
			json: () => Promise.resolve( true ),
		} );
		const { deleteTrackForGuid } = await getVideoTracksModule();

		await deleteTrackForGuid(
			{
				kind: 'captions',
				srcLang: 'en',
			},
			'abc123'
		);

		expect( apiFetch ).toHaveBeenCalledWith(
			expect.objectContaining( {
				apiNamespace: 'rest/v1.1',
				formData: [
					[ 'kind', 'captions' ],
					[ 'srclang', 'en' ],
				],
				global: true,
				method: 'POST',
				path: '/videos/abc123/tracks/delete',
				parse: false,
			} )
		);
	} );

	describe( 'fetchTrackContentForGuid', () => {
		it( 'resolves a filename against the video file_url_base and fetches it', async () => {
			const fetchVideoItem = await getFetchVideoItemMock();
			fetchVideoItem.mockResolvedValue( {
				file_url_base: { https: 'https://videos.files.wordpress.com/abc123/' },
			} );
			const fetchMock = jest.fn().mockResolvedValue( {
				ok: true,
				status: 200,
				text: () => Promise.resolve( 'WEBVTT\n\nCaption text.' ),
			} );
			global.fetch = fetchMock;
			const { fetchTrackContentForGuid } = await getVideoTracksModule();

			await expect(
				fetchTrackContentForGuid(
					{ kind: 'captions', srcLang: 'en', label: 'English', src: 'english.vtt' },
					'abc123'
				)
			).resolves.toBe( 'WEBVTT\n\nCaption text.' );

			expect( fetchVideoItem ).toHaveBeenCalledWith( { guid: 'abc123', isPrivate: false } );
			expect( fetchMock ).toHaveBeenCalledWith(
				'https://videos.files.wordpress.com/abc123/english.vtt'
			);
		} );

		it( 'fetches an absolute track src directly without resolving a base', async () => {
			const fetchVideoItem = await getFetchVideoItemMock();
			const fetchMock = jest.fn().mockResolvedValue( {
				ok: true,
				status: 200,
				text: () => Promise.resolve( 'WEBVTT' ),
			} );
			global.fetch = fetchMock;
			const { fetchTrackContentForGuid } = await getVideoTracksModule();

			await expect(
				fetchTrackContentForGuid(
					{
						kind: 'captions',
						srcLang: 'en',
						label: 'English',
						src: 'https://example.com/english.vtt',
					},
					'abc123'
				)
			).resolves.toBe( 'WEBVTT' );

			expect( fetchVideoItem ).not.toHaveBeenCalled();
			expect( fetchMock ).toHaveBeenCalledWith( 'https://example.com/english.vtt' );
		} );

		it( 'retries with a playback token when the file is forbidden', async () => {
			const getMediaToken = await getMediaTokenMock();
			getMediaToken.mockResolvedValue( { token: 'tok', blogId: 1 } );
			const fetchMock = jest
				.fn()
				.mockResolvedValueOnce( { ok: false, status: 403 } )
				.mockResolvedValueOnce( {
					ok: true,
					status: 200,
					text: () => Promise.resolve( 'WEBVTT' ),
				} );
			global.fetch = fetchMock;
			const { fetchTrackContentForGuid } = await getVideoTracksModule();

			await expect(
				fetchTrackContentForGuid(
					{
						kind: 'captions',
						srcLang: 'en',
						label: 'English',
						src: 'https://example.com/english.vtt',
					},
					'abc123'
				)
			).resolves.toBe( 'WEBVTT' );

			expect( getMediaToken ).toHaveBeenCalledWith( 'playback', { guid: 'abc123' } );
			expect( fetchMock ).toHaveBeenLastCalledWith(
				'https://example.com/english.vtt?metadata_token=tok'
			);
		} );

		it( 'returns an empty string when the track has no src', async () => {
			const { fetchTrackContentForGuid } = await getVideoTracksModule();

			await expect(
				fetchTrackContentForGuid(
					{ kind: 'captions', srcLang: 'en', label: 'English', src: '' },
					'abc123'
				)
			).resolves.toBe( '' );
		} );

		it( 'returns an empty string when the network request rejects', async () => {
			const fetchMock = jest.fn().mockRejectedValue( new Error( 'Network down' ) );
			global.fetch = fetchMock;
			const { fetchTrackContentForGuid } = await getVideoTracksModule();

			await expect(
				fetchTrackContentForGuid(
					{
						kind: 'captions',
						srcLang: 'en',
						label: 'English',
						src: 'https://example.com/english.vtt',
					},
					'abc123'
				)
			).resolves.toBe( '' );
		} );
	} );

	describe( 'isAutogeneratedChapterFile', () => {
		const okResponse = ( body: string ) => ( {
			ok: true,
			status: 200,
			text: () => Promise.resolve( body ),
		} );

		it( 'returns false when no file URL is provided', async () => {
			const { isAutogeneratedChapterFile } = await getVideoTracksModule();

			await expect( isAutogeneratedChapterFile( '' ) ).resolves.toBe( false );
		} );

		it( 'detects the auto-generated marker in a public file', async () => {
			const fetchMock = jest
				.fn()
				.mockResolvedValue( okResponse( 'WEBVTT\n\nvideopress-chapters-auto-generated' ) );
			global.fetch = fetchMock;
			const { isAutogeneratedChapterFile } = await getVideoTracksModule();

			await expect(
				isAutogeneratedChapterFile( 'https://example.com/chapters.vtt', { guid: 'abc123' } )
			).resolves.toBe( true );
			expect( fetchMock ).toHaveBeenCalledWith( 'https://example.com/chapters.vtt' );
		} );

		it( 'returns false when the marker is absent', async () => {
			const fetchMock = jest.fn().mockResolvedValue( okResponse( 'WEBVTT\n\nJust a caption.' ) );
			global.fetch = fetchMock;
			const { isAutogeneratedChapterFile } = await getVideoTracksModule();

			await expect(
				isAutogeneratedChapterFile( 'https://example.com/chapters.vtt', { guid: 'abc123' } )
			).resolves.toBe( false );
		} );

		it( 'requests a playback token for private files', async () => {
			const getMediaToken = await getMediaTokenMock();
			getMediaToken.mockResolvedValue( { token: 'tok', blogId: 1 } );
			const fetchMock = jest
				.fn()
				.mockResolvedValue( okResponse( 'videopress-chapters-auto-generated' ) );
			global.fetch = fetchMock;
			const { isAutogeneratedChapterFile } = await getVideoTracksModule();

			await expect(
				isAutogeneratedChapterFile( 'https://example.com/chapters.vtt', {
					guid: 'abc123',
					isPrivate: true,
				} )
			).resolves.toBe( true );

			expect( getMediaToken ).toHaveBeenCalledWith( 'playback', { guid: 'abc123' } );
			expect( fetchMock ).toHaveBeenCalledWith(
				'https://example.com/chapters.vtt?metadata_token=tok'
			);
		} );

		it( 'retries with a token when a public request is forbidden', async () => {
			const getMediaToken = await getMediaTokenMock();
			getMediaToken.mockResolvedValue( { token: 'tok', blogId: 1 } );
			const fetchMock = jest
				.fn()
				.mockResolvedValueOnce( { ok: false, status: 403 } )
				.mockResolvedValueOnce( okResponse( 'videopress-chapters-auto-generated' ) );
			global.fetch = fetchMock;
			const { isAutogeneratedChapterFile } = await getVideoTracksModule();

			await expect(
				isAutogeneratedChapterFile( 'https://example.com/chapters.vtt', { guid: 'abc123' } )
			).resolves.toBe( true );

			expect( fetchMock ).toHaveBeenCalledTimes( 2 );
			expect( fetchMock ).toHaveBeenLastCalledWith(
				'https://example.com/chapters.vtt?metadata_token=tok'
			);
		} );

		it( 'returns false when the request fails', async () => {
			const fetchMock = jest.fn().mockResolvedValue( { ok: false, status: 500 } );
			global.fetch = fetchMock;
			const { isAutogeneratedChapterFile } = await getVideoTracksModule();

			await expect(
				isAutogeneratedChapterFile( 'https://example.com/chapters.vtt', { guid: 'abc123' } )
			).resolves.toBe( false );
		} );
	} );
} );
