export const JETPACK_PLUGINS_DATA_FETCH = 'JETPACK_PLUGINS_DATA_FETCH';
export const JETPACK_PLUGINS_DATA_FETCH_RECEIVE = 'JETPACK_PLUGINS_DATA_FETCH_RECEIVE';
export const JETPACK_PLUGINS_DATA_FETCH_FAIL = 'JETPACK_PLUGINS_DATA_FETCH_FAIL';