export const ASYNC_ROUTINE_DISPATCH = 'ASYNC_ROUTINE_DISPATCH';
export const FINISH_RESOLUTION = 'FINISH_RESOLUTION';

export const RESPONSES_FETCH = 'RESPONSES_FETCH';
export const RESPONSES_FETCH_RECEIVE = 'RESPONSES_FETCH_RECEIVE';
export const RESPONSES_FETCH_FAIL = 'RESPONSES_FETCH_FAIL';

export const INBOX_SEARCH = 'INBOX_SEARCH';
