export const ASYNC_ROUTINE_DISPATCH = 'ASYNC_ROUTINE_DISPATCH';
export const FINISH_RESOLUTION = 'FINISH_RESOLUTION';

export const JETPACK_FORMS_RESPONSES_FETCH = 'JETPACK_FORMS_RESPONSES_FETCH';
export const JETPACK_FORMS_RESPONSES_FETCH_RECEIVE = 'JETPACK_FORMS_RESPONSES_FETCH_RECEIVE';
export const JETPACK_FORMS_RESPONSES_FETCH_FAIL = 'JETPACK_FORMS_RESPONSES_FETCH_FAIL';
