export const ASYNC_ROUTINE_DISPATCH = 'ASYNC_ROUTINE_DISPATCH';

export const RESPONSES_FETCH = 'RESPONSES_FETCH';
export const RESPONSES_FETCH_RECEIVE = 'RESPONSES_FETCH_RECEIVE';
export const RESPONSES_FETCH_FAIL = 'RESPONSES_FETCH_FAIL';

export const RESPONSES_CURRENT_PAGE_SET = 'RESPONSES_CURRENT_PAGE_SET';

export const RESPONSES_LOADING_SET = 'RESPONSES_LOADING_SET';

export const RESPONSES_QUERY_RESET = 'RESPONSES_QUERY_RESET';
export const RESPONSES_QUERY_SEARCH_UPDATE = 'RESPONSES_QUERY_SEARCH_UPDATE';
export const RESPONSES_QUERY_STATUS_UPDATE = 'RESPONSES_QUERY_STATUS_UPDATE';
export const RESPONSES_QUERY_MONTH_UPDATE = 'RESPONSES_QUERY_MONTH_UPDATE';
export const RESPONSES_QUERY_SOURCE_UPDATE = 'RESPONSES_QUERY_SOURCE_UPDATE';
