/**
 * Manual-chapters-track probe, shared by every chapters editing surface
 * (the dashboard editor's Chapters tool and the block editor's chapter
 * manager modal).
 *
 * A chapters VTT uploaded by the user must never be regenerated from the
 * description, so editors probe before offering edits. The probe fails OPEN:
 * any error reports 'editable', because `syncChapters` re-checks the guard
 * authoritatively at write time — a false 'editable' only shows edit
 * affordances whose save would then skip the VTT sync, while a false
 * 'manual' would lock the user out of a perfectly editable video.
 */
import { fetchVideoItem } from '../../../lib/fetch-video-item';
import { isAutogeneratedChapterFile } from '../../../lib/video-tracks';
import type {
	VideoTracksLegacyResponseBodyProps,
	WPCOMRestAPIVideosGetEndpointResponseProps,
} from '../../../types';

/**
 * The fields the probe needs from a video.
 */
export type ChaptersProbeVideo = {
	/** The video's VideoPress guid. */
	guid: string;
	/** Whether the video is private (the probe must sign its requests). */
	isPrivate: boolean;
};

/**
 * Options for `probeManualTrack`.
 */
export type ChaptersProbeOptions = {
	/**
	 * A video item already fetched by the caller (from `fetchVideoItem`),
	 * so a surface that fetches the item anyway doesn't fetch it twice.
	 */
	item?: WPCOMRestAPIVideosGetEndpointResponseProps;
};

/**
 * Probe whether the video carries a MANUALLY uploaded chapters VTT (which
 * the chapters editors must never touch).
 *
 * @param video   - The video to probe.
 * @param options - Optional pre-fetched video item to reuse.
 * @return Whether the chapters track is manual or safe to edit.
 */
export async function probeManualTrack(
	video: ChaptersProbeVideo,
	options?: ChaptersProbeOptions
): Promise< 'manual' | 'editable' > {
	try {
		const item =
			options?.item ?? ( await fetchVideoItem( { guid: video.guid, isPrivate: video.isPrivate } ) );
		/*
		 * fetchVideoItem returns the legacy kind→language nested track map,
		 * so narrow the broader response type before reading the chapters
		 * source.
		 */
		const legacyTracks = item?.tracks as VideoTracksLegacyResponseBodyProps | undefined;
		const trackSrc = legacyTracks?.chapters?.en?.src;
		if ( typeof trackSrc !== 'string' || trackSrc === '' ) {
			return 'editable';
		}
		const trackUrl = `https://videos.files.wordpress.com/${ video.guid }/${ trackSrc }`;
		const isAutogenerated = await isAutogeneratedChapterFile( trackUrl, {
			guid: video.guid,
			isPrivate: video.isPrivate,
		} );
		return isAutogenerated ? 'editable' : 'manual';
	} catch {
		return 'editable';
	}
}
