<?php
/**
 * Phan only sees the root-namespace versions of the classes,
 * it doesn't know about what gets generated by the test infrastructure.
 * So add stubs here.
 *
 * The tests also use some other on-the-fly or nonexistent classes that confuse Phan.
 *
 * @package automattic/jetpack-autoloader
 */

namespace Automattic\Jetpack\Autoloader\jpCurrent {
	class Autoloader extends \Autoloader {}
	class Autoloader_Handler extends \Autoloader_Handler {}
	class Autoloader_Locator extends \Autoloader_Locator {}
	class Container extends \Container {}
	class Hook_Manager extends \Hook_Manager {}
	class Latest_Autoloader_Guard extends \Latest_Autoloader_Guard {}
	class Manifest_Reader extends \Manifest_Reader {}
	class Path_Processor extends \Path_Processor {}
	class PHP_Autoloader extends \PHP_Autoloader {}
	class Plugin_Locator extends \Plugin_Locator {}
	class Plugins_Handler extends \Plugins_Handler {}
	class Shutdown_Handler extends \Shutdown_Handler {}
	class Version_Loader extends \Version_Loader {}
	class Version_Selector extends \Version_Selector {}
}

namespace {
	class Classmap_Test_Class {}
}

namespace Automattic\Jetpack\AutoloaderTesting {
	class SharedTestClass {}
}

namespace Automattic\Jetpack\AutoloaderTesting\Current {
	class UniqueTestClass {}
}

namespace Automattic\Jetpack\AutoloaderTesting\Currentmu {
	class UniqueTestClass {}
}
