export const RECEIVE_CONFIG = 'RECEIVE_CONFIG';
export const RECEIVE_CONFIG_VALUE = 'RECEIVE_CONFIG_VALUE';
export const INVALIDATE_CONFIG = 'INVALIDATE_CONFIG';
export const SET_CONFIG_LOADING = 'SET_CONFIG_LOADING';
export const SET_CONFIG_ERROR = 'SET_CONFIG_ERROR';
