<?php
/**
 * This is an automatically generated baseline for Phan issues.
 * When Phan is invoked with --load-baseline=path/to/baseline.php,
 * The pre-existing issues listed in this file won't be emitted.
 *
 * This file can be updated by invoking Phan with --save-baseline=path/to/baseline.php
 * (can be combined with --load-baseline)
 */
return [
    // # Issue statistics:
    // PhanTypeMismatchArgument : 420+ occurrences
    // PhanTypeMismatchArgumentProbablyReal : 220+ occurrences
    // PhanTypeMismatchReturn : 140+ occurrences
    // PhanTypeMismatchReturnProbablyReal : 110+ occurrences
    // PhanTypePossiblyInvalidDimOffset : 90+ occurrences
    // PhanTypeArraySuspiciousNullable : 70+ occurrences
    // PhanDeprecatedFunction : 60+ occurrences
    // PhanRedefineFunction : 45+ occurrences
    // PhanTypeExpectedObjectPropAccess : 30+ occurrences
    // PhanDeprecatedProperty : 25+ occurrences
    // PhanTypeMismatchDefault : 25+ occurrences
    // PhanTypeMismatchPropertyProbablyReal : 25+ occurrences
    // PhanParamSignatureMismatch : 20+ occurrences
    // PhanTypeMismatchDimFetch : 20+ occurrences
    // PhanUndeclaredMethod : 20+ occurrences
    // PhanSuspiciousMagicConstant : 15+ occurrences
    // PhanTypeArraySuspicious : 15+ occurrences
    // PhanTypeMismatchArgumentNullable : 15+ occurrences
    // PhanTypeMismatchPropertyDefault : 15+ occurrences
    // PhanTypeSuspiciousNonTraversableForeach : 15+ occurrences
    // PhanPluginMixedKeyNoKey : 10+ occurrences
    // PhanPluginUnreachableCode : 10+ occurrences
    // PhanRedefineClass : 10+ occurrences
    // PhanTypeMismatchArgumentNullableInternal : 10+ occurrences
    // PhanTypeMismatchProperty : 10+ occurrences
    // PhanTypeMismatchReturnNullable : 10+ occurrences
    // PhanUndeclaredFunction : 10+ occurrences
    // PhanRedefinedClassReference : 8 occurrences
    // PhanTypeMissingReturn : 8 occurrences
    // PhanTypeComparisonToArray : 7 occurrences
    // PhanCommentAbstractOnInheritedMethod : 6 occurrences
    // PhanTypeMismatchArgumentInternal : 6 occurrences
    // PhanDeprecatedClass : 5 occurrences
    // PhanPossiblyUndeclaredVariable : 5 occurrences
    // PhanTypeMismatchDimAssignment : 5 occurrences
    // PhanTypeInvalidDimOffset : 4 occurrences
    // PhanTypeInvalidLeftOperandOfAdd : 4 occurrences
    // PhanTypeInvalidLeftOperandOfBitwiseOp : 4 occurrences
    // PhanTypeInvalidLeftOperandOfNumericOp : 4 occurrences
    // PhanTypeInvalidRightOperandOfBitwiseOp : 4 occurrences
    // PhanDeprecatedTrait : 3 occurrences
    // PhanStaticPropIsStaticType : 3 occurrences
    // PhanTypeMismatchArgumentReal : 3 occurrences
    // PhanTypeObjectUnsetDeclaredProperty : 3 occurrences
    // PhanUndeclaredMethodInCallable : 3 occurrences
    // PhanDeprecatedFunctionInternal : 2 occurrences
    // PhanImpossibleConditionInLoop : 2 occurrences
    // PhanNonClassMethodCall : 2 occurrences
    // PhanParamTooManyCallable : 2 occurrences
    // PhanPluginDuplicateSwitchCaseLooseEquality : 2 occurrences
    // PhanUndeclaredClassInCallable : 2 occurrences
    // PhanUndeclaredClassMethod : 2 occurrences
    // PhanUndeclaredFunctionInCallable : 2 occurrences
    // PhanCoalescingAlwaysNull : 1 occurrence
    // PhanDeprecatedPartiallySupportedCallable : 1 occurrence
    // PhanPluginInvalidPregRegex : 1 occurrence
    // PhanPluginUseReturnValueInternalKnown : 1 occurrence
    // PhanStaticCallToNonStatic : 1 occurrence
    // PhanTypeMismatchArgumentInternalProbablyReal : 1 occurrence
    // PhanTypeMismatchArgumentInternalReal : 1 occurrence
    // PhanTypeSuspiciousStringExpression : 1 occurrence
    // PhanUndeclaredExtendedClass : 1 occurrence
    // PhanUndeclaredTypeReturnType : 1 occurrence
    // PhanUndeclaredVariable : 1 occurrence
    // UnusedPluginSuppression : 1 occurrence

    // Currently, file_suppressions and directory_suppressions are the only supported suppressions
    'file_suppressions' => [
        '3rd-party/bbpress.php' => ['PhanTypeMismatchArgumentProbablyReal', 'PhanUndeclaredFunction'],
        '3rd-party/class-domain-mapping.php' => ['PhanUndeclaredClassInCallable', 'PhanUndeclaredClassMethod', 'PhanUndeclaredFunctionInCallable', 'PhanUndeclaredTypeReturnType'],
        '3rd-party/class-jetpack-bbpress-rest-api.php' => ['PhanUndeclaredFunction'],
        '3rd-party/class.jetpack-amp-support.php' => ['PhanDeprecatedFunction'],
        '3rd-party/debug-bar/class-jetpack-search-debug-bar.php' => ['PhanUndeclaredExtendedClass', 'PhanUndeclaredMethod'],
        '3rd-party/qtranslate-x.php' => ['PhanTypeMismatchReturn'],
        '3rd-party/wpml.php' => ['PhanUndeclaredFunction'],
        '_inc/class.jetpack-provision.php' => ['PhanTypeMismatchArgument', 'PhanTypeMismatchReturnNullable'],
        '_inc/genericons.php' => ['PhanTypeMismatchArgumentProbablyReal'],
        '_inc/lib/admin-pages/class-jetpack-about-page.php' => ['PhanTypeMismatchArgument'],
        '_inc/lib/admin-pages/class-jetpack-redux-state-helper.php' => ['PhanTypeMismatchDimAssignment'],
        '_inc/lib/admin-pages/class.jetpack-admin-page.php' => ['PhanTypeMismatchReturnProbablyReal'],
        '_inc/lib/class-jetpack-ai-helper.php' => ['PhanTypeMismatchArgument', 'PhanTypeMismatchPropertyDefault'],
        '_inc/lib/class-jetpack-instagram-gallery-helper.php' => ['PhanTypeMismatchArgument'],
        '_inc/lib/class-jetpack-mapbox-helper.php' => ['PhanTypeMismatchArgumentNullable'],
        '_inc/lib/class-jetpack-podcast-feed-locator.php' => ['PhanDeprecatedFunctionInternal'],
        '_inc/lib/class-jetpack-podcast-helper.php' => ['PhanStaticCallToNonStatic', 'PhanTypeMismatchReturnProbablyReal', 'PhanTypeSuspiciousStringExpression'],
        '_inc/lib/class.core-rest-api-endpoints.php' => ['PhanTypeMismatchArgumentInternal', 'PhanTypeMismatchArgumentProbablyReal', 'PhanTypeMismatchDefault', 'PhanTypeMismatchReturn', 'PhanTypeMismatchReturnProbablyReal', 'PhanUndeclaredMethod'],
        '_inc/lib/class.jetpack-password-checker.php' => ['PhanTypeMismatchArgument', 'PhanTypeMismatchDefault', 'PhanTypeMismatchProperty', 'PhanTypeMismatchPropertyDefault', 'PhanTypeMismatchPropertyProbablyReal'],
        '_inc/lib/class.media-extractor.php' => ['PhanTypeMismatchDefault', 'PhanTypePossiblyInvalidDimOffset'],
        '_inc/lib/class.media.php' => ['PhanTypePossiblyInvalidDimOffset'],
        '_inc/lib/core-api/class-wpcom-rest-field-controller.php' => ['PhanTypeMismatchReturnProbablyReal', 'PhanTypeMissingReturn'],
        '_inc/lib/core-api/class.jetpack-core-api-module-endpoints.php' => ['PhanNonClassMethodCall', 'PhanTypeComparisonToArray', 'PhanTypeMismatchArgument', 'PhanTypeMismatchDimFetch', 'PhanTypeMismatchReturn'],
        '_inc/lib/core-api/class.jetpack-core-api-site-endpoints.php' => ['PhanTypeMismatchReturn'],
        '_inc/lib/core-api/class.jetpack-core-api-widgets-endpoints.php' => ['PhanTypeMismatchReturn'],
        '_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-admin-menu.php' => ['PhanPluginMixedKeyNoKey'],
        '_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-ai.php' => ['PhanPluginMixedKeyNoKey', 'PhanTypeMismatchArgument'],
        '_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-external-media.php' => ['PhanTypeMismatchArgumentProbablyReal'],
        '_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-newsletter-categories-list.php' => ['PhanUndeclaredMethod'],
        '_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-podcast-player.php' => ['PhanTypeMismatchReturn'],
        '_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-related-posts.php' => ['PhanPluginMixedKeyNoKey', 'PhanTypeMismatchReturn'],
        '_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-resolve-redirect.php' => ['PhanPluginMixedKeyNoKey'],
        '_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-send-email-preview.php' => ['PhanTypeMismatchReturn'],
        '_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-template-loader.php' => ['PhanTypeMismatchReturnProbablyReal'],
        '_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v3-endpoint-blogging-prompts.php' => ['PhanPluginMixedKeyNoKey', 'PhanTypeInvalidLeftOperandOfAdd', 'PhanTypeMismatchReturnProbablyReal'],
        '_inc/lib/core-api/wpcom-endpoints/gutenberg-available-extensions.php' => ['PhanPluginMixedKeyNoKey'],
        '_inc/lib/core-api/wpcom-endpoints/memberships.php' => ['PhanPluginUnreachableCode', 'PhanTypeArraySuspicious'],
        '_inc/lib/core-api/wpcom-endpoints/publicize-connection-test-results.php' => ['PhanPluginMixedKeyNoKey', 'PhanTypeMismatchArgument'],
        '_inc/lib/core-api/wpcom-endpoints/service-api-keys.php' => ['PhanTypeArraySuspicious', 'PhanTypeMismatchReturnProbablyReal'],
        '_inc/lib/debugger/class-jetpack-debug-data.php' => ['PhanTypeMismatchArgument'],
        '_inc/lib/debugger/class-jetpack-debugger.php' => ['PhanTypeMismatchArgumentProbablyReal'],
        '_inc/lib/debugger/debug-functions.php' => ['PhanTypeMismatchReturnProbablyReal'],
        '_inc/lib/icalendar-reader.php' => ['PhanPossiblyUndeclaredVariable', 'PhanTypeInvalidLeftOperandOfNumericOp', 'PhanTypeMismatchArgumentNullableInternal', 'PhanTypeMismatchDimFetch', 'PhanTypeMismatchReturnProbablyReal'],
        '_inc/lib/markdown/extra.php' => ['PhanImpossibleConditionInLoop', 'PhanPossiblyUndeclaredVariable', 'PhanTypeMismatchReturn'],
        '_inc/lib/plans.php' => ['PhanTypeMismatchReturn', 'PhanTypeMismatchReturnProbablyReal'],
        '_inc/lib/tonesque.php' => ['PhanRedefineClass', 'PhanRedefinedClassReference', 'PhanTypeMismatchArgument', 'PhanTypeMismatchArgumentProbablyReal'],
        '_inc/lib/widgets.php' => ['PhanTypeArraySuspiciousNullable', 'PhanTypeMismatchArgumentNullable', 'PhanTypeMismatchReturn'],
        '_inc/social-logos.php' => ['PhanTypeMismatchArgumentProbablyReal'],
        'class-jetpack-pre-connection-jitms.php' => ['PhanTypeMismatchArgument'],
        'class.jetpack-admin.php' => ['PhanPluginMixedKeyNoKey', 'PhanTypeMismatchArgumentProbablyReal'],
        'class.jetpack-autoupdate.php' => ['PhanTypeMismatchArgument'],
        'class.jetpack-cli.php' => ['PhanParamTooManyCallable', 'PhanTypeMismatchArgument', 'PhanTypeMismatchArgumentNullable', 'PhanTypeMismatchDefault', 'PhanTypeMismatchReturn'],
        'class.jetpack-gutenberg.php' => ['PhanTypeMismatchArgumentNullableInternal', 'PhanTypeMismatchPropertyProbablyReal', 'PhanTypeMismatchReturn'],
        'class.jetpack-heartbeat.php' => ['PhanTypeMismatchPropertyDefault'],
        'class.jetpack-modules-list-table.php' => ['PhanCommentAbstractOnInheritedMethod'],
        'class.jetpack-network-sites-list-table.php' => ['PhanCommentAbstractOnInheritedMethod'],
        'class.jetpack-network.php' => ['PhanTypeMismatchReturnNullable', 'PhanTypeMismatchReturnProbablyReal'],
        'class.jetpack.php' => ['PhanDeprecatedFunction', 'PhanTypeArraySuspiciousNullable', 'PhanTypeExpectedObjectPropAccess', 'PhanTypeMismatchArgument', 'PhanTypeMismatchArgumentNullableInternal', 'PhanTypeMismatchArgumentProbablyReal', 'PhanTypeMismatchDefault', 'PhanTypeMismatchPropertyDefault', 'PhanTypeMismatchReturn', 'PhanTypeMismatchReturnProbablyReal'],
        'class.json-api-endpoints.php' => ['PhanTypeArraySuspiciousNullable', 'PhanTypeComparisonToArray', 'PhanTypeMismatchArgument', 'PhanTypeMismatchArgumentInternal', 'PhanTypeMismatchArgumentNullable', 'PhanTypeMismatchArgumentProbablyReal', 'PhanTypeMismatchReturnProbablyReal'],
        'class.json-api.php' => ['PhanPluginDuplicateSwitchCaseLooseEquality', 'PhanTypeArraySuspicious', 'PhanTypeArraySuspiciousNullable', 'PhanTypeMismatchProperty', 'PhanTypeMismatchPropertyDefault', 'PhanTypeMismatchReturnProbablyReal'],
        'enhanced-open-graph.php' => ['PhanTypeArraySuspiciousNullable'],
        'extensions/blocks/ai-chat/ai-chat.php' => ['PhanTypeMismatchArgument'],
        'extensions/blocks/blog-stats/render.php' => ['PhanTypeMismatchReturnProbablyReal'],
        'extensions/blocks/calendly/render.php' => ['PhanTypeMismatchArgumentProbablyReal', 'PhanTypeMismatchReturnProbablyReal'],
        'extensions/blocks/gif/render.php' => ['PhanTypeMismatchReturnProbablyReal'],
        'extensions/blocks/image-compare/render.php' => ['PhanTypeMismatchArgument'],
        'extensions/blocks/like/render.php' => ['PhanTypeMismatchReturnProbablyReal'],
        'extensions/blocks/mailchimp/render.php' => ['PhanTypeMismatchReturnProbablyReal'],
        'extensions/blocks/nextdoor/render.php' => ['PhanTypeMismatchReturnProbablyReal'],
        'extensions/blocks/opentable/render.php' => ['PhanTypeMismatchArgumentNullableInternal'],
        'extensions/blocks/pinterest/pinterest.php' => ['PhanTypeArraySuspiciousNullable'],
        'extensions/blocks/premium-content/_inc/access-check.php' => ['PhanUndeclaredMethod'],
        'extensions/blocks/premium-content/_inc/subscription-service/class-abstract-token-subscription-service.php' => ['PhanParamSignatureMismatch', 'PhanTypeMismatchArgument', 'PhanTypeSuspiciousNonTraversableForeach'],
        'extensions/blocks/premium-content/_inc/subscription-service/class-jetpack-token-subscription-service.php' => ['PhanTypeMismatchReturn'],
        'extensions/blocks/premium-content/_inc/subscription-service/class-jwt.php' => ['PhanTypeMismatchReturnNullable'],
        'extensions/blocks/premium-content/_inc/subscription-service/class-wpcom-online-subscription-service.php' => ['PhanParamSignatureMismatch'],
        'extensions/blocks/rating-star/rating-meta.php' => ['PhanTypeMismatchArgument'],
        'extensions/blocks/rating-star/rating-star.php' => ['PhanTypeMismatchArgumentNullableInternal'],
        'extensions/blocks/sharing-button/class-sharing-source-block.php' => ['PhanTypeMismatchArgument', 'PhanTypeMismatchReturnProbablyReal'],
        'extensions/blocks/slideshow/render.php' => ['PhanTypeMismatchArgument'],
        'extensions/blocks/top-posts/render.php' => ['PhanTypeMismatchReturnProbablyReal'],
        'extensions/blocks/wordads/wordads.php' => ['PhanTypeMismatchArgument'],
        'functions.compat.php' => ['PhanRedefineFunction'],
        'functions.global.php' => ['PhanRedefineFunction', 'PhanSuspiciousMagicConstant', 'PhanTypeMismatchArgument'],
        'json-endpoints/class.wpcom-json-api-add-widget-endpoint.php' => ['PhanTypeMismatchReturn'],
        'json-endpoints/class.wpcom-json-api-autosave-post-v1-1-endpoint.php' => ['PhanTypeMismatchReturn'],
        'json-endpoints/class.wpcom-json-api-bulk-delete-post-endpoint.php' => ['PhanTypeMismatchArgument', 'PhanTypeMismatchReturn'],
        'json-endpoints/class.wpcom-json-api-bulk-restore-post-endpoint.php' => ['PhanParamSignatureMismatch', 'PhanTypeMismatchReturn'],
        'json-endpoints/class.wpcom-json-api-bulk-update-comments-endpoint.php' => ['PhanTypeMismatchReturn', 'PhanTypeMismatchReturnProbablyReal'],
        'json-endpoints/class.wpcom-json-api-comment-endpoint.php' => ['PhanTypeMismatchArgument'],
        'json-endpoints/class.wpcom-json-api-delete-media-endpoint.php' => ['PhanTypeMismatchReturn'],
        'json-endpoints/class.wpcom-json-api-delete-media-v1-1-endpoint.php' => ['PhanTypeMismatchReturn'],
        'json-endpoints/class.wpcom-json-api-edit-media-v1-2-endpoint.php' => ['PhanTypeMismatchReturn', 'PhanTypeMismatchReturnProbablyReal', 'PhanTypePossiblyInvalidDimOffset'],
        'json-endpoints/class.wpcom-json-api-get-comment-counts-endpoint.php' => ['PhanTypeMismatchReturn'],
        'json-endpoints/class.wpcom-json-api-get-comment-endpoint.php' => ['PhanTypeMismatchArgumentProbablyReal', 'PhanTypeMismatchReturn'],
        'json-endpoints/class.wpcom-json-api-get-comment-history-endpoint.php' => ['PhanTypeMismatchReturn'],
        'json-endpoints/class.wpcom-json-api-get-comments-tree-endpoint.php' => ['PhanTypeMismatchReturn', 'PhanTypeMismatchReturnProbablyReal'],
        'json-endpoints/class.wpcom-json-api-get-comments-tree-v1-2-endpoint.php' => ['PhanTypeMismatchReturn', 'PhanTypeMismatchReturnProbablyReal'],
        'json-endpoints/class.wpcom-json-api-get-customcss.php' => ['PhanTypeMismatchReturn'],
        'json-endpoints/class.wpcom-json-api-get-media-endpoint.php' => ['PhanTypeMismatchReturn'],
        'json-endpoints/class.wpcom-json-api-get-media-v1-1-endpoint.php' => ['PhanTypeMismatchReturn'],
        'json-endpoints/class.wpcom-json-api-get-post-counts-v1-1-endpoint.php' => ['PhanTypeMismatchReturn', 'PhanTypeMismatchReturnProbablyReal'],
        'json-endpoints/class.wpcom-json-api-get-post-endpoint.php' => ['PhanTypeMismatchArgument', 'PhanTypeMismatchReturn'],
        'json-endpoints/class.wpcom-json-api-get-post-v1-1-endpoint.php' => ['PhanTypeMismatchArgument', 'PhanTypeMismatchReturn'],
        'json-endpoints/class.wpcom-json-api-get-site-endpoint.php' => ['PhanTypeMismatchReturn'],
        'json-endpoints/class.wpcom-json-api-get-taxonomies-endpoint.php' => ['PhanTypeMismatchReturn'],
        'json-endpoints/class.wpcom-json-api-get-taxonomy-endpoint.php' => ['PhanTypeMismatchReturn', 'PhanTypeMismatchReturnNullable'],
        'json-endpoints/class.wpcom-json-api-get-term-endpoint.php' => ['PhanTypeMismatchReturn', 'PhanTypeMismatchReturnNullable'],
        'json-endpoints/class.wpcom-json-api-list-comments-endpoint.php' => ['PhanCommentAbstractOnInheritedMethod', 'PhanParamSignatureMismatch', 'PhanTypeMismatchArgument', 'PhanTypeMismatchReturn'],
        'json-endpoints/class.wpcom-json-api-list-dropdown-pages-endpoint.php' => ['PhanTypeMismatchDimFetch', 'PhanTypeMismatchReturn', 'PhanTypeSuspiciousNonTraversableForeach'],
        'json-endpoints/class.wpcom-json-api-list-embeds-endpoint.php' => ['PhanTypeMismatchReturn'],
        'json-endpoints/class.wpcom-json-api-list-media-endpoint.php' => ['PhanTypeMismatchDefault', 'PhanTypeMismatchReturn'],
        'json-endpoints/class.wpcom-json-api-list-media-v1-1-endpoint.php' => ['PhanTypeMismatchDefault', 'PhanTypeMismatchReturn'],
        'json-endpoints/class.wpcom-json-api-list-media-v1-2-endpoint.php' => ['PhanTypeMismatchDefault'],
        'json-endpoints/class.wpcom-json-api-list-post-type-taxonomies-endpoint.php' => ['PhanTypeMismatchDefault', 'PhanTypeMismatchReturn'],
        'json-endpoints/class.wpcom-json-api-list-post-types-endpoint.php' => ['PhanTypeMismatchDefault', 'PhanTypeMismatchReturn'],
        'json-endpoints/class.wpcom-json-api-list-posts-endpoint.php' => ['PhanTypeMismatchArgument', 'PhanTypeMismatchDefault', 'PhanTypeMismatchReturn', 'PhanTypePossiblyInvalidDimOffset'],
        'json-endpoints/class.wpcom-json-api-list-posts-v1-1-endpoint.php' => ['PhanTypeInvalidDimOffset', 'PhanTypeMismatchArgument', 'PhanTypeMismatchDefault', 'PhanTypeMismatchReturn', 'PhanTypePossiblyInvalidDimOffset'],
        'json-endpoints/class.wpcom-json-api-list-posts-v1-2-endpoint.php' => ['PhanTypeInvalidDimOffset', 'PhanTypeMismatchArgument', 'PhanTypeMismatchDefault', 'PhanTypeMismatchReturn', 'PhanTypePossiblyInvalidDimOffset'],
        'json-endpoints/class.wpcom-json-api-list-roles-endpoint.php' => ['PhanDeprecatedPartiallySupportedCallable', 'PhanTypeMismatchDefault', 'PhanTypeMismatchReturn'],
        'json-endpoints/class.wpcom-json-api-list-shortcodes-endpoint.php' => ['PhanTypeMismatchDefault', 'PhanTypeMismatchReturn'],
        'json-endpoints/class.wpcom-json-api-list-terms-endpoint.php' => ['PhanTypeMismatchDefault', 'PhanTypeMismatchReturn', 'PhanTypeSuspiciousNonTraversableForeach'],
        'json-endpoints/class.wpcom-json-api-list-users-endpoint.php' => ['PhanTypeMismatchDefault', 'PhanTypeMismatchReturn'],
        'json-endpoints/class.wpcom-json-api-menus-v1-1-endpoint.php' => ['PhanTypeMismatchArgument', 'PhanTypeMismatchReturn', 'PhanTypeMismatchReturnProbablyReal', 'PhanTypePossiblyInvalidDimOffset'],
        'json-endpoints/class.wpcom-json-api-post-endpoint.php' => ['PhanTypeMismatchArgument', 'PhanTypeMismatchArgumentInternalReal', 'PhanTypeMismatchArgumentNullableInternal', 'PhanTypeMismatchReturn', 'PhanTypeSuspiciousNonTraversableForeach'],
        'json-endpoints/class.wpcom-json-api-post-v1-1-endpoint.php' => ['PhanTypeMismatchArgument', 'PhanTypeMismatchReturn'],
        'json-endpoints/class.wpcom-json-api-render-embed-endpoint.php' => ['PhanTypeMismatchReturn'],
        'json-endpoints/class.wpcom-json-api-render-embed-reversal-endpoint.php' => ['PhanTypeMismatchReturn'],
        'json-endpoints/class.wpcom-json-api-render-shortcode-endpoint.php' => ['PhanTypeMismatchReturn'],
        'json-endpoints/class.wpcom-json-api-sharing-buttons-endpoint.php' => ['PhanTypeMismatchArgument', 'PhanTypeMismatchReturn', 'PhanTypePossiblyInvalidDimOffset'],
        'json-endpoints/class.wpcom-json-api-site-settings-endpoint.php' => ['PhanDeprecatedFunction', 'PhanTypeMismatchArgument', 'PhanTypeMismatchReturn', 'PhanTypePossiblyInvalidDimOffset'],
        'json-endpoints/class.wpcom-json-api-site-user-endpoint.php' => ['PhanTypeMismatchArgument', 'PhanTypeMismatchArgumentInternalProbablyReal', 'PhanTypeMismatchReturn', 'PhanTypeMismatchReturnNullable'],
        'json-endpoints/class.wpcom-json-api-update-comment-endpoint.php' => ['PhanTypeMismatchArgument', 'PhanTypeMismatchReturn'],
        'json-endpoints/class.wpcom-json-api-update-customcss.php' => ['PhanTypeMismatchReturn'],
        'json-endpoints/class.wpcom-json-api-update-media-endpoint.php' => ['PhanTypeMismatchReturn'],
        'json-endpoints/class.wpcom-json-api-update-media-v1-1-endpoint.php' => ['PhanTypeMismatchArgument', 'PhanTypeMismatchReturn'],
        'json-endpoints/class.wpcom-json-api-update-post-endpoint.php' => ['PhanTypeMismatchArgument', 'PhanTypeMismatchArgumentNullable', 'PhanTypeMismatchReturn', 'PhanTypePossiblyInvalidDimOffset'],
        'json-endpoints/class.wpcom-json-api-update-post-v1-1-endpoint.php' => ['PhanTypeMismatchArgument', 'PhanTypeMismatchArgumentNullable', 'PhanTypeMismatchReturn', 'PhanTypePossiblyInvalidDimOffset'],
        'json-endpoints/class.wpcom-json-api-update-post-v1-2-endpoint.php' => ['PhanTypeArraySuspiciousNullable', 'PhanTypeMismatchArgument', 'PhanTypeMismatchArgumentNullable', 'PhanTypePossiblyInvalidDimOffset'],
        'json-endpoints/class.wpcom-json-api-update-site-homepage-endpoint.php' => ['PhanTypeMismatchReturn'],
        'json-endpoints/class.wpcom-json-api-update-site-logo-endpoint.php' => ['PhanTypeMismatchReturn'],
        'json-endpoints/class.wpcom-json-api-update-taxonomy-endpoint.php' => ['PhanTypeMismatchArgument', 'PhanTypeMismatchReturn'],
        'json-endpoints/class.wpcom-json-api-update-term-endpoint.php' => ['PhanTypeMismatchArgument', 'PhanTypeMismatchReturn'],
        'json-endpoints/class.wpcom-json-api-update-user-endpoint.php' => ['PhanDeprecatedFunction', 'PhanTypeMismatchReturn', 'PhanTypeMismatchReturnProbablyReal'],
        'json-endpoints/class.wpcom-json-api-upload-media-endpoint.php' => ['PhanTypeMismatchReturn'],
        'json-endpoints/jetpack/class-jetpack-json-api-delete-backup-helper-script-endpoint.php' => ['PhanParamSignatureMismatch'],
        'json-endpoints/jetpack/class-jetpack-json-api-install-backup-helper-script-endpoint.php' => ['PhanParamSignatureMismatch'],
        'json-endpoints/jetpack/class.jetpack-json-api-check-capabilities-endpoint.php' => ['PhanTypeMismatchArgumentProbablyReal'],
        'json-endpoints/jetpack/class.jetpack-json-api-cron-endpoint.php' => ['PhanTypeComparisonToArray'],
        'json-endpoints/jetpack/class.jetpack-json-api-endpoint.php' => ['PhanTypeMismatchArgument', 'PhanTypeMismatchReturn', 'PhanTypeMismatchReturnProbablyReal'],
        'json-endpoints/jetpack/class.jetpack-json-api-get-comment-backup-endpoint.php' => ['PhanParamSignatureMismatch'],
        'json-endpoints/jetpack/class.jetpack-json-api-get-database-object-backup-endpoint.php' => ['PhanTypeMismatchDimFetch'],
        'json-endpoints/jetpack/class.jetpack-json-api-get-post-backup-endpoint.php' => ['PhanParamSignatureMismatch', 'PhanTypeMismatchReturnProbablyReal'],
        'json-endpoints/jetpack/class.jetpack-json-api-get-term-backup-endpoint.php' => ['PhanParamSignatureMismatch'],
        'json-endpoints/jetpack/class.jetpack-json-api-get-user-backup-endpoint.php' => ['PhanParamSignatureMismatch'],
        'json-endpoints/jetpack/class.jetpack-json-api-log-endpoint.php' => ['PhanTypeMismatchPropertyDefault'],
        'json-endpoints/jetpack/class.jetpack-json-api-modules-endpoint.php' => ['PhanParamSignatureMismatch', 'PhanTypeMismatchArgument'],
        'json-endpoints/jetpack/class.jetpack-json-api-plugins-endpoint.php' => ['PhanParamSignatureMismatch', 'PhanTypeMismatchArgument'],
        'json-endpoints/jetpack/class.jetpack-json-api-plugins-install-endpoint.php' => ['PhanTypeMismatchDimAssignment'],
        'json-endpoints/jetpack/class.jetpack-json-api-plugins-modify-endpoint.php' => ['PhanTypeInvalidLeftOperandOfBitwiseOp', 'PhanTypeInvalidRightOperandOfBitwiseOp', 'PhanTypeMismatchArgumentProbablyReal'],
        'json-endpoints/jetpack/class.jetpack-json-api-plugins-modify-v1-2-endpoint.php' => ['PhanTypeInvalidLeftOperandOfBitwiseOp', 'PhanTypeInvalidRightOperandOfBitwiseOp'],
        'json-endpoints/jetpack/class.jetpack-json-api-plugins-new-endpoint.php' => ['PhanParamSignatureMismatch', 'PhanTypeMismatchArgument', 'PhanTypeMissingReturn'],
        'json-endpoints/jetpack/class.jetpack-json-api-sync-endpoint.php' => ['PhanParamSignatureMismatch', 'PhanParamTooManyCallable', 'PhanTypeMismatchArgument', 'PhanTypeMismatchArgumentNullable', 'PhanTypeMismatchArgumentProbablyReal', 'PhanTypeMismatchReturn', 'PhanTypePossiblyInvalidDimOffset'],
        'json-endpoints/jetpack/class.jetpack-json-api-themes-active-endpoint.php' => ['PhanTypeMismatchArgumentProbablyReal'],
        'json-endpoints/jetpack/class.jetpack-json-api-themes-endpoint.php' => ['PhanParamSignatureMismatch', 'PhanTypeMismatchArgument', 'PhanTypeMismatchProperty'],
        'json-endpoints/jetpack/class.jetpack-json-api-themes-modify-endpoint.php' => ['PhanTypeMismatchArgumentProbablyReal'],
        'json-endpoints/jetpack/class.jetpack-json-api-themes-new-endpoint.php' => ['PhanParamSignatureMismatch', 'PhanTypeMismatchArgument', 'PhanTypeMismatchReturnProbablyReal', 'PhanTypeMissingReturn'],
        'json-endpoints/jetpack/class.jetpack-json-api-updates-status-endpoint.php' => ['PhanCoalescingAlwaysNull', 'PhanUndeclaredVariable', 'UnusedPluginSuppression'],
        'json-endpoints/jetpack/class.jetpack-json-api-user-connect-endpoint.php' => ['PhanParamSignatureMismatch', 'PhanTypeMismatchArgument'],
        'json-endpoints/jetpack/class.jetpack-json-api-user-create-endpoint.php' => ['PhanTypeMismatchArgument', 'PhanTypeMismatchPropertyProbablyReal', 'PhanTypeMismatchReturnNullable'],
        'json-endpoints/jetpack/class.wpcom-json-api-update-option-endpoint.php' => ['PhanTypeMismatchPropertyProbablyReal'],
        'modules/carousel/jetpack-carousel.php' => ['PhanDeprecatedProperty', 'PhanTypeMismatchArgument', 'PhanTypeMismatchArgumentProbablyReal', 'PhanTypeMismatchReturn', 'PhanTypeMismatchReturnProbablyReal', 'PhanTypeMissingReturn'],
        'modules/comments/admin.php' => ['PhanTypeMismatchReturn'],
        'modules/comments/base.php' => ['PhanTypeMismatchReturnProbablyReal'],
        'modules/comments/comments.php' => ['PhanTypeExpectedObjectPropAccess', 'PhanTypeMismatchArgument', 'PhanUndeclaredFunction'],
        'modules/comments/subscription-modal-on-comment/class-jetpack-subscription-modal-on-comment.php' => ['PhanTypeMismatchReturnNullable'],
        'modules/custom-content-types.php' => ['PhanRedefineFunction'],
        'modules/google-fonts/current/load-google-fonts.php' => ['PhanTypeArraySuspicious'],
        'modules/gravatar-hovercards.php' => ['PhanTypeMismatchArgumentProbablyReal'],
        'modules/infinite-scroll.php' => ['PhanUndeclaredClassMethod'],
        'modules/infinite-scroll/infinity.php' => ['PhanTypeComparisonToArray', 'PhanTypeMismatchArgument', 'PhanTypeMismatchArgumentProbablyReal', 'PhanTypeMismatchReturn', 'PhanTypeMismatchReturnProbablyReal', 'PhanTypeMissingReturn'],
        'modules/likes.php' => ['PhanUndeclaredFunction'],
        'modules/likes/jetpack-likes-settings.php' => ['PhanDeprecatedFunction'],
        'modules/markdown/easy-markdown.php' => ['PhanTypeArraySuspiciousNullable', 'PhanTypeMismatchArgument'],
        'modules/memberships/class-jetpack-memberships.php' => ['PhanTypeMismatchArgument', 'PhanTypeMismatchArgumentProbablyReal', 'PhanUndeclaredMethod'],
        'modules/monitor.php' => ['PhanTypeMismatchReturnProbablyReal'],
        'modules/plugin-search.php' => ['PhanTypePossiblyInvalidDimOffset'],
        'modules/post-by-email/class-jetpack-post-by-email.php' => ['PhanUndeclaredMethodInCallable'],
        'modules/publicize.php' => ['PhanRedefineFunction'],
        'modules/related-posts/jetpack-related-posts.php' => ['PhanTypeMismatchArgument', 'PhanTypeMismatchArgumentNullable', 'PhanTypeMismatchReturnProbablyReal', 'PhanUndeclaredFunction'],
        'modules/scan/class-admin-bar-notice.php' => ['PhanTypeMismatchReturnProbablyReal'],
        'modules/search.php' => ['PhanTypeMismatchArgument'],
        'modules/sharedaddy/sharing-service.php' => ['PhanTypeArraySuspicious', 'PhanTypeMismatchArgument', 'PhanTypeMismatchProperty', 'PhanTypeMismatchPropertyDefault', 'PhanTypeMismatchPropertyProbablyReal', 'PhanTypePossiblyInvalidDimOffset', 'PhanUndeclaredFunction'],
        'modules/sharedaddy/sharing-sources.php' => ['PhanParamSignatureMismatch', 'PhanTypeMismatchProperty', 'PhanTypeSuspiciousNonTraversableForeach'],
        'modules/sharedaddy/sharing.php' => ['PhanTypeMismatchArgument', 'PhanTypeMismatchArgumentProbablyReal'],
        'modules/shortcodes/archiveorg-book.php' => ['PhanTypeMismatchArgument'],
        'modules/shortcodes/archiveorg.php' => ['PhanTypeMismatchArgument'],
        'modules/shortcodes/brightcove.php' => ['PhanTypeMismatchArgument'],
        'modules/shortcodes/class.filter-embedded-html-objects.php' => ['PhanTypeMismatchPropertyDefault'],
        'modules/shortcodes/dailymotion.php' => ['PhanTypeMismatchArgument'],
        'modules/shortcodes/flickr.php' => ['PhanTypeMismatchReturn'],
        'modules/shortcodes/getty.php' => ['PhanTypeMismatchArgument'],
        'modules/shortcodes/gist.php' => ['PhanTypeMismatchArgument'],
        'modules/shortcodes/googleapps.php' => ['PhanTypeMismatchArgument', 'PhanTypePossiblyInvalidDimOffset'],
        'modules/shortcodes/gravatar.php' => ['PhanTypeMismatchArgument', 'PhanTypeMismatchReturn'],
        'modules/shortcodes/inline-pdfs.php' => ['PhanTypeMismatchArgument'],
        'modules/shortcodes/pinterest.php' => ['PhanTypeMismatchArgument'],
        'modules/shortcodes/presentations.php' => ['PhanTypeMismatchArgument', 'PhanTypePossiblyInvalidDimOffset'],
        'modules/shortcodes/quiz.php' => ['PhanTypeMismatchArgument', 'PhanTypeMismatchProperty', 'PhanTypeMismatchPropertyProbablyReal'],
        'modules/shortcodes/recipe.php' => ['PhanTypeMismatchArgument'],
        'modules/shortcodes/soundcloud.php' => ['PhanTypeMismatchArgument', 'PhanTypePossiblyInvalidDimOffset'],
        'modules/shortcodes/spotify.php' => ['PhanTypeMismatchArgument'],
        'modules/shortcodes/tweet.php' => ['PhanTypeMismatchArgument'],
        'modules/shortcodes/twitchtv.php' => ['PhanTypeMismatchArgument'],
        'modules/shortcodes/ustream.php' => ['PhanTypeMismatchArgument'],
        'modules/shortcodes/vimeo.php' => ['PhanTypeMismatchArgument'],
        'modules/shortcodes/youtube.php' => ['PhanRedefineFunction'],
        'modules/shortlinks.php' => ['PhanTypeMismatchArgumentProbablyReal'],
        'modules/sitemaps/sitemap-buffer-fallback.php' => ['PhanTypeArraySuspicious'],
        'modules/sitemaps/sitemap-buffer-image-fallback.php' => ['PhanRedefineClass', 'PhanTypeMismatchPropertyProbablyReal'],
        'modules/sitemaps/sitemap-buffer-image.php' => ['PhanRedefineClass'],
        'modules/sitemaps/sitemap-buffer-master-fallback.php' => ['PhanRedefineClass', 'PhanTypeMismatchPropertyProbablyReal'],
        'modules/sitemaps/sitemap-buffer-master.php' => ['PhanRedefineClass'],
        'modules/sitemaps/sitemap-buffer-news-fallback.php' => ['PhanRedefineClass', 'PhanTypeMismatchPropertyProbablyReal'],
        'modules/sitemaps/sitemap-buffer-news.php' => ['PhanRedefineClass'],
        'modules/sitemaps/sitemap-buffer-page-fallback.php' => ['PhanRedefineClass', 'PhanTypeMismatchPropertyProbablyReal'],
        'modules/sitemaps/sitemap-buffer-page.php' => ['PhanRedefineClass'],
        'modules/sitemaps/sitemap-buffer-video-fallback.php' => ['PhanRedefineClass', 'PhanTypeMismatchPropertyProbablyReal'],
        'modules/sitemaps/sitemap-buffer-video.php' => ['PhanRedefineClass'],
        'modules/sitemaps/sitemap-buffer.php' => ['PhanTypeMismatchReturn'],
        'modules/sitemaps/sitemap-builder.php' => ['PhanTypeMismatchArgument', 'PhanTypeMismatchArgumentNullableInternal', 'PhanTypeMismatchDimFetch', 'PhanTypeMismatchReturnProbablyReal'],
        'modules/sitemaps/sitemap-librarian.php' => ['PhanTypeMismatchArgument', 'PhanTypeMismatchReturnProbablyReal'],
        'modules/sitemaps/sitemap-logger.php' => ['PhanTypeMismatchProperty'],
        'modules/sitemaps/sitemaps.php' => ['PhanTypeMismatchArgument'],
        'modules/stats.php' => ['PhanSuspiciousMagicConstant', 'PhanTypeMismatchArgument', 'PhanTypeMismatchArgumentProbablyReal', 'PhanTypeMismatchReturn', 'PhanTypeMismatchReturnNullable', 'PhanTypeMismatchReturnProbablyReal'],
        'modules/subscriptions.php' => ['PhanTypeMismatchArgument', 'PhanTypeMismatchArgumentProbablyReal', 'PhanTypeMismatchDefault', 'PhanTypeMismatchReturnProbablyReal', 'PhanTypeSuspiciousNonTraversableForeach'],
        'modules/subscriptions/subscribe-modal/class-jetpack-subscribe-modal.php' => ['PhanTypeMismatchReturnNullable'],
        'modules/subscriptions/views.php' => ['PhanTypeMismatchArgument', 'PhanTypePossiblyInvalidDimOffset'],
        'modules/theme-tools/content-options.php' => ['PhanRedefineFunction'],
        'modules/theme-tools/content-options/author-bio.php' => ['PhanRedefineFunction', 'PhanTypeMismatchArgument'],
        'modules/theme-tools/content-options/blog-display.php' => ['PhanRedefineFunction'],
        'modules/theme-tools/content-options/customizer.php' => ['PhanRedefineClass', 'PhanRedefineFunction', 'PhanRedefinedClassReference', 'PhanTypeMismatchReturn'],
        'modules/theme-tools/content-options/featured-images-fallback.php' => ['PhanRedefineFunction', 'PhanTypeMismatchArgument'],
        'modules/theme-tools/content-options/featured-images.php' => ['PhanRedefineFunction', 'PhanTypeMismatchArgument'],
        'modules/theme-tools/content-options/post-details.php' => ['PhanRedefineFunction'],
        'modules/theme-tools/responsive-videos.php' => ['PhanRedefineFunction'],
        'modules/theme-tools/site-breadcrumbs.php' => ['PhanTypeMismatchArgument', 'PhanTypeMismatchReturn'],
        'modules/theme-tools/site-logo/inc/class-site-logo.php' => ['PhanTypeComparisonToArray', 'PhanTypeMismatchReturn'],
        'modules/theme-tools/site-logo/inc/functions.php' => ['PhanTypeMismatchReturnProbablyReal'],
        'modules/theme-tools/social-menu.php' => ['PhanRedefineFunction', 'PhanTypeMismatchArgumentNullable'],
        'modules/theme-tools/social-menu/icon-functions.php' => ['PhanRedefineFunction', 'PhanTypeExpectedObjectPropAccess'],
        'modules/tiled-gallery/math/class-constrained-array-rounding.php' => ['PhanTypeMismatchDefault'],
        'modules/tiled-gallery/tiled-gallery.php' => ['PhanTypeMismatchArgumentProbablyReal'],
        'modules/tiled-gallery/tiled-gallery/templates/carousel-container.php' => ['PhanTypeMismatchArgument'],
        'modules/tiled-gallery/tiled-gallery/templates/partials/carousel-image-args.php' => ['PhanTypeMismatchArgument'],
        'modules/tiled-gallery/tiled-gallery/templates/rectangular-layout.php' => ['PhanTypeMismatchArgument'],
        'modules/tiled-gallery/tiled-gallery/tiled-gallery-shape.php' => ['PhanTypeMismatchArgument', 'PhanTypeMismatchReturnProbablyReal'],
        'modules/tiled-gallery/tiled-gallery/tiled-gallery-square.php' => ['PhanTypeMismatchArgument'],
        'modules/videopress/class-videopress-attachment-metadata.php' => ['PhanTypeMismatchArgument'],
        'modules/videopress/class.jetpack-videopress.php' => ['PhanTypeMismatchDefault'],
        'modules/videopress/class.videopress-edit-attachment.php' => ['PhanTypeMismatchArgument', 'PhanTypeMismatchArgumentProbablyReal'],
        'modules/videopress/class.videopress-gutenberg.php' => ['PhanDeprecatedFunction', 'PhanTypeMismatchArgumentProbablyReal', 'PhanTypeMismatchReturnProbablyReal'],
        'modules/videopress/class.videopress-player.php' => ['PhanPluginMixedKeyNoKey', 'PhanTypeExpectedObjectPropAccess', 'PhanTypeInvalidLeftOperandOfNumericOp', 'PhanTypeMismatchArgument', 'PhanTypeMismatchArgumentNullable', 'PhanUndeclaredMethod'],
        'modules/videopress/class.videopress-video.php' => ['PhanTypeMismatchReturn', 'PhanTypeMismatchReturnProbablyReal'],
        'modules/videopress/editor-media-view.php' => ['PhanSuspiciousMagicConstant'],
        'modules/widget-visibility/widget-conditions.php' => ['PhanTypeComparisonToArray', 'PhanTypeExpectedObjectPropAccess', 'PhanTypeMismatchArgumentNullable', 'PhanTypeMismatchDefault', 'PhanTypeMismatchReturnProbablyReal', 'PhanTypePossiblyInvalidDimOffset', 'PhanTypeSuspiciousNonTraversableForeach'],
        'modules/widgets/authors.php' => ['PhanTypeMismatchArgument'],
        'modules/widgets/blog-stats.php' => ['PhanTypeMismatchArgument'],
        'modules/widgets/class-jetpack-eu-cookie-law-widget.php' => ['PhanTypeMismatchArgument'],
        'modules/widgets/class-jetpack-instagram-widget.php' => ['PhanTypeMismatchArgument', 'PhanTypeMismatchReturn', 'PhanTypePossiblyInvalidDimOffset'],
        'modules/widgets/contact-info.php' => ['PhanTypeMismatchArgument'],
        'modules/widgets/facebook-likebox.php' => ['PhanTypeMismatchArgument', 'PhanTypePossiblyInvalidDimOffset'],
        'modules/widgets/flickr.php' => ['PhanTypeMismatchArgumentNullable'],
        'modules/widgets/flickr/form.php' => ['PhanTypeMismatchArgument'],
        'modules/widgets/follow-button.php' => ['PhanPluginUseReturnValueInternalKnown'],
        'modules/widgets/gallery.php' => ['PhanTypeMismatchReturnProbablyReal'],
        'modules/widgets/image-widget.php' => ['PhanTypeMismatchArgumentProbablyReal'],
        'modules/widgets/milestone/class-milestone-widget.php' => ['PhanTypeMismatchArgument', 'PhanTypeMismatchReturn', 'PhanTypePossiblyInvalidDimOffset'],
        'modules/widgets/rsslinks-widget.php' => ['PhanTypeMismatchArgumentNullable', 'PhanTypeMismatchArgumentNullableInternal'],
        'modules/widgets/social-media-icons.php' => ['PhanTypeMismatchReturn'],
        'modules/widgets/twitter-timeline.php' => ['PhanTypePossiblyInvalidDimOffset'],
        'modules/widgets/wordpress-post-widget/class.jetpack-display-posts-widget-base.php' => ['PhanNonClassMethodCall', 'PhanTypeMismatchArgument', 'PhanTypeMismatchDimAssignment', 'PhanTypeMismatchDimFetch', 'PhanTypeMismatchReturnProbablyReal'],
        'modules/woocommerce-analytics/class-jetpack-woocommerce-analytics.php' => ['PhanDeprecatedClass', 'PhanDeprecatedFunction', 'PhanStaticPropIsStaticType', 'PhanTypeMismatchPropertyDefault', 'PhanTypeMismatchPropertyProbablyReal'],
        'modules/woocommerce-analytics/classes/class-jetpack-woocommerce-analytics-checkout-flow.php' => ['PhanDeprecatedFunction', 'PhanDeprecatedTrait'],
        'modules/woocommerce-analytics/classes/class-jetpack-woocommerce-analytics-my-account.php' => ['PhanDeprecatedFunction', 'PhanDeprecatedTrait'],
        'modules/woocommerce-analytics/classes/class-jetpack-woocommerce-analytics-trait.php' => ['PhanDeprecatedFunction', 'PhanTypeSuspiciousNonTraversableForeach', 'PhanUndeclaredMethod'],
        'modules/woocommerce-analytics/classes/class-jetpack-woocommerce-analytics-universal.php' => ['PhanDeprecatedFunction', 'PhanDeprecatedTrait'],
        'modules/wordads/class-wordads.php' => ['PhanTypeMismatchArgument'],
        'modules/wordads/php/class-wordads-admin.php' => ['PhanTypeMismatchArgumentProbablyReal'],
        'modules/wordads/php/class-wordads-api.php' => ['PhanTypeMismatchReturn', 'PhanTypeMismatchReturnProbablyReal'],
        'modules/wordads/php/class-wordads-params.php' => ['PhanTypeMismatchReturn'],
        'modules/wordads/php/class-wordads-sidebar-widget.php' => ['PhanTypeMismatchArgument'],
        'sal/class.json-api-links.php' => ['PhanTypeMismatchArgumentInternal', 'PhanTypeMismatchReturn', 'PhanTypeMismatchReturnProbablyReal'],
        'sal/class.json-api-post-base.php' => ['PhanTypeMismatchArgument', 'PhanTypeMismatchReturnNullable', 'PhanTypeMismatchReturnProbablyReal', 'PhanTypePossiblyInvalidDimOffset', 'PhanTypeSuspiciousNonTraversableForeach'],
        'sal/class.json-api-site-base.php' => ['PhanTypeMismatchArgument', 'PhanTypeMismatchReturnProbablyReal'],
        'sal/class.json-api-site-jetpack-base.php' => ['PhanTypeMismatchReturnProbablyReal'],
        'sal/class.json-api-site-jetpack.php' => ['PhanParamSignatureMismatch'],
        'sal/class.json-api-token.php' => ['PhanTypeMismatchArgumentProbablyReal'],
        'tests/php/3rd-party/Jetpack_AMP_Support_Test.php' => ['PhanTypeMismatchArgumentProbablyReal'],
        'tests/php/Functions_OpenGraph_Test.php' => ['PhanTypeMismatchArgumentProbablyReal'],
        'tests/php/_inc/lib/Jetpack_Blogging_Prompts_Test.php' => ['PhanTypeMismatchArgumentNullable'],
        'tests/php/_inc/lib/Jetpack_REST_API_endpoints_Test.php' => ['PhanTypeInvalidLeftOperandOfAdd', 'PhanTypeMismatchReturn', 'PhanTypeMismatchReturnProbablyReal'],
        'tests/php/core-api/WPCOM_REST_API_V2_Field_Controller_Test.php' => ['PhanTypeMismatchArgument', 'PhanTypeMismatchArgumentProbablyReal'],
        'tests/php/core-api/wpcom-endpoints/WPCOM_REST_API_V2_Endpoint_Admin_Menu_Test.php' => ['PhanPluginMixedKeyNoKey', 'PhanTypeArraySuspiciousNullable', 'PhanTypeMismatchReturn'],
        'tests/php/core-api/wpcom-endpoints/WPCOM_REST_API_V2_Endpoint_External_Media_Test.php' => ['PhanTypeExpectedObjectPropAccess', 'PhanTypeMismatchArgument'],
        'tests/php/core-api/wpcom-fields/WPCOM_REST_API_V2_Attachment_VideoPress_Field_Test.php' => ['PhanTypeMismatchArgumentProbablyReal'],
        'tests/php/extensions/blocks/premium-content/Jetpack_Premium_Content_Test.php' => ['PhanDeprecatedProperty', 'PhanTypeMismatchArgumentProbablyReal', 'PhanTypeMissingReturn', 'PhanUndeclaredMethod'],
        'tests/php/general/Jetpack_Client_Server_Test.php' => ['PhanTypeMismatchArgumentProbablyReal'],
        'tests/php/general/Jetpack_Test.php' => ['PhanTypeMismatchPropertyDefault'],
        'tests/php/general/Jetpack_User_Agent_Test.php' => ['PhanDeprecatedFunction'],
        'tests/php/general/Jetpack_XMLRPC_Server_Test.php' => ['PhanDeprecatedFunction'],
        'tests/php/json-api/Jetpack_Base_Json_Api_Endpoints_Test.php' => ['PhanTypeMismatchArgument', 'PhanTypeMismatchArgumentProbablyReal'],
        'tests/php/json-api/Jetpack_Json_Api_Endpoints_Test.php' => ['PhanTypeMismatchArgumentProbablyReal'],
        'tests/php/json-api/Jetpack_Site_Json_Api_Endpoints_Test.php' => ['PhanImpossibleConditionInLoop'],
        'tests/php/json-api/SalPostsTest.php' => ['PhanTypeMismatchArgument'],
        'tests/php/json-api/SalSiteTest.php' => ['PhanTypeMismatchArgument'],
        'tests/php/media/Jetpack_MediaExtractor_Test.php' => ['PhanTypeMismatchArgument', 'PhanTypeMismatchArgumentProbablyReal'],
        'tests/php/modules/photon/Jetpack_Photon_Static_Assets_CDN_Test.php' => ['PhanTypeMismatchProperty'],
        'tests/php/modules/publicize/Publicize_Test.php' => ['PhanPluginUnreachableCode'],
        'tests/php/modules/sharedaddy/Jetpack_ReCaptcha_Test.php' => ['PhanDeprecatedClass'],
        'tests/php/modules/shortcodes/Jetpack_Shortcodes_Getty_Test.php' => ['PhanPluginInvalidPregRegex'],
        'tests/php/modules/shortcodes/Jetpack_Shortcodes_Instagram_Test.php' => ['PhanTypeMismatchArgument'],
        'tests/php/modules/shortcodes/Jetpack_Shortcodes_PocketCasts_Test.php' => ['PhanTypeMismatchArgument'],
        'tests/php/modules/shortcodes/Jetpack_Shortcodes_Slideshow_Test.php' => ['PhanTypeMismatchArgumentProbablyReal'],
        'tests/php/modules/shortcodes/Jetpack_Shortcodes_Ted_Test.php' => ['PhanTypeMismatchArgument'],
        'tests/php/modules/shortcodes/Jetpack_Shortcodes_Tweet_Test.php' => ['PhanTypeMismatchArgument'],
        'tests/php/modules/shortcodes/Jetpack_Shortcodes_Vimeo_Test.php' => ['PhanTypeMismatchArgumentProbablyReal'],
        'tests/php/modules/sitemaps/Jetpack_Sitemap_Buffer_Test.php' => ['PhanTypeMismatchArgumentProbablyReal', 'PhanTypeMismatchPropertyProbablyReal'],
        'tests/php/modules/sitemaps/Jetpack_Sitemap_Librarian_Test.php' => ['PhanTypeMismatchArgument'],
        'tests/php/modules/subscriptions/Jetpack_Subscriptions_Test.php' => ['PhanDeprecatedProperty', 'PhanTypeMismatchArgument', 'PhanTypeMismatchArgumentProbablyReal'],
        'tests/php/modules/widgets/Contact_Info_Widget_Test.php' => ['PhanTypeMismatchArgumentProbablyReal'],
        'tests/php/modules/widgets/Jetpack_Display_Posts_Widget_Test.php' => ['PhanTypeMismatchArgumentProbablyReal'],
        'tests/php/sync/Jetpack_Sync_Checksum_Smoke_Test.php' => ['PhanTypeMismatchArgument', 'PhanTypeMismatchReturn'],
        'tests/php/sync/Jetpack_Sync_Checksum_Test.php' => ['PhanTypeArraySuspiciousNullable', 'PhanTypeMismatchReturn'],
        'tests/php/sync/Jetpack_Sync_Comments_Test.php' => ['PhanTypeMismatchArgument'],
        'tests/php/sync/Jetpack_Sync_Full_Immediately_Test.php' => ['PhanTypeArraySuspiciousNullable', 'PhanTypeMismatchArgumentProbablyReal'],
        'tests/php/sync/Jetpack_Sync_Full_Test.php' => ['PhanTypeMismatchArgument', 'PhanTypeMismatchArgumentProbablyReal', 'PhanTypeMismatchArgumentReal'],
        'tests/php/sync/Jetpack_Sync_Functions_Test.php' => ['PhanTypeMismatchArgumentProbablyReal', 'PhanTypeMismatchDimFetch', 'PhanTypeMissingReturn'],
        'tests/php/sync/Jetpack_Sync_Import_Test.php' => ['PhanRedefineClass'],
        'tests/php/sync/Jetpack_Sync_Integration_Test.php' => ['PhanTypeMismatchArgumentProbablyReal', 'PhanTypeMismatchPropertyProbablyReal'],
        'tests/php/sync/Jetpack_Sync_Menus_Test.php' => ['PhanTypeMismatchArgumentProbablyReal'],
        'tests/php/sync/Jetpack_Sync_Meta_Test.php' => ['PhanTypeArraySuspiciousNullable', 'PhanTypeMismatchArgument'],
        'tests/php/sync/Jetpack_Sync_Post_Test.php' => ['PhanTypeExpectedObjectPropAccess', 'PhanTypeMismatchArgumentProbablyReal'],
        'tests/php/sync/Jetpack_Sync_Queue_Dedicated_Table_Test.php' => ['PhanTypeMismatchArgumentProbablyReal'],
        'tests/php/sync/Jetpack_Sync_Queue_Options_Table_Test.php' => ['PhanTypeMismatchArgumentProbablyReal'],
        'tests/php/sync/Jetpack_Sync_Queue_Test.php' => ['PhanTypeMismatchArgument', 'PhanTypeMismatchArgumentProbablyReal'],
        'tests/php/sync/Jetpack_Sync_Queue_TestBase.php' => ['PhanTypeMismatchArgument', 'PhanTypeMismatchArgumentProbablyReal'],
        'tests/php/sync/Jetpack_Sync_Sender_Test.php' => ['PhanTypeMismatchArgumentProbablyReal'],
        'tests/php/sync/Jetpack_Sync_Term_Relationships_Test.php' => ['PhanPluginUnreachableCode'],
        'tests/php/sync/Jetpack_Sync_TestBase.php' => ['PhanTypeMismatchArgumentProbablyReal', 'PhanTypeMismatchReturn'],
        'tests/php/sync/Jetpack_Sync_Users_Test.php' => ['PhanTypeMismatchArgument'],
        'tests/php/sync/Jetpack_Sync_WP_Super_Cache_Test.php' => ['PhanTypeArraySuspiciousNullable'],
        'tests/php/sync/Jetpack_Sync_WooCommerce_Test.php' => ['PhanTypeMismatchArgument'],
        'tests/php/sync/Z_IJetpack_Sync_Replicastore_Test.php' => ['PhanTypeObjectUnsetDeclaredProperty'],
        'tests/php/sync/server/class.jetpack-sync-test-object-factory.php' => ['PhanTypeMismatchArgumentProbablyReal'],
        'tests/php/sync/server/class.jetpack-sync-test-replicastore.php' => ['PhanTypeInvalidLeftOperandOfAdd'],
        'tools/build-asset-cdn-json.php' => ['PhanTypeArraySuspiciousNullable', 'PhanTypeMismatchArgument'],
    ],
    // 'directory_suppressions' => ['src/directory_name' => ['PhanIssueName1', 'PhanIssueName2']] can be manually added if needed.
    // (directory_suppressions will currently be ignored by subsequent calls to --save-baseline, but may be preserved in future Phan releases)
];
