name: Auto-tagger rolling mode.

on:
  push:
    branches:
      - trunk

jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest
    steps:
      - name: Check that the secret is set
        env:
          TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
        run: |
          if [[ -z "$TOKEN" ]]; then
            echo '::error::The secret API_TOKEN_GITHUB must be set.'
            exit 1
          fi

      - uses: actions/checkout@v4
        with:
          # We want to potentially trigger "tag" events, but the default GITHUB_TOKEN
          # explicitly does not trigger events.
          token: ${{ secrets.API_TOKEN_GITHUB }}

      - name: Check branch
        id: check-branch
        run: |
          if [[ "$GITHUB_REF" != "refs/heads/trunk" ]]; then
            echo "::error::Expected to be called for \"refs/heads/trunk\", not \"$GITHUB_REF\""
            exit 1
          fi

          ROLLING_MODE=
          if [[ -e composer.json ]]; then
            ROLLING_MODE=$(jq -r '.extra["release-from-trunk"]' composer.json)
          fi

          if [[ -z "$ROLLING_MODE" ]]; then
            echo "::notice::Ignoring push to $GITHUB_REF, as this project has not enabled rolling release mode."
            echo "run=false" >> "$GITHUB_OUTPUT"
          fi

          echo "Push to \"$GITHUB_REF\" ok"
          echo "run=true" >> "$GITHUB_OUTPUT"

      - name: Tag
        if: steps.check-branch.outputs.run == 'true'
        env:
          VER: ${{ steps.version.outputs.version }}
        run: |
          export GIT_AUTHOR_NAME=matticbot
          export GIT_AUTHOR_EMAIL=matticbot@users.noreply.github.com
          export GIT_COMMITTER_NAME=matticbot
          export GIT_COMMITTER_EMAIL=matticbot@users.noreply.github.com
          TAG="trunk-tip"

          echo "::notice::Tagging $TAG"
          git tag --force "$TAG"
          git push --force origin "$TAG"
