name: Auto-tagger

on:
  push:
    branches:
      - master
      - trunk

jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest
    steps:
      - name: Check that the secret is set
        env:
          TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
        run: |
          if [[ -z "$TOKEN" ]]; then
            echo '::error::The secret API_TOKEN_GITHUB must be set.'
            exit 1
          fi

      - uses: actions/checkout@v3
        with:
          # We want to potentially trigger "tag" events, but the default GITHUB_TOKEN
          # explicitly does not trigger events.
          token: ${{ secrets.API_TOKEN_GITHUB }}

      - name: Tag
        run: |
          VER=$(sed -nEe 's/^## \[?([^]]*)\]? - .*/\1/;T;p;q' CHANGELOG.md || true)
          echo "Version from changelog is ${VER:-<unknown>}"
          if [[ "$VER" =~ ^[0-9]+(\.[0-9]+)+$ ]]; then
            export GIT_AUTHOR_NAME=matticbot
            export GIT_AUTHOR_EMAIL=matticbot@users.noreply.github.com
            export GIT_COMMITTER_NAME=matticbot
            export GIT_COMMITTER_EMAIL=matticbot@users.noreply.github.com
            if [[ -e composer.json ]] && ! jq -e 'if try ( .extra.autotagger | has("v") ) catch false then .extra.autotagger.v else true end' composer.json >/dev/null; then
              TAG="$VER"
            else
              TAG="v$VER"
            fi
            git tag "$TAG"
            git push origin "$TAG"
            if [[ -e composer.json ]] && jq -e '.extra.autotagger.major?' composer.json >/dev/null; then
              git tag --force "${TAG%%.*}"
              git push --force origin "${TAG%%.*}"
            fi
          fi
