<?php
/**
 * An in-wp-admin Backup page for WordPress.com Simple sites.
 *
 * Simple sites cannot be backed up, so this resolves the same upgrade or
 * activate state Calypso shows and hands it to a wp-build page.
 *
 * @package automattic/jetpack-mu-wpcom
 */

use Automattic\Jetpack\WP_Build_Polyfills\WP_Build_Polyfills;

/**
 * Admin page slug. Matches Jetpack_Backup::JETPACK_BACKUP_SLUG so the URL
 * survives a transfer to WoA, where the real Backup page takes it over — which
 * is why this must never register off Simple.
 */
const WPCOM_SIMPLE_BACKUP_MENU_SLUG = 'jetpack-backup';

/**
 * Page name for wp-build, as declared in routes/wpcom-backup/package.json.
 *
 * Deliberately not the menu slug: wp-build derives its own page slug and render
 * function from this name.
 */
const WPCOM_SIMPLE_BACKUP_WP_BUILD_PAGE = 'wpcom-backup';

/**
 * Render callback generated by wp-build in build/pages/wpcom-backup/page-wp-admin.php.
 */
const WPCOM_SIMPLE_BACKUP_RENDER_CALLBACK = 'jetpack_mu_wpcom_wpcom_backup_wp_admin_render_page';

/**
 * Site has no backup-capable plan. Offer an upgrade.
 */
const WPCOM_SIMPLE_BACKUP_STATE_UPGRADE = 'upgrade';

/**
 * A transfer to WoA is already running or queued. Offer nothing; report status.
 */
const WPCOM_SIMPLE_BACKUP_STATE_IN_PROGRESS = 'in_progress';

/**
 * Site has the plan and can transfer. Offer activation.
 */
const WPCOM_SIMPLE_BACKUP_STATE_ACTIVATE = 'activate';

/**
 * Site has the plan but cannot transfer yet. Explain why.
 */
const WPCOM_SIMPLE_BACKUP_STATE_INELIGIBLE = 'ineligible';

/**
 * Boot the feature, loading the wp-build assets only on the Backup page itself.
 *
 * @return void
 */
function wpcom_simple_backup_init() {
	add_action( 'admin_menu', 'wpcom_simple_backup_register_page', 1000000 );

	if ( ! wpcom_simple_backup_is_backup_admin_request() ) {
		return;
	}

	wpcom_simple_backup_load_wp_build();

	add_action( 'current_screen', 'wpcom_simple_backup_alias_screen_id' );
	add_action( 'admin_enqueue_scripts', 'wpcom_simple_backup_enqueue_initial_state', 20 );
}
add_action( 'init', 'wpcom_simple_backup_init' );

/**
 * Whether the current request targets the Backup admin page.
 *
 * `$_GET['page']` is populated by wp-admin/admin.php before any of our hooks
 * run, so this is reliable from plugins_loaded onwards.
 *
 * @return bool
 */
function wpcom_simple_backup_is_backup_admin_request() {
	// phpcs:ignore WordPress.Security.NonceVerification.Recommended -- Read-only routing check; no form data is processed.
	if ( ! is_admin() || ! isset( $_GET['page'] ) ) {
		return false;
	}

	// phpcs:ignore WordPress.Security.NonceVerification.Recommended -- Read-only routing check; no form data is processed.
	return WPCOM_SIMPLE_BACKUP_MENU_SLUG === sanitize_text_field( wp_unslash( $_GET['page'] ) );
}

/**
 * Register the Backup page without adding it to the Jetpack menu.
 *
 * `remove_submenu_page()` only unsets `$submenu`, leaving the `$_registered_pages`
 * entry that makes `?page=` route — so the page stays reachable by URL. Drop the
 * remove_* call to surface it later.
 *
 * @return void
 */
function wpcom_simple_backup_register_page() {
	// build/build.php defines the render callback but only loads on this page's
	// own request, so elsewhere fall back rather than fataling.
	$callback = function_exists( WPCOM_SIMPLE_BACKUP_RENDER_CALLBACK )
		? WPCOM_SIMPLE_BACKUP_RENDER_CALLBACK
		: '__return_empty_string';

	add_submenu_page(
		'jetpack',
		// "VaultPress Backup" is a product name, do not translate.
		'Jetpack VaultPress Backup',
		'VaultPress Backup',
		'manage_options',
		WPCOM_SIMPLE_BACKUP_MENU_SLUG,
		$callback
	);

	remove_submenu_page( 'jetpack', WPCOM_SIMPLE_BACKUP_MENU_SLUG );
}

/**
 * Load the wp-build generated asset registrations and the boot polyfills.
 *
 * `build/` is produced at release time, so an unbuilt checkout has none; bail
 * quietly, since register_page() already falls back to an empty render.
 *
 * @return void
 */
function wpcom_simple_backup_load_wp_build() {
	$wp_build_index = dirname( __DIR__, 3 ) . '/build/build.php';

	if ( ! file_exists( $wp_build_index ) ) {
		return;
	}

	require_once $wp_build_index;

	// Register polyfills for WP < 7.0 (must run before enqueue).
	WP_Build_Polyfills::register(
		'jetpack-mu-wpcom',
		array_merge(
			WP_Build_Polyfills::SCRIPT_HANDLES,
			WP_Build_Polyfills::MODULE_IDS
		)
	);
}

/**
 * Make wp-build's enqueue check pass without changing the page URL.
 *
 * Its enqueue callback needs a screen ID of `<page>`, which our `jetpack-backup`
 * slug does not produce. The body class is untouched and still reads
 * `jetpack_page_jetpack-backup`, which the route stylesheet scopes to.
 *
 * @param \WP_Screen|null $screen The current screen object, passed by WP.
 * @return void
 */
function wpcom_simple_backup_alias_screen_id( $screen ) {
	if ( ! is_object( $screen ) ) {
		return;
	}

	$screen->id = WPCOM_SIMPLE_BACKUP_WP_BUILD_PAGE;
}

/**
 * Hand the resolved state to the page's boot script.
 *
 * @return void
 */
function wpcom_simple_backup_enqueue_initial_state() {
	$handle = WPCOM_SIMPLE_BACKUP_WP_BUILD_PAGE . '-wp-admin-prerequisites';

	if ( ! wp_script_is( $handle, 'registered' ) ) {
		return;
	}

	$blog_id = get_current_blog_id();
	$user_id = get_current_user_id();
	$domain  = wp_parse_url( home_url(), PHP_URL_HOST );
	$state   = wpcom_simple_backup_get_state( $blog_id, $user_id );

	wp_localize_script(
		$handle,
		'wpcomSimpleBackupInitialState',
		array(
			'state'       => $state,
			'domain'      => $domain,
			// Only meaningful in the ineligible state; empty everywhere else.
			'blockers'    => WPCOM_SIMPLE_BACKUP_STATE_INELIGIBLE === $state
				? wpcom_simple_backup_get_blocker_messages( wpcom_simple_backup_get_eligibility( $blog_id, $user_id ) )
				: array(),
			'upgradeUrl'  => 'https://wordpress.com/plans/' . $domain,
			'activateUrl' => 'https://wordpress.com/backup/' . $domain,
			'supportUrl'  => 'https://wordpress.com/support/backups/',
		)
	);
}

/**
 * Whether the site's plan includes backups.
 *
 * @param int $blog_id Blog ID.
 * @return bool
 */
function wpcom_simple_backup_has_backup_feature( $blog_id ) {
	if ( ! function_exists( 'wpcom_site_has_feature' ) || ! class_exists( '\WPCOM_Features' ) ) {
		return false;
	}

	return (bool) wpcom_site_has_feature( \WPCOM_Features::BACKUPS, $blog_id );
}

/**
 * Whether a transfer to WoA is already underway.
 *
 * Two signals: `is_wpcom_atomic()` needs a transfer record to exist, while
 * `has_site_pending_automated_transfer()` covers the earlier gap from checkout
 * until that record is written. Offering "activate" in it would start a second.
 *
 * @param int $blog_id Blog ID.
 * @return bool
 */
function wpcom_simple_backup_is_transfer_in_progress( $blog_id ) {
	if ( ! function_exists( 'require_lib' ) ) {
		return false;
	}

	require_lib( 'atomic' );

	if ( function_exists( '\A8C\Atomic\has_site_pending_automated_transfer' )
		&& \A8C\Atomic\has_site_pending_automated_transfer( $blog_id ) ) {
		return true;
	}

	if ( function_exists( '\A8C\Atomic\is_wpcom_atomic' ) ) {
		// Second argument includes pending/active/provisioned transfers.
		return (bool) \A8C\Atomic\is_wpcom_atomic( $blog_id, true );
	}

	return false;
}

/**
 * Transfer eligibility for the site, or null when it cannot be determined.
 *
 * An in-progress transfer is reported as a `transfer_already_exists` error, so
 * that state is checked first and never reaches here as a blocker.
 *
 * @param int $blog_id Blog ID.
 * @param int $user_id User ID.
 * @return array|null { is_eligible: bool, errors: array, warnings: array }
 */
function wpcom_simple_backup_get_eligibility( $blog_id, $user_id ) {
	if ( ! function_exists( 'require_lib' ) ) {
		return null;
	}

	require_lib( 'atomic' );

	if ( ! function_exists( '\A8C\Atomic\get_status_for_site' ) ) {
		return null;
	}

	return \A8C\Atomic\get_status_for_site( $blog_id, $user_id );
}

/**
 * Resolve which prompt the page should show.
 *
 * @param int $blog_id Blog ID.
 * @param int $user_id User ID.
 * @return string One of the WPCOM_SIMPLE_BACKUP_STATE_* constants.
 */
function wpcom_simple_backup_get_state( $blog_id, $user_id ) {
	if ( ! wpcom_simple_backup_has_backup_feature( $blog_id ) ) {
		$state = WPCOM_SIMPLE_BACKUP_STATE_UPGRADE;
	} elseif ( wpcom_simple_backup_is_transfer_in_progress( $blog_id ) ) {
		$state = WPCOM_SIMPLE_BACKUP_STATE_IN_PROGRESS;
	} else {
		$eligibility = wpcom_simple_backup_get_eligibility( $blog_id, $user_id );

		// Null means the library was unavailable, not that the site failed a
		// check; let the transfer flow reject it instead.
		$state = ( null === $eligibility || ! empty( $eligibility['is_eligible'] ) )
			? WPCOM_SIMPLE_BACKUP_STATE_ACTIVATE
			: WPCOM_SIMPLE_BACKUP_STATE_INELIGIBLE;
	}

	/**
	 * Filter the state rendered by the Simple Backup page.
	 *
	 * Lets each prompt be previewed on a sandbox without arranging real state.
	 *
	 * @param string $state   One of the WPCOM_SIMPLE_BACKUP_STATE_* constants.
	 * @param int    $blog_id Blog ID.
	 * @param int    $user_id User ID.
	 */
	return apply_filters( 'wpcom_simple_backup_state', $state, $blog_id, $user_id );
}

/**
 * Human-readable reasons a site cannot be transferred.
 *
 * @param array|null $eligibility Result of wpcom_simple_backup_get_eligibility().
 * @return string[]
 */
function wpcom_simple_backup_get_blocker_messages( $eligibility ) {
	if ( empty( $eligibility['errors'] ) || ! is_array( $eligibility['errors'] ) ) {
		return array();
	}

	$messages = array();
	foreach ( $eligibility['errors'] as $error ) {
		if ( ! empty( $error['message'] ) ) {
			$messages[] = (string) $error['message'];
		}
	}

	return $messages;
}
