version: '3.3'

services:
  phpmyadmin:
    # container_name: jetpack_phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db:mysql
    ports:
      - 8181:80
    environment:
      MYSQL_USERNAME: '${MYSQL_USER:-wordpress}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD:-wordpress}'

  ## SMTP Server + Web Interface for viewing and testing emails during development.
  ## http://maildev.github.io/maildev/
  maildev:
    image: maildev/maildev
    # container_name: maildev
    ports:
      - '${PORT_MAILDEV:-1080}:80'
      - '${PORT_SMTP:-25}:25'

  ## SFTP server running at localhost:1022
  sftp:
    # container_name: jetpack_sftp
    image: atmoz/sftp
    volumes:
      ## WordPress and its plugins and themes should be defined in docker/compose-volumes.yml{.sample}, not here!
      ## That avoids having to define them both here and in the "wordpress" service.
      - dockerdirectory:/usr/local/src/jetpack-monorepo/tools/docker
      - ./data/ssh.keys:/home/wordpress/.ssh/keys:ro
    ports:
      - '${PORT_SFTP:-1022}:22'
    env_file:
      - ./default.env
      - ./.env
