services:
  monorepo:
    profiles:
      - dev
    build:
      context: ${HOST_CWD:-.}/tools/docker
      dockerfile: Dockerfile.monorepo
      args:
        PHP_VERSION: ${PHP_VERSION}
        COMPOSER_VERSION: ${COMPOSER_VERSION}
        NODE_VERSION: ${NODE_VERSION}
        PNPM_VERSION: ${PNPM_VERSION}
    volumes:
      - ${HOST_CWD:-.}:/usr/local/src/jetpack-monorepo
    working_dir: /usr/local/src/jetpack-monorepo
