import { ToggleControl } from '@wordpress/components';
import { __ } from '@wordpress/i18n';
import { Card } from '@wordpress/ui';
import DashboardLayout from '../../src/dashboard/components/dashboard-layout';
import QueryClientWrapper from '../../src/dashboard/components/query-client-wrapper';
import { useSettings, useUpdateSettings } from '../../src/dashboard/hooks/use-settings';
import './style.scss';

/**
 * Renders a settings card wrapping a single toggle control.
 *
 * @param {object}   props          - Component props.
 * @param {string}   props.title    - Card title.
 * @param {string}   props.label    - Toggle label.
 * @param {boolean}  props.checked  - Whether the toggle is on.
 * @param {boolean}  props.disabled - Whether the toggle is disabled.
 * @param {Function} props.onChange - Called with the next checked value.
 * @param {string}   [props.help]   - Optional help text shown below the toggle.
 * @return {JSX.Element} The settings card.
 */
const SettingCard = ( {
	title,
	label,
	checked,
	disabled,
	onChange,
	help,
}: {
	title: string;
	label: string;
	checked: boolean;
	disabled: boolean;
	onChange: ( next: boolean ) => void;
	help?: string;
} ) => (
	<Card.Root>
		<Card.Header>
			<Card.Title>{ title }</Card.Title>
		</Card.Header>
		<Card.Content>
			<ToggleControl
				__nextHasNoMarginBottom
				label={ label }
				help={ help }
				checked={ checked }
				disabled={ disabled }
				onChange={ onChange }
			/>
		</Card.Content>
	</Card.Root>
);

const SettingsForm = () => {
	const settings = useSettings();
	const update = useUpdateSettings();
	const privateForSite = settings.data?.videoPressVideosPrivateForSite ?? false;
	const autoCaptionsDisabled = settings.data?.videoPressAutoGeneratedCaptionsDisabled ?? false;
	const disabled = settings.isLoading || update.isPending;

	return (
		<>
			<SettingCard
				title={ __( 'Restrict video access', 'jetpack-videopress-pkg' ) }
				label={ __( 'Only logged-in users can play your videos', 'jetpack-videopress-pkg' ) }
				checked={ privateForSite }
				disabled={ disabled }
				onChange={ next => update.mutate( { videoPressVideosPrivateForSite: next } ) }
			/>
			<SettingCard
				title={ __( 'Captions', 'jetpack-videopress-pkg' ) }
				label={ __( 'Automatically generate captions for new videos', 'jetpack-videopress-pkg' ) }
				help={ __(
					'When enabled, captions are generated automatically for videos uploaded to this site. Existing captions are not affected.',
					'jetpack-videopress-pkg'
				) }
				checked={ ! autoCaptionsDisabled }
				disabled={ disabled }
				onChange={ next => update.mutate( { videoPressAutoGeneratedCaptionsDisabled: ! next } ) }
			/>
		</>
	);
};

const Stage = () => (
	<QueryClientWrapper>
		<DashboardLayout activeTab="settings">
			<div className="jp-videopress-settings">
				<SettingsForm />
			</div>
		</DashboardLayout>
	</QueryClientWrapper>
);

export { Stage as stage };
