name: Build master branch production zip
on:
  push:
    branches:
      - add/actions-upload-artifact

jobs:
  build_master_job:
    runs-on: ubuntu-latest
    name: Build production version of master to master-built branch!
    steps:
      - name: Checkout Jetpack
        uses: actions/checkout@master

      - name: Build production version
        run: yarn build-production

      - name: Clean out dev files
        run: ./bin/purge-dev-files.sh

      - name: Upload build zip
        uses: actions/upload-artifact@v1
        with:
          name: master-built
          path: .
