name: Cancelling
on:
  workflow_run:
    workflows:
      # Only list workflows that are expected to be somewhat long-running.
      - Build
      - "PHP & JS Code coverage"
      - E2E Tests
      - JS tests
      - Linting
      - PHP Compatibility
      - PHPUnit tests
    types: [ 'requested' ]

jobs:
  cancel-dups:
    name: Cancel duplicate workflow runs
    runs-on: ubuntu-latest
    if: github.event.workflow_run.name != 'Build'

    steps:
      - uses: potiuk/cancel-workflow-runs@master
        name: "Cancel duplicate workflow runs"
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          cancelMode: duplicates
          sourceRunId: ${{ github.event.workflow_run.id }}

  cancel-builds:
    name: Cancel duplicate builds
    runs-on: ubuntu-latest

    # Keep the branch part of this condition in sync with the corresponding condition in build.yml
    if: >
      github.event.workflow_run.name == 'Build' && ! (
        github.event.workflow_run.head_branch == 'master' || contains( github.event.workflow_run.head_branch, '/branch-' )
      )

    steps:
      - uses: potiuk/cancel-workflow-runs@master
        name: "Cancel duplicate builds"
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          cancelMode: duplicates
          sourceRunId: ${{ github.event.workflow_run.id }}
