name: Check Actions rate limit
on:
  workflow_dispatch:

jobs:
  check:
    name: Check Actions rate limit
    runs-on: ubuntu-latest
    steps:
      - name: Check rate limit
        env:
          TOKEN: ${{ github.token }}
        run: |
          curl -v --no-progress-meter --header "Authorization: Bearer $TOKEN" https://api.github.com/rate_limit
