name: E2E Tests

on:
  push:

jobs:
  e2e-tests:
    name: "e2e tests"
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
    - uses: actions/checkout@v3

    - name: Setup tools
      uses: ./.github/actions/tool-setup

    - name: Install monorepo
      run: |
        pnpm install

    - name: Test environment set-up
      working-directory: projects/plugins/jetpack/tests/e2e
      env:
        CONFIG_KEY: ${{ secrets.E2E_CONFIG_KEY }}
        COMPOSER_ROOT_VERSION: "dev-master"
      run: |
          echo "::group::Build plugin(s)"
          pnpm run build
          echo "::endgroup::"

          echo "::group::Start docker environment"
          pnpm run env:up
          echo "::endgroup::"

    - name: Test environment tear-down
      if: ${{ always() }}
      working-directory: projects/plugins/jetpack/tests/e2e
      continue-on-error: true
      run: |
        ls -lh ../../../../../tools/docker
        pnpm run env:clean
