name: E2E Tests

on:
  push:

jobs:
  e2e-tests:
    name: "e2e tests"
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 16.13.2

    - name: Setup pnpm
      if: steps.versions.outputs.node-version != 'false'
      uses: pnpm/action-setup@v2.2.1
      with:
        version: 6.23.6

    - name: Install monorepo
      run: |
        pnpm install

    - name: Test environment set-up
      working-directory: projects/plugins/jetpack/tests/e2e
      env:
        CONFIG_KEY: ${{ secrets.E2E_CONFIG_KEY }}
        COMPOSER_ROOT_VERSION: "dev-master"
      run: |
          echo "::group::Build plugin(s)"
          pnpm run build
          echo "::endgroup::"

          echo "::group::Start docker environment"
          pnpm run env:up
          echo "::endgroup::"

          echo "::group::Create tunnel"
          pnpm run tunnel:up
          echo "::endgroup::"

    - name: Test environment tear-down
      if: ${{ always() }}
      working-directory: projects/plugins/jetpack/tests/e2e
      continue-on-error: true
      run: |
        pnpm run tunnel:down
        ls -lh ../../../../../tools/docker
        pnpm run env:clean
