name: E2E Tests on Atomic sites

on:
  schedule:
    - cron:  '0 */4 * * *'

jobs:
  e2e-tests:
    name: "E2E tests"
    runs-on: ubuntu-latest
    timeout-minutes: 25
    env:
      TEST_SITE: atomic

    steps:
    - uses: actions/checkout@v2

    - name: Setup tools
      uses: ./.github/actions/tool-setup
      with:
        php: false

    - name: Install
      working-directory: projects/plugins/jetpack/tests/e2e
      env:
        CONFIG_KEY: ${{ secrets.E2E_CONFIG_KEY }}
      run: |
        pnpm install
        pnpm run test-decrypt-all-config

    - name: Run tests
      working-directory: projects/plugins/jetpack/tests/e2e
      run: pnpm run test-e2e -- --group=atomic --testNamePattern='^(?!Paid blocks WordAds block).*$'

    - name: Upload test artifacts
      if: ${{ always() }}
      continue-on-error: true
      uses: actions/upload-artifact@v2
      with:
        name: test-output-${{ matrix.group }}
        path: projects/plugins/jetpack/tests/e2e/output

    - name: Send Slack notification
      if: ${{ failure() }}
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      working-directory: projects/plugins/jetpack/tests/e2e
      run: pnpm slack -- suite atomic --report atomic

    - uses: testspace-com/setup-testspace@v1
      with:
        domain: ${{github.repository_owner}}
      if: always()
    - name: Publish to Testspace
      working-directory: projects/plugins/jetpack/tests/e2e
      run: |
        testspace "[${GROUP}]output/reports/junit-*.xml"
      if: always()

  slack-notification:
    name: "Slack notification"
    runs-on: ubuntu-latest
    needs: e2e-tests
    env:
      CONFIG_KEY: ${{ secrets.E2E_CONFIG_KEY }}
      GITHUB_CONTEXT: ${{ toJson(github) }}
      TEST_SITE: atomic

    steps:
      - uses: actions/checkout@v2

      - name: Setup tools
        uses: ./.github/actions/tool-setup
        with:
          php: false

      - name: Send Slack notification
        working-directory: projects/plugins/jetpack/tests/e2e
        env:
          RESULT: ${{ needs.e2e-tests.result }}
        run: |
          pnpm install
          pnpm run test-decrypt-all-config
          pnpm slack -- status $RESULT --report atomic

  test-reports:
    name: "Trigger test report workflow"
    runs-on: ubuntu-latest
    if: ${{ ! cancelled() }}
    needs: e2e-tests

    steps:
      - uses: actions/checkout@v2

      - name: Trigger test report workflow
        uses: ./.github/actions/test-report-dispatch
        with:
          token: ${{ secrets.E2E_TEST_REPORTS_TOKEN }}
          report_name: atomic
