name: k6 Tests for Jetpack Staging Test Sites
# Runs k6 tests for the same sites updated by `update-jetpack-staging-sites.yml`.

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1,6,12,18 * * *" # “At minute 0 past hour 1, 6, 12, and 18.”

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run k6 frontend tests
        uses: grafana/k6-action@v0.3.0
        with:
          filename: .github/files/jetpack-staging-sites/k6-frontend.js
        env:
          JETPACKSTAGING_K6_USERNAME: ${{ secrets.JETPACKSTAGING_K6_USERNAME }}
          JETPACKSTAGING_K6_PASSWORD: ${{ secrets.JETPACKSTAGING_K6_PASSWORD }}

      - name: Run k6 backend tests
        uses: grafana/k6-action@v0.3.0
        with:
          filename: .github/files/jetpack-staging-sites/k6-backend.js
        env:
          JETPACKSTAGING_K6_USERNAME: ${{ secrets.JETPACKSTAGING_K6_USERNAME }}
          JETPACKSTAGING_K6_PASSWORD: ${{ secrets.JETPACKSTAGING_K6_PASSWORD }}

      - name: Send Slack alert on failure
        uses: slackapi/slack-github-action@v1.23.0
        if: ${{ failure() }}
        with:
          channel-id: ${{ secrets.SLACK_JP_ALERTS_CHANNEL }}
          payload: |
            {
              "icon_emoji": ":github-rejected:",
              "text": "Failure for workflow `${{ github.workflow }}`: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Failure for workflow `${{ github.workflow }}`: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}
