name: "Needs Review Label Actions"
on:
  pull_request:
    types: [labeled]

jobs:
  comment:
    runs-on: ubuntu-latest
    name: Comment on Needs Review label
    steps:
      - name: Get context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
