name: "Needs Review Label Actions"
on:
  pull_request:
    types: [labeled]

jobs:
  comment:
    runs-on: ubuntu-latest
    name: Comment on Needs Review label
    if: github.event.label.name == '[Status] Needs Review'
    steps:
      - name: Comment
        uses: actions/github-script@0.8.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Needs review comment!'
            })
