name: Post-Build
on:
  workflow_run:
    types: [ 'completed' ]
    workflows:
      - Build
concurrency:
  # Cancel concurrent jobs on pull_request but not push, by including the run_id in the concurrency group for the latter.
  group: post-build-${{ github.event.workflow_run.event == 'push' && github.run_id || 'pr' }}-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: true

env:
  COMPOSER_ROOT_VERSION: "dev-trunk"
  SUMMARY: Post-Build run [#${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for Build run [#${{ github.event.workflow_run.id }}](${{ github.event.workflow_run.html_url }})

# Note the job logic here is a bit unusual. That's because this workflow is triggered by `workflow_run`, and so is not shown on the PR by default.
# Instead we have to manually report back, including where we could normally just skip or let a failure be handled.
#  - If the "Build" job failed, we need to set our status as failed too (build_failed).
#  - If the find_artifact job fails for some reason, we need a step to explicitly report that back.
#  - If no plugins are found, we need to explicitly report back a "skipped" status.
#  - And the upgrade_test job both explicitly sets "in progress" at its start and updates at its end.

jobs:
  build_failed:
    name: Handle build failure
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion != 'success'
    timeout-minutes: 2  # 2022-08-26: Seems like it should be fast.
    steps:
      - uses: actions/checkout@v3
      - name: Create failed checks
        uses: ./.github/actions/check-run
        with:
          name: Test plugin upgrades
          sha: ${{ github.event.workflow_run.head_sha }}
          conclusion: cancelled
          title: Build failed
          summary: |
            ${{ env.SUMMARY }}

            Post-build run aborted because the build did not succeed.

  find_artifact:
    name: Find artifact
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    timeout-minutes: 2  # 2022-08-26: Seems like it should be fast.
    outputs:
      zip_url: ${{ steps.run.outputs.zip_url }}
      any_plugins: ${{ steps.run.outputs.any_plugins }}
    steps:
      - uses: actions/checkout@v3
      - name: Find artifact
        id: run
        env:
          TOKEN: ${{ github.token }}
          URL: ${{ github.event.workflow_run.artifacts_url }}
        run: |
          for (( i=1; i<=5; i++ )); do
            [[ $i -gt 1 ]] && sleep 10
            echo "::group::Fetch list of artifacts (attempt $i/5)"
            JSON="$(curl -v -L --get \
              --header "Authorization: token $TOKEN" \
              --url "$URL"
            )"
            echo "$JSON"
            echo "::endgroup::"
            ZIPURL="$(jq -r '.artifacts[] | select( .name == "jetpack-build" ) | .archive_download_url' <<<"$JSON")"
            PLUGINS="$(jq -r '.artifacts[] | select( .name == "plugins" )' <<<"$JSON")"
            if [[ -n "$ZIPURL" ]]; then
              break
            fi
          done
          [[ -z "$ZIPURL" ]] && { echo "::error::Failed to find artifact."; exit 1; }
          echo "Zip URL: $ZIPURL"
          echo "::set-output name=zip_url::${ZIPURL}"
          if [[ -z "$PLUGINS" ]]; then
            echo "Any plugins? No"
            echo "::set-output name=any_plugins::false"
          else
            echo "Any plugins? Yes"
            echo "::set-output name=any_plugins::true"
          fi

      - name: Create failed checks
        if: ${{ ! success() }}
        uses: ./.github/actions/check-run
        with:
          name: Test plugin upgrades
          sha: ${{ github.event.workflow_run.head_sha }}
          conclusion: failure
          title: Failed to find build artifact
          summary: |
            ${{ env.SUMMARY }}

            Post-build run aborted because the "Find artifact" step failed.

  no_plugins:
    name: Handle no-plugins
    runs-on: ubuntu-latest
    needs: find_artifact
    if: needs.find_artifact.outputs.any_plugins == 'false'
    timeout-minutes: 2  # 2022-08-26: Seems like it should be fast.
    steps:
      - uses: actions/checkout@v3
      - name: Create skipped checks
        uses: ./.github/actions/check-run
        with:
          name: Test plugin upgrades
          sha: ${{ github.event.workflow_run.head_sha }}
          conclusion: skipped
          title: No plugins were built
          summary: |
            ${{ env.SUMMARY }}

            Post-build run skipped because no plugins were built.

  upgrade_test:
    name: Test plugin upgrades
    runs-on: ubuntu-latest
    needs: find_artifact
    if: needs.find_artifact.outputs.any_plugins == 'true'
    timeout-minutes: 15  # 2022-08-26: Successful runs seem to take about 6 minutes, but give some extra time for the downloads.
    services:
      db:
        image: mariadb:latest
        env:
          MARIADB_ROOT_PASSWORD: wordpress
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
    container:
      image: ghcr.io/automattic/jetpack-wordpress-dev:latest
      env:
        WP_DOMAIN: localhost
        WP_ADMIN_USER: wordpress
        WP_ADMIN_EMAIL: wordpress@example.com
        WP_ADMIN_PASSWORD: wordpress
        WP_TITLE: Hello World
        MYSQL_HOST: db:3306
        MYSQL_DATABASE: wordpress
        MYSQL_USER: root
        MYSQL_PASSWORD: wordpress
        HOST_PORT: 80
      ports:
        - 80:80
    steps:
      - uses: actions/checkout@v3
        with:
          path: monorepo

      - name: Notify check in progress
        id: create_run
        uses: ./monorepo/.github/actions/check-run
        with:
          name: Test plugin upgrades
          sha: ${{ github.event.workflow_run.head_sha }}
          status: in_progress
          title: Test started...
          summary: |
            ${{ env.SUMMARY }}

            See run [#${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details.

      - name: Download build artifact
        env:
          TOKEN: ${{ github.token }}
          ZIPURL: ${{ needs.find_artifact.outputs.zip_url }}
        shell: bash
        run: |
          for (( i=1; i<=2; i++ )); do
            [[ $i -gt 1 ]] && sleep 10
            echo "::group::Downloading artifact (attempt $i/2)"
            curl -v -L --get \
              --header "Authorization: token $TOKEN" \
              --url "$ZIPURL" \
              --output "artifact.zip"
            echo "::endgroup::"
            if [[ -e "artifact.zip" ]] && zipinfo artifact.zip &>/dev/null; then
              break
            fi
          done
          [[ ! -e "artifact.zip" ]] && { echo "::error::Failed to download artifact."; exit 1; }
          unzip artifact.zip
          tar --xz -xvvf build.tar.xz

      - name: Setup WordPress
        run: monorepo/.github/files/test-plugin-update/setup.sh

      - name: Prepare plugin zips
        run: monorepo/.github/files/test-plugin-update/prepare-zips.sh

      - name: Test upgrades
        run: monorepo/.github/files/test-plugin-update/test.sh

      - name: Notify final status
        if: always() && steps.create_run.outputs.id
        uses: ./monorepo/.github/actions/check-run
        with:
          id: ${{ steps.create_run.outputs.id }}
          conclusion: ${{ job.status }}
          title: ${{ job.status == 'success' && 'Tests passed' || job.status == 'cancelled' && 'Cancelled' || 'Tests failed' }}
          summary: |
            ${{ env.SUMMARY }}

            See run [#${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details.
