name: Renovate
on:
  pull_request:
    branches: [ 'master' ]
concurrency:
  group: renovate-helper-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

env:
  COMPOSER_ROOT_VERSION: "dev-master"

jobs:
  cleanup:
    name: Amend Renovate PR
    runs-on: ubuntu-latest
    if: github.actor == 'renovate[bot]'
    timeout-minutes: 5  # 2021-03-25: Guess.

    steps:
      - uses: actions/checkout@v2

      - name: Read tool versions
        id: versions
        uses: ./.github/actions/read-versions

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ steps.versions.outputs.php-version }}
          tools: composer:${{ steps.versions.outputs.composer-version }}
          extensions: mysql, imagick
          coverage: none

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.versions.outputs.node-version }}

      - name: Get Composer cache directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Use composer cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Use pnpm cache
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ steps.versions.outputs.node-version }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-${{ steps.versions.outputs.node-version }}-

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: ${{ steps.versions.outputs.pnpm-version }}

      - name: Tool versions
        run: |
          which php
          php --version
          which composer
          composer --version
          which node
          node --version
          which pnpm
          pnpm --version
          which jq
          jq --version

      - run: .github/files/renovate-helper.sh
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
