name: Renovate
on:
  pull_request:
    branches: [ 'master' ]

env:
  COMPOSER_ROOT_VERSION: "dev-master"

jobs:
  cleanup:
    name: Amend Renovate PR
    runs-on: ubuntu-latest
    if: github.actor == 'renovate[bot]'
    timeout-minutes: 5  # 2021-03-25: Guess.

    steps:
      - uses: actions/checkout@v2

      - name: Read PHP and Node versions
        id: versions
        run: |
          echo "::set-output name=php-version::$(<.github/php-version)"
          echo "::set-output name=node-version::$(<.nvmrc)"

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ steps.versions.outputs.php-version }}
          tools: composer
          extensions: mysql, imagick
          coverage: none

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.versions.outputs.node-version }}

      - name: Get Composer cache directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Use composer cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Use yarn cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Tool versions
        run: |
          which php
          php --version
          which composer
          composer --version
          which node
          node --version
          which yarn
          yarn --version
          which jq
          jq --version

      - run: .github/files/renovate-helper.sh
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
