name: Slack branch existence notification
on:
  create:
  delete:

permissions:
  # actions/checkout
  contents: read

jobs:
  notify:
    name: Notify
    runs-on: ubuntu-latest
    timeout-minutes: 5 # 2025-11-20: Takes a few seconds.
    if: github.event.ref == 'prerelease'

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          ref: trunk
      - name: Generate message
        id: message
        env:
          SLACK_RELEASES_CHANNEL: ${{ vars.SLACK_RELEASES_CHANNEL }}
        run: |
          source .github/files/gh-funcs.sh

          if [[ "$GITHUB_EVENT_NAME" == 'create' ]]; then
            gh_set_output message "$(
              jq -nc --arg C "$SLACK_RELEASES_CHANNEL" --slurpfile event "$GITHUB_EVENT_PATH" '$event[0] as $e | {
                channel: $C,
                icon_emoji: ":lock:",
                text: "Incoming release! Prerelease branch was created by \( $e.sender.login ).",
                blocks: [
                  {
                    type: "section",
                    text: {
                      type: "mrkdwn",
                      text: ":holdontoyourbutts: Incoming release! Prerelease branch was created by \( $e.sender.login ).",
                    },
                  }
                ],
              }'
            )"
          elif [[ "$GITHUB_EVENT_NAME" == 'delete' ]]; then
            gh_set_output message "$(
              jq -nc --arg C "$SLACK_RELEASES_CHANNEL" --slurpfile event "$GITHUB_EVENT_PATH" '$event[0] as $e | {
                channel: $C,
                icon_emoji: ":unlock:",
                text: "Prerelease branch was deleted by \( $e.sender.login ).",
                blocks: [
                  {
                    type: "section",
                    text: {
                      type: "mrkdwn",
                      text: "Prerelease branch was deleted by \( $e.sender.login ).",
                    },
                  }
                ],
              }'
            )"
          else
            echo "::error::Unknown event \"$GITHUB_EVENT_NAME\""
            exit 1
          fi

      - name: Send message to releases channel
        uses: slackapi/slack-github-action@45a88b9581bfab2566dc881e2cd66d334e621e2c # v3.0.3
        with:
          token: ${{ secrets.SLACK_TOKEN }}
          method: chat.postMessage
          payload: ${{ steps.message.outputs.message }}
