name: Storybook GitHub Pages

on:
  push:
    branches:
      - master
    paths:
      - projects/js-packages/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'Automattic/jetpack' }}
    strategy:
      matrix:
        node: ['14']

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Read tool versions
        id: versions
        uses: ./.github/actions/read-versions

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ steps.versions.outputs.php-version }}
          tools: composer:${{ steps.versions.outputs.composer-version }}
          extensions: mysql, imagick
          coverage: none

      - name: Use desired version of NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.versions.outputs.node-version }}

      - name: Get Composer cache directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Use composer cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Use pnpm cache
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ steps.versions.outputs.node-version }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-${{ steps.versions.outputs.node-version }}-

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: ${{ steps.versions.outputs.pnpm-version }}

      - name: Install Dependencies
        run: pnpm install

      - name: Build Storybook
        run: pnpx jetpack build js-packages/storybook -v

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./projects/js-packages/storybook/storybook/build
          destination_dir: storybook
          force_orphan: true
