name: Update a package when it is updated in the monorepo
on:
  push:
    branches:
      - master # Every time a PR is merged to master.
    paths:
      - 'projects/packages/**' # Only when package files are modified.

jobs:
  update_package:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name
    steps:
      - uses: actions/checkout@master
      - name: Keep Jetpack Packages up to date
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        run: |
          sh ./.github/actions/update-package/update-package.sh
