name: Update Jetpack Staging Test Sites
# Ran as part of the `UpdateJetpackStaging` TeamCity build.

on:
  workflow_dispatch:

jobs:
  run_shell_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Env config
        env:
          SSH_KNOWN_HOSTS: ${{ secrets.UPDATEJETPACKSTAGING_SSH_KNOWN_HOSTS }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts

      - name: Execute shell script
        shell: bash
        env:
          UPDATEJETPACKSTAGING_SSH_KEY: ${{ secrets.UPDATEJETPACKSTAGING_SSH_KEY }}
        run: .github/files/update-jetpack-staging-sites.sh
