name: WP Cloud Unit Testing for WPCOMSH

on:
  pull_request:
  push:
    branches: ['trunk', '*/branch-*']
concurrency:
  group: wpcloud-wpcomsh
  cancel-in-progress: false
  # Concurrency is set up to make sure we can only run one WP Cloud testing job at the same time.

permissions:
  # actions/checkout, actions/upload-artifact, actions/download-artifact
  contents: read

jobs:
  build:
    name: Install the Monorepo and build wpcomsh
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name
    outputs:
      wpcomsh: ${{ steps.changed.outputs.wpcomsh }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      # For pull requests, list-changed-projects.sh needs the merge base.
      # But it doesn't have to be checked out.
      - name: Deepen to merge base
        if: github.event_name == 'pull_request'
        uses: ./.github/actions/deepen-to-merge-base
        with:
          checkout: false

      - name: Setup tools
        uses: ./.github/actions/tool-setup
        with:
          # Match PHP version on WP Cloud so the right vendor packages get installed.
          php: 8.3
      - name: Monorepo install
        run: |
          echo "::group::Pnpm"
          pnpm install
          echo "::endgroup::"
      - name: Detect if wpcomsh has changed
        id: changed
        run: |
          CHANGED="$(EXTRA=test .github/files/list-changed-projects.sh)"

          WPCOMSH_CHANGED="$(jq --argjson changed "$CHANGED" -n '$changed | has( "plugins/wpcomsh" ) ')"
          echo "wpcomsh=${WPCOMSH_CHANGED}" >> "$GITHUB_OUTPUT"
      - name: Build wpcomsh
        if: steps.changed.outputs.wpcomsh == 'true'
        run: |
          echo "::group::Installing and building wpcomsh"
          rm projects/plugins/wpcomsh/composer.lock
          pnpm jetpack build -v --deps plugins/wpcomsh
          echo "::endgroup::"

          echo "::group::Preparing artifact"
          pnpm jetpack rsync -v --non-interactive wpcomsh /tmp/wpcomsh
          cp -a projects/plugins/wpcomsh/bin /tmp/wpcomsh
          cp -a projects/plugins/wpcomsh/tests /tmp/wpcomsh
          # The test on WP Cloud won't use `phpunit-select-config`, so select config manually.
          cp -aL projects/plugins/wpcomsh/phpunit.12.xml.dist /tmp/wpcomsh/phpunit.xml.dist
          tar -cvvf wpcomsh.tar.xz -C /tmp/ wpcomsh
          echo "::endgroup::"

      - name: Store artifact
        uses: actions/upload-artifact@v7
        with:
          path: wpcomsh.tar.xz
          retention-days: 1
          # Already compressed.
          compression-level: 0
          archive: false

  deploy:
    name: Run PHPUnit on the WP Cloud test site
    runs-on: ubuntu-latest
    needs: build
    if: needs.build.outputs.wpcomsh == 'true'
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v8
        with:
          name: wpcomsh.tar.xz

      - name: Extract wpcomsh build
        run: |
          tar -xvvf wpcomsh.tar.xz wpcomsh

      - name: Configure Github to be able to SSH to the WP Cloud site
        env:
          SSH_KEY: ${{ secrets.UPDATEJETPACKSTAGING_SSH_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.UPDATEJETPACKSTAGING_SSH_KNOWN_HOSTS }}
        run: |
          mkdir -vp ~/.ssh/
          chmod -v 700 ~/.ssh

          touch ~/.ssh/id_site
          touch ~/.ssh/known_hosts
          touch ~/.ssh/config
          chmod 600 ~/.ssh/id_site
          chmod 600 ~/.ssh/known_hosts
          chmod 600 ~/.ssh/config
          echo "$SSH_KEY" > ~/.ssh/id_site
          echo "wrote ~/.ssh/id_site"
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          echo "wrote ~/.ssh/known_hosts"
          echo "Host jpwpcomsh" > ~/.ssh/config
          echo "  Hostname sftp.wp.com" >> ~/.ssh/config
          echo "  User wpcom-jetpackisbestpack-default-237778992" >> ~/.ssh/config
          echo "  IdentityFile ~/.ssh/id_site" >> ~/.ssh/config
          echo "  IdentitiesOnly yes" >> ~/.ssh/config

      - name: Transfer wpcomsh to the testing server
        run: |
          # This can give errors if the previous state was broken, so ignore them
          ssh jpwpcomsh "wp --skip-plugins --skip-themes dereferenced freshen > /dev/null 2>&1" || echo "wp dereferenced freshen has exited with code $?"
          ssh jpwpcomsh "rm -rf /tmp/old-* > /dev/null 2>&1"
          rsync -azKPv --prune-empty-dirs --delete --delete-after --delete-excluded --copy-links wpcomsh/. jpwpcomsh:/srv/htdocs/wp-content/mu-plugins/wpcomsh/.

      - name: Smoke test
        run: |
          # Do a basic check to verify the site is loading
          CODE=0
          SITE_URL=$(ssh jpwpcomsh "wp option get siteurl" 2>/dev/null) || CODE=$?
          if [[ $CODE -ne 0 ]]; then
            echo '::error::Unable to run a basic `wp` command! Something is wrong with the site.'
            exit 1
          elif [[ ! "$SITE_URL" =~ ^https?://[a-z0-9_.-]+$ ]]; then
            echo '::error::Site URL retrieved does not seem to be a URL.'
            exit 1
          else
            echo 'No issues using a simple command in WP-CLI.'
            curl -s --fail "$SITE_URL" > /dev/null || CODE=$?
            if [[ $CODE -ne 0 ]]; then
              echo '::error::Unable to load site! Something is wrong with the site.'
              CODE=1
            else
              echo 'No issues slurping site with `curl`.'
            fi
          fi

      - name: Run PHPUnit tests
        run: |
          ssh jpwpcomsh "/srv/htdocs/wp-content/mu-plugins/wpcomsh/bin/run-phpunit-tests.sh"

      - name: Cleanup
        if: always()
        run: |
          rm -rvf ~/.ssh/
