<?php
/**
 * Newsletter Mode page shell.
 *
 * @package automattic/jetpack-mu-wpcom
 */

namespace Automattic\Jetpack\Jetpack_Mu_Wpcom;

use Automattic\Jetpack\WP_Build_Polyfills\WP_Build_Polyfills;

/**
 * Registers the gated Newsletter Mode page and its wp-build assets.
 *
 * @since $$next-version$$
 */
class Newsletter_Mode {

	/**
	 * Per-site enrollment option.
	 */
	const OPTION_ENABLED = 'wpcom_newsletter_mode_enabled';

	/**
	 * Emergency constant that disables the feature even for enrolled sites.
	 */
	const DISABLE_CONSTANT = 'WPCOM_NEWSLETTER_MODE_DISABLED';

	/**
	 * WP Build page ID.
	 */
	const PAGE_ID = 'newsletter-mode';

	/**
	 * WP Admin menu slug generated for a WP Build page.
	 */
	const MENU_SLUG = self::PAGE_ID . '-wp-admin';

	/**
	 * Render callback generated by wp-build in build/pages/newsletter-mode/page-wp-admin.php.
	 */
	const RENDER_CALLBACK = 'jetpack_mu_wpcom_newsletter_mode_wp_admin_render_page';

	/**
	 * Capability required to enter the shell.
	 *
	 * Features added later retain the capabilities of their corresponding
	 * wp-admin screens and APIs.
	 */
	const ACCESS_CAPABILITY = 'publish_posts';

	/**
	 * Initialize Newsletter Mode for an enrolled site.
	 */
	public static function init() {
		if ( ! is_admin() || wp_doing_ajax() ) {
			return;
		}

		if ( ! self::is_enabled() ) {
			return;
		}

		add_action( 'admin_menu', array( __CLASS__, 'register_menu' ) );

		if ( ! self::is_page_request() || ! current_user_can( self::ACCESS_CAPABILITY ) ) {
			return;
		}

		self::load_wp_build();
	}

	/**
	 * Whether the emergency kill switch allows Newsletter Mode to run.
	 *
	 * @return bool
	 */
	public static function is_available() {
		return ! defined( self::DISABLE_CONSTANT ) || ! constant( self::DISABLE_CONSTANT );
	}

	/**
	 * Whether the current site is enrolled and the feature is available.
	 *
	 * Enroll the current site from its WP-CLI context with:
	 * `wp option update wpcom_newsletter_mode_enabled 1`.
	 *
	 * @return bool
	 */
	public static function is_enabled() {
		return self::is_available() && (bool) get_option( self::OPTION_ENABLED, false );
	}

	/**
	 * Register the top-level Newsletter menu page for eligible users.
	 */
	public static function register_menu() {
		if ( ! self::is_enabled() ) {
			return;
		}

		// The generated callback only exists after build/build.php is loaded on
		// the Newsletter Mode request. The fallback keeps menu registration safe
		// in source checkouts and when build artifacts are unavailable.
		$callback = function_exists( self::RENDER_CALLBACK )
			? self::RENDER_CALLBACK
			: '__return_empty_string';

		add_menu_page(
			__( 'Newsletter', 'jetpack-mu-wpcom' ),
			__( 'Newsletter', 'jetpack-mu-wpcom' ),
			self::ACCESS_CAPABILITY,
			self::MENU_SLUG,
			$callback,
			'dashicons-email-alt',
			3
		);
	}

	/**
	 * Load wp-build's generated registrations for the Newsletter Mode page.
	 */
	private static function load_wp_build() {
		$wp_build_index = dirname( __DIR__, 3 ) . '/build/build.php';

		if ( ! file_exists( $wp_build_index ) ) {
			return;
		}

		require_once $wp_build_index;

		WP_Build_Polyfills::register(
			'jetpack-mu-wpcom',
			array_merge(
				WP_Build_Polyfills::SCRIPT_HANDLES,
				WP_Build_Polyfills::MODULE_IDS
			)
		);
	}

	/**
	 * Whether this request targets the Newsletter Mode wp-build page.
	 *
	 * @return bool
	 */
	private static function is_page_request() {
		// phpcs:ignore WordPress.Security.NonceVerification.Recommended -- Read-only routing parameter.
		return is_admin() && isset( $_GET['page'] ) && self::MENU_SLUG === $_GET['page'];
	}
}
